Improve K32W Docker image used by Build example - K32W with SE051 workflow
project-chip/connectedhomeip pull request #10041
Opened 2021-09-29 00:26 UTC by electrocucaracha

#### Problem
[Hadolint](https://github.com/hadolint/hadolint) tool helps to build Docker images following best practices. Using those guidelines can help to reduce the size of the image and speed up the pulling process during the CI execution.

#### Change overview
This change uses the [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) feature to get the MCUXpresso SDK Builder in one stage and installing it in the following stage.

#### Testing
This was tested locally using the act tool (`$ act -j k32w`) using the Docker image built with these changes.

2021-09-29 03:15 UTC, bzbarsky-apple approved these changes

2021-09-29 03:53 UTC, saurabhst approved these changes

2021-09-29 16:23 UTC, woody-apple approved these changes

2021-09-29 21:12 UTC, jmartinez-silabs approved these changes

2021-09-29 21:16 UTC, andy31415 requested changes, later dismissed
Since image changed, please update the version file

2021-10-07 21:12 UTC, electrocucaracha commented
> Since image changed, please update the version file

I've upgrade the version file to reflect this change.

2021-10-07 21:18 UTC, msandstedt approved these changes

2021-10-21 21:55 UTC, electrocucaracha commented
> @electrocucaracha

@woody-apple I just rebased the changes of this patchset

2021-10-22 16:29 UTC, merged