[nrf5] enable Thread on lock app
project-chip/connectedhomeip pull request #1011
Opened 2020-06-05 05:31 UTC by bukepo

#### Problem
Thread network is not enabled.

 #### Summary of Changes
This commit enables OpenThread in the lock-app on nRF52840. The UART provides access
to OpenThread CLI. Device layer code are borrowed and modified from the OpenWeave project.

fixes #947

2020-06-08 17:14 UTC, woody-apple approved these changes

2020-06-09 20:35 UTC, gerickson requested changes
See comment regarding `CHIP_ENABLE_OPENTHREAD` conditionals.

2020-06-10 13:27 UTC, gerickson requested changes

2020-06-11 01:56 UTC, gerickson approved these changes

2020-06-11 21:06 UTC, jelderton approved these changes

2020-06-11 21:25 UTC, merged