Update chip-build Dockerfile
project-chip/connectedhomeip pull request #10149
Opened 2021-10-01 15:10 UTC by kpschoedel

#### Problem

`gh_report.py` doesn't run in the `chip-build` container.

#### Change overview

Add python packages `cxxfilt` `ghapi` `pandas`.

#### Testing

Local run of `gh_report.py` in the updated container.

2021-10-01 15:11 UTC, saurabhst approved these changes

2021-10-01 15:17 UTC, woody-apple approved these changes

2021-10-01 15:44 UTC, bzbarsky-apple requested changes
Need to bump the version number.

2021-10-01 15:52 UTC, bzbarsky-apple approved these changes
Approving (so this is not blocked on me) if the version is bumped or @andy31415 or @woody-apple say it doesn't need to be.

2021-10-01 15:52 UTC, bzbarsky-apple commented on integrations/docker/images/chip-build/Dockerfile
> +    && pip3 install attrs coloredlogs PyGithub pygit future portpicker mobly click cxxfilt ghapi pandas \
Needs version bump.

2021-10-04 14:31 UTC, kpschoedel commented on integrations/docker/images/chip-build/Dockerfile
> +    && pip3 install attrs coloredlogs PyGithub pygit future portpicker mobly click cxxfilt ghapi pandas \
Done

2021-10-04 18:13 UTC, yufengwangca approved these changes

2021-10-04 18:26 UTC, andy31415 approved these changes

2021-10-04 18:26 UTC, merged