Don't pass destination as nullptr to OpenSSL encrypt/decrypt calls
project-chip/connectedhomeip pull request #10231
Opened 2021-10-05 16:03 UTC by pan-apple

#### Problem
Passing `nullptr` as destination pointer to `OpenSSL` crypto API causes failures. 
* Fixes #10190

#### Change overview
The unit tests were allocating destination buffer even though the length was 0, and test vectors had it as nullptr. This prevented the tests from catching the failures.

This PR updates the tests to not allocate destination buffer if the length is 0. That verified that the tests actually fail for the given test vectors.

The OpenSSL PAL is updated to allocate a temporary buffer for the destination if the provided buffer is `nullptr` and the length is 0.

#### Testing
Updated CHIPCryptoPALTest to catch this error condition.

2021-10-05 16:20 UTC, tcarmelveilleux requested changes

2021-10-05 16:20 UTC, tcarmelveilleux commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    chip::Platform::ScopedMemoryBuffer<uint8_t> ciphertext_buf;
We should not require heap for these calls at all.

2021-10-05 16:21 UTC, tcarmelveilleux commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +        if (ciphertext == nullptr)
ciphertext can never be nullptr if plaintext != nullptr.

2021-10-05 16:49 UTC, bluebin14 commented
Could use a simple 1 byte static for catching both source and destination null pointers or even better (uint8_t *) 1 to catch any non compliant crypto implementation.

2021-10-05 18:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=10231) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=10231) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=10231) it.</sub>

2021-10-05 18:39 UTC, tcarmelveilleux approved these changes

2021-10-05 19:17 UTC, emargolis approved these changes

2021-10-05 22:24 UTC, jmartinez-silabs approved these changes

2021-10-06 20:35 UTC, bluebin14 approved these changes

2021-10-07 03:05 UTC, woody-apple approved these changes

2021-10-07 13:58 UTC, merged