[QPG610x] Advertising bug fix and device name changes
project-chip/connectedhomeip pull request #10305
Opened 2021-10-07 11:31 UTC by jimlyall-q

#### Problem
* Advertising was broken by previous change
* Device name was being advertised passively against spec recommendations

#### Change overview
Buffer changes to restore the advertising
Move device name advertising to scan response

#### Testing
* Tested on top of test_event_6 branch by running MA 1.10 testcase

2021-10-07 15:30 UTC, msandstedt approved these changes

2021-10-11 22:31 UTC, woody-apple commented
@mrjerryjohns @saurabhst @andy31415 @Damian-Nordic @jelderton @jepenven-silabs @jmartinez-silabs ?

2021-10-18 22:55 UTC, LuDuda approved these changes

2021-10-21 15:47 UTC, bzbarsky-apple requested changes

2021-10-21 16:42 UTC, bzbarsky-apple approved these changes
Thank you!

2021-10-21 17:11 UTC, msandstedt approved these changes

2021-10-21 21:57 UTC, jmartinez-silabs approved these changes

2021-10-22 16:27 UTC, merged