ESP32: Read General Diagnostics cluster attribute at runtime
project-chip/connectedhomeip pull request #10314
Opened 2021-10-07 14:36 UTC by sweetymhaiske

#### Problem
* Actual value from the platform is not populated at runtime for General diagnostics attributes.

#### Change overview
* Read General Diagnostic attributes from a platform at runtime

#### Testing
* All clusters app is compiled and checked using python controller.

2021-10-07 15:13 UTC, bzbarsky-apple approved these changes

2021-10-11 16:19 UTC, bzbarsky-apple requested changes

2021-10-15 04:44 UTC, bzbarsky-apple approved these changes

2021-10-20 07:35 UTC, gjc13 approved these changes

2021-10-20 10:24 UTC, dhrishi approved these changes

2021-10-20 10:36 UTC, dhrishi commented
@andy31415 @msandstedt PTAL

2021-10-21 18:10 UTC, andy31415 approved these changes

2021-10-21 18:11 UTC, merged