Update Message Header with spec
project-chip/connectedhomeip pull request #10325
Opened 2021-10-07 18:55 UTC by jepenven-silabs

#### Problem
Matter message Header is not up to spec.

#### Change overview
- Removed Encrypted flag (replaced with SessionID != 0  spec : 4.4.1.3 ) 
- Removed SessionType from Header (was actually Message Integrity Type) 
- Split Message header into 2 8 bits section as per the specification (Messages flags and Security flags)
- Change Session ID allocator to exclude session id of 0 since it is an unsecure session.
- Updated Unit tests for message header

#### Testing
- Tested with the ./scripts/tests/test_suites.sh 
- Tested with the Units Tests
- Commissioning tested with an EFR32 with Thread

2021-10-07 20:13 UTC, bzbarsky-apple approved these changes

2021-10-07 20:59 UTC, jmartinez-silabs approved these changes

2021-10-08 01:31 UTC, turon commented
Sorry for the churn, but please note this spec issue with relying on SessionID==0 as the check for unencrypted messages: 
https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4379

2021-10-08 02:20 UTC, turon requested changes
This is a great start! Marking this for follow-up review given the number of requested edits.

2021-10-13 03:15 UTC, turon approved these changes
Just need to get CI tests passing.

2021-10-18 14:36 UTC, merged