Include information for contributors to get started
project-chip/connectedhomeip pull request #1032
Opened 2020-06-07 11:16 UTC by kedars

#### Problem
Capture information that helps contributors get started. Specifically, what this repository does, what to build and run where, what are the low-hanging fruits, etc.

 #### Summary of Changes
Added this information in the CONTRIBUTING.md file. It can be moved to some other place where folks think its more relevant.

Questions:
* I have listed my understanding, please correct where applicable.
* I have used the 'controller' and 'accessory' as terminologies, but I am not sure what are the perfect ways to refer to these.
* I wanted to also include a pointer to Coding-Style guide, but I see that this is not available in the 'master' but part of some other commit-tree in the repository.

2020-06-08 17:13 UTC, woody-apple approved these changes

2020-06-09 15:07 UTC, BroderickCarlin approved these changes

2020-06-09 17:38 UTC, gerickson requested changes
Minor word-smithing suggested.

2020-06-10 13:10 UTC, gerickson approved these changes

2020-06-10 13:10 UTC, merged