add initial keepSubscription feature
project-chip/connectedhomeip pull request #10339
Opened 2021-10-08 00:21 UTC by yunhanw-google

#### Problem
Need to implement KeepSubscriptions feature so that it can tear down the previous subscription when KeepSubscriptions = false, and run multiple subscription test continuously.

#### Change overview
See above

#### Testing
Add unit test and cirque python controller test to test multiple subscriptions，previous subscription would be kicked off by new subscription.

2021-10-08 14:25 UTC, msandstedt requested changes
~~I am concerned about this design.~~

~~In my mind, this is too much automatic logic in the InteractionModelEngine.  This uses state inside the engine in order to automatically determine whether the node (or engine) has reset and, therefore, all existing subscriptions with a given peer should be discarded.~~

~~The first problem with this is that this only works if the interaction model engine is a singleton.  The only singleton we ought to need is the subscription ID allocator.   We shouldn't be marching further down the IMEngine==singleton path if we don't have to.~~

~~The second problem is that this will only work if subscription / response messaging is fully serialized.  We do not have ordered messaging in the MRP layer, and message ordering is critical for the keep-subscriptions flag.  Consider multiple in-flight subscription requests where the first request has the keep-subscriptions=false and the second (and all subsequent) have keep-subscriptions=true.  These are not guaranteed to arrive or be processed in order, so the app has to strictly serialize by not issuing new requests until previous responses are received.  This imposes a per-peer subscribe interaction window of 1 for all time.~~

~~I just do not think that this is something that should be baked this deeply into the sdk.  The App has all of the context it needs to set this flag and set it correctly.  Why is the engine doing this on the app's behalf?~~

Edit: Discussed offline; I had misunderstood this PR as introducing a client-side mechanism to automatically set the KeepSubscriptions flag.  But this is only introducing support on the server side.

Makes sense.

2021-10-12 23:34 UTC, msandstedt approved these changes

2021-10-12 23:35 UTC, mrjerryjohns approved these changes

2021-10-12 23:42 UTC, msandstedt approved these changes

2021-10-13 00:35 UTC, jmartinez-silabs approved these changes

2021-10-13 00:44 UTC, merged