[Descriptor]: Support read attribute with complex type via AttributeAccessInterface for descriptor cluster
project-chip/connectedhomeip pull request #10374
Opened 2021-10-11 02:58 UTC by yufengwangca

#### Problem
What is being fixed?  Examples:
* Currently, our SDK does not support read attribute with complex type such as list well. For descriptor cluster, right now we are putting these lists in the attr store.  But we want to stop doing that and just create them on-the-fly using AttributeAccessInterface when read.

#### Change overview
Support read attribute with complex type via AttributeAccessInterface for descriptor cluster.

#### Testing
How was this tested? (at least one bullet point required)
* The client side change is still in progress, the server side change is temperately disabled by flag CHIP_CLUSTER_CONFIG_ENABLE_COMPLEX_ATTRIBUTE_READ. We will enable this flag until the client-side bits get done.
* The test is conducted with test client side change.

```
chip-device-ctrl > 
chip-device-ctrl > zclread Descriptor PartsList 12344321 0 0
[1633915768.491543][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x2 and protocolId (0, 1) on exchange 7561i with MessageCounter:2.
[1633915768.491639][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:2 to 0x0000000000BC5C01 at monotonic time: 196182278 msec
[1633915768.728309][429879:429887] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:2 on exchange 7561i
[1633915768.729738][429879:429887] CHIP:ZCL: ReadAttributesResponse:
[1633915768.729788][429879:429887] CHIP:ZCL:   ClusterId: 0x0000_001D
[1633915768.729816][429879:429887] CHIP:ZCL:   attributeId: 0x0000_0003
[1633915768.729837][429879:429887] CHIP:ZCL:   status: Success                (0x0000)
[1633915768.729856][429879:429887] CHIP:ZCL:   attribute TLV Type: 0x16
[1633915768.730152][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x1 and protocolId (0, 1) on exchange 7561i with MessageCounter:3.
[1633915768.730233][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:3 to 0x0000000000BC5C01 at monotonic time: 196182516 msec
AttributeReadResult(path=AttributePath(nodeId=12344321, endpointId=0, clusterId=29, attributeId=3), status=0, value=[0, 1, 2])
chip-device-ctrl > [1633915768.737316][429879:429887] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3 on exchange 7561i

chip-device-ctrl > zclread Descriptor ServerList 12344321 0 0
[1633915868.486598][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x2 and protocolId (0, 1) on exchange 7562i with MessageCounter:4.
[1633915868.486698][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:4 to 0x0000000000BC5C01 at monotonic time: 196282273 msec
[1633915868.505656][429879:429887] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:4 on exchange 7562i
[1633915868.506061][429879:429887] CHIP:ZCL: ReadAttributesResponse:
[1633915868.506074][429879:429887] CHIP:ZCL:   ClusterId: 0x0000_001D
[1633915868.506083][429879:429887] CHIP:ZCL:   attributeId: 0x0000_0001
[1633915868.506088][429879:429887] CHIP:ZCL:   status: Success                (0x0000)
[1633915868.506094][429879:429887] CHIP:ZCL:   attribute TLV Type: 0x16
[1633915868.506181][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x1 and protocolId (0, 1) on exchange 7562i with MessageCounter:5.
[1633915868.506203][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:5 to 0x0000000000BC5C01 at monotonic time: 196282292 msec
AttributeReadResult(path=AttributePath(nodeId=12344321, endpointId=0, clusterId=29, attributeId=1), status=0, value=[29, 40, 48, 49, 50, 51, 52, 53, 54, 55, 60, 62])
chip-device-ctrl > [1633915868.515807][429879:429887] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:5 on exchange 7562i

chip-device-ctrl > zclread Descriptor ClientList 12344321 0 0
[1633915885.193521][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x2 and protocolId (0, 1) on exchange 7563i with MessageCounter:6.
[1633915885.193555][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:6 to 0x0000000000BC5C01 at monotonic time: 196298980 msec
[1633915885.463107][429879:429887] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:6 on exchange 7563i
[1633915885.463915][429879:429887] CHIP:ZCL: ReadAttributesResponse:
[1633915885.463964][429879:429887] CHIP:ZCL:   ClusterId: 0x0000_001D
[1633915885.463993][429879:429887] CHIP:ZCL:   attributeId: 0x0000_0002
[1633915885.464012][429879:429887] CHIP:ZCL:   status: Success                (0x0000)
[1633915885.464042][429879:429887] CHIP:ZCL:   attribute TLV Type: 0x16
[1633915885.464304][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x1 and protocolId (0, 1) on exchange 7563i with MessageCounter:7.
[1633915885.464371][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:7 to 0x0000000000BC5C01 at monotonic time: 196299251 msec
AttributeReadResult(path=AttributePath(nodeId=12344321, endpointId=0, clusterId=29, attributeId=2), status=0, value=[])
chip-device-ctrl > [1633915885.477337][429879:429887] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:7 on exchange 7563i

chip-device-ctrl > zclread Descriptor DeviceList 12344321 0 0
[1633915924.126135][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x2 and protocolId (0, 1) on exchange 7564i with MessageCounter:8.
[1633915924.126244][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:8 to 0x0000000000BC5C01 at monotonic time: 196337912 msec
[1633915924.204321][429879:429887] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:8 on exchange 7564i
[1633915924.205390][429879:429887] CHIP:ZCL: ReadAttributesResponse:
[1633915924.205441][429879:429887] CHIP:ZCL:   ClusterId: 0x0000_001D
[1633915924.205480][429879:429887] CHIP:ZCL:   attributeId: 0x0000_0000
[1633915924.205500][429879:429887] CHIP:ZCL:   status: Success                (0x0000)
[1633915924.205526][429879:429887] CHIP:ZCL:   attribute TLV Type: 0x16
[1633915924.205803][429879:429887] CHIP:IN: Prepared encrypted message 0x23269a0 to 0x0000000000BC5C01 of type 0x1 and protocolId (0, 1) on exchange 7564i with MessageCounter:9.
[1633915924.205872][429879:429887] CHIP:IN: Sending encrypted msg 0x23269a0 with MessageCounter:9 to 0x0000000000BC5C01 at monotonic time: 196337992 msec
AttributeReadResult(path=AttributePath(nodeId=12344321, endpointId=0, clusterId=29, attributeId=0), status=0, value=[{0: 0, 1: 1}])
chip-device-ctrl > [1633915924.264006][429879:429887] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:9 on exchange 7564i
```

2021-10-11 08:58 UTC, jmeg-sfy approved these changes

2021-10-11 15:47 UTC, bzbarsky-apple requested changes

2021-10-11 17:10 UTC, bzbarsky-apple reviewed
Oh, one other issue: with this change, reporting is broken.  The old setup has the `emberAfPluginDescriptorServerInitCallback` call in `emberAfEndpointEnableDisable` which updates the stored values for the new topology.  But in the new setup, that's not going to do anything once we stop writing to the attr store from the init callback.  Instead, we need something to prod the reporting machinery when the set of enabled endpoints changes.

It's probably ok to have a followup for this so we can unblock the non-reporting use cases....

2021-10-11 22:18 UTC, woody-apple approved these changes

2021-10-12 19:59 UTC, bzbarsky-apple reviewed
This looks great, but the submodule changes should not be in this PR.

2021-10-12 22:25 UTC, bzbarsky-apple approved these changes

2021-10-12 22:42 UTC, yunhanw-google approved these changes

2021-10-12 22:51 UTC, jmartinez-silabs approved these changes

2021-10-12 22:53 UTC, merged