Fixes for building nRF5 platform
project-chip/connectedhomeip pull request #104
Opened 2020-03-24 20:28 UTC by pan-apple

#### Problem
Code for nRF5 platform is not getting built.

 #### Summary of Changes

1. Imported missing code
2. Removed dependency on `Profiles`
3. Fix code, and makefiles
4. Some code is heavily dependent on `Profiles` and other code that we are not importing. So that is still not being built (ConfigurationManager, ThreadStackManager, SoftwareUpdateManager)
5. Some code has been removed because of dependency on `Profiles`. Need to analyze that code, and bring it back with new framework.

ToDo: File issues for 4, and 5 above.

fixes #80

2020-03-24 20:29 UTC, woody-apple requested changes

2020-03-24 20:38 UTC, gerickson requested changes
There's a sufficiently large amount of commented out / changed code in here that I'd recommend determining a "breadcrumb" convention such that you / we know that we need to come back and revisit those breadcrumbs for those comment outs / changes.

2020-03-24 23:02 UTC, woody-apple approved these changes

2020-03-25 15:58 UTC, gerickson approved these changes

2020-03-25 16:00 UTC, hawk248 approved these changes
👍

2020-03-25 18:13 UTC, merged