Make Udp transport generic, prepare to add others (TCP, BLE, thread etc.)
project-chip/connectedhomeip pull request #1040
Opened 2020-06-09 12:55 UTC by andy31415

#### Problem
Need to integrate Weave message packing. Since WML as a whole did not get merged, adding piecewise transport bits.

 #### Summary of Changes
Major update to UDP transport:
- Created a base trasport defining typesafe calbacks and types. Prepare for a shared connection management implementation to maintain multiple connections as needed.
- Udp transport is not point to point anymore (since multip devices require single listening sockets). Expect transports to handle multiple connections, single connections set at higher levels
- Added header serialization and deserialization

Adjusted unit tests, updated device controller.

This is work towards #159

2020-06-09 15:24 UTC, gerickson requested changes
Looking good at a high-level. Some minor and moderate things to address.

2020-06-10 15:28 UTC, gerickson approved these changes

2020-06-10 17:33 UTC, woody-apple requested changes
Based on @sagar-apple & @pan-apple's comments. Can folks sync up on this this?

2020-06-12 16:36 UTC, saurabhst approved these changes
Subject to resolving the merge conflict

2020-06-16 17:29 UTC, woody-apple approved these changes

2020-06-16 17:29 UTC, merged