[ota-requestor-app] Reference implementation for AnnounceOTAProvider command
project-chip/connectedhomeip pull request #10434
Opened 2021-10-13 01:51 UTC by holbrookt

#### Problem
`ota-requestor-app` does not currently implement the OTA Requestor cluster nor does it accept or handle the `AnnounceOTAProvider` command.

In addition, the current `ota-requestor-app` implementation starts the OTA process immediately, which is not realistic or feasible for all platforms and not useful for certification or testing. `AnnounceOTAProvider` can be used to trigger the beginning of the OTA process.

* Fixes #9522

#### Change overview
* change `providerLocation` in `AnnounceOTAProvider` to be type `NODE_ID` instead of `BYTE_SPAN`
* add `emberAf*` callback for `AnnounceOTAProvider` and `ExampleOTARequestor` class for reusable application logic

#### Testing
Tested using an additional incoming PR which adds esp32 support. The linux `ota-requestor-app` cannot be used for testing because it cannot be commissioned and cannot receive commands from `chip-tool`.

2021-10-13 17:38 UTC, selissia approved these changes

2021-10-15 23:36 UTC, mrjerryjohns requested changes

2021-10-20 20:37 UTC, carol-apple approved these changes

2021-10-21 23:52 UTC, mrjerryjohns approved these changes
Thanks for the quick turnaround!

2021-10-22 00:32 UTC, holbrookt commented
Currently blocked by https://github.com/project-chip/connectedhomeip/issues/10818

2021-10-26 03:20 UTC, merged