[OperationalCredentials]: Support read attribute with complex type via AttributeAccessInterface
project-chip/connectedhomeip pull request #10459
Opened 2021-10-13 17:52 UTC by yufengwangca

#### Problem
What is being fixed?  Examples:
* Currently, our SDK does not support read attribute with list type in OperationalCredentials cluster, we want to create and encode the list attributes in OperationalCredentials cluster on-the-fly using AttributeAccessInterface when read.

#### Change overview
Support read attribute with complex type via AttributeAccessInterface

#### Testing
How was this tested? (at least one bullet point required)
The client bits to read the list attribute with new encoding is not ready, the test is conducted with my private python device controller.

```
chip-device-ctrl > zclread OperationalCredentials FabricsList 12344321 0 0
[1634146520.207612][907267:907275] CHIP:IN: Prepared encrypted message 0x27feb00 to 0x0000000000BC5C01 of type 0x2 and protocolId (0, 1) on exchange 31635i with MessageCounter:0.
[1634146520.207709][907267:907275] CHIP:IN: Sending encrypted msg 0x27feb00 with MessageCounter:0 to 0x0000000000BC5C01 at monotonic time: 365205347 msec
[1634146520.210678][907267:907275] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:1 on exchange 31635i
[1634146520.212128][907267:907275] CHIP:ZCL: ReadAttributesResponse:
[1634146520.212176][907267:907275] CHIP:ZCL:   ClusterId: 0x0000_003E
[1634146520.212211][907267:907275] CHIP:ZCL:   attributeId: 0x0000_0001
[1634146520.212239][907267:907275] CHIP:ZCL:   status: Success                (0x0000)
[1634146520.212275][907267:907275] CHIP:ZCL:   attribute TLV Type: 0x16
[1634146520.212668][907267:907275] CHIP:IN: Prepared encrypted message 0x27feb00 to 0x0000000000BC5C01 of type 0x1 and protocolId (0, 1) on exchange 31635i with MessageCounter:1.
AttributeReadResult(path=AttributePath(nodeId=12344321, endpointId=0, clusterId=62, attributeId=1), status=0, value=[{0: 1, 1: b'\x04\x8e!\xca>\xd6\x18]\x9b\xe6\xb7\xdc\x11\x7f\x9f\xb2\x9a\xd9Cv|_|\xb9ZoxE\xcda\xdclR:\x01\x04\x9f"\xbeJ]3\xf3\xa2\x90\x00gz\x14\x18\xf4z\xaa\xd3KJ\xd2\xa9e\xbb\x9b\x19\x06\x03Z', 2: 40896, 3: 0, 4: 12344321, 5: b''}, {0: 2, 1: b'\x04\x8e!\xca>\xd6\x18]\x9b\xe6\xb7\xdc\x11\x7f\x9f\xb2\x9a\xd9Cv|_|\xb9ZoxE\xcda\xdclR:\x01\x04\x9f"\xbeJ]3\xf3\xa2\x90\x00gz\x14\x18\xf4z\xaa\xd3KJ\xd2\xa9e\xbb\x9b\x19\x06\x03Z', 2: 40896, 3: 0, 4: 12344321, 5: b''}])
```

2021-10-13 18:06 UTC, andy31415 approved these changes

2021-10-13 18:09 UTC, yunhanw-google approved these changes
LGTM, thanks

2021-10-13 21:18 UTC, bzbarsky-apple requested changes

2021-10-14 15:37 UTC, bzbarsky-apple approved these changes

2021-10-14 15:51 UTC, saurabhst approved these changes

2021-10-14 16:09 UTC, bzbarsky-apple commented
@msandstedt @LuDuda @Damian-Nordic @saurabhst @jepenven-silabs @jmartinez-silabs Please take a look?

2021-10-14 16:17 UTC, jmartinez-silabs approved these changes

2021-10-14 16:27 UTC, merged