Remove use of GetDevice() from Python controller
project-chip/connectedhomeip pull request #10463
Opened 2021-10-13 19:51 UTC by pan-apple

#### Problem
Python controller app is using `GetDevice()` API to retrieve device object. This API doesn't trigger a CASE session establishment and relies on existing session. The usage of this should be replaced with `GetConnectedDevice()` API call.

#### Change overview
Replaced most calls to `GetDevice()` with `GetConnectedDevice()`.
`GetAddressAndPort()` doesn't require an active secure session. Replaced it with a new controller API to retrieve the address. This should eventually be replaced with a call to DNS cache.

#### Testing
Tested commissioning flow using the Python controller. Tested network commissioning (which uses the updated ZCL APIs) and calls to read attributes.

2021-10-13 20:56 UTC, woody-apple approved these changes

2021-10-13 21:45 UTC, bzbarsky-apple approved these changes

2021-10-13 22:06 UTC, jmartinez-silabs approved these changes

2021-10-15 06:34 UTC, erjiaqing approved these changes
Thanks.

I guess the next step is to create a corresponding device class in python later.

2021-10-15 06:38 UTC, erjiaqing requested changes
Please change the function signature.

We should return the device object and raise an error on failure.

2021-10-18 02:31 UTC, erjiaqing approved these changes

2021-10-18 02:31 UTC, merged