Update Command Path
project-chip/connectedhomeip pull request #10486
Opened 2021-10-14 08:39 UTC by yunhanw-google

#### Problem
Need to align command path with latest IM spec

#### Change overview
-- Rename CommandPath to CommandPathIB.
-- Remove group id from CommandPathIB

#### Testing
The existing tests covers.

2021-10-14 14:38 UTC, andy31415 approved these changes

2021-10-14 20:44 UTC, yufengwangca approved these changes

2021-10-15 04:16 UTC, bzbarsky-apple requested changes
The cluster changes here are wrong.  The path passed to cluster callbacks should in fact be a ConcreteCommandPath, not a CommandPathIB.  In particular it _must_ have a specific endpoint.  Otherwise there is no way to have the callbacks do their job properly.

When doing wildcarding or group-invoke, we need to convert those non-concrete paths to multiple calls into cluster logic, each with a concrete path.

Please read the invoke parts of the IM spec.

2021-10-15 04:30 UTC, bzbarsky-apple commented
> Need to align command path with latest IM spec

But that's not what this PR is doing....

> --Rename CommandPath to CommandPathIB and remove groupdId inside(spec remove that from commandPathIB)

The _IM_ spec has a group id inside CommandPathIB.

> --Add Type struct inside CommandPathIB

Why?  This is, in my opinion, a bad pattern that we should not have more of.  There's no reason CommandPathIB can't be the actual object type representing command paths, without the extra ::Type bit.

> that can replace the existing CommandPathParams and ConcretePathParams so that we can manage command path in one place.

This seems to be based on a misunderstanding of what sorts of command paths we have in the spec.

In the spec, there are at least three concepts of "command path":

1. The thing that gets encoded into the TLV.  This may or may not have an endpoint id but always has a cluster id and command id, it it's valid.
2. The IM CommandPathIB.  This can be reconstructed from the TLV bits and session information (the latter for node ids and group ids, plus determining whether missing endpoint id means "wildcard" or "group invoke").  This has either a node id and a (possibly wildcard) endpoint id or a group id.  In practice, the node id is _always_ the node id of the recipient, hence for our purposes we just need to keep track of whether the path is targeting a particular endpoint, all endpoints, or a particular group, plus
3. A concrete path.  See "8.8.2.3. Incoming Invoke Request Action" in the spec, the bits about concrete paths vs things that require "Request Path to Concrete Path Expansion".

What I think we should be doing is to have a CommandPathIB type that represents the IM CommandPathIB.  This type can be properly deserialized from a message only based on a combination of the message TLV and message metadata.  It cannot be reconstructed just from the TLV.

We should also have a separate ConcreteCommandPath.  We _could_ reuse CommandPathIB to represent that, in theory, since obviosly it _can_ represent a concrete path.  But it seems clearer to me to keep track of where our paths might be group/wildcard and where they're guaranteed to be concrete, such that you don't have to worry about the wildcarding.  The right boundary for that is probably about where we have the boundary right now: DispatchSingleClusterCommand.  The "Single" means we need a concrete path at that point.

Once we have group (and maybe wildcard) support, CommandHandler will need to desugar group/wildcard paths into concrete paths and call DispatchSingleClusterCommand one by one on the resulting set of concrete paths.

2021-10-20 19:40 UTC, bzbarsky-apple approved these changes
So there is no actual CommandPathIB _type_ yet, right?

If so, this seems fine.

2021-10-20 21:20 UTC, jmartinez-silabs approved these changes

2021-10-20 23:33 UTC, merged