[CI] Add Matter[Pre/Post]CommandReceivedCallback
project-chip/connectedhomeip pull request #10500
Opened 2021-10-14 14:16 UTC by vivien-apple

#### Problem

It uses to be a `emberAfPreCommandReceived` callback. This is useful in some contexts, notably in CI where you want to observer what is happening on the device.
This PR adds it back as `Matter[Pre/Post]CommandReceivedCallback(const chip::app::ConcreteCommandPath & commandPath)`

#### Change overview
 * Add `Matter[Pre/Post]CommandReceivedCallback(const chip::app::ConcreteCommandPath & commandPath)`
 * Update generated content

#### Testing
At the moment there is no consumer of this API but I'm planning to add some into some accessory test.

2021-10-14 17:22 UTC, bzbarsky-apple approved these changes

2021-10-15 18:50 UTC, mrjerryjohns requested changes

2021-10-22 16:39 UTC, woody-apple approved these changes

2021-11-02 16:20 UTC, vivien-apple commented
I have updated a bit the code so there is no stub generation anymore, but instead hardcoded stubs. This is not the final solution I would like but this will unlock CI so it is probably better to not wait for the final solution and land that as if.

2021-11-02 23:56 UTC, merged