[TE7]:Add GetNetworkInterfaces/ReleaseNetworkInterfaces APIs in ConnectivityMgr
project-chip/connectedhomeip pull request #10622
Opened 2021-10-18 18:01 UTC by yufengwangca

#### Problem
What is being fixed?  Examples:
* We need APIs to retrieve current network interfaces from the platform, this is needed for General Diagnostics.

#### Change overview
Add GetNetworkInterfaces/ReleaseNetworkInterfaces APIs in ConnectivityMgr

#### Testing
How was this tested? (at least one bullet point required)
* New unit tests were added to cover these APIs.

2021-10-19 04:48 UTC, bzbarsky-apple requested changes

2021-10-19 04:50 UTC, bzbarsky-apple commented
And as a general note: this API seems to presuppose heap-allocation of all the interface data.  Would it make more sense to have some API that hands out an iterator that you can get interface data from one at a time?

2021-10-22 04:15 UTC, bzbarsky-apple requested changes

2021-10-26 20:25 UTC, bzbarsky-apple approved these changes

2021-10-26 20:33 UTC, saurabhst approved these changes

2021-10-26 20:35 UTC, yunhanw-google approved these changes

2021-10-26 20:36 UTC, kpschoedel approved these changes

2021-10-26 20:41 UTC, merged