[Android] Generate cluster info mapping
project-chip/connectedhomeip pull request #10629
Opened 2021-10-18 20:38 UTC by JasonLiuZhuoCheng

#### Change overview
A new zapt file named ClusterInfo-java.zapt which generates all the required hierarchical relationship mapping for clusters, commands parameters and callbacks.

The new ClusterInfoMapping contains Map<String, ClusterInfo>. ClusterInfo contains a genetic clusterConstructor, which takes DevicePtr and endpointId to create the cluster. ClusterInfo also contains all the necessary information about commands, command parameters and all the types associated with the parameters.

The mapping is needed because on the UI side, it will be easy to trigger to correct function, i.e. `selectedCommandInfo.getCommandFunction().invokeCommand(selectedCluster, selectedCommandCallback, commandArguments)`

A new button on the cluster interaction tool that triggers the desired functions. For now, it is hard-coded to the on function from onOffCluster.

#### Testing
manually tested the on/off command from onOffCluster.

2021-10-19 02:57 UTC, austinh0 requested changes
Forgot to mark as request changes

2021-10-20 01:19 UTC, austinh0 requested changes

2021-10-21 00:54 UTC, austinh0 approved these changes

2021-10-23 00:32 UTC, woody-apple approved these changes

2021-10-23 00:33 UTC, merged