[Ameba] Remove python2 from dockerfile
project-chip/connectedhomeip pull request #10654
Opened 2021-10-19 11:52 UTC by pankore

#### Problem
To be aligned with the change applied in ameba sdk for fixing the 'python2: not found' issue in vscode instance build.

#### Change overview
Modification on dockerfile.

#### Testing
Tested with build_examples build without python2 installed.

2021-10-19 12:26 UTC, andy31415 requested changes
Two changes please:
   - this changes docker images, so please update the docker version
   - the `git clone` has to be from a fixed SHA so that docker builds are reproducible (builds today should be the same as builds 1 month from now)

2021-10-19 12:43 UTC, andy31415 approved these changes

2021-10-19 15:18 UTC, bzbarsky-apple approved these changes

2021-10-20 19:57 UTC, LuDuda approved these changes

2021-10-20 19:59 UTC, merged