Android add discover
project-chip/connectedhomeip pull request #10682
Opened 2021-10-20 02:51 UTC by joonhaengHeo

#### Problem
What is being fixed?  
* Android Test Application is not supported dns discover. (Python chip-ctrl-tool command is "discover -all")

#### Change overview
 - Add NsdManagerDiscoverService class.
 - Support discover function in AddressCommissioning activiry.

#### Testing
How was this tested? (at least one bullet point required)
* Check to be able to discover in Android App.

2021-10-20 02:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=10682) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=10682) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: austinh0<br/>:x: joonhaengHeo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=10682) it.</sub>

2021-10-20 19:48 UTC, bzbarsky-apple approved these changes

2021-10-21 00:25 UTC, austinh0 requested changes
Similar to what Damian said - if you are going to add `NsdManagerServiceDiscover` in the platform code, then you should also implement the platform [DnssdImpl::ChipDnssdBrowse](https://github.com/project-chip/connectedhomeip/blob/6e22d13c0ffa3e640d19b39a7755df8c1942b77e/src/platform/android/DnssdImpl.cpp#L78).

I can accept doing mDNS discovery purely in the app code (i.e. use `NsdManager` directly in the app), at least as a temporary solution, but we should not mix these two approaches. 

Will review the PR in more detail after this is resolved.

2021-10-21 00:50 UTC, joonhaengHeo commented
@austinh0 Does it mean that it should be implemented in a jni format similar to the implementation of Service Resolver?

2021-10-21 01:13 UTC, austinh0 commented
> @austinh0 Does it mean that it should be implemented in a jni format similar to the implementation of Service Resolver?

Ideally, yes. Service Resolver is used like so: 
`CHIPDeviceController::UpdateDevice` -> common native code -> `platform/android/DnssdImpl::ChipDnssdResolve` -> (Java) `ServiceResolver.resolve` -> (Java) `ChipMdnsCallback.handleServiceResolve` -> `AndroidChipPlatform-JNI::handleServiceResolve` -> `DnssdImpl::HandleResolve`

So I would expect mDNS browse to follow a similar path starting with `CHIPDeviceController:DiscoverCommissionableNodes`, with some Java `ServiceBrowser.browse`.

This is a fair amount of effort since you need to write Java -> C++ (and vice versa) translation for the `DnssdService` struct, which is why I mentioned I'm also ok with a simple app-only implementation that directly uses NsdManager as a temporary solution.

2021-10-29 02:29 UTC, austinh0 requested changes
Looks good overall.

Is there a reason we call `discoverCommissionableNodes`, wait, and the check `getDiscoveredDevice` instead of having some sort of callback method that is invoked when a device is discovered? I haven't looked at the native implementation in a while.

2021-11-01 02:52 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/ChipMdnsCallbackImpl.java
> +  }
OK. I understand.

2021-11-01 02:52 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/AndroidChipPlatform.java
>    }
OK. I understand.

2021-11-01 02:52 UTC, joonhaengHeo commented on src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/AddressCommissioningFragment.kt
> +      ipAddressList.add("${device.ipAddress},${device.discriminator}")
resolved.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/AddressCommissioningFragment.kt
> +    for(i: Int in 0..10) {
Resolved.
I confirmed that it is 10 in the code below.

https://github.com/project-chip/connectedhomeip/blob/master/src/controller/CHIPCommissionableNodeController.h#L69

https://github.com/project-chip/connectedhomeip/blob/8e62dd6794d86f73c7b3639c6b7633708b9530c5/src/include/platform/CHIPDeviceConfig.h#L1098

2021-11-01 02:53 UTC, joonhaengHeo commented on src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/AddressCommissioningFragment.kt
> +        override fun onNothingSelected(parent: AdapterView<*>?) {}
Resolved.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/NsdManagerServiceBrowse.java
> +public class NsdManagerServiceBrowse implements ServiceBrowse {
OK. I understand.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/AddressCommissioningFragment.kt
> +      updateSpinnerHandler.sendEmptyMessageDelayed(0, 5000)
Resolved.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/AddressCommissioningFragment.kt
> +        override fun onItemSelected(parent: AdapterView<*>?, view: View?, position: Int, id: Long) {
Resolved.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/AddressCommissioningFragment.kt
> +    private val ipAddressList = ArrayList<String>()
I agree that it doesn't have to be static.
The reason for not using DiscoveredDevice is that when creating a Spinner, if it is not a String, it is inconvenient to define a new class for spinner. Therefore, it is implemented using String.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/controller/java/CHIPDeviceController-JNI.cpp
> +    jclass discoveredDevicecls = env->FindClass("chip/devicecontroller/ChipDeviceController$DiscoveredDevice");
Resolved.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/controller/java/src/chip/devicecontroller/ChipDeviceController.java
> +  }
Resolved.

2021-11-01 02:53 UTC, joonhaengHeo commented on src/controller/java/src/chip/devicecontroller/ChipDeviceController.java
> +  public void discoverCommissionableNodes() {
Resolved.

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/AndroidChipPlatform.java
> +  private void setServiceResolver(
Resolved.

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/NsdManagerServiceBrowse.java
> +  private static final long DISCOVER_SERVICE_TIMEOUT = 3000;
Resolved. I will change to 5 sec. And, I also change to wait application delay to 6 sec.

AddressCommissioningFragment.kt
     scope.launch {
        delay(**6000**)
        updateSpinner()
        discoverBtn.isEnabled = true
      }

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/NsdManagerServiceBrowse.java
> +  private static final long DISCOVER_SERVICE_TIMEOUT = 3000;
After testing, delay value is changed to 7 sec.

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/NsdManagerServiceBrowse.java
> +    handler.sendMessageDelayed(msg, DISCOVER_SERVICE_TIMEOUT);
Resolved.

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/NsdManagerServiceBrowse.java
> +  private HashMap<Long, NsdManagerDiscovery> callbackMap = new HashMap<>();
Resolved.

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/NsdManagerServiceBrowse.java
> +    public void sendCallback() {
Resolved.

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/NsdManagerServiceResolver.java
> -                instanceName, serviceType, null, 0, callbackHandle, contextHandle);
I have restored it.
I was mistaken for an implementation before.

2021-11-01 02:54 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/ServiceBrowse.java
> +  /** TO-DO */
Updated.

2021-11-01 02:55 UTC, joonhaengHeo commented on src/platform/android/java/chip/platform/ServiceBrowse.java
> +}
Resolved.

2021-11-01 18:55 UTC, austinh0 approved these changes

2021-11-02 13:19 UTC, jmeg-sfy approved these changes

2021-11-02 14:04 UTC, andy31415 commented
/rebase

2021-11-02 16:28 UTC, merged