Initial cluster status code support
project-chip/connectedhomeip pull request #10732
Opened 2021-10-20 22:54 UTC by yunhanw-google

#### Problem
Add cluster status code support in IM command

#### Change overview
See above

#### Testing
Add unit test for status code validation

2021-10-21 23:09 UTC, yufengwangca approved these changes

2021-10-23 06:42 UTC, bzbarsky-apple requested changes

2021-10-25 20:55 UTC, bzbarsky-apple approved these changes

2021-10-25 22:12 UTC, jmartinez-silabs approved these changes

2021-10-26 03:32 UTC, erjiaqing requested changes
Python code change is required for this.

2021-10-26 07:30 UTC, erjiaqing approved these changes

2021-10-26 14:32 UTC, merged