Make clusters responsible for registering init/pre-attribute-changed/attribute-changed/message-sent callbacks instead of having an hardcoded list into our templates
project-chip/connectedhomeip pull request #10851
Opened 2021-10-22 16:23 UTC by vivien-apple

#### Problem

`src/app/zap-templates/templates/app/helper.js` contains an hardcoded list of cluster specific hooks.

This PR moves the responsibility of registering hooks to the cluster code itself. So instead of generating a list of functions at build time, clusters can register a list of functions during the plugin initialization.

#### Change overview
 * Update `examples/thermostat/linux/main.cpp` since this code was just trampolining the attribute changed
 * Remove `GENERATED_FUNCTION_ARRAYS` and the associated helpers from `helper.js`
 * Remove some generated declarations from `src/app/zap-templates/templates/app/callback.zapt` since the methods are now part of the cluster code itself.

#### Testing
I have manually verified that the init callbacks are called for some clusters, as well as the attribute changed callbacks.

#fixes 4369

2021-10-22 17:02 UTC, woody-apple approved these changes

2021-10-22 19:30 UTC, bzbarsky-apple approved these changes

2021-10-23 04:44 UTC, bzbarsky-apple requested changes
@vivien-apple OK, now we seem to be seeing a bunch of changes from rodata to data.  I think we should not do that and should have separate places for storing the mutable and immutable data here....

2021-11-04 14:11 UTC, woody-apple commented
@vivien-apple ?

2021-11-12 19:56 UTC, vivien-apple commented
I'm closing this one. I need to rework it in order to make things lives into `rodata` and the solution will requires some time and some different approach.

2021-11-12 19:56 UTC, closed without merging