Display endpoint list
project-chip/connectedhomeip pull request #10942
Opened 2021-10-26 02:06 UTC by JasonLiuZhuoCheng

#### Change overview
Display a list of endpoints on cluster-interaction screen. Now it is hard-coded to be 0 and 1. The endpoint list is implemented using recycler view. Also implemented customized onClickListener to go to cluster detail page after clicking on the endpoint list item.

#### Testing
manually tested.

2021-10-27 01:41 UTC, woody-apple approved these changes

2021-10-28 17:31 UTC, andy31415 approved these changes
Approve pending the removal of repeated TODO

2021-10-28 19:06 UTC, austinh0 requested changes
Please resolve the merge conflict in `src/android/CHIPTool/app/src/main/res/values/strings.xml`.

2021-10-29 02:47 UTC, austinh0 approved these changes

2021-10-29 22:03 UTC, JasonLiuZhuoCheng commented
@chrisdecenzo @Damian-Nordic @jelderton @jmartinez-silabs @saurabhst can you help review? Thanks!

2021-10-29 22:16 UTC, saurabhst approved these changes

2021-10-29 23:46 UTC, merged