Enable Docker-slim tool
project-chip/connectedhomeip pull request #10940
Opened 2021-10-26 01:29 UTC by electrocucaracha

#### Problem
[Docker-slim tool](https://dockersl.im/) allows to reduce the size of the Docker images and improve the time required to download the image during the CI execution.

#### Change overview
This flag enables the execution of the docker-slim tool in case this is installed. This change also includes ameba as part of the building images in the CI.

#### Testing
The following table displays the sizes of the images generated with the tool

| Name                                    | Original | Slim   |
|-----------------------------------------|----------|--------|
| connectedhomeip/chip-build              | 2.63GB   | 3.71MB |
| connectedhomeip/chip-build-ameba        | 4.15GB   | 3.71MB |
| connectedhomeip/chip-build-android      | 7.21GB   | 3.71MB |
| connectedhomeip/chip-build-cirque       | 3.19GB   | 3.71MB |
| connectedhomeip/chip-build-crosscompile | 5.2GB    | 3.71MB |
| connectedhomeip/chip-build-efr32        | 3.17GB   | 3.71MB |
| connectedhomeip/chip-build-esp32        | 5.49GB   | 3.71MB |
| connectedhomeip/chip-build-esp32-qemu   | 7.3GB    | 3.71MB |
| connectedhomeip/chip-build-infineon     | 4.73GB   | 3.71MB |
| connectedhomeip/chip-build-k32w         | 3.04GB   | 3.71MB |
| connectedhomeip/chip-build-mbed-os      | 2.64GB   | 3.71MB |
| connectedhomeip/chip-build-nrf-platform | 4.14GB   | 5.46MB |
| connectedhomeip/chip-build-telink       | 6.73GB   | 3.71MB |
| connectedhomeip/chip-build-tizen        | 3.48GB   | 3.71MB |
| connectedhomeip/chip-build-vscode       | 22.5GB   | 3.71MB |

2021-10-26 01:46 UTC, woody-apple approved these changes

2021-10-26 02:08 UTC, yunhanw-google approved these changes

2021-10-26 13:15 UTC, andy31415 requested changes
Changes requested: I belive the size changs are amazing, however I would like confirmation that the resulting images are usable for compilations. I would expect probably not - the PR probably needs extra instructions on how to build a usable  image.

VSCode *must* be bigger than the rest since it should be capable to compile everything.

2021-10-26 15:43 UTC, andy31415 requested changes

2021-11-04 13:59 UTC, andy31415 commented
Closing: I do not believe slim usage has sufficient stability to be consistently used. It seems suitable for long-running services but not as a build image base (it may remove unused headers and this would cause future builds trying to use such headers to fail)

2021-11-04 13:59 UTC, closed without merging