[IM] Move ReadClient callbacks to separate callback class
project-chip/connectedhomeip pull request #10963
Opened 2021-10-26 11:20 UTC by erjiaqing

#### Problem

Fixes #10573 

Move read / subscribe related callbacks to seperate class.

#### Change overview

- Move Read / Subscribe related callbacks to seperate class.

#### Testing

- This should be covered by existing test cases.

2021-10-27 04:08 UTC, bzbarsky-apple requested changes

2021-10-27 04:09 UTC, bzbarsky-apple requested changes
Oh, and please fix the typo in the commit message (not just in the PR title); should be "separate".

2021-10-29 04:39 UTC, yunhanw-google approved these changes

2021-10-30 02:01 UTC, bzbarsky-apple approved these changes

2021-11-01 01:43 UTC, erjiaqing commented
@Damian-Nordic @saurabhst  @msandstedt PTAL thanks

2021-11-01 15:29 UTC, andy31415 commented
fast track: several day old PR, created by domain owner with separate approval from another domain owner. General refactor of code.

2021-11-01 15:30 UTC, merged