Add SystemClock, SystemMutex, and SystemError
project-chip/connectedhomeip pull request #11
Opened 2020-03-04 22:58 UTC by sagar-apple

Added the first little bits for system as libSystemLayer.

Should help lay the foundation for more system components and other dependencies.

- Add SystemMutex and SystemError
- Add SystemClock to libSystemLayer.a 
- Add a sanity unit test for SystemMutex and SystemClock

Note this PR contains a pre-generated BuildConfig file since we do not currently have a way to autogen these. It will have to be swapped out at some later date.

2020-03-04 23:56 UTC, gerickson approved these changes

2020-03-05 01:38 UTC, woody-apple approved these changes

2020-03-06 21:13 UTC, robszewczyk requested changes
Per earlier discussion: copyright should be accumulative.  It does not seem quite right to just drop in `<COPYRIGHT>`

2020-03-07 01:14 UTC, robszewczyk approved these changes

2020-03-08 14:42 UTC, hawk248 approved these changes
OK

2020-03-08 15:15 UTC, merged