IM/ReadHandler: remove NodeId usage
project-chip/connectedhomeip pull request #11089
Opened 2021-10-27 21:35 UTC by kghost

#### Problem
In IM ReadHandler, we match different reader by comparing their node id which is grabbed from session. But we should compare the session directly.

#### Change overview
Comparing session instead of node in IM ReadHandler

#### Testing
Verified by unit-tests.

2021-10-27 21:47 UTC, LuDuda approved these changes

2021-10-27 22:01 UTC, emargolis approved these changes

2021-10-28 00:58 UTC, bzbarsky-apple approved these changes

2021-10-28 00:59 UTC, bzbarsky-apple requested changes
Actually, wait.  Why should a particular subscription be bound to a particular session?  Nothing requires that.....

2021-10-28 04:17 UTC, msandstedt requested changes
> Actually, wait. Why should a particular subscription be bound to a particular session? Nothing requires that.....

~~I believe the problem is slightly different than this.~~

~~I think is debatable whether it would actually be useful for any given subscription to span multiple sessions; I suspect it would not be.~~

What's happening in this PR is that we are disallowing subscriptions requests coming from the same node from canceling other subscriptions for that node associated with different sessions.  This is definitely incorrect.  The keep-subscriptions flag is associated with the initiator node, not a particular session.

So yes, this isn't correct.

Edit: bzbarsky-apple and kghost are also correct about the general notion of subscriptions spanning sessions.  I was thinking about exchanges, which cannot span multiple sessions.  But subscriptions comprise multiple exchanges.

2021-11-11 22:04 UTC, closed without merging