Integrate system tests to ESP32 QEMU and run in CI
project-chip/connectedhomeip pull request #1116
Opened 2020-06-13 23:27 UTC by pan-apple

#### Problem
`system` tests are not run on ESP32 QEMU.

 #### Summary of Changes
Integrate tests to ESP32 QEMU and CI.
Also run `Inet` tests on QEMU in CI.

2020-06-15 16:18 UTC, gerickson requested changes
Some minor tweaks around ESP32 conditionals.

2020-06-15 16:53 UTC, turon requested changes
Thanks for taking on running the SystemLayer tests on device.  There are a number of open issues in this space.

It would be great to generalize this work, where possible, to make sure general issues are resolved in a a way that can fix building these tests on nRF5 and EFR32 as well.

2020-06-15 18:45 UTC, gerickson approved these changes

2020-06-15 20:05 UTC, turon approved these changes

2020-06-16 14:55 UTC, woody-apple approved these changes

2020-06-16 14:55 UTC, merged

2020-06-16 14:56 UTC, saurabhst reviewed
Approved👍