Pull up LayerLwIP::ScheduleLambda to SystemLayer
project-chip/connectedhomeip pull request #11187
Opened 2021-10-29 12:19 UTC by kghost

#### Problem
`ScheduleLambda` is a convenient function, should be available on all platforms

#### Change overview
Pull up `LayerLwIP::ScheduleLambda` to SystemLayer

Implement `ScheduleLambdaBridge` for `LayerImplLibevent` and `LayerImplSelect`

#### Testing
Verified by unit-tests

2021-10-29 12:57 UTC, Damian-Nordic requested changes

2021-10-29 17:48 UTC, Damian-Nordic approved these changes

2021-11-01 16:46 UTC, andy31415 approved these changes
Looks good to me except please convert struct to class and delete the `@file` comments.

2021-11-01 16:46 UTC, andy31415 commented on src/lib/support/LambdaBridge.h
> +struct LambdaBridge
why is this a struct instead of a class? It seems that the way it is declared resembles more a class.

2021-11-01 16:46 UTC, andy31415 commented on src/system/SystemLayer.cpp
> + *      This file implements LayerImplLwIP using LwIP.
please stop using `@file` comments in the source code. They very easily suffer from copy & paste inaccuracies (this seems like one of those instances) and provide no useful info to code readers, often  just restating the file name and using up vertical space.

2021-11-01 16:50 UTC, kghost commented on src/system/SystemLayerImplSelect.cpp
> +    CHIP_ERROR err = ScheduleWork(RunScheduledLambda, this);
I made `LwIPEventSupport` universal, not it will use it for all platforms.

2021-11-02 13:57 UTC, merged

2021-11-03 00:12 UTC, bzbarsky-apple commented
@kghost Note that this was reverted because it broke various platforms...