InetLayer/SystemLayer use C++11 singleton patter instead of global variable
project-chip/connectedhomeip pull request #11184
Opened 2021-10-29 09:55 UTC by kghost

#### Problem
The constructor order of global variables are not controllable

#### Change overview
use C++11 singleton patter for InetLayer/SystemLayer

#### Testing
Verified by unit-tests

2021-10-29 16:52 UTC, kpschoedel requested changes
Need to retain a straightforward way to mock `System::Layer`.

2021-11-01 14:21 UTC, kpschoedel approved these changes

2021-11-01 15:49 UTC, msandstedt approved these changes

2021-11-01 21:19 UTC, emargolis approved these changes

2021-11-02 15:09 UTC, mspang commented on src/platform/Globals.cpp
> +#ifndef NDEBUG
I think it needs to be possible to run tests in "release" builds. Testing is orthogonal to debugging.

2021-11-02 15:30 UTC, woody-apple approved these changes

2021-11-02 21:22 UTC, merged