Increase commissioning session establishment timeout
project-chip/connectedhomeip pull request #11470
Opened 2021-11-05 13:26 UTC by doru91

Signed-off-by: Doru Gucea <doru-cristian.gucea@nxp.com>

#### Problem
Second admin commissioning was failing on K32W platform due to timeout - see the logs

[second_admin_logs.txt](https://github.com/project-chip/connectedhomeip/files/7486277/second_admin_logs.txt)
[device_logs.txt](https://github.com/project-chip/connectedhomeip/files/7486279/device_logs.txt)

#### Change overview
Increase the commissioning timeout. This is just a temporary solution until optimizations are being applied.

#### Testing
Manual testing

2021-11-05 14:58 UTC, andy31415 commented
@pan-apple ?

40 seconds seems huge. We bumped it up from 10 secons to 30 yesterday I believe ... now 40. Do we actually believe that we are this slow?

2021-11-05 15:02 UTC, andy31415 commented
Given occasional darwin failures, I actually wonder if we are somehow dealing with packet loss rather than just slowness.

2021-11-05 17:56 UTC, cecille commented
Is this really a timeout issue? If you look in the logs, right at the bottom, it looks like the timeout is going much earlier than 40 seconds

controller sends sigma one at 1636034575.403011. Timeout isn't timestamped, but it happens before the sigma2 is received back at 1636034579.113697. To me, that looks like about 4 seconds, which corresponds to what the device says (3430 ms).

controller:
```
[1636034575.402768][16181:16188] CHIP:IN: Sending msg on generic transport
[1636034575.403011][16181:16188] CHIP:SC: Sent SigmaR1 msg
[1636034578.274423][16181:16188] CHIP:CTL: SyncSetKeyValue on StartKeyID
Failed to establish secure session to device: 50
CHIP Error 0x00000032: Timeout
chip-device-ctrl > [1636034579.113697][16181:16188] CHIP:EM: Received message of type 0x31 with vendorId 0x0000 and protocolId 0x0000 on exchange 45886i
```

device sending back sigma 2:
```
[162266][P][IN]Build plaintext message 0x400c1d0 to 0x0000000000000000 of type 49 and protocolId 0 on exchange 45886i with MessageCounter 4115307905.
[162280][P][IN]Sending plaintext msg 0x400c1d0 to 0x0000000000000000 at utc time: ld msec
[162288][P][IN]Sending msg on generic transport
[162294][D][DL]Thread packet SENT: UDP, len 751
[162298][D][DL]    src  FD11:22::902D:60D4:BBE0:DFED, port 5540
[162304][D][DL]    dest 2A02:2F0F:D00E:2600:DEA6:32FF:FEA5:D8D9, port 39741
[162312][D][SC]Sent SigmaR2 msg
[162315][E][DL]Long dispatch time: 3430 ms, for event type 4
```

2021-11-05 18:52 UTC, andy31415 requested changes
I believe this is packet loss rather than more timeout increase.

Please try to confirm if this is really a timeout (and if so, what makes 40s work but not 30s ... a lot of computation can be done in 30s and it is probably a solid threshold for users to not want to wait that long)

2021-11-06 03:13 UTC, bzbarsky-apple approved these changes

2021-11-09 17:52 UTC, woody-apple commented
@pan-apple ?

2021-11-23 19:05 UTC, closed without merging