fix warnings
project-chip/connectedhomeip pull request #115
Opened 2020-03-25 21:50 UTC by rwalker-apple

#### Problem
 A couple of errant warnings from newly added code

 #### Summary of Changes
 Fixups

2020-03-25 22:19 UTC, gerickson requested changes

2020-03-25 23:24 UTC, woody-apple approved these changes
Agree with @gerickson

2020-03-26 02:02 UTC, BroderickCarlin approved these changes

2020-03-26 15:59 UTC, hawk248 approved these changes
👍

2020-03-26 21:37 UTC, gerickson approved these changes

2020-03-26 21:38 UTC, merged