Add a "TimeSource" class
project-chip/connectedhomeip pull request #1153
Opened 2020-06-17 16:02 UTC by andy31415

#### Problem
System layer time source is a 'real' time source, making it hard to unit test time-dependent things. I would like to implement connection expiring logic, and controlling system time seems very useful in those instances.

 #### Summary of Changes
Adds a templated 'time source' class which can be switched to either the test time source or keep using the system time.

This was my first idea, but it will start propagating templates around. if there are other suggestions to be able to control time for tests (maybe weak linkage or maybe our extern timesources could be swizzled at link time) please let me know. I find this should be clean enough, but if other methods are considered cleaner I would be interested to see them. This should have been a problem already in all other projects that handle time.

This is working towards #1088
fixes #1156 because I had qemu errors and I needed to see what failed.

2020-06-17 16:39 UTC, gerickson requested changes
@andy31415, please sync up with @robszewczyk who has been in the process of open sourcing Nest's "Plaid" time manipulation framework for some time that will address this issue without propagating templates around.

2020-06-18 14:35 UTC, gerickson approved these changes

2020-06-18 14:47 UTC, woody-apple approved these changes
@rwalker-apple ?

2020-06-18 14:50 UTC, woody-apple reviewed
/pullapprove-test

```
version: 3

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - len(groups.approved.include('reviewer-groups-*')) >= 3
        reviews:
            required: 3

    ############################################################
    #  Reviewer Groups
    ############################################################
    reviewer-groups-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-amazon
    reviewer-groups-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-apple
    reviewer-groups-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-comcast
    reviewer-groups-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-google
    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-samsung
```

2020-06-18 19:44 UTC, saurabhst approved these changes

2020-06-18 21:13 UTC, robszewczyk approved these changes

2020-06-18 21:15 UTC, merged