Clean up Security Header structure and add missing fields, tests
project-chip/connectedhomeip pull request #1175
Opened 2020-06-18 19:06 UTC by pan-apple

#### Problem
Security header needs clean up, and addition of some missing fields. Also, need more unit tests. 

 #### Summary of Changes
Added fields, and tests. The header may still change based on ongoing discussions. Current structure is based on feedback from Secure Channel TT.

fixes #1028

2020-06-18 19:10 UTC, andy31415 requested changes
Is security header encrypted or unencrypted?

If it is unencrypted, it should go into MessageHeader,  so that we have a single header to manage. MessageHeader is encoded/decoded and should be passed along any required send/receive paths already.

2020-06-18 19:40 UTC, woody-apple reviewed
/pullapprove-test

```
version: 3

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

2020-06-18 20:39 UTC, BroderickCarlin approved these changes

2020-06-19 13:14 UTC, andy31415 approved these changes

2020-06-19 14:39 UTC, jelderton approved these changes

2020-06-19 16:36 UTC, woody-apple approved these changes

2020-06-19 16:52 UTC, merged