Remove sleep calls from transport network IO tests
project-chip/connectedhomeip pull request #1237
Opened 2020-06-24 14:41 UTC by andy31415

Add max wait time and completion function for IO loops.
Tested that unit tests in transport now are very fast.

fixes #1073

2020-06-24 14:44 UTC, gerickson requested changes
Needs to work for LwIP.

2020-06-24 18:30 UTC, woody-apple approved these changes

2020-06-25 17:12 UTC, saurabhst approved these changes

2020-06-26 15:39 UTC, gerickson approved these changes
LGTM now that we have the issue filed for cleaning up the cross-module shared infrastructure.

2020-06-29 13:35 UTC, robszewczyk approved these changes

2020-06-29 13:38 UTC, merged