support logging of arbitrary binary payload
project-chip/connectedhomeip pull request #1249
Opened 2020-06-24 20:19 UTC by rwalker-apple

#### Problem
 hoping a binary string will "just print" seems error-prone

 #### Summary of Changes
 sanitize to something like "od -c"

2020-06-24 21:09 UTC, woody-apple approved these changes

2020-06-25 13:41 UTC, andy31415 approved these changes

2020-06-25 21:59 UTC, woody-apple requested changes
I like @andy31415 's suggestions, and also needs merge fix :)

2020-06-26 14:40 UTC, woody-apple approved these changes

2020-06-26 20:39 UTC, saurabhst approved these changes

2020-06-26 20:40 UTC, merged