Add dependency on pigweed
project-chip/connectedhomeip pull request #1264
Opened 2020-06-25 08:37 UTC by mspang

Pigweed is a open source project containing libraries and tools for
embedded development. It provides a package management system that
downloads versioned development tools including ARM GCC, cmake, GN,
ninja, openocd, and python on Linux, Mac, & Windows. These packages are
hosted by Google in CIPD, which is part of Chrome's open source
infrastructure.

Using the tools provided by pigweed is not required, but having the
option of using a reproducible development environment is useful,
especially for new developers.
    
Usage:
    source pw_bootstrap.sh  # first time and after an update
    source activate.sh  # setup environment from prior bootstrap

Depends on https://github.com/project-chip/connectedhomeip/pull/1262

2020-06-25 13:21 UTC, andy31415 approved these changes
Generally looks good as it gets developers started faster.

CIPD usage may need be discussed separately - are there alternatives or could we provide docs on how others (e.g. china) may setup their own CIPD so that things do not look locked down.

2020-06-25 21:26 UTC, jelderton approved these changes
Seems fine, but wasn't sure if that CHIP_ROOT was getting changed or not

2020-06-25 21:58 UTC, woody-apple requested changes

2020-06-26 14:40 UTC, woody-apple approved these changes

2020-06-26 15:47 UTC, merged