[Inet] InetIterator::GetHardwareAddress for LwIP
project-chip/connectedhomeip pull request #12687
Opened 2021-12-07 17:18 UTC by kpschoedel

#### Problem

1b2413793424 (#12552) added `InetIterator::GetHardwareAddress()`,
with an implementation for Zephyr and stubs for other builds.

#### Change overview

Implement `GetHardwareAddress()` for LwIP builds.

(For sockets builds, there is no cross-platform access to the
hardware MAC. Linux could use `SIOCGIFHWADDR`.)

#### Testing

CI (test from #12552)

2021-12-07 17:20 UTC, woody-apple approved these changes

2021-12-07 18:00 UTC, Damian-Nordic approved these changes

2021-12-07 18:01 UTC, Damian-Nordic requested changes

2021-12-07 18:01 UTC, Damian-Nordic commented on src/inet/InetInterface.cpp
> +    VerifyOrReturnError(addressSize >= mCurNetif->hwaddr_len, CHIP_ERROR_BUFFER_TOO_SMALL);
```suggestion
    VerifyOrReturnError(addressBufferSize >= mCurNetif->hwaddr_len, CHIP_ERROR_BUFFER_TOO_SMALL);
```

2021-12-08 08:27 UTC, Damian-Nordic approved these changes

2021-12-08 14:34 UTC, andy31415 approved these changes

2021-12-08 14:35 UTC, merged