[Network Commissioning] Update NetworkCommissioning Cluster define
project-chip/connectedhomeip pull request #12875
Opened 2021-12-10 09:00 UTC by erjiaqing

#### Problem

- Update network commissioning cluster define to align with latest spec.

#### Change overview

- Update .zap files
- Rerun codegen
- Update chip-tool code to use updated commands

#### Testing
* CI should still pass after this PR is finished.

2021-12-10 09:43 UTC, Damian-Nordic approved these changes

2021-12-10 09:47 UTC, Damian-Nordic commented
Could you also update the Python CHIP controller docs after renaming the commands?

2021-12-10 16:49 UTC, yufengwangca approved these changes

2021-12-10 17:12 UTC, woody-apple requested changes
This seems to imply we support multiple WiFi and or thread networks, but we don’t?

2021-12-13 03:12 UTC, erjiaqing commented
> This seems to imply we support multiple WiFi and or thread networks, but we don’t?

This PR is focusing on basic renaming, and not the full functions, a refactor of network commissioning cluster is at https://github.com/project-chip/connectedhomeip/pull/12931

2021-12-13 16:14 UTC, woody-apple approved these changes

2021-12-13 20:16 UTC, merged