[openthread] fix build when thread disabled (CHIP_ENABLE_OPENTHREAD=0).
project-chip/connectedhomeip pull request #1287
Opened 2020-06-26 04:34 UTC by turon

#### Problem
There are build issues on NRF5 when OpenThread support is disabled.

 #### Summary of Changes
Fixes the issues.

2020-06-26 04:35 UTC, saurabhst approved these changes

2020-06-26 13:57 UTC, andy31415 approved these changes

2020-06-26 20:38 UTC, woody-apple requested changes
Marking as changes, pending @andy31415 & @gerickson's comments

2020-07-01 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=1287) it.</sub>

2020-07-09 09:06 UTC, closed without merging