[platform] Fix friend functions to handle strict C++11 toolchains.
project-chip/connectedhomeip pull request #1290
Opened 2020-06-26 05:06 UTC by turon

#### Problem
Some toolchains report an error if the friend functions in device layer aren't in parenthesis.

 #### Summary of Changes
Fix the friend functions as required.

2020-06-26 05:07 UTC, saurabhst approved these changes

2020-06-26 14:02 UTC, andy31415 approved these changes

2020-06-26 14:30 UTC, woody-apple approved these changes

2020-06-26 14:37 UTC, woody-apple requested changes
@turon looks like this broke ESP32

2020-07-01 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=1290) it.</sub>

2020-07-06 17:54 UTC, woody-apple commented
@turon can you rebase this? Might help

2020-07-09 02:25 UTC, woody-apple commented
ping @turon

2020-07-09 09:05 UTC, closed without merging