[linux] Use new chip SHA256 class to re-implement CHIP provisioning …
project-chip/connectedhomeip pull request #1302
Opened 2020-06-26 17:18 UTC by yufengwangca

#### Problem
CHIP provisioning hash logic within configuration manager is temporarily disabled and wait for final CHIP SHA256 implementation.  

 #### Summary of Changes
* SHA256 class for CHIP is merged. Replace legacy SHA256 with chip::Crypto::Hash_SHA256_stream in configuration manager
* Enable flag CHIP_DEVICE_CONFIG_LOG_PROVISIONING_HASH

fixes #<1166>

2020-06-26 18:06 UTC, woody-apple approved these changes

2020-06-26 18:09 UTC, saurabhst approved these changes

2020-06-26 18:41 UTC, gerickson requested changes
This regresses important functionality.

2020-06-26 19:04 UTC, woody-apple requested changes
Let's move move off of our current platform malloc

2020-07-01 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1302) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1302) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=1302) it.</sub>

2020-07-02 21:14 UTC, yufengwangca commented
need re-open after re-fork the master branch

2020-07-02 21:14 UTC, closed without merging