[esp32] Add lighting example
project-chip/connectedhomeip pull request #13174
Opened 2021-12-21 06:50 UTC by chshu

#### Problem
Somehow, a simple Lighting example is missing for ESP platform. The all-cluster-app is too complex as a lighting device reference.

#### Change overview
Add lighting example for ESP platform, also add the new ESP32-S3 platform support.

#### Testing
Verified on ESP32, ESP32-C3, ESP32-S3.

2021-12-21 09:46 UTC, gjc13 approved these changes

2021-12-21 09:46 UTC, gjc13 commented on examples/lighting-app/esp32/main/DeviceCallbacks.cpp
> +    VerifyOrExit(endpointId == 1 || endpointId == 2, ESP_LOGE(TAG, "Unexpected EndPoint ID: `0x%02x'", endpointId));
If endpoint 2 doesn't really have a handler, shall we consider removing it?

2021-12-21 20:03 UTC, bzbarsky-apple approved these changes

2021-12-21 20:03 UTC, bzbarsky-apple commented on examples/lighting-app/esp32/main/DeviceCallbacks.cpp
> +    case ZCL_ON_OFF_CLUSTER_ID:
Please use the namespaced cluster ids (app::Clusters:OnOff:Id, etc).  If you `using namespace chip::app::Clusters;` those can be quite short.

2021-12-21 20:03 UTC, bzbarsky-apple commented on examples/lighting-app/esp32/main/DeviceCallbacks.cpp
> +    VerifyOrExit(attributeId == ZCL_ON_OFF_ATTRIBUTE_ID, ESP_LOGI(TAG, "Unhandled Attribute ID: '0x%04x", attributeId));
Please use the namespaced attribute ids (`Clusters::OnOff::Attributes::OnOff::Id`, etc).  Again, sane use of `using` keeps the verbosity down.

2022-01-04 16:03 UTC, andy31415 requested changes
Please also add build_examples.py support for compilation.

2022-01-07 22:30 UTC, bzbarsky-apple commented
/rebase

2022-01-07 23:02 UTC, andy31415 approved these changes

2022-01-08 05:37 UTC, merged