Add an option in KConfig for the esp32 demo app to choose the Rendezv…
project-chip/connectedhomeip pull request #1329
Opened 2020-06-29 09:06 UTC by vivien-apple

…ous mode of the peripheral

 Add an option in Kconfig for the esp32 demo app to choose the Rendezvous mode of the peripheral. It will allow more customisation of the startup process of the demo app.

By default the rendezvous mode is set to SoftAP since the Ble part if not fully ready right now.

2020-06-29 11:27 UTC, kedars approved these changes

2020-06-29 11:37 UTC, saurabhst approved these changes

2020-06-29 12:16 UTC, gerickson requested changes
Requested a bit more richness in the Kconfig descriptions.

2020-06-29 20:06 UTC, woody-apple approved these changes

2020-07-01 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1329) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=1329) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=1329) it.</sub>

2020-07-01 20:17 UTC, smides-nest commented on examples/wifi-echo/server/esp32/main/Kconfig.projbuild
> +      config RENDEZVOUS_MODE_SOFTAP
I think Wi-Fi makes more sense. Within Rendezvous TT we've decided that all devices shall implement a SoftAP-based setup mechanism + whatever else we determine (now in the Wi-Fi Setup TT). There's no optionality that a device will support one or the other, so if you're able to be commissioned over Wi-Fi, you must support them all.

Hope that helps clarify.

2020-07-01 20:17 UTC, woody-apple commented on examples/wifi-echo/server/esp32/main/Kconfig.projbuild
> +      config RENDEZVOUS_MODE_SOFTAP
@vivien-apple ?

2020-07-01 20:44 UTC, vivien-apple commented
Closing in favour of #1408. I rename Soft-AP -> WIFI there.

2020-07-01 20:44 UTC, closed without merging