ESP:Remove ApplyUpdateRequest console command from ESP ota-requestor-app
project-chip/connectedhomeip pull request #13567
Opened 2022-01-14 06:49 UTC by wqx6

#### Problem
Now the OTARequestor can send the ApplyImage command to the OTAProvider and apply the image downloaded, so we don't need the ApplyUpdateRequest console command now.

#### Change overview
Remove ESPConsole in ota-requestor-app of ESP platform.

#### Testing
Test with ESP32C3 manually.

2022-01-14 07:27 UTC, bzbarsky-apple approved these changes

2022-01-14 08:06 UTC, dhrishi approved these changes

2022-01-14 18:41 UTC, shubhamdp commented
@wqx6 it was removed in the PR: https://github.com/project-chip/connectedhomeip/pull/13532/files#diff-c6bbfef87fb989e354f8724a4beec08e5f5fa963254d8607ee563496d35886a0

2022-01-15 04:32 UTC, carol-apple approved these changes

2022-01-15 04:56 UTC, dhrishi requested changes
@wqx6 Please check if these changes are already in and if this PR is now needed (as per the comment from @shubhamdp )

2022-01-17 02:55 UTC, wqx6 commented
Close this PR since #13532 merged

2022-01-17 02:55 UTC, closed without merging