[chip-tool] Use an onDone callback when reading events
project-chip/connectedhomeip pull request #13582
Opened 2022-01-14 14:32 UTC by vivien-apple

#### Problem

`./out/debug/standalone/chip-tool testcluster read-event test-event 0x12345 1` waits forever if no events exists.
This is because the `ReadEvent` API does not inform the caller of the completion of the request.

#### Change overview
 * Add a `onDoneCb` argument
 * Improve logging by passing the event header up to the success/error callbacks
 
#### Testing
`./out/debug/standalone/chip-tool testcluster read-event test-event 0x12345 1`  now returns.

2022-01-14 15:42 UTC, andy31415 commented on examples/chip-tool/templates/commands.zapt
> +void LogEventHeader(const chip::app::EventHeader & eventHeader)
This function does not seem to depend on  parameters  given to the template. Please move to a propper C++/header as there is no reason for this to be "codegen".

2022-01-14 15:42 UTC, andy31415 commented on examples/chip-tool/templates/commands.zapt
> +static void OnDefaultEventFailure(void * context, const chip::app::EventHeader & eventHeader, EmberAfStatus status)
No need to codegen this either.

2022-01-14 15:43 UTC, andy31415 requested changes
Changes requested for not adding non-generated code to codegen.

Complex codegen is harder to  review (no syntax highlighting), cannot be unit tested easily, is duplicated in many placed.

2022-01-14 18:55 UTC, mrjerryjohns requested changes

2022-01-14 18:55 UTC, mrjerryjohns commented on src/controller/ReadInteraction.h
> +                     typename TypedReadEventCallback<DecodableEventType>::OnSubscriptionEstablishedCallbackType onDoneCb = nullptr)
If the expectation of this function is that you're trying to read out a specific type of event, and if you don't actually get any of those events, shouldn't that be interpreted as an error (in the context of this function)?

If so, I don't think adding a onDone cb is quite right - rather, it should call `onErrorCb`.

2022-01-19 10:19 UTC, vivien-apple commented
Closing this one. I have an other approach.

2022-01-19 10:19 UTC, closed without merging