Separate out client and server clusters in IDL
project-chip/connectedhomeip pull request #13636
Opened 2022-01-17 20:08 UTC by andy31415

#### Problem
Zigbee data model has client and server clusters.

This does not make sense in matter as client clusters could be on any endpoint. 

#### Change overview
List server  clusters on endpoints, all other clusters are marked  as 'uses' to help review in what is being code-generated.

#### Testing
IDL generated.

2022-01-17 22:37 UTC, andy31415 commented
/rebase

2022-01-18 13:53 UTC, bzbarsky-apple commented
> This does not make sense in matter as client clusters could be on any endpoint.

Not true if bindings are going to work.  Client clusters on devices like light switches need to be on a specific endoint that you can then bind to things.

Client clusters on things like phone apps or whatnot, that don't implement any server bits at all, can do whatever, of course.

2022-01-18 13:53 UTC, bzbarsky-apple requested changes
The endpoint a client cluster is on matters.

2022-01-18 13:55 UTC, bzbarsky-apple commented on src/app/zap-templates/templates/chip/helper.js
> +function if_server_side(options)
Oh and the normal idiom here is:
```
{#if (isServer side)}}
```

2022-01-18 14:07 UTC, andy31415 commented
Had chat with @bzbarsky-apple - it seems that the data model that zap exposes for clusters is representing 'bindings'.

I will close the PR and add side in some form inside the endpoint.

2022-01-18 14:07 UTC, closed without merging