Setting the endpoint_id of all the uninitialized endpoints to invalid…
project-chip/connectedhomeip pull request #13814
Opened 2022-01-21 11:45 UTC by chiragatal

… instead of 0

#### Problem
Fixing corner cases where dynamic endpoints are added and removed.

#### Change overview
* Setting the endpoint IDs for uninitialized or removed endpoints to EMBER_AF_INVALID_ENDPOINT instead of setting it to 0.
* reference: https://github.com/project-chip/connectedhomeip/pull/12934#discussion_r769262073

#### Testing
* Added and removed dynamic endpoints multiple times.
* Removed an endpoint and added another one on the same index.

2022-01-21 12:31 UTC, dhrishi approved these changes

2022-01-21 12:32 UTC, dhrishi commented
@bzbarsky-apple PTAL, wrt your comment https://github.com/project-chip/connectedhomeip/pull/12934#discussion_r769262073

2022-01-21 13:30 UTC, andy31415 approved these changes

2022-01-21 15:01 UTC, msandstedt approved these changes

2022-01-22 04:23 UTC, bzbarsky-apple requested changes
So first of all, EMBER_AF_INVALID_ENDPOINT is actually set to a value which is a valid endpoint id (in Matter, which has a different range of endpoint ids than Zigbee).  So that would need to change at the very least.

But past that, I am trying to understand the underlying problem here that #12934 was trying to solve.  Why would endpoint 0 be a dynamic endpoint?  Is this a device with _only_ dynamic endpoints configured?

2022-01-24 06:16 UTC, chiragatal commented
Updated the EMBER_AF_INVALID_ENDPOINT to 0xFFFF.

> Is this a device with only dynamic endpoints configured?

Yes, experimenting to create all the endpoints dynamically.

2022-01-25 03:22 UTC, bzbarsky-apple approved these changes

2022-01-25 03:22 UTC, bzbarsky-apple commented on src/app/util/attribute-storage.cpp
> +            emAfEndpoints[ep].endpoint = EMBER_AF_INVALID_ENDPOINT;
```suggestion
            emAfEndpoints[ep].endpoint = kInvalidEndpointId;
```

2022-01-25 03:22 UTC, bzbarsky-apple commented on src/app/util/attribute-storage.cpp
> +    if (id == EMBER_AF_INVALID_ENDPOINT)
```suggestion
    if (id == kInvalidEndpointId)
```

2022-01-25 03:22 UTC, bzbarsky-apple commented on src/app/util/attribute-storage.cpp
> +    if ((index < MAX_ENDPOINT_COUNT) && (emAfEndpoints[index].endpoint != EMBER_AF_INVALID_ENDPOINT) &&
```suggestion
    if ((index < MAX_ENDPOINT_COUNT) && (emAfEndpoints[index].endpoint != kInvalidEndpointId) &&
```

2022-01-25 07:31 UTC, chiragatal commented on src/app/util/attribute-storage.cpp
> +            emAfEndpoints[ep].endpoint = EMBER_AF_INVALID_ENDPOINT;
Changed

2022-01-25 07:31 UTC, chiragatal commented on src/app/util/attribute-storage.cpp
> +    if (id == EMBER_AF_INVALID_ENDPOINT)
Changed

2022-01-25 07:31 UTC, chiragatal commented on src/app/util/attribute-storage.cpp
> +    if ((index < MAX_ENDPOINT_COUNT) && (emAfEndpoints[index].endpoint != EMBER_AF_INVALID_ENDPOINT) &&
Changed

2022-01-25 08:03 UTC, dhrishi commented
/rebase

2022-01-25 11:16 UTC, merged