Use FabricIndex instead of CompressedFabricId inside PeerId
project-chip/connectedhomeip pull request #13834
Opened 2022-01-21 21:19 UTC by kghost

#### Problem
`PeerId` is tuple of `<NodeId, CompressedFabricId>`, but `CompressedFabricId` is only being used in mDNS, on the other hand `FabricIndex` is mostly used everywhere.

#### Change overview
Change `PeerId` into tuple of `<NodeId, FabricIndex>`
For mDNS, add another class `PeerInfo`, which holds `<NodeId, CompressedFabricId>` as same as `PeerId` as before. mDNS will focus on `PeerInfo`

#### Testing
Verified by unit-tests.

2022-01-22 03:06 UTC, bzbarsky-apple commented on src/lib/core/PeerId.h
> +        if (mFabricIndex == kUndefinedFabricIndex)
So this `operator==` is not symmetric, right?  If `this` has `mFabricIndex == kUndefinedFabricIndex` but `other` does not, then we could have `*this == other` but `other != *this`.

Is this purposeful?  It's not a great behavior for an `operator==`.

2022-01-22 03:07 UTC, bzbarsky-apple commented
Also, not sure about the naming....  In particular, which should be PeerInfo and which should be PeerId.

> Use ObjectPool for DnssdCache::mLookupTable and ActiveResolveAttempts::mRetryQueue

Can this part be a separate PR, please?

2022-01-23 15:45 UTC, msandstedt commented
> Also, not sure about the naming.... In particular, which should be PeerInfo and which should be PeerId.
> 
> > Use ObjectPool for DnssdCache::mLookupTable and ActiveResolveAttempts::mRetryQueue
> 
> Can this part be a separate PR, please?

I was just discussing this naming with some others.  We have two concepts in the spec that can help us:

* Operational ID: the tuple <root CA public key, fabric ID, node ID>
* Operational Instance Name: compressedFabricId-nodeID

We should be able to somehow leverages these.

2022-01-23 15:51 UTC, msandstedt requested changes
1. PeerInfo and PeerId are both bad names.  We need something else.  As noted elsewhere, we ought to be able to leverage these spec concepts:

* Operational ID: the tuple <root CA public key, fabric ID, node ID>
* Operational Instance Name: compressedFabricId-nodeID

2. The SDK must be able to conceive of nodes without necessarily holding a fabric table.  For instance, it is absolutely possible to commission nodes without being on the fabric.  We must not formalize a concept in the sdk that precludes this.

Can't we just have an OperationalId that holds <Crypto::P256PublicKey, FabricId, NodeID>?  If it's large, pass it by reference...

2022-01-27 05:10 UTC, woody-apple commented
Fast tracking, given > 3 business days for review.

2022-02-11 04:18 UTC, closed without merging