Remove uses of "pragma message" for unsuppressable warnings
project-chip/connectedhomeip pull request #1445
Opened 2020-07-06 03:17 UTC by mspang

Compiling this file generates unsuppressable output when certain lwIP
options are disabled. If these configurations are legal, then merely
compiling shouldn't print out an objection to them. If they are truly
not intended to be used, the lwIP configs for the examples should be
corrected.

Fixes #1444

2020-07-06 13:54 UTC, andy31415 approved these changes

2020-07-06 15:23 UTC, gerickson requested changes
Any suggested alternative outside of removing these?

2020-07-06 16:00 UTC, woody-apple approved these changes

2020-07-06 18:16 UTC, mspang commented
> Any suggested alternative outside of removing these?

The description suggests one: enable these in the examples (and probably turn it into an #warning in that case if we really don't intend to allow this combination).

If we intend to allow it and still want to give a hint we could handle it via documentation, or alternatively add another #define like CHIP_SUPPRESS_CONFIG_RECOMMENDATIONS so there's an opt out. Currently it is impossible to make the examples build clean of diagnostic messages and the goal is mainly to make it possible.

2020-07-06 18:40 UTC, BroderickCarlin approved these changes

2020-07-07 16:26 UTC, gerickson approved these changes

2020-07-07 16:27 UTC, merged