Add missing parts in Bridged Device Basic Info cluster
project-chip/connectedhomeip pull request #14620
Opened 2022-02-01 07:09 UTC by yufengwangca

#### Problem
What is being fixed?  Examples:
* Bridged Device Basic Info cluster xml definition is out of date, we need to update it to align with the latest spec

#### Change overview
Add missing parts in Bridged Device Basic Info cluster

#### Testing
How was this tested? (at least one bullet point required)
* xml definition update only

2022-02-01 17:14 UTC, andy31415 approved these changes

2022-02-01 23:55 UTC, saurabhst approved these changes

2022-02-02 00:02 UTC, bzbarsky-apple requested changes

2022-02-02 01:24 UTC, yufengwangca commented on src/app/zap-templates/zcl/data-model/chip/bridged-device-basic.xml
> +        <event side="server" code="0x00" name="StartUp" priority="critical" optional="false">
It overwrote the conformance from Basic Information Cluster

2022-02-02 04:50 UTC, bzbarsky-apple approved these changes

2022-02-02 14:06 UTC, merged