Fix Engine::ScheduleRun() in case callback function done before ScheduleWork() returns. (#14596)
project-chip/connectedhomeip pull request #14697
Opened 2022-02-02 13:17 UTC by lnikulin

#### Problem
* Fixes #14596 Incorrect processing in Engine::ScheduleRun()

#### Change overview
setup 'mRunScheduled = true' before execute ScheduleWork() to avoid case when scheduled callback has been done before  ScheduleWork() returns

2022-02-02 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=14697) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=14697) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=14697) it.</sub>

2022-02-02 14:04 UTC, andy31415 approved these changes

2022-02-02 18:00 UTC, yufengwangca approved these changes

2022-02-02 19:00 UTC, mrjerryjohns requested changes
This doesn't actually fix the core issue. If there are multiple threads calling `ScheduleRun`, this all still breaks.

The correct solution (and resultant analysis needed) is posted in the original issue.

2022-02-02 19:01 UTC, mrjerryjohns approved these changes

2022-02-03 06:32 UTC, bzbarsky-apple requested changes
Yes, this does not seem like the right fix.  Let's follow up in #14596 to figure out what's going on here.

2022-02-10 01:50 UTC, mrjerryjohns requested changes
Given the updates in the related issue, this should be closed.

2022-02-10 01:50 UTC, closed without merging