Remove TODOs and code in application launcher cluster
project-chip/connectedhomeip pull request #14975
Opened 2022-02-09 20:38 UTC by lazarkov

#### Problem
- TODOs were not removed from application launcher cluster code

#### Issues reported
This PR will resolve these reported issues:
https://github.com/project-chip/connectedhomeip/issues/14424
https://github.com/project-chip/connectedhomeip/issues/14425

#### Change overview
see above

#### Testing
Run `./scripts/run_in_build_env.sh \  
                  "./scripts/tests/run_test_suite.py \
                     --chip-tool ./out/debug/standalone/chip-tool \
                     run \
                     --iterations 1 \
                     --all-clusters-app ./out/debug/standalone/chip-all-clusters-app \
                     --tv-app ./out/debug/standalone/chip-tv-app \
                  "`

2022-02-09 20:52 UTC, andy31415 approved these changes

2022-02-10 04:05 UTC, bzbarsky-apple commented on src/app/clusters/application-launcher-server/application-launcher-server.cpp
>      return aEncoder.Encode(currentApp);
But ... this is not returning null.  Should it?

2022-02-10 04:05 UTC, bzbarsky-apple requested changes

2022-02-10 04:05 UTC, bzbarsky-apple commented on src/app/clusters/application-launcher-server/application-launcher-server.cpp
>      return aEncoder.Encode(currentApp);
Per the issue this is claiming to resolve, it should.

Should this be:
```
    return aEncoder.EncodeNull();
```
?

2022-02-11 06:34 UTC, bzbarsky-apple approved these changes

2022-02-11 06:53 UTC, merged