Add submodules for nlio, nlassert and nlunit-test
project-chip/connectedhomeip pull request #15
Opened 2020-03-07 00:10 UTC by pan-apple

Adding git submodules for third party libraries.

The PR has checked out a specific commit of the individual git project.

An alternate approach is to copy the source code directly into third_party folder (and removing corresponding `.git` folders in the libraries). Upgrading to a newer release of these libraries will be complicated in future.

2020-03-07 00:18 UTC, gerickson requested changes

2020-03-07 01:04 UTC, gerickson approved these changes

2020-03-07 01:05 UTC, woody-apple approved these changes

2020-03-07 01:13 UTC, robszewczyk approved these changes

2020-03-08 14:16 UTC, hawk248 approved these changes
ok

2020-03-08 15:17 UTC, merged