Add cosmetic_enabled to config cosmetic
project-chip/connectedhomeip pull request #15242
Opened 2022-02-16 09:25 UTC by TE-N-ElvenWang

Some build integration environment cannot work with pw_build which is
imported by default_configs_cosmetic. So add a variable to ignore it.

TEST:
gn gen --args="cosmetic_enabled=false"
ninja -C

Signed-off-by: Haoran Wang <elven.wang@nxp.com>

#### Problem
What is being fixed?  Examples:
As the default cosmetic using pw_build and it will include all pw_build related module into it.
For regular build environment, there is no problem. But for some special environment which don't want to build pw_build it will make it force to build.
The reason why I make this change is because of issue #15191  and with the --args="cosmetic_enabled=false" the default Python2.7 in my integration environment can make the target complete successfully. 

Actually I'm not very sure whether this is the best solution, hope maintainers can give some comments in it.

2022-02-16 14:29 UTC, andy31415 reviewed
Python2 has been sunsetted since January 1 2020:

https://www.python.org/doc/sunset-python-2/#:~:text=We%20have%20decided%20that%20January,as%20soon%20as%20you%20can.

2022-02-16 14:32 UTC, andy31415 commented
I can understand not maybe wanting to colorize, however to not use pw_build in general is probably not possible or something we want to maintain. Same for python2 support - we have a requirement of python3 and that seems reasonable given the dates of python2 sunsetting and python3 availability.

2022-02-16 14:34 UTC, andy31415 requested changes
```
src/darwin/Framework/chip_xcode_build_connector.sh
95:    'default_configs_cosmetic=[]' # suppress colorization
```

can we use that instead of adding another flag in the build?

2022-02-16 14:45 UTC, TE-N-ElvenWang commented
> ```
> src/darwin/Framework/chip_xcode_build_connector.sh
> 95:    'default_configs_cosmetic=[]' # suppress colorization
> ```
> 
> can we use that instead of adding another flag in the build?

Thank you for your reply and explain about python2.  Actually when I was trying to fix my issue, I tried to overrite "default_configs_cosmetic" to null. In the generated "args.gn", it does overwrite to []. But the build.ninja still included the pw_build related phony. Is there anything I missed?

2022-02-17 06:23 UTC, bzbarsky-apple approved these changes

2022-02-17 16:40 UTC, andy31415 commented
> > ```
> > src/darwin/Framework/chip_xcode_build_connector.sh
> > 95:    'default_configs_cosmetic=[]' # suppress colorization
> > ```
> > can we use that instead of adding another flag in the build?
> 
> Thank you for your reply and explain about python2. Actually when I was trying to fix my issue, I tried to overrite "default_configs_cosmetic" to null. In the generated "args.gn", it does overwrite to []. But the build.ninja still included the pw_build related phony. Is there anything I missed?

I thought pw_build is a required thing.
My comment is that if we desire to disable coloring, this seems to be possible today. If we have a desire to 'support python2 for compilation' that is not something that we are working towards in the SDK and the reasoning seems sound enough for me (2-year old deprecated already). I am explicitly *not* approving an attempt for python2 support for V1 development.

2022-02-17 16:42 UTC, andy31415 commented
Maybe @mspang ping for ideas on the build system and regarding pw_build, if there are workarounds.

I am not willing to accept code complexity to add python2 support, however if there are workarounds or reasonable changes that do not increase complexity, then that may be ok.

2022-02-17 17:03 UTC, mspang commented
What's breaking for you when pw_build/BUILD.gn is loaded ?

2022-02-18 00:41 UTC, TE-N-ElvenWang commented
> > > ```
> > > src/darwin/Framework/chip_xcode_build_connector.sh
> > > 95:    'default_configs_cosmetic=[]' # suppress colorization
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > can we use that instead of adding another flag in the build?
> > 
> > 
> > Thank you for your reply and explain about python2. Actually when I was trying to fix my issue, I tried to overrite "default_configs_cosmetic" to null. In the generated "args.gn", it does overwrite to []. But the build.ninja still included the pw_build related phony. Is there anything I missed?
> 
> I thought pw_build is a required thing. My comment is that if we desire to disable coloring, this seems to be possible today. If we have a desire to 'support python2 for compilation' that is not something that we are working towards in the SDK and the reasoning seems sound enough for me (2-year old deprecated already). I am explicitly _rejecting_ an attempt for python2 support for V1 development.

Very appreciate for your comments.
I agree with you that we cannot add python2 support in it. And just like my question ticket in #15191 and I'm checking how to config python environment to force use python3. But looks not easy to achieve that. Also modifying current codes is not what we expecting. This PR is only one of my idea for adding optional pretty outputing configs for bypassing my issue for now.
A workaround for using existing configuration would be best for us. As after V1, we will also switch the environment totally to the Python3 one.
Thanks.

2022-02-18 04:46 UTC, andy31415 commented
I am unsure about the environment unfortunately.

One option would be to use docker or podman to setup an environment where you have full control over what python is installed. Alternatively virtualenv is the typical path. If that does not work but you have ptyhon3, could you make `python` as python3 to be aliased or found first in the path?

Thinking ideas like `alias python=python3` or maybe `mkdir -p $HOME/bin/overrides && ln -s /usr/bin/python3 /usr/bin/overrides/python && export PATH="$HOME/bin/overrides:$PATH` or some workaround like that.

overall our build system relies on python a lot and bootstrap.sh is setting up a python3 virtualenv.

2022-02-19 00:36 UTC, mspang commented
See my answers in https://github.com/project-chip/connectedhomeip/issues/15191

2022-02-20 01:09 UTC, TE-N-ElvenWang commented
@mspang @andy31415 
Very appreciate for your great help and comments. Now I got the way without this change to bypass my issue. This PR can be close directly. 
Thanks!

2022-02-20 01:09 UTC, closed without merging