fix: devicetype ID for temperature-sensor fixed. Sample sets fixed te…
project-chip/connectedhomeip pull request #15421
Opened 2022-02-22 18:01 UTC by rochaferraz

#### Problem
* No commissioning QR code link shown on logs from temperature-measurement app
* Device ID show on second endpoint is nottemperature-measurement-app/esp32/main/temperature-measurement.zap temperature-measurement

#### Change overview
* QR is printed
* Value of temperature is set to 20C at startup
* Device ID changed on ZAP file to temperature-measurement

#### Testing
* Tested on ESP32 M5 unit

2022-02-23 02:00 UTC, andy31415 commented
/rebase

2022-02-23 05:07 UTC, andy31415 commented
/rebase

2022-02-23 06:43 UTC, bzbarsky-apple commented on examples/temperature-measurement-app/esp32/main/main.cpp
> +    EmberAfStatus status = emberAfWriteAttribute(1, ZCL_TEMP_MEASUREMENT_CLUSTER_ID, ZCL_TEMP_MEASURED_VALUE_ATTRIBUTE_ID,
Please use the type-safe attibute accessors.

2022-02-23 06:46 UTC, bzbarsky-apple requested changes
Need to use type-safe accessors.

2022-02-23 06:46 UTC, bzbarsky-apple commented
Also, shouldn't this be a PR against master?

2022-02-24 22:26 UTC, rochaferraz commented
Purpose of commit is mostly to test interoperability of this temperature sample in this branch. Master has time-format-localization-server cluster, which doesn't build/exists in this branch.

I can eventually push a similar PR to master too.

2022-02-25 04:25 UTC, bzbarsky-apple approved these changes

2022-03-02 17:52 UTC, woody-apple commented
@rochaferraz By default, we don't allow branches on the main repo outside of master. Can this work be done on a fork?

2022-03-03 15:15 UTC, closed without merging

2022-03-03 15:16 UTC, rochaferraz commented
Yup, no problem, thanks.