Pr/cluster/tempmeasure
project-chip/connectedhomeip pull request #15821
Opened 2022-03-03 18:58 UTC by yufengwangca

#### Problem
What is being fixed?  Examples:
* MaxMeasuredValue needs to be between -27314 to 32767 , but SDK is reporting -32768.

* Fixes #9864

#### Change overview
Fix MaxMeasuredValue is out of range Temperature Measurement Cluster

#### Testing
How was this tested? (at least one bullet point required)
```
yufengw@yufengw-SEi:~/connectedhomeip/out/debug/standalone$ ./chip-tool temperaturemeasurement read measured-value 
.....
[1646333860.006585][34569:34574] CHIP:DMG: ReportDataMessage =
[1646333860.006589][34569:34574] CHIP:DMG: {
[1646333860.006592][34569:34574] CHIP:DMG: 	AttributeReportIBs =
[1646333860.006598][34569:34574] CHIP:DMG: 	[
[1646333860.006601][34569:34574] CHIP:DMG: 		AttributeReportIB =
[1646333860.006606][34569:34574] CHIP:DMG: 		{
[1646333860.006610][34569:34574] CHIP:DMG: 			AttributeDataIB =
[1646333860.006614][34569:34574] CHIP:DMG: 			{
[1646333860.006618][34569:34574] CHIP:DMG: 				DataVersion = 0x9651a08a,
[1646333860.006622][34569:34574] CHIP:DMG: 				AttributePathIB =
[1646333860.006626][34569:34574] CHIP:DMG: 				{
[1646333860.006630][34569:34574] CHIP:DMG: 					Endpoint = 0x1,
[1646333860.006634][34569:34574] CHIP:DMG: 					Cluster = 0x402,
[1646333860.006638][34569:34574] CHIP:DMG: 					Attribute = 0x0000_0000,
[1646333860.006642][34569:34574] CHIP:DMG: 				}
[1646333860.006646][34569:34574] CHIP:DMG: 					
[1646333860.006650][34569:34574] CHIP:DMG: 					Data = NULL
[1646333860.006654][34569:34574] CHIP:DMG: 			},
[1646333860.006658][34569:34574] CHIP:DMG: 			
[1646333860.006662][34569:34574] CHIP:DMG: 		},
[1646333860.006666][34569:34574] CHIP:DMG: 		
[1646333860.006670][34569:34574] CHIP:DMG: 	],
[1646333860.006674][34569:34574] CHIP:DMG: 	
[1646333860.006678][34569:34574] CHIP:DMG: 	SuppressResponse = true, 
[1646333860.006681][34569:34574] CHIP:DMG: 	InteractionModelRevision = 1
[1646333860.006684][34569:34574] CHIP:DMG: }
[1646333860.006739][34569:34574] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0402 Attribute 0x0000_0000DataVersion: 2521931914
[1646333860.006759][34569:34574] CHIP:TOO:   MeasuredValue: null

```

2022-03-03 21:27 UTC, woody-apple approved these changes

2022-03-04 06:21 UTC, bzbarsky-apple requested changes

2022-03-04 06:21 UTC, bzbarsky-apple commented on src/app/clusters/temperature-measurement-server/temperature-measurement-server.cpp
> +        requested = static_cast<int16_t>(chip::Encoding::LittleEndian::Get16(value));
This is wrong, I believe.  `value` is native-endian, not little-endian, as far as I know.  Same for the other attributes.

2022-03-04 06:21 UTC, bzbarsky-apple commented on src/app/clusters/temperature-measurement-server/temperature-measurement-server.cpp
> +        if (requested < (MinMeasuredValue.IsNull() ? kMinMeasuredValueLowerLimit : MinMeasuredValue.Value()))
We should pull `ValueOr` into `Nullable` and use that here.  Followup fine for this part.

2022-03-04 06:21 UTC, bzbarsky-apple commented on src/app/clusters/temperature-measurement-server/temperature-measurement-server.cpp
> +        else if (requested > (MaxMeasuredValue.IsNull() ? kMaxMeasuredValueUpperLimit : MaxMeasuredValue.Value()))
This is going to disallow setting the attribute to null, no?  Was this tested?  Same for the other attributes.

2022-03-04 06:21 UTC, bzbarsky-apple commented on src/app/clusters/temperature-measurement-server/temperature-measurement-server.cpp
> +Protocols::InteractionModel::Status MatterTemperatureMeasurementClusterServerPreAttributeChangedCallback(
I am wondering why this is here at all.  The attributes are not writable.  Are we trying to protect the app author from accidentally setting an invalid value?  But this is also forcing them to set min/max/measured in the right order, which is not documented anywhere....

2022-03-05 04:06 UTC, yufengwangca commented
Per sync offline, we will not enforce the range check in SDK, but just assume that the device maker will not set the invalid value. All temperature attributes shall be null if their value is unknown.

2022-03-05 06:10 UTC, bzbarsky-apple approved these changes
Thank you!

2022-03-07 13:53 UTC, andy31415 approved these changes

2022-03-07 13:57 UTC, merged