[gn] Simplify Support::CHIPMem build.
project-chip/connectedhomeip pull request #1592
Opened 2020-07-14 05:43 UTC by turon

#### Problem
When a source file is wrapped internally to activate when the configuration macros are passed, then we can simplify the build to just include all files.

 #### Summary of Changes
Perform such a simplification for `support/CHIPMem`

2020-07-14 05:52 UTC, rwalker-apple approved these changes
lgtm

2020-07-14 12:56 UTC, andy31415 approved these changes
At some point we should pull out the #ifdefs from the alloc cpp files (after autotools is changed).

2020-07-14 12:58 UTC, andy31415 requested changes
I actually read the patch in reverse: why do we want to compile the files and rely on #ifdef macros to include or not functions inside the alloc. This looks backwards to me - we should fix autotools instead.

2020-07-14 12:59 UTC, andy31415 commented
> I actually read the patch in reverse: why do we want to compile the files and rely on #ifdef macros to include or not functions inside the alloc. This looks backwards to me - we should fix autotools instead.

I will leave it to spang@ about best practices, but this seems backwards to me - if I see 'foo.cpp' being compiler, I assume it has useful code. if foo.cpp contains a '#ifdef FOO_ENABLED...' and then I compile and get nothing, that is very confusing.

2020-07-14 15:16 UTC, mspang commented
It causes a warning on Mac if we build a static library containing a file with no symbols.

2020-07-14 15:19 UTC, mspang commented
> It causes a warning on Mac if we build a static library containing a file with no symbols.

Chrome has a wrapper for Mac's libtool to suppress these warnings, so another solution is to adopt such a wrapper to suppress the warning.

2020-07-14 15:21 UTC, mspang requested changes
Marking request changes. We should have some way to avoid the warning.

2020-07-14 15:59 UTC, andy31415 approved these changes
Created #1595 to figure out some way to to standardize things or get a decision if the #ifdef pattern is a pattern we want to stick with. 

Generally the pattern is alien to me (I expect that I only compile what I need and if I compile something, that something is generating output), however if this is somehow standard across many libraries I can live with it. Marking approve on this one for now.

2020-07-14 16:06 UTC, woody-apple approved these changes

2020-07-14 17:54 UTC, turon commented
> I actually read the patch in reverse: why do we want to compile the files and rely on #ifdef macros to include or not functions inside the alloc. This looks backwards to me - we should fix autotools instead.

2020-07-14 18:26 UTC, mspang commented
> > I actually read the patch in reverse: why do we want to compile the files and rely on #ifdef macros to include or not functions inside the alloc. This looks backwards to me - we should fix autotools instead.
> 
> @andy31415 Thanks for opening #1595. @mspang I agree we need a workaround for empty file warnings on Mac -- any ideas on how to do that?

Three ideas

1. Wrap libtool with a script that filters out uninteresting warnings. Chrome does this.
2. Do nothing? No warning if we conditionally compile the file.
3. (hacky) Add some unused symbol to the file.

> 
> I'm not super opinionated on small adjustments like this, but I can say that large systems such as CHIP tend to have many ways to pass configuration:
> 
> 1. through the build system (thus building hard dependencies and maintenance requirements on those build systems that are supported)
> 2. through C defines and config.h headers
> 3. both
> 
> In order to better decouple the codebase from any particular build system, OpenThread as a project had agreed upon and moved to a model where most configuration was passed via (2). This PR is exploiting the fact that (2) is in place already for CHIPMem, and therefor decoupling that config from GN. For consistency, the PR should probably make the parallel updates to autotools as well.

2020-07-16 16:33 UTC, BroderickCarlin approved these changes

2020-07-20 18:09 UTC, woody-apple commented
@andy31415 @mspang next steps?

2020-07-22 04:29 UTC, mspang commented
> @andy31415 @mspang next steps?

I would like to hold the line on avoiding uninteresting build output as this can drown out useful information. Here is the script Chrome uses to squelch uninteresting libtool warnings on Mac:

https://chromium.googlesource.com/chromium/src.git/+/master/build/toolchain/mac/filter_libtool.py

2020-07-22 18:58 UTC, jelderton approved these changes

2020-07-30 22:15 UTC, woody-apple commented
@turon Can we address @mspang 's feedback here?

2020-07-31 18:04 UTC, turon commented
Closing until more general mechanisms for handling empty file warnings are in place.

2020-07-31 18:04 UTC, closed without merging