[chiptest] Network-independent RPC server shutdown
project-chip/connectedhomeip pull request #15954
Opened 2022-03-08 11:00 UTC by Arkq

#### Problem
Terminating app-register RPC server with the usage RPC call itself might cause troubles in case when the network connection is not reliable (e.g. no route to the server). When this will happen, the test runner will not terminate properly (in my case it happens always):
```
$ ./scripts/tests/run_test_suite.py --target-glob "DL_LockUnlock" run 
2022-03-08 11:52:34.880 INFO    Ensuring /run is privately accessible
2022-03-08 11:52:35.043 INFO    Waiting for IPv6 DaD to complete (no tentative addresses)
2022-03-08 11:52:36.764 INFO    No more tentative addresses
2022-03-08 11:52:36.765 INFO    Each test will be executed 1 times
2022-03-08 11:52:36.765 INFO    Starting iteration 1
2022-03-08 11:52:39.482 INFO    DL_LockUnlock        - Completed in 2.72 seconds         <- here it stuck until RPC call timeout
^C
Aborted!
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

#### Change overview

- This commit simplifies the shutdown process by using dedicated shutdown method.

#### Testing

Now command `./scripts/tests/run_test_suite.py --target-glob "DL_LockUnlock" run` exits properly (no Ctrl-C required).

2022-03-16 14:56 UTC, andy31415 commented
@vivien-apple ?

2022-03-16 16:10 UTC, Arkq commented
I'd be glad if that PR could be merged, because, somehow, in my setup this "not clean" tests shutdown occurs all the time...

2022-03-16 17:29 UTC, woody-apple approved these changes

2022-03-16 17:29 UTC, woody-apple commented
Fast tracking given this has had enough time for review.

2022-03-21 13:47 UTC, andy31415 requested changes
@Arkq - could you explain the `when the network is not reliable`? 

run_test_suite.py is generally created to run local unit tests, in which case the network should always be quite reliable (either localhost or containers).

Or is this not running local unit tests?
This is why I requested feedback from @vivien-apple - where is this proxy used? Is this fix ok or not?

Generally I do not understand the problem or implications of the fix.

2022-03-22 08:03 UTC, Arkq commented
> run_test_suite.py is generally created to run local unit tests, in which case the network should always be quite reliable (either localhost or containers)

OK, so I can explain my setup. I'm running tests locally on Ubuntu 20.04 (not in the docker container). I'm running it as follows:
```sh
source scripts/activate.sh
./scripts/tests/run_test_suite.py --target "TestSystemCommands" run   # only one test, but when running all test the issue is the same
```
output (after the line "TestSystemCommands   - Completed in 3.55 seconds" it hangs for ~60 seconds (network timeout)):
```
2022-03-22 08:51:14.220 INFO    Ensuring /run is privately accessible
2022-03-22 08:51:14.444 INFO    Waiting for IPv6 DaD to complete (no tentative addresses)
2022-03-22 08:51:16.363 INFO    No more tentative addresses
2022-03-22 08:51:16.365 INFO    Each test will be executed 1 times
2022-03-22 08:51:16.366 INFO    Starting iteration 1
10.10.10.2 - - [22/Mar/2022 08:51:18] "POST / HTTP/1.1" 200 -
10.10.10.2 - - [22/Mar/2022 08:51:18] "POST / HTTP/1.1" 200 -
10.10.10.2 - - [22/Mar/2022 08:51:18] "POST / HTTP/1.1" 200 -
10.10.10.2 - - [22/Mar/2022 08:51:18] "POST / HTTP/1.1" 200 -
2022-03-22 08:51:19.919 INFO    TestSystemCommands   - Completed in 3.55 seconds
Traceback (most recent call last):
  File "./scripts/tests/run_test_suite.py", line 241, in <module>
    main()
  File "/home/a.bokowy/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/a.bokowy/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/a.bokowy/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/a.bokowy/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/a.bokowy/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/a.bokowy/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./scripts/tests/run_test_suite.py", line 224, in cmd_run
    apps_register.uninit()
  File "/home/a.bokowy/connectedhomeip/scripts/tests/chiptest/accessories.py", line 36, in uninit
    self.__stopXMLRPCServer()
  File "/home/a.bokowy/connectedhomeip/scripts/tests/chiptest/accessories.py", line 133, in __stopXMLRPCServer
    client.ping()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

After the change proposed in this PR, there should be no implications other than server termination will be handled "locally" (it will not rely on the "ping" RPC, which IMHO is a bad design, just because of the network component required for server termination). This "ping" RPC was used only during the shutdown, so I've removed it as well. For this explanation I've selected "TestSystemCommands" test on purpose. It uses the RPC server for performing the test (RPCs: stop, start, reboot, factoryReset), so you can see that the test application is able to communicate with the server. However, during test shutdown the test framework can not connect to it's own server thread.... So, I've assumed that there has to be something wrong with the network/routing setup. Hence, I've called it "when the network is not reliable". But maybe it is indeed not the best wording for this issue.

2022-03-24 12:45 UTC, andy31415 approved these changes

2022-03-24 12:45 UTC, merged