When establishing a CASE session fails, the failure callback in not c…
project-chip/connectedhomeip pull request #16061
Opened 2022-03-10 11:39 UTC by vivien-apple

…alled

#### Problem

The mdns platform implementation can not map a failure to resolve a node id to the original session.

#### Change overview
 * Add a timeout to the darwin mdns resolve implementation
 * Update the mdns platform resolver implementation so if there is a name into the result it can be converted to a `peerId` before beeing used to retrieved the corresponding `OperationalDeviceProxy` 
 * Get `CASESessionManager` to actually use the failure callback if the mdns resolving fails.

2022-03-10 14:39 UTC, andy31415 requested changes, later dismissed
Please hold off until after #15934 (if at all required there).

That PR already found that resolution callbacks were not properly used and that should be fixed.

2022-03-10 14:40 UTC, andy31415 reviewed
We can add the MDNS implementation fixes separately.

2022-03-14 13:32 UTC, andy31415 commented
@vivien-apple now that #15934 was merged, could you check if fixes are still required?

2022-03-26 03:51 UTC, woody-apple approved these changes

2022-03-26 03:51 UTC, woody-apple commented
I tested this briefly, it appears still useful.

2022-03-28 14:00 UTC, closed without merging