BL602 pull request
project-chip/connectedhomeip pull request #16370
Opened 2022-03-17 13:39 UTC by jczhang777

#### Problem
* Add new platform for matter

#### Change overview
Add chip bl602 for matter

#### Testing
How was this tested? (at least one bullet point required)
* see "connectedhomeip/examples/lighting-app/bouffalolab/bl602/README.md"

2022-03-17 13:42 UTC, andy31415 commented
@jczhang777 is this the same as #16358 ?

2022-03-17 13:44 UTC, andy31415 requested changes, later dismissed
There seems to be some reviews lost in history as the same pull request is being created over and over again: https://github.com/project-chip/connectedhomeip/pulls?q=is%3Apr+bl602

See comments in #16283 - need build_examples support.

Also for history and review please keep the same PR and do not open new PRs for every change as that is very spammy

2022-03-17 13:53 UTC, jczhang777 commented
> There seems to be some reviews lost in history as the same pull request is being created over and over again: https://github.com/project-chip/connectedhomeip/pulls?q=is%3Apr+bl602
> 
> See comments in #16283 - need build_examples support.
> 
> Also for history and review please keep the same PR and do not open new PRs for every change as that is very spammy

sorry about that.

2022-03-17 19:14 UTC, andy31415 commented
> > There seems to be some reviews lost in history as the same pull request is being created over and over again: https://github.com/project-chip/connectedhomeip/pulls?q=is%3Apr+bl602
> > See comments in #16283 - need build_examples support.
> > Also for history and review please keep the same PR and do not open new PRs for every change as that is very spammy
> 
> sorry about that. i had fixed issues that #16283 mentioned。but i do not know why spell check failed in README.md. build_examples support is changed as you comments.

for build_examples.py to work I expect changes in `scripts/build/build/targets.py` as well as adding a new platform  and unit test updates. I do not see these in this PR.

2022-03-17 19:15 UTC, andy31415 reviewed
Please remove README.pdf

git does not like binary files, we have a readme.md

2022-03-17 19:17 UTC, andy31415 commented on examples/lighting-app/bouffalolab/bl602/README.md
> +connectedhomeip$ ./scripts/examples/gn_bl602_example.sh ./examples/lighting-app/bouffalolab/bl602 out/lighting_app_bl602
I expect this to be like:

```
./scripts/build/build_examples.py --target bouffalolab-bl602-lighting-app build
```

2022-03-18 01:47 UTC, jczhang777 commented
> Restyler complains just about one empty line:
> 
> [380f3e1](https://github.com/project-chip/connectedhomeip/commit/380f3e1129de71d06af61816738292194c01fde1)

very thankful.

2022-03-18 01:48 UTC, jczhang777 commented
> Please remove README.pdf
> 
> git does not like binary files, we have a readme.md

ok.

2022-03-25 12:35 UTC, jczhang777 commented
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

this project is on going.

2022-03-26 03:48 UTC, woody-apple commented
/rebase

2022-03-26 03:48 UTC, woody-apple approved these changes
Fast tracking platform changes.

2022-03-28 07:16 UTC, jczhang777 commented
> Fast tracking platform changes.



> /rebase

working on it. thanks.

> Fast tracking platform changes.

ok, I am working on it.

2022-04-01 07:21 UTC, jczhang777 commented
@andy31415 Hi, I had rebased my code, and fix some problems.Include https://github.com/project-chip/connectedhomeip/pull/16370#discussion_r829411785 that you had mentioned。

2022-04-01 07:23 UTC, jczhang777 commented
Hi, I had rebased my code, and fix some problems.Include https://github.com/project-chip/connectedhomeip/pull/16370#discussion_r829411785 that you had mentioned。Are there any other issues that I need to fix? very thankful。

2022-04-01 08:29 UTC, jczhang777 commented
@andy31415 Hi, I had rebased my code, and fix some problems.Include https://github.com/project-chip/connectedhomeip/pull/16370#discussion_r829411785 that you had mentioned。Are there any other issues that I need to fix? very thankful。

2022-04-01 20:21 UTC, bzbarsky-apple commented
> Are there any other issues that I need to fix

The restyle failure.  See the automatically created commits in https://github.com/project-chip/connectedhomeip/pull/16921 for the needed changes.

2022-04-02 02:23 UTC, jczhang777 commented
> > Are there any other issues that I need to fix
> 
> The restyle failure. See the automatically created commits in #16921 for the needed changes.



> > Are there any other issues that I need to fix
> 
> The restyle failure. See the automatically created commits in #16921 for the needed changes.
I just fixed it. If there is anything else I need to modify, please let me know. thank you very much. 


> > Are there any other issues that I need to fix
> 
> The restyle failure. See the automatically created commits in #16921 for the needed changes.
I just fixed it. If there is anything else I need to modify, please let me know. thank you very much.

2022-04-02 02:24 UTC, jczhang777 commented
> > Are there any other issues that I need to fix
> 
> The restyle failure. See the automatically created commits in #16921 for the needed changes.

I just fixed it. If there is anything else I need to modify, please let me know. thank you very much.

2022-04-02 03:15 UTC, bzbarsky-apple commented
/rebase

2022-04-02 03:19 UTC, bzbarsky-apple commented
For some reason CI did not kick off properly there.. You might need to force-push again.  :(

2022-04-02 03:23 UTC, jczhang777 commented
> For some reason CI did not kick off properly there.. You might need to force-push again. :(

I have pushed forcibly pushed up. Please check if there is anything else to modify. Thank you.

2022-04-04 13:33 UTC, merged