Remove special characters from functiona names in code gen
project-chip/connectedhomeip pull request #16386
Opened 2022-03-17 18:27 UTC by krypton36

#### Problem
When special characters are added to the label in YAML test files, the code gen attempts to create a function with it, but C++ does not accept special characters as function names. See issue below:

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
* If unit tests were added, how do they cover this issue?
* If unit tests existed, how were they fixed/modified to prevent this in future?
* If new unit tests are not added, why not?
* If integration tests were added, how do they verify this change?
* If new integration tests are not added, why not?
* If manually tested, what platforms controller and device platforms were manually tested, and how?
* If no testing is required, why not?

2022-03-17 19:10 UTC, bzbarsky-apple approved these changes

2022-03-17 20:54 UTC, andy31415 reviewed
Could you provide examples of what is being added into names?

I wonder if stricter requirements of what things can be named is beneficial instead of erasing any non-alpha-numeric character.

2022-03-17 20:56 UTC, andy31415 requested changes
The method seems to say `asUpperCamelCase` which I would translate as `changes case of the string`.

I would find it unexpected to change the string itself. It already seems to do that by replacing slash/dot/colon but that seems atually wrong to me. If we need a `stripSpecialCharacters` we should add a method that does that.

or name the `asLowerCamelCase` differently.

2022-03-17 21:51 UTC, krypton36 commented
> Could you provide examples of what is being added into names?
> 
> I wonder if stricter requirements of what things can be named is beneficial instead of erasing any non-alpha-numeric character.

Issue https://github.com/project-chip/connectedhomeip/issues/16236 has the YAML file that is being used. It is currently a comma that is causing the issue. The current implementation is to use the label of the test to extract the function name. I added it here because this javascript function is particularly used for identifiers. This [doc](https://docs.microsoft.com/en-us/cpp/cpp/identifiers-cpp?redirectedfrom=MSDN&view=msvc-170) indicates the limitation of identifiers. There is already a level string stripping that is occurring, ie the following example:

```
console.log(asLowerCamelCase("HELLO _& WORLD :_"));
> helloWorld
```

I am simply enforcing the convention even further. We can rename, but that means a pretty large refactor.

2022-03-18 03:28 UTC, bzbarsky-apple commented
@andy31415 These functions already do all sorts of non-alphanumeric removal, and their consumers depend on it happening.  The idea is to convert an arbitrary string to a camel-cased identifier.  That means removing non-identifier characters.

2022-03-18 14:08 UTC, andy31415 commented
> @andy31415 These functions already do all sorts of non-alphanumeric removal, and their consumers depend on it happening. The idea is to convert an arbitrary string to a camel-cased identifier. That means removing non-identifier characters.

Could we rename them as `asLowerCamelCaseIdentifier` ? then it seems to make sense as it makes an identifier.

2022-03-18 14:09 UTC, andy31415 commented
> > @andy31415 These functions already do all sorts of non-alphanumeric removal, and their consumers depend on it happening. The idea is to convert an arbitrary string to a camel-cased identifier. That means removing non-identifier characters.
> 
> Could we rename them as `asLowerCamelCaseIdentifier` ? then it seems to make sense as it makes an identifier.

I also agree that renaming is a silly reason to block such a PR ... so adding a checkmark. But a followup for rename would be appreciated.

2022-03-18 14:09 UTC, andy31415 approved these changes

2022-03-18 16:27 UTC, krypton36 commented
> > > @andy31415 These functions already do all sorts of non-alphanumeric removal, and their consumers depend on it happening. The idea is to convert an arbitrary string to a camel-cased identifier. That means removing non-identifier characters.
> > 
> > 
> > Could we rename them as `asLowerCamelCaseIdentifier` ? then it seems to make sense as it makes an identifier.
> 
> I also agree that renaming is a silly reason to block such a PR ... so adding a checkmark. But a followup for rename would be appreciated.

Ok. Created an issue: https://github.com/project-chip/connectedhomeip/issues/16447

2022-03-19 06:02 UTC, merged