Build IPv6 builds by default, make ipv4 opt-in instead of opt-out
project-chip/connectedhomeip pull request #16436
Opened 2022-03-18 13:53 UTC by andy31415

#### Problem
Certification validates ipv6 only builds, generally want to reproduce and catch IPv6 issues by default

#### Change overview
Switches ipv4-disabled as a default for builds, makes 'enable ipv4' as a opt-in option.

#### Testing
CI will validate builds. IPv6 generally has been validated to work on several platforms and thread devices are already only ipv6.

2022-03-23 00:35 UTC, tcarmelveilleux approved these changes

2022-03-23 01:00 UTC, chrisdecenzo requested changes
I prefer not to have this be the default since it will lead many devices to not support IPv4

2022-03-23 12:55 UTC, jepenven-silabs approved these changes

2022-03-26 03:48 UTC, woody-apple requested changes
We need to have the SDK build both to verify ipv4 and ipv6.  Certification will verify IPv6 only mode.

2022-04-05 16:03 UTC, closed without merging