Stop using a fixed salt when opening commissioning windows.
project-chip/connectedhomeip pull request #16645
Opened 2022-03-24 20:15 UTC by bzbarsky-apple

Fixes https://github.com/project-chip/connectedhomeip/issues/10586

#### Problem
We're using a hardcoded salt value, which is not the right thing.

#### Change overview
Add a way for consumers to pass in a salt (if they want to reuse a single onboarding payload for multiple devices) or have it be randomly generated.

#### Testing
Verified that `chip-tool pairing open-commissioning-window` works and I can then commission into a different fabric using the resulting onboarding payload.

2022-03-24 20:16 UTC, tcarmelveilleux commented on src/controller/CommissioningWindowOpener.cpp
> +        constexpr size_t saltLength = (kSpake2p_Min_PBKDF_Salt_Length + kSpake2p_Max_PBKDF_Salt_Length) / 2;
Use max length

2022-03-24 20:25 UTC, bzbarsky-apple commented on src/controller/CommissioningWindowOpener.cpp
> +        constexpr size_t saltLength = (kSpake2p_Min_PBKDF_Salt_Length + kSpake2p_Max_PBKDF_Salt_Length) / 2;
Done.

2022-03-24 20:56 UTC, tcarmelveilleux approved these changes

2022-03-25 16:04 UTC, Damian-Nordic requested changes

2022-03-25 16:04 UTC, Damian-Nordic commented on src/controller/CommissioningWindowOpener.cpp
> +            (salt.Value().size() >= kSpake2p_Max_PBKDF_Salt_Length && salt.Value().size() <= kSpake2p_Max_PBKDF_Salt_Length),
```suggestion
            (salt.Value().size() >= kSpake2p_Min_PBKDF_Salt_Length && salt.Value().size() <= kSpake2p_Max_PBKDF_Salt_Length),
```

2022-03-26 03:56 UTC, woody-apple approved these changes

2022-03-28 07:17 UTC, Damian-Nordic approved these changes

2022-03-28 08:38 UTC, merged