[chip-tool] Allow setting the KeepSubscriptions flag
project-chip/connectedhomeip pull request #16706
Opened 2022-03-28 08:34 UTC by vivien-apple

#### Problem

`chip-tool` can not set the `KeepSubscriptions` flag.

fix #15845

#### Change overview
 * Add `chip-tool` support for setting the `KeepSubscriptions` flag.

#### Testing
I have checked the logs to make sure the flag is set appropriately.

2022-03-28 11:25 UTC, Arkq approved these changes

2022-03-28 11:28 UTC, Arkq requested changes

2022-03-28 11:28 UTC, Arkq commented on examples/chip-tool/commands/clusters/ReportCommand.h
> +        }
Extra bracket

2022-03-28 13:12 UTC, Arkq approved these changes

2022-03-29 04:56 UTC, bzbarsky-apple approved these changes

2022-04-01 16:44 UTC, woody-apple approved these changes
Fast tracking, given this has had enough time for review (> 3 days)

2022-04-01 19:56 UTC, merged