Added option to override Vendor & Product IDs via cmd-line
project-chip/connectedhomeip pull request #17001
Opened 2022-04-04 15:51 UTC by vijs

#### Problem
* Example applications (on Linux Platform) do not allow overriding of the default Vendor and Product ID values via cmd-line. Functionality is there but it is currently not working.
* Example applications (on Linux Platform) always override the DAC Provider that was set prior to the blocking ChipLinuxAppMainLoop() method call.
* ChipLinuxAppMainLoop() method always overrides the DAC Provider with the ExampleDACProvider.
#### Change overview
* Extend Linux Configuration Manager implementation to support read and store of uint16_t values
* Added specific Vendor and Product ID methods to store and retrieve value from File system.
* Add optional parameter dacProvider to the ChipLinuxAppMainLoop method.
  * If parameter not provided, defaults to nullptr
  * If parameter is provided, ChipLinuxAppMainLoop sets the desired DAC Provider passed by the user.
#### Testing
* Matter Unit Tests
* Tested Commissioning flow (chip-tool vs chip-all-clusters-app)

2022-04-04 17:42 UTC, tcarmelveilleux commented on src/include/platform/ConfigurationManager.h
> +    virtual CHIP_ERROR StoreProductId(uint16_t productId)                                           = 0;
Storage does NOT belong in the ConfigurationManager API. We have been removing all setters for "fundamental" (i.e. don't change at runtime) values. If this is added, it should only be to the Linux version altogether, not the general API

2022-04-04 17:45 UTC, tcarmelveilleux requested changes
- [ ] This testing/example-only mechanism must not be added beyond the Linux implementation. Please remove from `ConfigurationManager` interface and from `GenerickConfigurationManagerImpl`, and move to Linux-only config manager

2022-04-04 17:49 UTC, woody-apple approved these changes

2022-04-05 18:21 UTC, tcarmelveilleux approved these changes

2022-04-05 22:18 UTC, hawk248 approved these changes

2022-04-07 12:28 UTC, merged