enable content app platform on android
project-chip/connectedhomeip pull request #17302
Opened 2022-04-13 00:02 UTC by chrisdecenzo

#### Problem
* Fix https://github.com/project-chip/connectedhomeip/issues/17301

#### Change overview
* include content-app platform version of tv-app clusters
* include content-app platform initializers
* include commissioner

#### Testing
* Tested using tv-app on android, running in android tv emulator
* Regression tested using linux/docker tv-app

2022-04-15 22:12 UTC, amitnj approved these changes

2022-04-18 04:09 UTC, xylophone21 requested changes

2022-04-18 12:55 UTC, lazarkov approved these changes

2022-04-18 15:20 UTC, chrisdecenzo commented on examples/tv-app/android/java/TVApp-JNI.cpp
> -#if CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY
moved the location for user setting overrides to new "PreServerInit()" method in AppImpl.cpp

however, the default for extended discovery can be set by updating CHIP_DEVICE_CONFIG_EXTENDED_DISCOVERY_TIMEOUT_SECS in ChipProjectAppConfig.h and its currently set to a non-forever value.

the reason to call DnssdServer::Instance().SetExtendedDiscoveryTimeoutSecs would be for overrides specified by the user (and persisted across restarts).

2022-04-18 15:21 UTC, chrisdecenzo commented on examples/tv-app/android/java/TVApp-JNI.cpp
> +#if CHIP_DEVICE_CONFIG_ENABLE_BOTH_COMMISSIONER_AND_COMMISSIONEE
Done - moved this to AppImpl.cpp which is one of the files that is expected to be modified by the tv maker.

2022-04-18 15:22 UTC, chrisdecenzo commented on examples/tv-app/android/App/platform-app/src/main/java/com/matter/tv/server/service/MatterServant.java
> +
I created two methods now - preServerInit and postServerInit so that there are callbacks before and after the ChipAppServer gets initialized.

2022-04-18 17:18 UTC, chrisdecenzo commented on examples/tv-app/android/App/app/src/main/java/com/tcl/chip/chiptvserver/service/MatterServant.java
> -    mTvApp.postInit();
added preServerInit and postServerInit so that we can have callbacks before and after the ChipAppServer gets started

2022-04-19 01:41 UTC, xylophone21 commented on examples/tv-app/android/App/app/src/main/java/com/tcl/chip/chiptvserver/service/MatterServant.java
> -    mTvApp.postInit();
Yes, both pre and post init is a good idea if we need them. But I notice that related code on Linux is running in prePost, why did we move them to postInit on Andoird? And also I think they should run in prePost

2022-04-19 01:57 UTC, xylophone21 approved these changes

2022-04-19 01:59 UTC, merged