disable arg parser validity checks
project-chip/connectedhomeip pull request #17375
Opened 2022-04-14 06:13 UTC by cjandhyala

What is being fixed?  
disabled arg parser validity checks 

#### Change overview
disabled CHIP_CONFIG_ENABLE_ARG_PARSER_VALIDITY_CHECKS

#### Testing
compiled and provisioned all-cluster-app on raspi platform

2022-04-14 06:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=17375) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=17375) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=17375) it.</sub>

2022-04-14 06:55 UTC, bzbarsky-apple approved these changes

2022-04-15 03:09 UTC, andy31415 requested changes
Please update the summary with why the change is being made

2022-04-15 03:11 UTC, andy31415 commented
Note that #17394 is already merged and I understand that fixes some ARM64 abi strangeness (we do not need that validation logic).

Beyond that, this PR does not explain why it does things. Needs an actual answer on `What is being fixed?` as the description of "disabled arg parser validity checks" is what the PR does rather than a description of what is broken and being fixed.

2022-04-29 13:11 UTC, closed without merging