[Android] Add device param of GetAttestationChallenge.
project-chip/connectedhomeip pull request #17541
Opened 2022-04-20 10:51 UTC by chulspro

Signed-off-by: sanghyukko <sanghyuk.ko@samsung.com>
Signed-off-by: Charles Kim <chulspro.kim@samsung.com>

#### Problem
We need to update info of device proxy during attestation step.

#### Change overview
Change to set device proxy value on attestation step and use device secure session.

#### Testing
Device commissioning

2022-04-20 13:58 UTC, andy31415 commented on src/controller/CHIPDeviceController.cpp
> +CHIP_ERROR DeviceCommissioner::GetAttestationChallenge(DeviceProxy * device, ByteSpan & attestationChallenge)
Does this method now use `this` in any way? Should it be marked static in the header if it never uses this (and eventually moved around/refactored)?

2022-04-20 13:58 UTC, andy31415 approved these changes

2022-04-20 14:16 UTC, saurabhst approved these changes

2022-04-20 14:18 UTC, msandstedt requested changes
Instead of changing the `GetAttestationChallenge` interface, it would create less churn to add the desired `GetAttestationChallenge` signature as an overload.

The justification for this PR can only be that there are out-of-tree callers that need this, or that `mDeviceBeingCommissioned` is not the correct device for in-tree examples and we in fact have an underlying bug that we need to address directly.

Assuming the former (the need for this comes from out-of-tree callers), it does not makes sense to remove the existing interface, which can break other out-of-tree code.

An alternative would be just to manually extract the attestation challenge from the passed device pointer in the way this method demonstrates.

2022-04-20 19:08 UTC, bzbarsky-apple requested changes
Yes, I don't understand this at all.  If we have a specific device, we should just be getting the attestation challenge from that (and adding API on DeviceProxy as needed for that purpose).  The only reason we have `GetAttestationChallenge` on the _controller_ is specifically to get the attestation challenge of `mDeviceBeingCommissioned`.

2022-04-21 03:22 UTC, chulspro commented
> Instead of changing the `GetAttestationChallenge` interface, it would create less churn to add the desired `GetAttestationChallenge` signature as an overload.
> 
> The justification for this PR can only be that there are out-of-tree callers that need this, or that `mDeviceBeingCommissioned` is not the correct device for in-tree examples and we in fact have an underlying bug that we need to address directly.
> 
> Assuming the former (the need for this comes from out-of-tree callers), it does not makes sense to remove the existing interface, which can break other out-of-tree code.
> 
> An alternative would be just to manually extract the attestation challenge from the passed device pointer in the way this method demonstrates.

Okay, I will add new API for this and commit one more time after launch. Thank you for your feedback

2022-04-21 03:23 UTC, chulspro commented
> Yes, I don't understand this at all. If we have a specific device, we should just be getting the attestation challenge from that (and adding API on DeviceProxy as needed for that purpose). The only reason we have `GetAttestationChallenge` on the _controller_ is specifically to get the attestation challenge of `mDeviceBeingCommissioned`.

Okay, I will add new API recommended by @msandstedt

2022-04-21 20:13 UTC, bzbarsky-apple requested changes

2022-04-21 20:13 UTC, bzbarsky-apple commented on src/controller/CHIPDeviceController.cpp
> +CHIP_ERROR DeviceCommissioner::GetAttestationChallenge(DeviceProxy * device, ByteSpan & attestationChallenge)
Again, why is this an API on DeviceCommissioner?  It does not use the DeviceCommissioner in any way.

2022-05-13 23:07 UTC, closed without merging