Move toward enforcing use of DefaultStorageKeyAllocator with PersistentStorageDelegate.
project-chip/connectedhomeip pull request #17821
Opened 2022-04-27 19:49 UTC by bzbarsky-apple

For now we still have a few callsites of the *Deprecated methods, but
now it's clear what those are and we can work on removing them.

#### Problem
Possible for consumers to use keys not coming from DefaultStorageKeyAllocator with PersistentStorageDelegate.

#### Change overview
Move toward enforcing that the keys come from the key allocator.

#### Testing
No behavior changes.

2022-04-27 20:53 UTC, tcarmelveilleux requested changes
This cannot use DefaultStorageKeyAllocator everywhere (which cannot be overridden/modified). The approach here requires more discussion before such a wide-ranging PR.

2022-04-27 20:58 UTC, tcarmelveilleux commented on src/lib/support/tests/TestTestPersistentStorageDelegate.cpp
> +    err = storage.SyncDeleteKeyValue(roboto);
This changes the semantics of the test that is meant to allow arbitrary key storage to be tested. This cannot remain named "roboto"

2022-04-27 21:20 UTC, bzbarsky-apple commented
> The approach here requires more discussion before such a wide-ranging PR.

That is perfectly reasonable.  

What I am trying to accomplish is to make it very clear to an SDK consumer what sorts of keys the SDK might try to read/write.  The current use of strings as keys makes it too easy for somewhere in the SDK to just make up a string without anyone noticing.

I am _very_ much open to other solutions to this problem than the one in this PR, which I agree is not ideal.

I'll do some more thinking about options here, ideally ones that don't required changing the external-facing SDK API by default.

2022-10-25 17:18 UTC, bzbarsky-apple commented
Not going to happen in this form.

2022-10-25 17:18 UTC, closed without merging