Fix Tizen TPK build after changes in 831211b
project-chip/connectedhomeip pull request #18298
Opened 2022-05-11 06:34 UTC by Arkq

#### Problem

Predefined `tizen_sdk_cli` was removed in 831211b

#### Change overview

- define `tizen_sdk_cli` before usage

#### Testing

Building TPK flashbundle for Tizen

2022-05-11 13:13 UTC, andy31415 approved these changes

2022-05-11 13:17 UTC, andy31415 requested changes
Please update tizen builder to be compliant with build_examples.py:
  - output of `--dry-run` should be usable by a human to reproduce the build without the use of build_examples.py at all. 
  
  This means you cannot use file write/shutil or other programatic build operations. Just executing shell that will be outputed by `--dry-run`

2022-05-11 19:01 UTC, bzbarsky-apple approved these changes

2022-05-12 10:11 UTC, Arkq commented
> Please update tizen builder to be compliant with build_examples.py:

OK, however, for now I think I will postpone this PR until #18137 will be ready. It will be easier to provide proper build setup for Tizen TPK when Linux and Tizen apps will be separated.

2022-05-18 21:24 UTC, bzbarsky-apple approved these changes

2022-05-19 15:32 UTC, andy31415 approved these changes

2022-05-19 15:32 UTC, merged