Fixing linux tv-casting-app's build
project-chip/connectedhomeip pull request #18389
Opened 2022-05-12 17:14 UTC by sharadb-amazon

#### Problem
Refactoring of DiscoveredNodeData in https://github.com/project-chip/connectedhomeip/pull/18266 led to compilation failure of linux tv-casting-app

#### Change overview
Used the new resolutionData from DiscoveredNodeData.

#### Testing
Built and ran linux tv-casting-app and ensured User Directed Commissioning requests are getting delivered from the tv-casting-app to an instance of the tv-app.

2022-05-12 17:30 UTC, andy31415 approved these changes

2022-05-12 17:36 UTC, chrisdecenzo approved these changes

2022-05-12 17:56 UTC, andy31415 requested changes
Changes in testdata for build scripts without build script updates is unexpected.

2022-05-12 18:06 UTC, sharadb-amazon commented
> Changes in testdata for build scripts without build script updates is unexpected.

Removed delta from testdata.

2022-05-12 18:12 UTC, andy31415 approved these changes

2022-05-13 03:17 UTC, bzbarsky-apple approved these changes

2022-05-14 14:16 UTC, merged