Add events in power source cluster
project-chip/connectedhomeip pull request #18420
Opened 2022-05-13 10:40 UTC by fessehaeve

#### Problem
Events were missing in the XML definition of power source cluster

#### Change overview
added events for power source cluster

#### Testing
Tested with all-clusters-app

2022-05-14 04:31 UTC, bzbarsky-apple requested changes
Please raise the spec issues.  If you can't get them fixed yourself, please find someone to do that ASAP; the window on this is closing rapidly....

2022-05-14 04:31 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/power-source-cluster.xml
>      <event code="0x0000" name="WiredFaultChange" priority="info" side="server">
Where is the priority for these defined?  The spec definition of these (and in fact the whole cluster in the spec) does not follow the normal cluster template, so it's hard to tell whether these are correct.

2022-05-14 04:31 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/power-source-cluster.xml
>        <field id="1" name="WiredFaultChangeType" type="WiredFaultChangeType"/>
Again, the spec is kinda broken here, but what I would expect is that the event has two fields, not has a single field that is a struct.  That's the intent of what the spec was trying to define, at least, back when it was written.

Similar for the other events.

2022-05-16 07:36 UTC, eve-cxrp approved these changes

2022-06-04 01:34 UTC, closed without merging