[Darwin] Add support for multiple paths for generic read/subscribe methods
project-chip/connectedhomeip pull request #18509
Opened 2022-05-17 16:03 UTC by vivien-apple

#### Problem

The current generic APIs for darwin does not allow multiple paths.

#### Change overview
 * Add support for multiple paths by using `id` instead of `NSNumber *`

#### Testing
It was manually tested using `./out/debug/standalone/chip-tool-darwin any subscribe-by-id 6,6 0,0 1 5 1 0x12344321 1,2` and `./out/debug/standalone/chip-tool-darwin any read-by-id 6,6 0,0 1 5 1 0x12344321 1,2`

2022-05-17 16:34 UTC, isiu-apple commented on examples/chip-tool-darwin/commands/clusters/ModelCommandBridge.h
> +        AddArgument("endpoint-id", 0, UINT16_MAX, &mEndPointIds);
Is `AddArguments()` here coming from `examples/chip-tool/commands/common/Command.h`?  If so, shall we add the optional `desc` description string to the arguments we are modifying in this review?

2022-05-18 02:15 UTC, bzbarsky-apple requested changes

2022-05-18 02:15 UTC, bzbarsky-apple commented on src/darwin/Framework/CHIP/CHIPDevice.h
> +                        attributeId:(id _Nullable)attributeId
So now that I am looking at this API... this is really pretty annoying to use: you have to create three lists that line up, etc.

I think we should have a public `readAttributePaths` API, alongside the existing `readAttributeWithEndpointId`, which can call `readAttributePaths` internally.  And readAttributePaths should take a single list of paths, where each path is an object with three nullable members for endpoint/cluster/attribute, null representing wildcard.

2022-05-18 02:15 UTC, bzbarsky-apple commented on src/darwin/Framework/CHIP/CHIPDevice.mm
> +        chip::app::AttributePathParams attributePathParams[kMaxAllowedPaths];
But then the ReadClient will have a pointer to this stack object, and if it tries to resubscribe things will blow up, no?

2022-10-24 09:59 UTC, vivien-apple commented
Closing until I got some time to work on that again.

2022-10-24 09:59 UTC, closed without merging