[OnboardingPayload] Returns CHIP_ERROR_INVALID_ARGUMENT is the manual code starts with 8 or 9
project-chip/connectedhomeip pull request #18552
Opened 2022-05-18 12:43 UTC by vivien-apple

… setup pairer internaly distinguish both

#### Problem

While looking at #18454 I noticed that the stack does not throw an error if the manual code starts with "8" or "9", which means that the manual code version is not "0" and which imply that the encoding format has changed (since there is no good way to encode it properly otherwise).

#### Change overview 
 * Returns `CHIP_ERROR_INVALID_ARGUMENT` if the first digit is "8" or "9". 
 * Update `PairWithQRCode/PairWithManualCode` to `PairWithCode` since the setup code pairer is making the distinction internally.

#### Testing
 `./out/debug/standalone/chip-tool pairing code 0x12344321 84970112331`

2022-05-18 13:19 UTC, andy31415 requested changes, later dismissed
This change is much larger - it seems to contain an entire refactor of naming and replacing QRCode to just code.

Summary seems to just say "return invalid argument on manual code starting with 8 or 9".

Please split the PRs and make sure the PR content and summary match.

2022-05-19 10:22 UTC, vivien-apple commented
> This change is much larger - it seems to contain an entire refactor of naming and replacing QRCode to just code.
> 
> Summary seems to just say "return invalid argument on manual code starting with 8 or 9".
> 
> Please split the PRs and make sure the PR content and summary match.

Makes perfect sense. I did #18606 to cover the parts that are related to the payload validation. In this PR I have only kept the bits that are related to the renaming from `qrcode`/`manualcode` to `code`

2022-05-19 14:42 UTC, andy31415 approved these changes

2022-05-19 14:57 UTC, msandstedt approved these changes

2022-05-19 15:10 UTC, merged