AddGroup Command with the GroupID as 0 now responds as INVALID_COMMAND.
project-chip/connectedhomeip pull request #18815
Opened 2022-05-25 17:58 UTC by rcasallas-silabs

#### Problem
* Fixes [#18508](https://github.com/project-chip/connectedhomeip/issues/18508): TC-GR-2.2 Chiptool allows Group ID ' 0 ' in Group Cluster

#### Change overview
* Added GroupId validation in AddGroup command callback.
* Added new test case in the Groups cluster YAML.

#### Testing
* Groups Tests executed successfully.

2022-05-25 18:01 UTC, tcarmelveilleux approved these changes

2022-05-25 18:24 UTC, bzbarsky-apple requested changes

2022-05-30 11:51 UTC, rcasallas-silabs commented on src/app/clusters/groups-server/groups-server.cpp
> +    VerifyOrReturnError(IsValidGroupId(groupId), EMBER_ZCL_STATUS_INVALID_COMMAND);
IsValidGroupId condition moved first.

2022-06-02 13:52 UTC, jepenven-silabs commented on src/app/clusters/groups-server/groups-server.cpp
> +    VerifyOrReturnError(IsValidGroupId(groupId), EMBER_ZCL_STATUS_INVALID_COMMAND);
Well actually no it is now worse.... it's `CONSTRAINT_ERROR` as per : https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5314/files

2022-06-02 14:02 UTC, rcasallas-silabs commented on src/app/clusters/groups-server/groups-server.cpp
> +    VerifyOrReturnError(IsValidGroupId(groupId), EMBER_ZCL_STATUS_INVALID_COMMAND);
CONSTRAINT_ERROR is an alias for the now deprecated INVALID_VALUE, so these changes are no longer needed. However, I will replace the old name in the code.

2022-06-03 18:54 UTC, rcasallas-silabs commented on src/app/clusters/groups-server/groups-server.cpp
> +    VerifyOrReturnError(IsValidGroupId(groupId), EMBER_ZCL_STATUS_INVALID_COMMAND);
Spec change: The correct code is now CONSTRAINT_ERROR.

2022-06-03 18:55 UTC, rcasallas-silabs commented on src/app/clusters/groups-server/groups-server.cpp
> +    VerifyOrReturnError(IsFabricGroupId(groupId), EMBER_ZCL_STATUS_INVALID_COMMAND);
It is now.

2022-06-04 04:46 UTC, bzbarsky-apple approved these changes

2022-06-04 06:35 UTC, msandstedt approved these changes

2022-06-08 16:28 UTC, bzbarsky-apple reviewed
All the endpoint_config.h changes in this PR should be removed, right?  @rcasallas-silabs

2022-06-10 04:31 UTC, merged