Fix ReadIntearaction.h
project-chip/connectedhomeip pull request #18825
Opened 2022-05-25 23:27 UTC by yunhanw-google

#### Problem
When dataVersion is matching with the one in server, read/subscribe attribute API in ReadInteraction.h cannot get anything back, this application would stuck.
When read event, if no event is generated in server, read/subscribe event API in ReadInteraction.h cannot get anything back, this application would stuck.
#### Change overview
--Remove dataVersion filter from read/subscribe APIs in
ReadInteraction.h
--Add onDone callback for read/subscribe event APIs in
ReadInteraction.h

#### Testing
Update the tests.

2022-05-26 02:00 UTC, bzbarsky-apple requested changes
Please spell the filename right in the commit message.

2022-05-26 07:13 UTC, yunhanw-google commented on src/controller/CHIPCluster.h
> -                       bool aKeepPreviousSubscriptions = false, const Optional<DataVersion> & aDataVersion = NullOptional)
no need to remove it for subscribe. revert it back. thanks

2022-05-26 07:19 UTC, yunhanw-google commented on src/controller/CHIPCluster.h
> +                         ReadResponseFailureCallback failureCb, ReadDoneCallback doneCb)
updated, thanks

2022-05-26 07:19 UTC, yunhanw-google commented on src/controller/CHIPCluster.h
> +                              ReadResponseFailureCallback failureCb, ReadDoneCallback doneCb, uint16_t minIntervalFloorSeconds,
no need, update , thanks

2022-05-26 07:20 UTC, yunhanw-google commented on src/controller/ReadInteraction.h
> -    bool fabricFiltered = true, bool keepPreviousSubscriptions = false, const Optional<DataVersion> & aDataVersion = NullOptional)
revert it back, thanks

2022-05-26 07:20 UTC, yunhanw-google commented on src/controller/ReadInteraction.h
> +    ChipLogDetail(DataManagement, "adopt event read is called");
accidental debug log, removed, thanks

2022-05-26 07:20 UTC, yunhanw-google commented on src/controller/ReadInteraction.h
> +                          typename TypedReadEventCallback<DecodableEventType>::OnDoneCallbackType onDoneCb,
removed, thanks

2022-05-27 03:01 UTC, bzbarsky-apple approved these changes

2022-05-27 18:07 UTC, andy31415 approved these changes

2022-05-27 18:08 UTC, merged