Fix dangling entries in host.py builder
project-chip/connectedhomeip pull request #19202
Opened 2022-06-03 22:35 UTC by davidgoogle

#### Problem
What is being fixed?  Examples:
* Incorrect dangling entries in the host.py OutputNames class.

#### Change overview
Removed LIGHTING (duplicate of LIGHT) and renamed TV_CASTING and BRIDGE to their appropriate names.

#### Testing
Built tv-casting-app, tv-app, light, and bridge using build_examples.py.

2022-06-04 04:48 UTC, bzbarsky-apple approved these changes

2022-06-06 07:29 UTC, Arkq approved these changes

2022-06-06 13:59 UTC, Damian-Nordic approved these changes

2022-06-06 14:25 UTC, andy31415 requested changes, later dismissed
LIGHTING seems to have a constant called "LIGHT".

I merged #19232 for this

2022-06-06 14:26 UTC, andy31415 commented
> LIGHTING seems to have a constant called "LIGHT".
> 
> I merged #19232 for this

When I fixed I did not realize they were actually duplicate :( Will re-review this change.

2022-06-06 14:26 UTC, andy31415 approved these changes

2022-06-06 14:28 UTC, merged