Infineon p6 all clusters update
project-chip/connectedhomeip pull request #19245
Opened 2022-06-06 20:01 UTC by keithmwheeler

#### Problem
Fixed commissioning issue with all clusters; updated network commissioning wifi driver with needed lock/unlock sequences.

#### Change overview
Updated P6 all clusters and all clusters minimal apptask to support commissioning only on endpoint 0. Added necessary lock/unlock calls to P6 network commissioning wifi driver.

#### Testing
 Tested by commissioning both all clusters and all clusters minimal on P6 hardware.

2022-06-06 20:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=19245) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=19245) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Keith Wheeler<br/>:x: keithmwheeler<br/><hr/>**Keith Wheeler** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=19245) it.</sub>

2022-06-06 21:01 UTC, bzbarsky-apple requested changes
This should not be making changes to the EFR32 SDK or the ZAP repo... and probably not to mbedtls.

2022-06-07 04:23 UTC, bzbarsky-apple commented on examples/chip-tool/commands/interactive/InteractiveCommands.cpp
> +    std::string arg;
These changes look unrelated...

2022-06-07 04:23 UTC, bzbarsky-apple commented on src/credentials/CHIPCert.cpp
> +    // In CHIP certificate it is represented as a CHIP Epoch UTC time value of 0 sec (2000-01-01 00:00:00 UTC).
These also look unrelated.

2022-06-07 18:16 UTC, keithmwheeler commented on src/credentials/CHIPCert.cpp
> +    // In CHIP certificate it is represented as a CHIP Epoch UTC time value of 0 sec (2000-01-01 00:00:00 UTC).
Should be corrected in current commit.

2022-06-08 00:54 UTC, bzbarsky-apple approved these changes

2022-06-08 14:49 UTC, keithmwheeler commented on examples/chip-tool/commands/interactive/InteractiveCommands.cpp
> +    std::string arg;
Should be corrected in latest commit.

2022-06-08 17:03 UTC, bzbarsky-apple approved these changes

2022-06-09 16:57 UTC, andy31415 approved these changes

2022-06-09 16:57 UTC, merged