[misc] rename IsCategoryEnabled
project-chip/connectedhomeip pull request #1954
Opened 2020-08-03 05:31 UTC by gjc13

Rename to avoid conflict with other code bases.

2020-08-03 05:33 UTC, saurabhst approved these changes

2020-08-03 14:52 UTC, gerickson submitted a review, later dismissed
Is there any reason that this can't be converted to an inline and placed in the CHIP namespace to eliminate the need for preprocessor decoration in this fashion?

2020-08-03 18:52 UTC, woody-apple requested changes
Echoing @gerickson 's request for name-spacing, now that we're touching this.

2020-08-03 21:27 UTC, jelderton approved these changes

2020-08-04 12:34 UTC, gerickson commented on src/lib/support/logging/CHIPLogging.h
> +inline bool IsCategoryEnabled(uint8_t CAT)
The other inlines in this file have a static qualifier. Is there any reason these do not?

2020-08-04 13:40 UTC, woody-apple approved these changes

2020-08-05 05:12 UTC, mspang approved these changes

2020-08-05 14:56 UTC, andy31415 commented
@gerickson ? is the static inline change sufficient or are we asking for more reorganization?

2020-08-05 14:57 UTC, andy31415 commented
@gjc13  is this really a rename as the title claims? it looks to me like a move from macro to inline function. Maybe it should be constexpr as well.

2020-08-06 00:10 UTC, gjc13 commented
> @gjc13 is this really a rename as the title claims? it looks to me like a move from macro to inline function. Maybe it should be constexpr as well.

Already renamed. It cannot be constexpr since `gLogFilter` is involved and this can be set at runtime.

2020-08-06 01:00 UTC, BroderickCarlin approved these changes

2020-08-06 01:52 UTC, merged