Update SDK for BLE version array spec compliance
project-chip/connectedhomeip pull request #19722
Opened 2022-06-17 14:42 UTC by andy31415

#### Problem
Array order of versions is out of spec for SDK:
  - spec says high nibble is array[even] and low nibble is array[odd]
  - implementation does the reverse

Fixes #19720

#### Change overview
- send order spec compliant
- receive does NOT early stop, to be compatible with non-compliant clients for now.

#### Testing
Flashed an EFR32 with the new code:
   - commissioned with an old build of chip-tool (for compatibility test)
   - commissioned with a new build of chip-tool

NOTE: a new chip-tool with an OLD device build will not be compatible.
            this could be fixed by duplicating the versions (send both ver[0] and ver[1] to the same value).

2022-06-17 16:10 UTC, Damian-Nordic approved these changes

2022-06-17 16:17 UTC, andy31415 commented
NOTE: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5373 is still pending in spec, which flips the array order and makes the SDK spec compliant.

Please do not merge until we figure out if spec change is rejected or not. Prefer no SDK changes if possible.

2022-06-17 16:20 UTC, turon requested changes
We probably should fix this in spec, as the SDK behavior correctly matches legacy BTP:

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5373

2022-06-20 12:15 UTC, jmeg-sfy approved these changes

2022-06-26 20:07 UTC, andy31415 commented
Closing: spec will be updated instead.

2022-06-26 20:07 UTC, closed without merging