[Infineon] SoftwareDiagnostic update
project-chip/connectedhomeip pull request #19767
Opened 2022-06-20 12:32 UTC by AlvinHsiao

Problem
Infineon CYW30739 doesn't support DGSW.S.F00(Watermarks)

Change overview
Add DGSW.S.F00(Watermarks) support

Testing
./chip-tool softwarediagnostics reset-watermarks 1234 0

2022-06-21 04:39 UTC, bzbarsky-apple requested changes

2022-06-21 04:39 UTC, bzbarsky-apple commented on src/platform/CYW30739/DiagnosticDataProviderImpl.cpp
> +    // On CYW30739, overide with non-op to pass CI.
This does not make sense.  CI should not be assuming this is supported, if this provider says it's not supported: this is an optional feature.  What CI is this trying to pass?

2022-06-21 04:39 UTC, bzbarsky-apple commented on src/platform/CYW30739/DiagnosticDataProviderImpl.h
> +    bool SupportsWatermarks() override { return true; }
This should be returning false, given that this feature is not actually implemented.

2022-06-21 19:26 UTC, andy31415 requested changes
Optional feature not being implemented is ok. This change is not needed (and likely harmful by claiming an unimplemented feature works).

2022-06-21 21:14 UTC, woody-apple commented
> Optional feature not being implemented is ok. This change is not needed (and likely harmful by claiming an unimplemented feature works).

These are perfectly allowed in the SDK, they're just not mandatory. Approving

2022-06-21 21:15 UTC, woody-apple approved these changes

2022-06-22 05:54 UTC, bzbarsky-apple requested changes
@andy31415 is right.  An actual implementation of an optional feature would be fine in the SDK.  But this PR claims to implement the feature, but actually no-ops the call so the feature is not in fact implemented.  That is not an OK thing to do; it's introducing a spec violation.

2022-06-23 02:23 UTC, AlvinHsiao commented
@bzbarsky-apple We just added DGSW.S.F00(Watermarks) support to pass #3 "./chip-tool softwarediagnostics read feature-map 1  0" of TC-DGSW-1.1, or it would read the value "0" not expected "1".

2022-06-23 04:30 UTC, bzbarsky-apple commented
@AlvinHsiao That test only expects 1 if the relevant PICS is claiming that the device supports watermarks, no?

2022-06-23 04:57 UTC, AlvinHsiao commented
@bzbarsky-apple  Yes. But it seems no option to pass that test if the device not supports watermarks.

2022-06-23 17:45 UTC, andy31415 requested changes
Optional feature should either be implemented or not return 'supported'.

This PR marks it 'supported' and at the same time does a NOOP implementation,

2022-06-23 17:49 UTC, andy31415 commented
> @bzbarsky-apple Yes. But it seems no option to pass that test if the device not supports watermarks.

The test is wrong. If the spec says "Optional" you are allowed and spec compliant to not implement it.

2022-06-23 18:54 UTC, bzbarsky-apple commented
> But it seems no option to pass that test if the device not supports watermarks.

No option in what sense?  How _exactly_ are you running the test?

2022-06-24 01:33 UTC, AlvinHsiao commented
The test plan expects that the FeatureMap attribute has a value 1, but we got value 0 if we don't add "bool SupportsWatermarks() override { return true; }"

2022-06-24 06:05 UTC, bzbarsky-apple commented
> The test plan expects that the FeatureMap attribute has a value 1

If the test plan expects that, the test plan is broken and _that_ is what we should fix.  I filed https://github.com/CHIP-Specifications/chip-test-plans/issues/1571 on the test plan.

2022-07-13 11:21 UTC, closed without merging