[EFR32] Update gsdk to 4.1
project-chip/connectedhomeip pull request #19778
Opened 2022-06-20 18:42 UTC by mkardous-silabs

#### Change overview
* Update efr32 sdk to 4.1
* Clean silabs submodules to be under "silabs" instead of "efr32_sdk"

#### Testing
* Manual test with efr32 MG12 and MG24
* Automated tests to validate

2022-06-21 20:20 UTC, jmartinez-silabs requested changes

2022-06-21 20:20 UTC, jmartinez-silabs commented on examples/platform/efr32/ldscripts/efr32mg24.ld
> +/*
Again commented code

2022-06-21 20:29 UTC, mkardous-silabs commented on examples/platform/efr32/ldscripts/efr32mg24.ld
> +/*
done

2022-06-21 20:29 UTC, mkardous-silabs commented on examples/platform/efr32/ldscripts/efr32mg24.ld
> +/*
done

2022-06-21 20:39 UTC, mkardous-silabs commented on examples/platform/efr32/ldscripts/efr32mg24.ld
> +  FLASH (rx) : ORIGIN = 0x08000000, LENGTH = 0x178000
done

2022-06-21 20:39 UTC, mkardous-silabs commented on examples/platform/efr32/ldscripts/efr32mg12.ld
>   */
done

2022-06-21 20:41 UTC, jmartinez-silabs approved these changes

2022-06-21 21:13 UTC, woody-apple approved these changes

2022-06-22 20:00 UTC, andy31415 commented on .github/workflows/examples-efr32.yaml
> +             "./scripts/build/build_examples.py \
Will build_examples.py require to be run only after lfs updates? please make a check/run in the efr32.py logic then. Developers should be able to just compile efr32 builds without worrying about each platform particularities.

2022-06-22 20:09 UTC, andy31415 commented
Merging as a hotfix with the promise of @mkardous-silabs that updates to dockerfile and build_examples.py will happen quite soon (we talked about reverting the PR if followups are not happening, as a way to ensure they will occur).

2022-06-22 20:21 UTC, mkardous-silabs commented on .github/workflows/examples-efr32.yaml
> +      - name: Install git-lfs # Temporary measure untill docker container is updated
As discussed, this will be addressed in a subsequent PR.

2022-06-22 20:54 UTC, merged

2022-06-23 16:08 UTC, andy31415 commented
It turns out this breaks cloudbuilds (or generally out of the box builds in vscode image).
May not be easily fixable since we try to avoid running apt installs in images (vscode user has no root rights by default and running stuff as root does not seem right in general out of build scripts)