Update SoftwareFault event definition to match spec
project-chip/connectedhomeip pull request #19863
Opened 2022-06-22 18:32 UTC by yufengwangca

#### Problem
What is being fixed?  Examples:
* Per spec, this event should have three fields. In our implementation, it has one field, which is a struct with three fields. And even those fields do not match the spec event definition (e.g. they're all required, while some of the spec fields are optional).

* Fixes #19207

#### Change overview
Update SoftwareFault event definition to match spec

#### Testing
How was this tested? (at least one bullet point required)
* Trigger the event from new shell
```
yufengwang@yufengwang:~$ ps -A | grep chip
 122962 pts/4    00:00:00 chip-all-cluste
yufengwang@yufengwang:~$ kill -SIGUSR1 122962

```
* Confirm the software event is recorded
```
[1655922592.493622][122962:122962] CHIP:DL: Caught signal 10
[1655922592.493699][122962:122962] CHIP:DL: select failed: ../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/system/SystemLayerImplSelect.cpp:383: OS Error 0x02000004: Interrupted system call

[1655922592.493786][122962:122962] CHIP:ZCL: SoftwareDiagnosticsDelegate: OnSoftwareFaultDetected
[1655922592.493836][122962:122962] CHIP:EVL: LogEvent event number: 0x0000000000000002 priority: 1, endpoint id:  0x0 cluster id: 0x0000_0034 event id: 0x0 Sys timestamp: 0x0000000006A309A0
```

2022-06-22 19:36 UTC, tcarmelveilleux approved these changes

2022-06-22 20:38 UTC, andy31415 approved these changes

2022-06-22 21:47 UTC, yunhanw-google approved these changes

2022-06-22 22:50 UTC, woody-apple approved these changes

2022-06-23 03:31 UTC, woody-apple approved these changes

2022-06-23 04:34 UTC, bzbarsky-apple requested changes

2022-06-23 04:34 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/software-diagnostics-cluster.xml
> +      <field id="2" name="FaultRecording" type="OCTET_STRING" length="1024"/>
These two fields need to be optional, no?  The PR descroption says they should be... but they're not here.

2022-06-24 00:55 UTC, bzbarsky-apple approved these changes

2022-06-24 05:05 UTC, merged