BabbleSim Docker build support
project-chip/connectedhomeip pull request #206
Opened 2020-04-01 22:17 UTC by pan-apple

#### Problem
BabbleSim cannot be built inside our current Docker container.

 #### Summary of Changes
Some packages were missing. Added the missing packages to Dockerfile. Also, added a script to download and build BabbleSim. This script can be run from a Linux shell (native, or Docker VM) to install the simulator.

fixes #193

2020-04-01 22:26 UTC, woody-apple approved these changes

2020-04-02 00:31 UTC, BroderickCarlin approved these changes

2020-04-02 00:44 UTC, gerickson requested changes
Seems reasonable as a first pass; however, as is typical for the configure script, that script should determine whether or not BabbleSim is present (auto-detect), is a sane, expected version, and then set up the appropriate build state or environment such that it can run as expected.

If not, the build should inform the user BabbleSim wasn't present and happily skip along, so long as they didn't mandate it be present. In that latter case, it should error out.

2020-04-02 17:36 UTC, gerickson approved these changes
Fine with this for now as long as, if we are introducing long-term project dependencies on BabelSim (as optional as they may be), that we better integrate this with the build in the long-term.

2020-04-02 17:36 UTC, merged