[chip-tool] Interactive mode does not work great with complex/custom …
project-chip/connectedhomeip pull request #20615
Opened 2022-07-12 14:02 UTC by vivien-apple

…arguments using json formatting

#### Problem

In #19238 "double" quotes supports has been added to the interactive mode in order to pass string that may contains spaces instead of them being splitter into 2 arguments.

In this PR I would like to replace double quotes by double quote does not works great when one is trying to copy-paste complex json arguments to the command line such as:

`$ chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233,1111], "targets":null},{"fabricIndex": 1, "privilege": 3, "authMode": 3, "subjects": [3333], "targets":null}]' 0x12344321 0`

One would need to escape all the `"` characters to make it works properly, while using single quotes means such strings can be copy pasted without escaping and if one wants to pass an SSID that contains space, it should be 'My SSID' in stead of "My SSSID" which is a much easier and readable change.

#### Change overview
 * Use single quote character as the delimiter for std::quoted and not double quotes.

#### Testing

I tried to convert use the previous write all command into interactive mode.

2022-07-12 14:17 UTC, andy31415 approved these changes

2022-07-13 16:16 UTC, woody-apple approved these changes
Fast tracking tooling

2022-07-13 16:18 UTC, krypton36 requested changes

2022-07-13 16:18 UTC, krypton36 commented on examples/chip-tool/commands/interactive/InteractiveCommands.cpp
> +    while (ss >> std::quoted(arg, '\''))
Can you do this for darwin-framework-tool as well please?

2022-07-14 13:49 UTC, krypton36 approved these changes

2022-07-14 14:12 UTC, merged

2022-07-14 14:13 UTC, vivien-apple commented
> Why not just optionally accept a data model payload argument at stdin?

Do you mean an hex encoded data payload ?

2022-07-14 15:06 UTC, msandstedt commented
I'm not suggesting any specific format.  I'm just pointing out that if we are struggling with escape sequences in the command line interpreter, stdin is available to receive anything we like.