[EFR32] Adds fix for access point not found and retry logic for connecting again
project-chip/connectedhomeip pull request #20922
Opened 2022-07-19 07:57 UTC by shgutte

Problem
The access point is not found error shown during the commissioning.

Fixes added
Added fix for access point not found an issue
Added the retry logic for connecting to access point

Testing
Tested with AP which is causing the issue. And some sanity testing related to the door lock application using WF200 and EFR32

2022-07-19 11:15 UTC, Damian-Nordic approved these changes

2022-07-19 13:33 UTC, jmeg-sfy approved these changes

2022-07-19 15:42 UTC, woody-apple approved these changes

2022-07-20 06:40 UTC, woody-apple commented
@shgutte please note the merge conflict here

2022-07-20 06:44 UTC, shgutte commented
> @shgutte please note the merge conflict here

Yeah I'll resolve it before merging

2022-07-20 17:09 UTC, jmartinez-silabs requested changes
Your last commit is problematic. you now have 208 files changes which as nothing to do with your initial PR.

You must as made a wrong operation somewhere.

2022-07-20 19:28 UTC, shgutte commented
> Your last commit is problematic. you now have 208 files changes which as nothing to do with your initial PR.
> 
> You must as made a wrong operation somewhere.

I've fixed this

2022-07-20 19:33 UTC, jmartinez-silabs approved these changes

2022-07-20 20:59 UTC, merged