[BL602] Update button, not use dts to init
project-chip/connectedhomeip pull request #20929
Opened 2022-07-19 11:20 UTC by jczhang777

#### Problem
What is being fixed?  Examples:
* Update button to support factory reset.

#### Change overview
Update button to support factory reset.

#### Testing
How was this tested? (at least one bullet point required)
* Long press the reset button for at least 5s, the light will blink.

2022-07-19 14:41 UTC, Damian-Nordic approved these changes

2022-07-19 15:36 UTC, woody-apple requested changes
Working on branches is not supported in Matter. Please work on a separate fork if needed

2022-07-19 15:40 UTC, closed without merging

2022-07-20 08:29 UTC, stoneM2017 commented
> Working on branches is not supported in Matter. Please work on a separate fork if needed

@woody-apple we are not quite understand, do you mean the interop_testing_te9 is no longer used or maintained?  The changes in this PR have already been merged into master branch, and as usual, we want to merge these changes into the interop_testing_te9 branch.

2022-07-21 05:48 UTC, jczhang777 commented
> Working on branches is not supported in Matter. Please work on a separate fork if needed

Google will use the branch until October. This change is necessary. Is it possible to merge this PR?