Adds changes in the order of connected and IP notify events
project-chip/connectedhomeip pull request #21219
Opened 2022-07-26 10:45 UTC by rosahay-silabs

#### Problem
What is being fixed?  Examples:
* Fix failure of the commission flow due to IP assignment delay.

#### Change overview
Changes the order of the event notifications around access point connected and IP assignment. 

#### Testing
How was this tested? (at least one bullet point required)
* If new unit tests are not added, why not?
- Tested using the current commission flow.

2022-07-26 12:06 UTC, jepenven-silabs approved these changes

2022-07-26 12:29 UTC, jmartinez-silabs approved these changes

2022-07-26 14:43 UTC, jmartinez-silabs requested changes
blocking the PR until we fix the commit history oh the submodule.

2022-07-27 13:37 UTC, jmartinez-silabs approved these changes

2022-07-27 16:58 UTC, woody-apple approved these changes

2022-07-27 16:59 UTC, merged

2022-07-28 07:18 UTC, rosahay-silabs commented
can this be pulled into SVE ?

2022-07-28 21:26 UTC, bzbarsky-apple commented
@rosahay-silabs Can you create the PR for that?  The bot failed to because of merge conflicts: see https://github.com/project-chip/connectedhomeip/runs/7555113528?check_suite_focus=true