[TIZEN] Support for installing Tizen SDK without docker
project-chip/connectedhomeip pull request #21346
Opened 2022-07-28 11:29 UTC by DamMicSzm

#### Problem
* Needed support for install tizen on linux without docker.

#### Change overview
* Added new installation Tizen SDK script and changed Dockerfile for use it.
* I think not need to bump the docker version, because this change does not change the contents of the docker image, the only thing it does is isolate the installer outside of dokerfile so that you can install this studio sdk without a docker.

#### Testing
Docker
`./integrations/docker/images/chip-build-tizen/build.sh`
See help how to use installation script on linux without docker
`./scripts/setup/tizen/sdk-installer/install.sh --help`

2022-07-28 15:24 UTC, Arkq requested changes

2022-07-29 12:21 UTC, DamMicSzm commented on integrations/docker/images/chip-build-tizen/tizen-sdk-installer/install.sh
> +        wget -r -nd --no-parent --progress=dot:mega -A "$package" "$1"
Thank you Arkq for your attention. Of course, you are right! The download works a lot faster on your advice. Checking will also be useful. :)

2022-07-29 13:06 UTC, Arkq approved these changes

2022-07-29 20:01 UTC, woody-apple approved these changes

2022-07-29 20:01 UTC, woody-apple requested changes
Please update the Docker file version here (and rebase)

2022-08-02 05:13 UTC, wootak-jung approved these changes
Looks good to me.

2022-08-02 05:37 UTC, woody-apple approved these changes

2022-08-02 05:37 UTC, merged