[binding] Support binding to self
project-chip/connectedhomeip pull request #21623
Opened 2022-08-04 10:39 UTC by gjc13

#### Problem

If a device receives a binding entry pointing to it self, it will initiate a connection to self which will not succeed.

#### Change overview

The PR filters out the binding entries to self and directly forwards then to the user provided callback.

#### Testing
How was this tested? (at least one bullet point required)
* Manually tested on Linux `all-cluster-app`.

```
chip-tool airing onnetwork 1 20202021
chip-tool binding write binding '[{"fabricIndex": 1, "node":1, "endpoint":1, "cluster":6}]' 1 0x1
```

After typing the `switch on` command we will see the `Binding to self` output. The users are expected to implement their own application logic for self bindings.

2022-08-04 11:33 UTC, bzbarsky-apple commented
Might be good to wait for https://github.com/project-chip/connectedhomeip/pull/21256 to land first to reduce the conflicts for that large change....

2022-08-04 12:41 UTC, dhrishi approved these changes

2022-08-04 12:41 UTC, dhrishi commented on examples/all-clusters-app/all-clusters-common/src/binding-handler.cpp
> +        ChipLogError(NotSpecified, "Binding to self");
Can these not be errors? Just info logs?

2022-08-04 12:42 UTC, dhrishi commented
>Might be good to wait for https://github.com/project-chip/connectedhomeip/pull/21256 to land first to reduce the conflicts for that large change....

Ohh saw this after I approved

2022-08-04 13:02 UTC, jonsmirl commented
Some other things to consider...

1) What about groups? When the device is in the group, and when it is not in the group.
2) if there is a self-binding and then a network unicast binding is made, should it replace or override the self binding?
3) If all bindings are removed should the device revert to being self bound? ie override vs replace
4) How can we ship the device pre-configured in a self-bound state?

Consider a smart light switch. It is an integrated switch+bulb.  It should ship in the self-bound state.  But then the customer may choose to add it to a group -- like a synchronized pair at top and bottom of stair case.   Then the customer removes it from the group and expects it to revert to self-bound mode.

2022-08-04 13:07 UTC, bzbarsky-apple commented
>     1. What about groups? When the device is in the group, and when it is not in the group.

Does groupcast to self work?

>     2. if there is a self-binding and then a network unicast binding is made, should it replace or override the self binding?

I don't understand the question here.

>     3. If all bindings are removed should the device revert to being self bound? ie override vs replace

Why would it revert to "self bound" if all bindings are removed?  There is no "self bound" default.

>     4. How can we ship the device pre-configured in a self-bound state?

You have to do it out-of-band; the binding mechanism in Matter requires knowing node and group ids, which are not allocated by the device unless the device is self-commissioning.

> Consider a smart light switch. It is an integrated switch+bulb. It should ship in the self-bound state. But then the customer may choose to add it to a group -- like a synchronized pair at top and bottom of stair case. Then the customer removes it from the group and expects it to revert to self-bound mode.

That sounds like an out-of-band mechanism, at the moment.

2022-08-04 13:07 UTC, bzbarsky-apple approved these changes

2022-08-04 13:08 UTC, jonsmirl commented
Rules like this could work:

1) Allow the device to create a default self-bind without needing to be on a fabric. This self bind is permanent.
2) If you add a network unicast bind this bind will override the default bind until removed.
3) If bound to a group, send the multicast on the network -- and use the default self-bind. 
  3a) more complex - check if the device is in the group or not, use self bind if it is.

2022-08-04 13:09 UTC, bzbarsky-apple commented
Please feel free to file an issue with that suggestion.  Better yet, provide a PR.

2022-08-04 13:12 UTC, jonsmirl commented
Diagram of the use-case

![grouped-dimmers](https://user-images.githubusercontent.com/14943/182855397-c7452f03-9bef-4b70-9396-301985858a63.png)

2022-08-04 13:29 UTC, jonsmirl commented
Should Matter have special loop back node and group IDs? for example 0xFFFF or 0x0 always means self?

2022-08-04 13:40 UTC, jonsmirl commented
Related issue, could a fabric ID of 0x0 or -1 always indicate a device local fabric? ie a fabric which is only valid internally to the device and doesn't need encryption. This fabric would always be in a commissioned state.

2022-08-04 14:04 UTC, bzbarsky-apple commented
@jonsmirl None of that has to do with the specific issue this PR is trying to address, and once the PR is closed no one will see this discussion.  Please file an issue or set of issues on these things as needed, instead of bringing them up here.

2022-08-04 17:29 UTC, jonsmirl commented
I don't think this is a good solution to self-binding. There is a lot of device state logic contained in src/app/clusters/*  If you just kick the event up to me locally I have to duplicate all of that state behavior. And if I'm duplicating that code there is no guarantee that my code is going to faithfully match the code in src/app/clusters/*.  Duplicating this code adds several thousand lines of code to the device - you have to catch every command/attribute operation and handle it yourself via a separate path.

I would rather see operations follow the identical code path whether they originate locally or remotely. That mean the command needs to be looped back at the packet level.

2022-08-04 21:34 UTC, mrjerryjohns approved these changes

2022-08-09 14:14 UTC, woody-apple requested changes
Requesting changes for @jonsmirl

2023-06-18 06:57 UTC, closed without merging