Updated utility device types according to specs
project-chip/connectedhomeip pull request #21663
Opened 2022-08-05 05:44 UTC by jadhavrohit924

#### Problem
What is being fixed?  Examples:
* Utility device types was not as per specs.

#### Change overview
Updated utility device types according to specs

#### Testing
How was this tested? (at least one bullet point required)
* Verified that the xml is in sync with the specification.

2022-08-05 19:11 UTC, bzbarsky-apple requested changes
There are a bunch of differences here wrt spec (_after_ the changes for this PR).  Please create one PR per device type, so they can be reviewed independently.

2022-08-09 14:27 UTC, woody-apple approved these changes
For future changes, please keep them separated by PR.

2022-08-09 20:19 UTC, bzbarsky-apple requested changes
Like I said, there are a bunch of differences wrt spec here.  Please check that this is aligned with the spec.

2022-08-09 20:19 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
>              <include cluster="OTA Software Update Requestor" client="true" server="false" clientLocked="true" serverLocked="true"></include>
```suggestion
            <include cluster="OTA Software Update Requestor" client="true" server="false" clientLocked="false" serverLocked="true"></include>
```
This is optional in the spec.

2022-08-09 20:19 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +            <include cluster="Bridged Actions" client="false" server="false" clientLocked="true" serverLocked="false"></include>
```suggestion
            <include cluster="Actions" client="false" server="false" clientLocked="true" serverLocked="false"></include>
```

2022-08-09 20:19 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +            <include cluster="Binding" client="false" server="false" clientLocked="true" serverLocked="true">
Should just be removed, no?

2022-08-09 20:19 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
>              <include cluster="Bridged Device Basic" client="false" server="true" clientLocked="true" serverLocked="true">
Power Source and Power Source Configuration are both optional.

2022-08-10 04:53 UTC, jadhavrohit924 commented
Will add per device type separate PR soon to avoid confusion and easy to review. Closing this.

2022-08-10 04:53 UTC, closed without merging