Fix liveness timer not firing for subscriptions
project-chip/connectedhomeip pull request #21693
Opened 2022-08-05 19:15 UTC by mrjerryjohns

On subscriptions created with `ReadClient::SendRequest`,`ReadClient::RefreshLivenessCheckTimer` was erroring out due to the incorrect assumption that `mReadPrepareParams.mSessionHolder` would be
tracking a valid session, which it isn't in the re-sub disabled case.

Fixes:
- Have `mReadPrepareParams.mSessionHolder` always track the latest valid  session in all subscription related cases.
- Fix `RefreshLivenessCheckTimer` to be the type of function that just returns an error and let callers deal with calling `Close()`. Fix up callers to handle the error returned appropriately.
- Update the `MessagingContext` helper to use a much lower idle/active retrans timeout values for the test sessions to facilitate faster tests.

Tests:
- Added a new `TestSubscribeAttributeTimeout` test that checks for subscriptions timing out due to a liveness failure. Ensured that it failed prior to the change, and passes after.

2022-08-05 19:22 UTC, bzbarsky-apple approved these changes

2022-08-05 20:09 UTC, yunhanw-google approved these changes

2022-08-08 19:27 UTC, bzbarsky-apple approved these changes

2022-08-08 19:27 UTC, bzbarsky-apple commented on src/app/tests/TestReadInteraction.cpp
> -        NL_TEST_ASSERT(apSuite, ctx.GetLoopback().mSentMessageCount == 2);
This change is not OK.  After this change, this test no longer checks for the thing it's supposed to be checking for (that the ReadClient sends a Status Response) at all...

Similar for a lot of these other changes.

2022-08-08 19:28 UTC, bzbarsky-apple requested changes
Er, I meant to request changes...

2022-08-09 21:53 UTC, bzbarsky-apple approved these changes

2022-08-10 05:48 UTC, woody-apple commented
@mrjerryjohns can you rebase this?

2022-08-10 07:03 UTC, merged