[BEKEN] update examples build files for BEKEN
project-chip/connectedhomeip pull request #21993
Opened 2022-08-18 09:44 UTC by zhengyaohan

#### Change overview
* update examples build config files for BEKEN

2022-08-18 17:03 UTC, andy31415 requested changes
a zap file in `config/beken` does not look right.

2022-08-19 07:37 UTC, zhengyaohan commented
> a zap file in `config/beken` does not look right.

Thanks, We remove it by using lighting-common/lighting-app.zap.

2022-08-19 21:18 UTC, andy31415 approved these changes

2022-08-22 17:54 UTC, andy31415 commented
/rebase

2022-08-25 17:33 UTC, woody-apple approved these changes

2022-08-25 17:33 UTC, merged