Platform init refactoring
project-chip/connectedhomeip pull request #22098
Opened 2022-08-23 13:04 UTC by sharad-patil24

#### Problem
Platform init refactoring.

#### Change overview
We changed the GPIO and Bus init functions, now both these functions are called from
init_efr_platform().

#### Testing
How was this tested? (at least one bullet point required)

- Tested on HW ( MG12 + RS9116 & MG12 + WF200 )
- Commissioning 20 times.
- Sanity TC's

2022-08-23 13:50 UTC, jmartinez-silabs requested changes
Please add [EFR32] to your PR name

2022-08-23 13:50 UTC, jmartinez-silabs commented on examples/platform/efr32/init_efrPlatform.cpp
> +    wifi_board_init();
```suggestion
#ifdef SL_WIFI
    wifi_board_init();
#endif   
```

2022-08-23 13:50 UTC, jmartinez-silabs commented on examples/platform/efr32/init_efrPlatform.cpp
> +void wifi_board_init(void);
why is the prototype here? Shouldn't it be in a header file where your wifi source code is

2022-08-23 14:05 UTC, jmartinez-silabs requested changes
The hash you are using to update matter_support repo is not valid. That hash is not from the main branch. Your work there needs to be merge to matter support prior of you creating this PR...

This PR cannot be merge until that first step is done and the submodule update hash fixed.

2022-08-24 18:52 UTC, jepenven-silabs commented
@andy31415 this is indeed required and needed for the EFR32 platform with a WiFi rcp

2022-08-25 17:19 UTC, woody-apple approved these changes

2022-09-28 10:08 UTC, closed without merging