Fix the Network information does not restore back if failsafe is set …
project-chip/connectedhomeip pull request #22402
Opened 2022-09-05 16:00 UTC by AlvinHsiao

#### Problem
The dataset would not be written to flash and then unable to read  back the dataset after restore back.

#### Change overview
Change the order of mStagingNetwork to avoid this issue.

#### Testing
TC-CNET-4.10

2022-09-05 16:25 UTC, Damian-Nordic requested changes

2022-09-05 16:25 UTC, Damian-Nordic commented on src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.cpp
> +    mStagingNetwork = newDataset;
No, this was supposed to back up the previous configuration, not the one you're setting. Could you improve the PR description and tell exactly which scenario is failing for you?

2022-09-06 10:48 UTC, Damian-Nordic commented
Could you describe your testing scenario? The description only refers to ArmFailSafe command and Networks attribute while the PR modifies AddOrUpdateThreadNetwork, so I don't know how it might help.

2022-09-07 01:59 UTC, AlvinHsiao commented
@Damian-Nordic 
I followed the VerificationSteps https://groups.csa-iot.org/wg/matter-csg/document/26925?uploaded=1 to execute the commands as below:

Step1:
./chip-tool generalcommissioning arm-fail-safe 900 1 1 0 
Step2 and Step3:
./chip-tool networkcommissioning read networks 1 0
Step4:
./chip-tool networkcommissioning remove-network hex:11223344556677CC 1 0
Step5:
./chip-tool networkcommissioning read networks 1 0
Step6:
./chip-tool networkcommissioning read last-networking-status 1 0
Step7:
./chip-tool networkcommissioning read last-network-id 1 0
Step8:
./chip-tool generalcommissioning read breadcrumb 1 0
Step9:
./chip-tool networkcommissioning connect-network hex:11223344556677CC 1 0 --Breadcrumb 2 
Step10:
./chip-tool generalcommissioning read breadcrumb 1 0
Step11:
 ./chip-tool generalcommissioning arm-fail-safe 0 0 1 0
Step12:
./chip-tool networkcommissioning read networks 1 0

The results from Step1 to Step11 are as expected.
Step12 returns no entry.

2022-09-07 07:14 UTC, Damian-Nordic commented
@AlvinHsiao And why adding the fix to AddOrUpdateThreadNetwork helps with this procedure? Which platform do you test it on? Overall, it works in such a way that the backup is saved on the first RemoveNetwork, AddOrUpdateThreadNetwork or ConnectNetwork after arming the failsafe.

2022-09-07 07:24 UTC, AlvinHsiao commented
@Damian-Nordic
Adding the fix to AddOrUpdateThreadNetwork can make BackupConfiguration() to put newDataset into the storage.
I test it on CYW30739 platform.

2022-09-07 07:26 UTC, Damian-Nordic commented
Yes, but there's no AddOrUpdateThreadNetwork in the listed procedure. So how is it called?

2022-09-07 07:30 UTC, AlvinHsiao commented
@Damian-Nordic
It's called at the first commissioning TH and DUT on Thread setup:
 ./chip-tool pairing ble-thread 1 hex:0e080000000000010000000300001335060004001fffe0020811111111222222aa0708fd0f0577b70e426b051000112233445566778899aabbccddeeff030e4f70656e54687265616444656d6f01027788041067bf061e45ad0c7cb1c77a9b659379aa0c0402a0fff8 20202021 3840

2022-09-07 07:33 UTC, Damian-Nordic commented
Then it should have no impact on the listed procedure, because `CommissioningComplete` sent at the end of the commissioning should call the driver's `CommitConfiguration` which removes the backup, anyway. Doesn't it work that way for you?

2022-09-08 03:17 UTC, AlvinHsiao commented
@Damian-Nordic 
I found there is an issue in our platform, I will close this PR, thanks for your comments.

2022-09-08 03:18 UTC, closed without merging