[ColorControl] enhanced-move-to-hue-and-saturation should set enhancedcolormode to 3
project-chip/connectedhomeip pull request #22580
Opened 2022-09-13 08:30 UTC by pankore

#### Issue Being Resolved
- From spec, enhancedcolormode should be set to EnhancedCurrentHue and CurrentSaturation during enhanced-move-to-hue-and-saturation command
- Currently it is not set properly

#### Change overview
- Set enhancedcolormode to 3 (EnhancedCurrentHue and CurrentSaturation) during enhanced-move-to-hue-and-saturation command

#### Testing
- Tested with Ameba platform
- ./chip-tool colorcontrol enhanced-move-to-hue-and-saturation  16000 80 200 0 0 1 1
- ./chip-tool colorcontrol read enhanced-color-mode 1 1
- enhanced-color-mode should be 3

2022-09-13 12:37 UTC, jmartinez-silabs commented
Your patch works for that one case but the real issue lies within the function `handleModeSwitch`

In fact, I see it was patched the same way you are doing before for moveToHueCommand and I didn't catch it in that PR.

The real fix would add the EnhancedCurrentHue and CurrentSaturation mode (`COLOR_MODE_EHSV = 0x03`) in this enum in 
`src/app/clusters/color-control-server/color-control-server.h`
```
    enum ColorMode
    {
        COLOR_MODE_HSV         = 0x00,
        COLOR_MODE_CIE_XY      = 0x01,
        COLOR_MODE_TEMPERATURE = 0x02
    };
```

Check and correct all the calls of `handleModeSwitch(endpoint, COLOR_MODE_HSV);` to pass as argument the new `COLOR_MODE_EHSV` mode if the command's `isEnhanced==true`

In `handleModeSwitch`, add a check to transpose  COLOR_MODE_EHSV to COLOR_MODE_HSV  for the standard `Attributes::ColorMode::Set(endpoint, newColorMode);`

2022-09-13 12:38 UTC, jmartinez-silabs requested changes
Your patch works for that one case but the real issue lies within the function handleModeSwitch

In fact, I see it was patched the same way you are doing before for moveToHueCommand and I didn't catch it in that PR.

The real fix would add the EnhancedCurrentHue and CurrentSaturation mode (COLOR_MODE_EHSV = 0x03) in this enum in
src/app/clusters/color-control-server/color-control-server.h

    enum ColorMode
    {
        COLOR_MODE_HSV         = 0x00,
        COLOR_MODE_CIE_XY      = 0x01,
        COLOR_MODE_TEMPERATURE = 0x02
    };
Check and correct all the calls of handleModeSwitch(endpoint, COLOR_MODE_HSV); to pass as argument the new COLOR_MODE_EHSV mode if the command's isEnhanced==true

In handleModeSwitch, add a check to transpose COLOR_MODE_EHSV to COLOR_MODE_HSV for the standard Attributes::ColorMode::Set(endpoint, newColorMode);

2022-09-14 08:34 UTC, pankore commented
Updated PR description

2022-09-14 15:32 UTC, jmartinez-silabs approved these changes

2022-09-14 15:33 UTC, jmartinez-silabs commented
Thank you

2022-09-15 18:10 UTC, andy31415 commented
Accepted for 1.0: spec fix to pass cert

2022-09-15 18:10 UTC, andy31415 approved these changes

2022-09-15 18:37 UTC, merged

2022-09-20 16:16 UTC, raju-apple commented
@andy31415 @woody-apple can we cherry pick this onto SVE-2 branch please ?