[platform] make setup constants configurable in gn
project-chip/connectedhomeip pull request #2296
Opened 2020-08-24 10:26 UTC by gjc13

Now you can use:
```
extra_args="chip_device_test_setup_pincode=87654321 \
chip_device_test_setup_discriminator=1024" ./gn_build.sh
```
to specify the setup constants.

2020-08-24 10:31 UTC, bukepo approved these changes

2020-08-24 12:43 UTC, andy31415 approved these changes

2020-08-24 15:14 UTC, BroderickCarlin approved these changes
Should there also be some documentation changes to accompany this change?

2020-08-24 20:53 UTC, mspang requested changes
Can we pass this on the command line instead of environment?

2020-08-24 20:53 UTC, mspang commented on src/platform/BUILD.gn
> +    chip_device_test_setup_pincode = ""
Please use the same name for ifdef and GN arg.

2020-08-25 15:02 UTC, gjc13 commented
*DO NOT SUBMIT*

Have conflicts after https://github.com/project-chip/connectedhomeip/pull/2270 is merged.

We need to find a way to unify how we configure these macros.

2020-08-25 15:46 UTC, woody-apple approved these changes

2020-09-17 14:12 UTC, mspang requested changes

2020-09-17 14:12 UTC, mspang commented on gn_build.sh
> +opts=$(getopt --longoptions "pincode:,discriminator:" -n "$0" --options "" -- "$@")
Disagree with creating new bespoke options here, instead we could just generically accept args:

`gn_build.sh chip_device_config_use_test_setup_pin_code=12345`

But really, if you want a custom configuration, I'd actually recommend not using gn_build.sh at all and following the documented instructions for creating a custom configuration.

gn_build.sh is more intended to build what CI builds, without any local deviations.

2020-11-04 23:00 UTC, rwalker-apple commented
@gjc13 are you still working on this?

2020-11-25 02:26 UTC, closed without merging