[privacy] Drop privacy enabled messages until support is implemented.
project-chip/connectedhomeip pull request #23045
Opened 2022-10-06 06:44 UTC by turon

Given proper privacy parsing (#22783) is taking awhile to pass review and merge, this PR will drop any privacy enabled messages.

2022-10-06 12:02 UTC, andy31415 approved these changes

2022-10-06 17:47 UTC, emargolis approved these changes

2022-10-06 22:22 UTC, bzbarsky-apple commented on src/transport/SessionManager.cpp
> +    if (packetHeader.HasPrivacyFlag())
What is the path for rolling this out, given that some implementations are shipping something around sve2, not 1.0, and hence are still setting the P flag?

2022-10-06 22:31 UTC, bzbarsky-apple requested changes
We need to figure out a rollout plan for this, given what's actually getting shipped.

2022-11-04 22:18 UTC, turon commented
Closing this workaround in favor of waiting for #22783 completion.

2022-11-04 22:18 UTC, closed without merging