Set of fixes to unit-tests code
project-chip/connectedhomeip pull request #23071
Opened 2022-10-07 14:27 UTC by ATmobica

This PR contains some fixes inside the unit-test code for different modules.
Fixes:
 - Execute TestLogBufferAsHex only if CHIP_PROGRESS_LOGGING
 - PeerAddress string conversion test - allow uppercase IPV6 string conversion - check both cases
 - ArgParser in the support library - fix parse args for embedded non posix long_opt implementation, disable a parse args unit test for non posix long_opt, changed id in option sets in ParseArgs unit test
 - remove warnings of incorrect types in printf formatting
 - add missing assert header include in TestInetCommonPosix
 - TestReadInteraction - remove leftover debug printf,  drain and service IO repeatedly until the condition is met (#17528)
 - controller - fix test naming

2022-10-07 14:59 UTC, andy31415 approved these changes

2022-10-08 02:58 UTC, bzbarsky-apple requested changes

2022-10-08 02:58 UTC, bzbarsky-apple commented on src/app/tests/TestReadInteraction.cpp
> +                ctx.DrainAndServiceIO();
There shouldn't be more than one `DrainAndServiceIO` call needed here.  The fact that we're doing more than one indicates there's a bug somewhere that we need to fix...  Why is this losing the comment pointing to the tracking issue?

2022-10-08 02:58 UTC, bzbarsky-apple commented on src/app/util/mock/attribute-storage.cpp
> +                  (uint32_t) aPath.mEndpointId, (uint32_t) aPath.mClusterId, (uint32_t) aPath.mAttributeId);
Why are these casts being added?  `aPath.mClusterId` and `aPath.mAttributeId` should already be `uint32_t`, and if printing a `uint16_t` (aPath.mEndpointId) as `PRIx32` is not OK we should change it to `%x`, not add these casts.

2022-10-13 17:48 UTC, bzbarsky-apple approved these changes

2022-10-13 17:48 UTC, bzbarsky-apple commented on src/app/tests/TestReadInteraction.cpp
> -            // Not sure why I had to add this, and didn't have cycles to figure out why.
Please leave the comments explaining _what_ is being tracked (modified to the new setup as needed).

2022-10-21 22:46 UTC, merged