Implementation of the ManualSetupPayloadGenerator/Parser
project-chip/connectedhomeip pull request #231
Opened 2020-04-02 21:17 UTC by shana-apple

Implemented the ManualSetupPayloadGenerator which generates a decimal string from the manual setup payload.

Implemented the ManualSetupPayloadParser which populates a manual setup payload from a decimal string

Added unit tests

Here is the PR against my fork's master to confirm this builds correctly:
https://github.com/shana-apple/connectedhomeip/pull/1

2020-04-02 21:28 UTC, woody-apple requested changes
Can we fix the copyright here?

2020-04-02 21:40 UTC, bhaskar-apple requested changes

2020-04-07 16:10 UTC, woody-apple approved these changes

2020-04-08 22:15 UTC, bhaskar-apple submitted a review, later dismissed

2020-04-08 22:18 UTC, gerickson approved these changes

2020-04-09 16:57 UTC, hawk248 approved these changes

2020-04-09 19:07 UTC, merged