Remove include dependency on underlying crypto libraries
project-chip/connectedhomeip pull request #2310
Opened 2020-08-24 21:33 UTC by pan-apple

#### Problem
CHIPCryptoPal.h includes headers from underlying implementations (OpenSSL, mbedTLS). This requires the code at upper layers to be aware of which crypto implementation is being used, and requires it to specify include paths (e.g. iOS framework project file has to point to mbedTLS header file location).

 #### Summary of Changes
Move implementation specific code to individual implementation source code. The interface has opaque types for the context, and the size of context is checked via `static_assert` in each implementation file.

fixes #2284

2020-08-24 21:38 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mContext) >= sizeof(SHA256_CTX), "Need more memory to store SHA256 context");
Minor nit; however, if this file has no other C++11 dependencies, recommend using the portable static assertion in nlassert.h.

2020-08-24 21:38 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
Minor nit; however, if this file has no other C++11 dependencies, recommend using the portable static assertion in nlassert.h.

2020-08-24 21:38 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mContext) >= sizeof(mbedtls_sha256_context), "Need more memory to store SHA256 context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:39 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:40 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:40 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:40 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:40 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:40 UTC, gerickson commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    static_assert(sizeof(mSpake2pContext) >= sizeof(Spake2p_Context), "Need more memory for Spake2p Context");
See above.

2020-08-24 21:41 UTC, gerickson commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    SHA256_CTX * context = (SHA256_CTX *) &mContext;
Recommend C++-style rather than C-style casts.

2020-08-24 21:42 UTC, gerickson requested changes
Generally, I'd recommend:

1) Using C++ rather than C-style casts.
2) Seeing if static_asserts can be reduced by including them only in an initialization context. In addition, they are compile- rather than run-time, so I don't think they provide much value scattered about as they are.
3) Would recommend using the more portable static assertions from nlassert.h if there is nothing else about this module that has explicit C++11 dependencies.

2020-08-24 22:15 UTC, pan-apple commented
> Generally, I'd recommend:
> 
> 1. Using C++ rather than C-style casts.
> 2. Seeing if static_asserts can be reduced by including them only in an initialization context. In addition, they are compile- rather than run-time, so I don't think they provide much value scattered about as they are.
> 3. Would recommend using the more portable static assertions from nlassert.h if there is nothing else about this module that has explicit C++11 dependencies.

Thanks @gerickson , all these should be addressed now.

2020-08-24 22:17 UTC, gerickson approved these changes

2020-08-24 22:54 UTC, rwalker-apple commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    memset(mSpake2pContext, 0, sizeof(mSpake2pContext));
I think this is redundant, C++ constructors zero-initialize array member variables

2020-08-24 22:55 UTC, rwalker-apple commented on src/crypto/CHIPCryptoPALOpenSSL.cpp
> +    Spake2p_Context * context = reinterpret_cast<Spake2p_Context *>(mSpake2pContext);
what if you wrote little static inline functions that did the check, the cast, and returned the appropriate type, making it clearer the requirements for the variable, putting all the hacky stuff together?

2020-08-24 22:56 UTC, rwalker-apple commented on src/crypto/CHIPCryptoPALmbedTLS.cpp
> +    memset(mSpake2pContext, 0, sizeof(mSpake2pContext));
I think memset() to zero is redundant in a constructor

2020-08-24 22:57 UTC, rwalker-apple commented on src/darwin/Framework/CHIP.xcodeproj/project.pbxproj
> -					CHIP_CRYPTO_MBEDTLS,
sooo pretty!

2020-08-24 22:57 UTC, rwalker-apple approved these changes
lgtm, little nits

2020-08-25 01:46 UTC, rwalker-apple approved these changes
nice

2020-08-25 12:09 UTC, andy31415 approved these changes

2020-08-25 15:43 UTC, woody-apple approved these changes

2020-08-26 06:04 UTC, rwalker-apple commented
@woody-apple needs a button pusher

2020-08-26 17:45 UTC, pan-apple commented
@saurabhst, @jelderton, @BroderickCarlin, any comments?

2020-08-26 17:46 UTC, saurabhst approved these changes

2020-08-26 19:59 UTC, BroderickCarlin approved these changes

2020-08-26 19:59 UTC, merged