[Do not notify the resolve error of dnssd
project-chip/connectedhomeip pull request #23156
Opened 2022-10-13 02:38 UTC by hyunuktak

Signed-off-by: hyunuk.tak <hyunuk.tak@samsung.com>

> !!!!!!!!!! Please delete the instructions below and replace with PR desription
>
> If you have an issue number, please use a syntax of
> `Fixes #12345` and a brief change description
>
> If you do not have an issue number, please have a good description of
> the problem and the fix. Help the reviewer understand what to expect.
>
> Make sure you delete these instructions (to prove you have read them).
>
> !!!!!!!!!! Instructions end

2022-10-13 15:32 UTC, harsha-rajendran approved these changes

2022-10-13 17:27 UTC, andy31415 commented
@hyunuktak - please explain "It can cause a collision in the caller's user callback."

2022-10-13 17:28 UTC, andy31415 requested changes
Description of issue does not help me understand the problem and the fix.

I see a notification of error being removed, but I am unclear of why this is causing problems and why removing the error notification is the correct thing to do.

Silent error never seem ok. At least a log seems apropriate, but a callback of "error happened" seems even better.

Please make sure that your PR description is clear to understand for reviewers.

2022-10-14 00:46 UTC, hyunuktak commented
> @hyunuktak - please explain "It can cause a collision in the caller's user callback."

It seems that the explanation was insufficient.
I updated the detailed explanation. please refer to it.

2022-10-14 14:36 UTC, andy31415 commented
> > @hyunuktak - please explain "It can cause a collision in the caller's user callback."
> 
> It seems that the explanation was insufficient. I updated the detailed explanation. please refer to it.

The explanation is still vague. I do not understand it. The way I read it is:

"An error is reported when resoltion fails, but this may cause an error to the user like double free".


Why don't you fix the double free then? Fix on the other side. Reporting an error when an error occurs is ok. 
Unless you prove (with code links or some clear explanation) why user code never expects error reports and this is documented.

2022-10-14 14:38 UTC, andy31415 commented
`For example, user calls the resolve api of dnssd and cleans up the user data if it fails.` Why the vagueness of 'for example'?

If you fix it, make the user properly handle the cleanup of the data. This seems to be a bug in the user usage of resolution not in the implementation of error handling.

2022-10-14 14:42 UTC, andy31415 commented
I guess explanation could be done by example:

Linux avahi: https://github.com/project-chip/connectedhomeip/blob/master/src/platform/Linux/DnssdImpl.cpp#L693 does NOT callback error on failure

Darwin: https://github.com/project-chip/connectedhomeip/blob/master/src/platform/Darwin/DnssdImpl.cpp#L344 does NOT callback on failure.

I will update the summary

2022-10-14 14:44 UTC, andy31415 approved these changes

2022-10-14 14:44 UTC, merged