added clean build option using --clean flag in efr32_examples
project-chip/connectedhomeip pull request #23323
Opened 2022-10-24 15:34 UTC by lpbeliveau-silabs

Adds a new flag to do a clean build up when specifying : --clean
when using the gn_efr32_example.sh script to build examples.

2022-10-24 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=23323) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=23323) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=23323) it.</sub>

2022-10-24 16:46 UTC, andy31415 requested changes
Why are we not just using `scripts/build/build_examples.py`. That script has standardised arguments across many platforms and in particular will support `--clean`.

It is difficult to maintain several different scripts with several different arguments. As a core developer, remembering each argument for `scripts/examples` (I see androidn, efr32, psoc6, k32w, imxlinx, webos, nrfconnect, boufallolab there) is tedious.

2022-10-24 17:46 UTC, jmartinez-silabs commented
> Why are we not just using `scripts/build/build_examples.py`. That script has standardised arguments across many platforms and in particular will support `--clean`.
> 
> It is difficult to maintain several different scripts with several different arguments. As a core developer, remembering each argument for `scripts/examples` (I see android, efr32, psoc6, k32w, imxlinx, webos, nrfconnect, boufallolab there) is tedious.

@andy31415 We do maintain build_examples.py for the Silabs platform also and yes it is standardized and for stuff like CI, it is great. However, it doesn't allow as much flexibility for us. Each combination of arguments becomes a new string in the target name and It becomes even more tedious to remember the naming. If you type a wrong target name you get an error message and it prints hundreds of target names for every platform and argument combination.

With our own script that we maintain, we can provide presets that we do want to showcase but also complete flexibility in any arguments you would want to add or remove.

2022-12-22 08:53 UTC, jmeg-sfy approved these changes

2023-03-13 14:00 UTC, closed without merging