Address Darwin API review comments on MTRThreadOperationalDataset.
project-chip/connectedhomeip pull request #23392
Opened 2022-10-29 04:02 UTC by bzbarsky-apple

* Improve documentation
* Actually use our size constants in the error-checks we do.
* Make the properties non-nullable, since we always have them after successful init.

This is a re-landing of PR #22562 but modified to preserve old APIs.

2022-10-29 04:04 UTC, woody-apple approved these changes

2022-10-29 04:06 UTC, woody-apple requested changes
Don’t we have to deprecate the existing items? Example: MTRSizeThreadExtendedPanId

2022-10-29 04:10 UTC, bzbarsky-apple commented
> Don’t we have to deprecate the existing items? Example: MTRSizeThreadExtendedPanId

Yes, that's why it has the `MTR_NEWLY_DEPRECATED("Please use MTRSizeThreadExtendedPANID")` annotation.  Once we know what version numbers the deprecation macro should have, we can search/replace all `MTR_NEWLY_DEPRECATED` with the right thing.

2022-10-29 05:56 UTC, bzbarsky-apple commented
> Yes, that's why it has the MTR_NEWLY_DEPRECATED("Please use MTRSizeThreadExtendedPANID") annotation

Ah, I see.  The issue was the incorrect change from `MTRSizeThreadExtendedPanId` to `MTRSizeThreadExtendedPanID`.  Fixed.

2022-11-01 21:03 UTC, woody-apple approved these changes

2022-11-01 21:05 UTC, merged