Switch license headers to SPDX shortref, REUSE compliant
project-chip/connectedhomeip pull request #23561
Opened 2022-11-09 15:01 UTC by aalexanderr

### Problem

There are potential licensing issues in the repository (#23436) ,

### Potential solution
I think REUSE is one way to approach it to have it checked in CI

* Files that are licensed ONLY under Apache-2.0 were adjusted
* Apache License has been added to LICENSES/Apache-2.0.txt

### Testing
run:
https://github.com/fsfe/reuse-tool
on master and after applying this PR's commits

2022-11-09 15:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=23561) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=23561) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=23561) it.</sub>

2022-11-10 10:30 UTC, andy31415 requested changes
Is there a path that we could have avoiding chaging 5000+ files? Is updating `Copyright` to `SPDX-FileCopyrightText` really required?

This is a change that touches every single file and I am unsure why this would be mandatory - I would by default try to avoid something that touches every single file unless really mandated by something (e.g. some clear legal requirement or something like that).

2022-11-10 12:47 UTC, aalexanderr commented
@andy31415 - as for legal requirements - there are issues in the connectedhomeip repository, e.g. [src/lwip/cyw30739/arch/cc.h](https://github.com/project-chip/connectedhomeip/blob/master/src/lwip/cyw30739/arch/cc.h) has still proprietary headers
there are files under BSD-3-Clause, MIT, yet the license in the repo root indicates that it is apache-2.0 only. REUSE, while requiring modification to most of files in the repository and adding licensing information to ALL files (as a header, or for files thatdo not support comments - either DEP5 or using *.license files) gives:
* clear licensing situation as each file MUST have a license 
* ability to check if license is attached to every file in the repository (https://github.com/fsfe/reuse-tool)
* ability to produce spdx doc

2022-12-01 21:54 UTC, woody-apple requested changes
The repo requires all contributions to be Apache 2.0. Will follow up.

2023-05-20 11:24 UTC, closed without merging