Do not start the PASE Session establishement before device scan succeeds
project-chip/connectedhomeip pull request #23638
Opened 2022-11-16 17:39 UTC by vivien-apple

Fixes #23438

2022-11-16 21:47 UTC, bzbarsky-apple approved these changes

2022-11-16 21:47 UTC, bzbarsky-apple commented on src/controller/CHIPDeviceController.cpp
> +        self->ReleaseCommissioneeDevice(device);
Is it worth checking that the device's session is in fact a BLE session?  I'm a little worried about having these un-cancelable async bits, but I guess a lot of commissioning is like that.....

2022-11-17 09:31 UTC, Damian-Nordic requested changes

2022-11-17 09:31 UTC, Damian-Nordic commented on src/controller/CHIPDeviceController.cpp
> +        params.SetPeerAddress(Transport::PeerAddress::BLE()).SetConnectionObject(connObj);
It almost works, but you're dropping the pincode which obviously causes SPAKE to fail. I did a quick test and added `.SetSetupPINCode(20202021)` to this line - with that addition it works.

2022-11-21 15:09 UTC, Damian-Nordic approved these changes

2022-11-21 15:10 UTC, merged