Remove verbose text during building
project-chip/connectedhomeip pull request #23687
Opened 2022-11-18 20:04 UTC by andy31415

We need non-fatal diagnostics to not be printed by default during builds, since that just makes logs noisy.

Deleting a message about input matter IDL detection.

2022-11-18 20:25 UTC, mspang approved these changes

2022-11-19 06:41 UTC, yufengwangca approved these changes

2022-11-28 16:25 UTC, bzbarsky-apple requested changes

2022-11-28 16:25 UTC, bzbarsky-apple commented on src/controller/tests/data_model/TestRead.cpp
> +        // Increase timeout, so that slow versions (specifically gcc_debug) does not time out.
Why is this change needed?  Why are things fine without this change before but not fine after?

2022-11-28 16:25 UTC, bzbarsky-apple commented on src/controller/tests/data_model/TestRead.cpp
> +            Controller::detail::ReportAttribute<Clusters::UnitTesting::Attributes::ListStructOctetString::TypeInfo::DecodableType>(
You should not be using "detail" APIs here.  There are public APIs for all this; please use them.

2022-11-28 16:25 UTC, bzbarsky-apple commented on src/credentials/tests/BUILD.gn
> +    test_sources += [ "TestCommissionerDUTVectors.cpp" ]
Why is this change needed for a _logging_ change?

2022-11-28 16:25 UTC, bzbarsky-apple commented on src/transport/tests/TestSessionManager.cpp
> +#if CHIP_CONFIG_MEMORY_DEBUG_DMALLOC
Why is this needed for a logging change?

2022-11-28 17:02 UTC, closed without merging