[chip-tool] Add support for commands/attributes arguments formatted a…
project-chip/connectedhomeip pull request #24386
Opened 2023-01-12 18:09 UTC by vivien-apple

…s json

#### Problem

`chip-tool` now supports simple commands over web socket (e.g `onoff toggle 0x12344321 1`) but for commands that are more complex, the client does not necessarily know the arguments ordering.
Additional some arguments can not be passed over the wire as simple strings since they may contains control characters and notable `\0`.

This PR adds some supports to `chip-tool` to handle unordered commands over web sockets.
I have also updated the code such that `examples/chip-tool/commands/common/Commands.cpp` is now responsible for parsing "all" interactive commands - which avoid duplicating some code between `chip-tool` and `darwin-framework-tool`.

2023-01-14 03:04 UTC, bzbarsky-apple approved these changes

2023-01-14 03:04 UTC, bzbarsky-apple commented on examples/chip-tool/commands/common/Commands.cpp
> +    bool parsedArguments = JsonParser::ParseCustomArgument(encodedData, reinterpret_cast<char *>(decodedData.Get()), jsonArguments);
Uint8::to_char?

2023-01-14 03:04 UTC, bzbarsky-apple commented on examples/chip-tool/commands/common/Commands.cpp
> +    VerifyOrReturnValue(jsonArguments.isObject(), false, ChipLogError(chipTool, "Unexpected json type."));
Should say we expected object?

2023-01-14 03:04 UTC, bzbarsky-apple requested changes
Er, meant to request changes, for the off-the-end-of-the-array bit.

2023-01-17 14:45 UTC, vivien-apple commented on examples/chip-tool/commands/common/Commands.cpp
> +    auto err = RunCommand(argc, const_cast<char **>(argv), true);
I can not guarantee that. Some of the underlying code effectively modifies the arg string... I have updated the code.

2023-01-17 20:51 UTC, bzbarsky-apple approved these changes

2023-01-23 16:49 UTC, andy31415 approved these changes

2023-01-23 16:49 UTC, merged