Use chip-build as FROM for dev docker
project-chip/connectedhomeip pull request #244
Opened 2020-04-03 21:30 UTC by rwalker-apple

#### Problem
 chip-build has the list of tools for build, this Dockerfile has stuff
  for interactive development

 #### Summary of Changes
 * FROM rwalkerapple/chip-build
 * remove stuff already in chip-build

2020-04-03 22:32 UTC, woody-apple requested changes

2020-04-04 01:47 UTC, woody-apple approved these changes

2020-04-04 20:55 UTC, BroderickCarlin approved these changes

2020-04-06 18:17 UTC, hawk248 approved these changes
👍

2020-04-06 18:19 UTC, merged