Add ChipOverBluez build gn compilation support
project-chip/connectedhomeip pull request #2442
Opened 2020-09-03 07:06 UTC by yunhanw-google

-- Add Build gn support for ChipOverBluez
-- Clean unused variables and warning

fixes #2441

2020-09-03 08:41 UTC, mspang requested changes

2020-09-03 08:41 UTC, mspang commented on gn/chip/linux/gdbus_library.gni
> +        invoker.c_namespace,
dupe?

2020-09-03 08:41 UTC, mspang commented on src/platform/Linux/CHIPBluezHelper.cpp
> +    // GVariantBuilder optionsBuilder;
Remove

2020-09-03 08:41 UTC, mspang commented on src/platform/Linux/CHIPBluezHelper.cpp
> +    // g_variant_builder_init(&optionsBuilder, G_VARIANT_TYPE("a{sv}"));
Remove

2020-09-03 08:41 UTC, mspang commented on src/platform/Linux/CHIPBluezHelper.cpp
> +    // int16_t rssi           = bluez_device1_get_rssi(aDevice);
remove

2020-09-03 08:41 UTC, mspang commented on src/platform/Linux/CHIPBluezHelper.cpp
> +                    ChipLogProgress(DeviceLayer, "buf addr is %p", buf);
Did you mean to land this log?

2020-09-03 08:41 UTC, mspang commented on src/platform/Linux/dbus/bluez/BUILD.gn
> +  c_generate_object_manager = "Yes"
Could this be true instead of "Yes" ?

2020-09-03 08:49 UTC, yunhanw-google commented on gn/chip/linux/gdbus_library.gni
> +        invoker.c_namespace,
yep, just removed, thanks

2020-09-03 08:49 UTC, yunhanw-google commented on src/platform/Linux/CHIPBluezHelper.cpp
> +    // g_variant_builder_init(&optionsBuilder, G_VARIANT_TYPE("a{sv}"));
yep, just removed, thanks

2020-09-03 08:49 UTC, yunhanw-google commented on src/platform/Linux/CHIPBluezHelper.cpp
> +                    ChipLogProgress(DeviceLayer, "buf addr is %p", buf);
yep, just removed, thanks

2020-09-03 08:50 UTC, yunhanw-google commented on src/platform/Linux/dbus/bluez/BUILD.gn
> +  c_generate_object_manager = "Yes"
Done, thanks

2020-09-03 08:50 UTC, yunhanw-google commented on src/platform/Linux/CHIPBluezHelper.cpp
> +    // GVariantBuilder optionsBuilder;
done, thanks

2020-09-03 08:50 UTC, yunhanw-google commented on src/platform/Linux/CHIPBluezHelper.cpp
> +    // int16_t rssi           = bluez_device1_get_rssi(aDevice);
done, thanks

2020-09-03 09:43 UTC, mspang approved these changes

2020-09-03 09:43 UTC, mspang commented on src/platform/Linux/dbus/bluez/BUILD.gn
> +  c_generate_object_manager = "true"
boolean true instead of string?

2020-09-03 17:35 UTC, yunhanw-google commented on src/platform/Linux/dbus/bluez/BUILD.gn
> +  c_generate_object_manager = "true"
Yes, done, thanks

2020-09-05 03:26 UTC, rwalker-apple requested changes
@yunhanw-google please update the description using the PR template

2020-09-08 18:19 UTC, yunhanw-google commented
> @yunhanw-google please update the description using the PR template

@rwalker-apple Done, thank you!

2020-09-08 18:54 UTC, rwalker-apple approved these changes

2020-09-08 18:54 UTC, rwalker-apple commented
@saurabhst ?

2020-09-08 18:56 UTC, saurabhst approved these changes

2020-09-08 19:33 UTC, merged