[chip-tool] Add an API to list the discovered devices over mdns and ble
project-chip/connectedhomeip pull request #25374
Opened 2023-02-28 17:16 UTC by vivien-apple

#### Problem

There is no API to list commissionable BLE devices with darwin.  This PR adds one and add a chip-tool command for it.

2023-02-28 19:10 UTC, bzbarsky-apple requested changes

2023-02-28 19:10 UTC, bzbarsky-apple commented on examples/chip-tool/BUILD.gn
> +    "commands/pairing/DiscoverDevicesCommand.cpp",
We already have a `DiscoverCommissionablesCommand`.  How does this one differ, fundamentally?

2023-02-28 19:10 UTC, bzbarsky-apple commented on src/controller/CHIPDeviceController.h
> +    CHIP_ERROR DiscoverDevices(SetUpCodePairerDiscoveryDelegate * delegate, DiscoveryType discoveryType = DiscoveryType::kAll);
How does one stop the discovery once started?

2023-02-28 19:10 UTC, bzbarsky-apple commented on src/platform/Darwin/PlatformManagerImpl.h
> +    CHIP_ERROR PrepareCommissioning(PrepareCommissioningDelegate * delegate = nullptr);
Again, how does one cancel this if the `PrepareCommissioningDelegate` is being destroyed?

2023-03-01 18:07 UTC, vivien-apple commented
I have updated the PR. In short there are 2 new methods, `StartDiscoverDevices` and `StopDiscoverDevices`.

2023-03-01 18:09 UTC, vivien-apple commented
I am converting that to a draft since I would like to explore removal of nodes before getting that in.

2023-03-09 13:11 UTC, vivien-apple commented
I think this is in a shape where it can be reviewed. Please ignore the first commit (
[[darwin] Race when BleConnection stop is called](https://github.com/project-chip/connectedhomeip/pull/25374/commits/d4425a8f800d7ee9f527d8c30db6383d9be1950e)) which is reviewed separately.

2023-03-09 21:11 UTC, bzbarsky-apple approved these changes

2023-03-09 21:11 UTC, bzbarsky-apple commented on examples/chip-tool/commands/common/DeviceScanner.h
> +#define USE_BLE_SCANNER 1
Maybe call it CHIP_TOOL_DEVICE_SCANNER_USE_BLE just to avoid accidental collisions with something else?

2023-03-09 21:11 UTC, bzbarsky-apple commented on examples/chip-tool/commands/discover/DiscoverCommissionablesCommand.h
> +                    "Time, in seconds, before this command is considered to have timed out.");
When would this be useful?  This command does nothing sync, right?

2023-03-15 16:27 UTC, merged