fix lwip Thread interface address synchronization
project-chip/connectedhomeip pull request #2550
Opened 2020-09-10 07:58 UTC by gjc13

The interface status should track whether Thread IPv6 is enabled rather
than whether Thread is attached.

2020-09-10 08:02 UTC, bukepo approved these changes
LGTM:+1:

2020-09-10 15:34 UTC, yufengwangca approved these changes

2020-09-10 15:42 UTC, jwhui approved these changes

2020-09-10 16:34 UTC, rwalker-apple requested changes
please update the PR description with the PR template .github/PULL_REQUEST_TEMPLATE.md

2020-09-10 17:38 UTC, mspang approved these changes

2020-09-11 04:53 UTC, rwalker-apple approved these changes

2020-09-11 04:54 UTC, rwalker-apple commented
@hawk248 @jelderton @saurabhst ?

2020-09-11 04:54 UTC, saurabhst approved these changes

2020-09-11 05:36 UTC, merged