Fixes review issue 25498
project-chip/connectedhomeip pull request #25502
Opened 2023-03-06 22:18 UTC by mykrupp

https://github.com/project-chip/connectedhomeip/issues/25498

2023-03-07 02:06 UTC, bzbarsky-apple requested changes
This does not look like it addresses https://github.com/project-chip/connectedhomeip/pull/25465#discussion_r1127001709 or https://github.com/project-chip/connectedhomeip/pull/25465#discussion_r1127004425 in the SiWx918 LockManager.cpp

2023-03-07 02:06 UTC, bzbarsky-apple commented on examples/lock-app/silabs/efr32/src/LockManager.cpp
> +    for (auto currentCredential : mLockCredentials[to_underlying(CredentialTypeEnum::kPin)])
```suggestion
    for (const auto & currentCredential : mLockCredentials[to_underlying(CredentialTypeEnum::kPin)])
```

2023-03-07 02:44 UTC, bzbarsky-apple approved these changes

2023-03-07 02:44 UTC, bzbarsky-apple commented on examples/lock-app/silabs/SiWx917/src/LockManager.cpp
> +    for (const auto currentCredential & : mLockCredentials[to_underlying(CredentialTypeEnum::kPin)])
```suggestion
    for (const auto & currentCredential : mLockCredentials[to_underlying(CredentialTypeEnum::kPin)])
```

2023-03-07 02:44 UTC, bzbarsky-apple commented on examples/lock-app/silabs/efr32/src/LockManager.cpp
> +    for (const auto currentCredential & : mLockCredentials[to_underlying(CredentialTypeEnum::kPin)])
```suggestion
    for (const auto & currentCredential : mLockCredentials[to_underlying(CredentialTypeEnum::kPin)])
```

2023-03-08 17:08 UTC, yufengwangca approved these changes

2023-03-08 19:32 UTC, selissia approved these changes

2023-03-09 17:24 UTC, merged