[Silabs] DIC integration changes under mqtt flag and DIC macro
project-chip/connectedhomeip pull request #25694
Opened 2023-03-15 14:42 UTC by Thirsrin

Added :

DIC integration changes under mqtt flag(use_mqtt) and DIC macro(DIC_ENABLE)

Tested :

all builds success for efr32 and SiWx917

2023-03-16 12:55 UTC, jepenven-silabs requested changes

2023-03-16 12:55 UTC, jepenven-silabs commented on third_party/silabs/efr32_sdk.gni
> +        defines += [ "DIC_ENABLE=1" ]
This seems to duplicates the one present in `examples/platform/silabs/efr32/BUILD.gn`

2023-03-16 12:55 UTC, jepenven-silabs commented on third_party/silabs/SiWx917_sdk.gni
> +      "SIWX_917",
I don't see any `DIC_ENABLE=1` for 917 anywhere ...

2023-03-16 12:55 UTC, jepenven-silabs commented on src/platform/silabs/efr32/efr32-chip-mbedtls-config.h
> +#ifdef DIC_ENABLE
The defines should be all grouped inside a single #ifdef

2023-03-16 12:55 UTC, jepenven-silabs commented on src/platform/silabs/SiWx917/siwx917-chip-mbedtls-config.h
> +#ifdef DIC_ENABLE
Same comments these should all be grouped together

2023-03-16 12:55 UTC, jepenven-silabs commented on src/lwip/silabs/lwipopts-wf200.h
> +#ifdef DIC_ENABLE
Same comment please group all defines together under a single `#ifdef`

2023-03-16 12:55 UTC, jepenven-silabs commented on examples/platform/silabs/efr32/BUILD.gn
> +    defines += [ "DIC_ENABLE=1" ]
This seems to be duplicated with the one in `efr32_sdk.gni`

2023-03-16 12:55 UTC, jepenven-silabs commented on examples/platform/silabs/SiWx917/BUILD.gn
> +      "${chip_root}/src/inet",
I don't seen any `DIC_ENABLE=1` for 917

2023-03-17 16:32 UTC, jepenven-silabs approved these changes

2023-03-18 16:40 UTC, yufengwangca approved these changes

2023-03-18 16:40 UTC, merged