[silabs] Fix to SiWx917 SoC Auto MCU Reset issue
project-chip/connectedhomeip pull request #25755
Opened 2023-03-20 16:08 UTC by senthilku

#### problem:
917 SoC auto MCU reset issue is observed with this PR https://github.com/project-chip/connectedhomeip/pull/25503
__disable_irq() and __enable_irq() where added in the nvm3 lock for SoC but this is overriding now and it is causing the reset issue.

#### Fix:
We added __disable_irq() and __enable_irq() code in the nvm3_lockBegin() and nvm3_lockEnd() respectively for SoC to avoid the reset issue.

2023-03-20 18:17 UTC, jmartinez-silabs requested changes
Requesting change so this doesn't get merge before we discuss the issue

2023-03-20 18:17 UTC, jmartinez-silabs commented on src/platform/silabs/SilabsConfig.cpp
> +    __disable_irq();
need to be discussed internally. I don't believe we should disable IRQ in our multi-thread context. We need clarification on what causes the device to reboot.

2023-03-23 12:57 UTC, jmartinez-silabs approved these changes

2023-03-23 15:05 UTC, andy31415 approved these changes

2023-03-23 20:01 UTC, merged