[nrfconnect] Added on-boarding codes generation to the factory data script
project-chip/connectedhomeip pull request #25879
Opened 2023-03-29 12:00 UTC by ArekBalysNordic

Generate onboarding parameters:
 - manual pairing code
 - QRCode using Nrfconnect factory data script.

To generate onboarding parameters add --generate_onboarding to the generate_nrfconnect_chip_factory_data.py script.

2023-03-29 13:28 UTC, greg-fer requested changes

2023-03-29 13:28 UTC, greg-fer commented on docs/guides/nrfconnect_factory_data_configuration.md
> +5. Navigate to the output directory provided as `-o` argument.
```suggestion
5. Navigate to the output directory provided as the `-o` argument.
```

2023-03-29 13:28 UTC, greg-fer commented on docs/guides/nrfconnect_factory_data_configuration.md
> +    - .png file containing the generated QRCode as an image.
```suggestion
The output directory contains the following files you need:

- JSON file containing the latest factory data set.
- Test file containing the generated manual code and the text version of the QR Code.
- PNG file containing the generated QR Code as an image.
```

2023-03-29 18:11 UTC, bzbarsky-apple approved these changes

2023-03-29 18:11 UTC, bzbarsky-apple commented on .github/workflows/examples-nrfconnect.yaml
> +                  scripts/run_in_build_env.sh 'pip3 install -r scripts/setup/requirements.nrfconnect.txt'
I wonder whether it's worth having this as part of the Docker image...  followup for that if so.

2023-03-30 09:09 UTC, greg-fer requested changes

2023-03-31 08:39 UTC, greg-fer approved these changes
One nit.

2023-03-31 08:39 UTC, greg-fer commented on docs/guides/nrfconnect_factory_data_configuration.md
> +`-DCONFIG_CHIP_FACTORY_DATA_GENERATE_ONBOARDING_CODES=y`:
```suggestion
`-DCONFIG_CHIP_FACTORY_DATA_GENERATE_ONBOARDING_CODES=y`.
```

2023-03-31 13:18 UTC, kkasperczyk-no approved these changes

2023-03-31 13:51 UTC, merged