[esp32] Fix fail to establish CASE connection with ESP32 M5
project-chip/connectedhomeip pull request #25935
Opened 2023-04-02 05:15 UTC by yufengwangca

Use this memory configuration could increase the free heap from 

`I (2171) light-app-callbacks: Current free heap: 87440`

to

`I (2023) light-app-callbacks: Current free heap: 119400`

This significantly improve the success rate of CASE connection with ESP32 M5

Fix: https://github.com/project-chip/connectedhomeip/issues/25833

2023-04-02 05:41 UTC, dhrishi requested changes
I would suggest to not change the default example configuration defaults as it would affect a lot of existing use cases.

If you want to use the same example, create something like sdkconfig.optimize.defaults and use it through a flag while compiling. And then use that command for compilation.

2023-04-02 20:36 UTC, yufengwangca commented
> I would suggest to not change the default example configuration defaults as it would affect a lot of existing use cases.
> 
> If you want to use the same example, create something like sdkconfig.optimize.defaults and use it through a flag while compiling. And then use that command for compilation.

Acked

2023-04-03 22:11 UTC, bzbarsky-apple approved these changes
Approved, assuming @dhrishi is OK with this.

2023-04-04 05:15 UTC, dhrishi approved these changes

2023-04-04 15:22 UTC, merged