[Telink] Fix NotifyAdvertisingStopped with Null node
project-chip/connectedhomeip pull request #26033
Opened 2023-04-10 12:24 UTC by andriy-bilynskyy

Since in file src/platform/Zephyr/BLEAdvertisingArbiter.cpp function InsertRequest
obtains previous node using iteration via slist -
condition (prev == nullptr) is only true if slist is empty.
In that case NotifyAdvertisingStopped is always called with Null
and no Null checker inside the function.
As result crash.

Testing
Tested manually with chip-tool.
Steps:
- Run: $ chip-tool pairing ble-thread <...>
- Wait till success

2023-04-10 15:31 UTC, bzbarsky-apple requested changes

2023-04-10 15:31 UTC, bzbarsky-apple commented on src/platform/Zephyr/BLEAdvertisingArbiter.cpp
> -        NotifyAdvertisingStopped(sys_slist_peek_head(&sRequests));
This does not seem right.  The goal of this code is that if we are inserting the new request at the head of the list, that means we are stopping advertising on the current list head.  

It does need to account for the "no current list head" case, but removing the code altogether seems like a strange way to do said accounting.

2023-04-12 08:10 UTC, s07641069 approved these changes

2023-04-14 06:09 UTC, andriy-bilynskyy commented
@bzbarsky-apple could you look at applied changes you mentioned?

2023-04-14 19:38 UTC, bzbarsky-apple commented on src/platform/Zephyr/BLEAdvertisingArbiter.cpp
> +        NotifyAdvertisingStopped(sys_slist_peek_head(&sRequests));
I don't know whether this is right or not, (what's the API contract about notifying the consumer about advertising stop on a thing the consumer is canceling anyway?) but this does not address the question of what happend when InsertRequest inserts a new thing at the head....

2023-09-18 16:17 UTC, s07641069 commented
@andriy-bilynskyy Please close this PR as not valid.

2023-09-18 16:18 UTC, closed without merging