Fix template argument naming for value assign
project-chip/connectedhomeip pull request #26144
Opened 2023-04-18 14:55 UTC by andy31415

The SRC/DEST names were odd ... still correct, but saying `DEST src` sounds odd.

2023-04-18 17:11 UTC, arkq approved these changes
Is that only me, or GitHub doesn't show any files in the "Files changed" tab... ?

2023-04-18 17:43 UTC, bzbarsky-apple requested changes
There are no changes here.

2023-04-19 02:51 UTC, andy31415 commented
> There are no changes here.

I don't know what went wrong. re-created the delta.

2023-04-19 03:35 UTC, bzbarsky-apple approved these changes

2023-04-20 12:41 UTC, merged