[EFR32]Add MGM240P board support
project-chip/connectedhomeip pull request #26352
Opened 2023-05-03 15:26 UTC by lboue

Trying to add support for MGM240P board based on the Series 2 EFR32MG24 SoC.
Fixes #26350

_The MGM240P wireless module is built around the EFR32MG24 Wireless SoC with a 32-bit ARM Cortext-M33 core processor running at 39 MHz with 1536 kb Flash memory and 256 kb RAM. The MGM240P works with common 802.15.4 wireless protocols (Matter®, Zigbee®, and OpenThread®) as well as Bluetooth® Low Energy 5.3. The MGM240P supports Silicon Labs' [Secure Vault™](https://www.silabs.com/security/secure-vault) for Thread applications._

@jmartinez-silabs Does this look correct?

2023-05-03 18:12 UTC, jmartinez-silabs commented
Hi @lboue, the SparkFun board is already supported and is referenced as BRD2704A.

Use that board name to build your sample app for the SparkFun board. We can some notes to clearly identify that the board name has the Sparkfun one.

Note that your current PR would be a start in the right way to support a new board but not sufficient.

I will add that note also on the GitHub ticket you created.

2023-05-03 20:09 UTC, bzbarsky-apple approved these changes

2023-05-03 20:18 UTC, jmartinez-silabs commented
@lboue it is available for all our supported sample-app. The readme didn't get updated to reflect the addition of that board.

But it is and you can build the silabs apps with that board `BRD2704A`

2023-05-03 20:20 UTC, jmartinez-silabs requested changes
** requesting change so it doesn't get merge just yet ** 

See other comments before.
- Probably not needed
- Not sufficient to support a new board

2023-05-03 21:41 UTC, lboue commented
> @lboue it is available for all our supported sample-app. The readme didn't get updated to reflect the addition of that board.
> 
> But it is and you can build the silabs apps with that board `BRD2704A`

Thanks for the tip but it doesnt seems to work as described here:
* EFR32 lighting-app BRD2704A #26356
* EFR32 light-switch-app BRD2704A fatal error: sl_simple_button_instances.h: No such file or directory #26357

2023-05-03 22:42 UTC, lboue commented
> @lboue it is available for all our supported sample-app. The readme didn't get updated to reflect the addition of that board.
> 
> But it is and you can build the silabs apps with that board `BRD2704A`

BRD2704A directory is missing from SiliconLabs S_ilicon Labs Gecko SDK (GSDK)_ git repo:
https://github.com/SiliconLabs/sdk_support/tree/main/matter/efr32/efr32mg24/BRD2704A

2023-05-03 23:07 UTC, jmartinez-silabs commented
@lboue It is here
https://github.com/SiliconLabs/sdk_support/tree/main/matter%2Fefr32%2Fmgm24%2FBRD2704A

I'll try to build it and see the issue but it should work

2023-05-04 01:30 UTC, jepenven-silabs commented
@lboue SparkFun is only supported for the lighting app since all of our examples assumes the presence of at least 1 buttons. Since there is no buttons on the board itself there are not supported. With the current rework in progress we should be able to support all of them shortly for sais board but with limited functionality by default (unless of course you add a button and do the pin mapping manually)

2023-05-04 16:32 UTC, jmartinez-silabs commented
spark fun board is already supported but broken on master.
Fix the missing linkage is in this open pr

`https://github.com/project-chip/connectedhomeip/pull/26370`

2023-05-04 16:32 UTC, closed without merging