Add Room Air Conditioner device type definition
project-chip/connectedhomeip pull request #26472
Opened 2023-05-10 08:02 UTC by huangzh142

Add Room Air Conditioner device type definition

2023-05-10 08:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=26472) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=26472) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=26472) it.</sub>

2023-05-11 02:07 UTC, bzbarsky-apple requested changes

2023-05-11 02:07 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +                <requireCommand>IdentifyQuery</requireCommand>
This does not make sense.  This command is explicitly _disallowed_ in Matter.  Yes, I know other device types here probably get it wrong too; please file an issue on them and don't make the problem worse.

2023-05-11 02:07 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +                <requireCommand>TriggerEffect</requireCommand>
I don't see where this device type makes TriggerEffect mandatory.  This seems like a bad copy/paste from the lighting device types which _do_ make it mandatory.

Again, if other device types shouldn't make this mandatory but do, file issues.

2023-05-11 02:07 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +                <requireAttribute>PARTS_LIST</requireAttribute>
All those are mandatory in the cluster, so why do we need to list them here?

2023-05-11 02:07 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +            <include cluster="Binding" client="false" server="false" clientLocked="true" serverLocked="false">
Why?  This device type does not allow a optional Binding server.

2023-05-11 02:07 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +            <include cluster="On/Off" client="false" server="true" clientLocked="true" serverLocked="true"></include>
Why do we not have requireCommand bits for this one?  I suspect in practice we should not have them for any of the bits above except insofar as this device type overrides the default cluster conformance values.  Which it only does for Identify and On/Off.

2023-05-11 02:07 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +            <include cluster="Fan Control" client="false" server="false" clientLocked="false" serverLocked="true"></include>
This says "Optional Fan Control client".  That does not match the spec for this device type.

2023-05-11 02:07 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/matter-devices.xml
> +            <include cluster="Relative Humidity Measurement" client="false" server="false" clientLocked="false" serverLocked="true"></include>
Again, why is this allowing the _client_ clusters here?

2023-05-11 19:54 UTC, bzbarsky-apple approved these changes

2023-05-12 14:12 UTC, andy31415 approved these changes

2023-05-12 14:13 UTC, merged