[ASR] implement docker best practices
project-chip/connectedhomeip pull request #26561
Opened 2023-05-13 01:59 UTC by tx2rx

- implement docker best practices for asr docker
 - remove git lfs
 - toolchain for asr582x is enough for building

2023-05-15 07:14 UTC, arkq requested changes

2023-05-15 07:14 UTC, arkq commented on integrations/docker/images/chip-build-asr/Dockerfile
>      && apt-get update \
If `apt install` is not used in that "RUN", remove update as well.

2023-05-15 07:14 UTC, arkq commented on integrations/docker/images/chip-build-asr/Dockerfile
>      && tar -jxvf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 \
After untar, remove downloaded archive file to reduce image size.

2023-05-15 07:14 UTC, arkq commented on integrations/docker/images/chip-build-asr/Dockerfile
>  ARG ASR_DIR=/opt/asr
Maybe export this directory as `ASR_SDK_ROOT`. Many other platforms do that, e.g.: `ENV BOUFFALOLAB_SDK_ROOT=/opt/bouffalolab_sdk`

2023-05-15 08:19 UTC, arkq approved these changes

2023-05-16 02:44 UTC, bzbarsky-apple approved these changes

2023-05-16 02:45 UTC, merged