Add washer-controls cluster xml and generate zap
project-chip/connectedhomeip pull request #26702
Opened 2023-05-19 19:23 UTC by abeck-whirlpool

Adding in the washer-controls cluster xml file and performing the zap generation

2023-05-19 19:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=26702) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=26702) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=26702) it.</sub>

2023-05-19 19:59 UTC, rbultman commented on src/app/zap-templates/zcl/data-model/chip/washer-controls-cluster.xml
> +    <attribute side="server" code="0x0000" define="SPIN_SPEEDS"               type="ARRAY" entryType="STRING"                               writable="false" isNullable="false" optional="false">SpinSp
```suggestion
    <attribute side="server" code="0x0000" define="SPIN_SPEEDS"               type="ARRAY" entryType="SpinSpeedIndex"                               writable="false" isNullable="false" optional="false">SpinSpeeds</attribute>
```

2023-05-19 20:02 UTC, rbultman commented on src/app/zap-templates/zcl/data-model/chip/washer-controls-cluster.xml
> +  </struct>
Reading ahead to the PR that removes SpinSpeedIndex, you don't need this anymore.
```suggestion
```

2023-05-19 21:03 UTC, bzbarsky-apple commented
@rbultman @abeck-whirlpool please see https://github.com/project-chip/connectedhomeip/pull/26649

2023-05-22 16:16 UTC, abeck-whirlpool commented
> > @rbultman @abeck-whirlpool please see #26649
> 
> Do we know why the PR was closed? It looks like it was closed by the PR author without comment.

This was closed as we were going to do the two PR's one for XML and codegen and another for the server addition (which will be handled by NXP) per the TCC recommendation

2023-05-22 16:16 UTC, abeck-whirlpool commented
> @rbultman @abeck-whirlpool please see #26649

This was closed as we were going to do the two PR's one for XML and codegen and another for the server addition (which will be handled by NXP) per the TCC recommendation

2023-06-02 16:11 UTC, bzbarsky-apple requested changes

2023-06-02 17:27 UTC, bzbarsky-apple approved these changes

2023-06-06 13:37 UTC, bzbarsky-apple requested changes

2023-06-06 15:59 UTC, bzbarsky-apple approved these changes

2023-06-06 17:21 UTC, rbultman approved these changes

2023-06-06 17:21 UTC, rbultman approved these changes

2023-06-06 17:27 UTC, marktrayer commented
There's something missing on the Java side, I'm not familiar enough with the tool chain to know what though (see the build failures).

2023-06-06 19:01 UTC, marktrayer approved these changes

2023-06-06 20:26 UTC, andy31415 commented on src/controller/data_model/controller-clusters.matter
> +  readonly attribute optional OCTET_STRING spinSpeeds[] = 0;
spin speeds ios `string` in the spec, not octet_string (which would be binary data).

2023-06-06 20:29 UTC, marktrayer commented on src/app/zap-templates/zcl/data-model/chip/washer-controls-cluster.xml
> +    <attribute side="server" code="0x0000" define="SPIN_SPEEDS"               type="ARRAY" entryType="OCTET_STRING"                                writable="false" isNullable="false" optional="true">
Shouldn't OCTET_STRING be CHAR_STRING?

2023-06-06 20:31 UTC, andy31415 commented on src/app/zap-templates/zcl/data-model/chip/washer-controls-cluster.xml
> +    <attribute side="server" code="0x0003" define="MAXRINSES"                 type="INT8U"                                                         writable="false"                    optional="true">
not sure if we want to have min and max here. Spec is restrictive here (0 to 8)

2023-06-06 20:32 UTC, andy31415 commented on src/app/zap-templates/zcl/data-model/chip/washer-controls-cluster.xml
> +  <bitmap name="WasherControlFeature" type="BITMAP32">
Name this `Feature` based on us trying to standardize naming. We ended up asking everyone to just use `Feature` (we had some back and forth here)

2023-06-06 20:33 UTC, andy31415 approved these changes

2023-06-07 20:15 UTC, merged