Add nanopb as git submodule (#2668)
project-chip/connectedhomeip pull request #2671
Opened 2020-09-15 15:22 UTC by szatmz

#### Problem
nanopb is a lightweight protobuf implementation. Protobufs are required e.g. by some modules of Pigweed which already is a submodule.

 #### Summary of Changes
Adds https://github.com/nanopb/nanopb.git as a git submodule to
third_party/nanopb/repo

fixes #2668

2020-09-15 15:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=2671) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=2671) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=2671) it.</sub>

2020-09-15 15:29 UTC, gerickson commented
Since there are current no plans to use protocol buffers in CHIP, can we instead file a bug against Pigweed to short-circuit this dependency if CHIP isn't, in turn, using those facilities in Pigweed that depend on protobuf?

2020-09-15 15:50 UTC, robszewczyk commented
> Since there are current no plans to use protocol buffers in CHIP, can we instead file a bug against Pigweed to short-circuit this dependency if CHIP isn't, in turn, using those facilities in Pigweed that depend on protobuf?

Is there a way to perhaps work with the Pigweed team to pull in a different serialization mechanism?

2020-09-15 16:00 UTC, gerickson commented
> > Since there are current no plans to use protocol buffers in CHIP, can we instead file a bug against Pigweed to short-circuit this dependency if CHIP isn't, in turn, using those facilities in Pigweed that depend on protobuf?
> 
> Is there a way to perhaps work with the Pigweed team to pull in a different serialization mechanism?

If on-device testing is what we're trying to achieve, we should use CHIP TLV for encoding and define a new CHIP protocol, cluster, or extend an existing one with the requisite commands.

2020-09-15 16:09 UTC, andy31415 commented
@szatmz Could you explain usage? 
I imagine if this is to build/prototype separate functionality for testing this may be ok, however for shipping images we likely want to standardize a single encoding mechanism to not bloat/complicate code.

2020-09-15 16:14 UTC, szatmz commented
pw_rpc was proposed as the mechanism to be able to run on-device tests for development support and for some certification use cases, without having to have the full CHIP stack to send and receive commands that drive the tests. The flash cost of nanopb is estimated to be between 2500 and 8000 bytes. That cost only applies to debug builds as release/shipping builds won't have the Pigweed RPC side channel.

2020-09-15 20:02 UTC, rwalker-apple commented on .gitmodules
> +[submodule "third_party/nanopb/repo"]
prefer
```
[submodule "nanopb"]
```
as above

2020-09-15 20:03 UTC, rwalker-apple requested changes
prefer
```
[submodule "nanopb"]
```
as above

In the description: can you describe what not having nanopb is blocking?

2020-09-21 15:39 UTC, szatmz commented
> prefer
> 
> ```
> [submodule "nanopb"]
> ```
> 
> as above

Done

> 
> In the description: can you describe what not having nanopb is blocking?

Added README.md explaining that nanopb is restricted to on-device testing use cases.

2020-09-21 16:09 UTC, andy31415 approved these changes

2020-09-22 16:28 UTC, woody-apple approved these changes

2020-09-23 15:52 UTC, BroderickCarlin approved these changes

2020-09-23 22:08 UTC, rwalker-apple approved these changes

2020-09-23 22:09 UTC, rwalker-apple commented
conflicts and Android build failure to address...

2020-09-23 23:21 UTC, szatmz commented
Removed extra commits on this PR.

2020-09-24 00:12 UTC, merged