Ha low enum additions
project-chip/connectedhomeip pull request #26751
Opened 2023-05-23 15:22 UTC by simonhmorris1

This PR adds the HaLow enum for WiFiBand and WiFiVersionEnum as described here: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6333#pullrequestreview-1323895640

2023-05-24 02:30 UTC, bzbarsky-apple requested changes
@simonhmorris1 Note also the restyled failures in the C++ changes.

2023-05-24 02:30 UTC, bzbarsky-apple commented on src/darwin/Framework/CHIP/templates/availability.yaml
I appreciate you trying to fix these bits, but the changes to this file aren't right.  They are claiming that these new values shipped in iOS 16.1 for "1G" and iOS 16.4 for "Ah", which is hard without time-travel.

Please just revert the changes to this file and I'll update it after this PR lands.  Or I can push an additional changeset to this PR, or a PR against this PR, to put the right annotations in.  Let me know which of those you would prefer, @simonhmorris1

2023-05-24 13:18 UTC, simonhmorris1 commented on src/darwin/Framework/CHIP/templates/availability.yaml
Reverted the availability change, thanks for pointing this out. Please feel free to add a changeset to this PR. The auto generated  MTRBaseClusters.h now shows MTR_NEWLY_AVAILABLE. @bzbarsky-apple

2023-05-24 14:55 UTC, bzbarsky-apple approved these changes

2023-05-24 16:26 UTC, bzbarsky-apple commented
@simonhmorris1 You need to merge/rebase to tip and run `/scripts/tools/zap/generate.py examples/chef/devices/rootnode_pump_a811bb33a0.zap` to regenerate the bits for the new example app that got added...

2023-05-25 14:09 UTC, andy31415 approved these changes

2023-05-25 18:12 UTC, merged