Dont store transition val
project-chip/connectedhomeip pull request #26867
Opened 2023-05-26 08:41 UTC by step0035

- fix #26866 
- for attributes that supports transitioning, added a `isTemp` argument in their `Set` function
- if the transition is not completed yet, the attribute value is temporary and don't store it into kvs
- only store to kvs when the transition is completed

### Note
- i only added this for levelcontrol and colorcontrol attributes, not sure about other clusters, please help to add it in if i missed out any

2023-05-26 09:37 UTC, step0035 commented
will it be better if i create a separate `set` function for the affected attribute? Seems like there are a lot of build failures.

2023-05-26 09:52 UTC, Damian-Nordic commented
Note that we solved this issue using `DeferredAttributePersister` not to make changes in the attribute storage: https://github.com/project-chip/connectedhomeip/pull/23366. But maybe your approach is more straightforward, indeed.

2023-05-26 18:52 UTC, tcarmelveilleux commented on src/app/util/attribute-table.cpp
>  EmberAfStatus emberAfWriteAttribute(EndpointId endpoint, ClusterId cluster, AttributeId attributeID, uint8_t * dataPtr,
Suggest using a new method `emberAfWriteAttributeSkipNonVolatile` to be much more explicit, which calls the version with isTemp.

This way, almost none of the accessors below need to be changed.

2023-05-26 18:53 UTC, tcarmelveilleux commented on zzz_generated/app-common/app-common/zap-generated/attributes/Accessors.cpp
The template for codegen has to be changed. You cannot manually change files in zzz_generated. See comment higher up (`// THIS FILE IS GENERATED BY ZAP`)

2023-05-26 23:54 UTC, bzbarsky-apple requested changes
This is a spec violation if done in this blanket way.  See https://github.com/project-chip/connectedhomeip/blob/master/src/app/DeferredAttributePersistenceProvider.h for how this should be handled.

2023-05-29 01:49 UTC, step0035 commented
Thanks for the reviews, i will close this PR and look into `DeferredAttributePersistenceProvider`.

2023-05-29 01:49 UTC, closed without merging