Add concentration measurement clusters to all clusters app
project-chip/connectedhomeip pull request #26944
Opened 2023-05-30 09:34 UTC by hicklin

Fixes https://github.com/project-chip/connectedhomeip/issues/26833.

Adds the PM1, PM2.5, PM10, CO2, NO2, TVOC, CH2O, CO, Ozone & Radon concentration measurement clusters to the all-clusters-app.

2023-05-30 09:39 UTC, mhazley approved these changes

2023-05-30 11:50 UTC, tobiasgraf approved these changes

2023-05-30 12:26 UTC, p0fi commented on src/app/zap_cluster_list.json
Please sort the clusters alphabetically like the existing entries in the list

2023-05-30 12:27 UTC, p0fi requested changes

2023-05-30 12:27 UTC, p0fi commented on src/app/zap_cluster_list.json
Please sort the clusters alphabetically like the existing entries in the list

2023-05-30 12:50 UTC, p0fi approved these changes

2023-05-30 12:53 UTC, andy31415 approved these changes

2023-05-31 01:05 UTC, bzbarsky-apple approved these changes

2023-05-31 13:10 UTC, merged