[SILABS] [RS917] Added change for 917 SOC BLE commissioning fix
project-chip/connectedhomeip pull request #27026
Opened 2023-06-01 23:23 UTC by shgutte

Problem
RS917 SOC commissioning is not working with new BLE changes 

Fixes added
Fixed the RS917 SOC commissioning with new BLE changes 

Testing
I tested with all combinations of RS9116 and RS9117.

2023-06-02 00:29 UTC, bzbarsky-apple approved these changes

2023-06-03 13:16 UTC, selissia approved these changes

2023-06-05 17:11 UTC, jepenven-silabs requested changes
A comment to address/answer

2023-06-05 17:11 UTC, jepenven-silabs commented on src/platform/silabs/rs911x/BLEManagerImpl.cpp
> +#define RSI_BLE_ENABLE 1
Why is this needed here ?

2023-06-07 06:59 UTC, closed without merging