Sync temperature control clusters xml to spec
project-chip/connectedhomeip pull request #27036
Opened 2023-06-02 13:32 UTC by jadhavrohit924

- Problem
> Spec was unclear about the temperature control cluster.

- Changes
> Sync temperature control cluster xml to updated spec
> zap regen.
> Fixes #27021

2023-06-02 22:27 UTC, bzbarsky-apple requested changes

2023-06-02 22:27 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/temperature-control-cluster.xml
>      <attribute side="server" code="0x0003" define="STEP" type="INT16S" writable="false" optional="true">Step</attribute>
Pre-existing, but why are these using "INT16S" instead of "temperature" for types?

2023-06-02 22:27 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/temperature-control-cluster.xml
> +    <field mask="0x03" name="TemperatureStep" />
That does not look right the right mask value....

2023-06-05 15:45 UTC, bzbarsky-apple approved these changes

2023-06-05 15:56 UTC, bzbarsky-apple commented
@jadhavrohit924 It looks like the Darwin failure is because `src/app/zap-templates/zcl/data-model/chip/chip-types.xml ` does not say `signed="true"` for the `temperature` type.  It probably should, followed by a regen.

Please feel free to spin out the change to the "temperature" type into a separate PR, as desired.

2023-06-06 06:31 UTC, dhrishi approved these changes

2023-06-07 18:41 UTC, merged