Draft: TLV-JSON-TLV converter
project-chip/connectedhomeip pull request #27279
Opened 2023-06-15 18:36 UTC by chrisdecenzo

(for message serialization between android tv-app platform and content apps)

TODO:
- Add readme describing JSON schema
- Add call from android casting app
- Add translation to/from android intent to android tv-app

2023-06-15 18:37 UTC, chrisdecenzo commented on examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp
> +    ChipLogError(AppServer, "-----------------------CastingServer PrepareForCommissioning");
TODO: remove

2023-06-15 18:55 UTC, andy31415 requested changes
Request changes: please add unit tests for such large code changes that are quite stand-alone (parsing and creating a JSON seems like it would be unit testable ... and unit tests would also explain how the JSON looks like)

2023-06-15 18:55 UTC, andy31415 commented on examples/common/json/JsonTLV.h
> +extern CHIP_ERROR WriteJSON(const TLVReader & aReader, Encoding::BufferWriter & bWriter);
we probably do not need "extern"

2023-06-15 18:55 UTC, andy31415 commented on examples/common/json/JsonTLV.h
> +    static CHIP_ERROR Put(chip::TLV::TLVWriter * writer, chip::TLV::Tag tag, Json::Value & value)
This looks like complex code in a header. Should probably be in a C++ file.

Also please add unit tests.

2023-06-15 18:56 UTC, andy31415 commented on examples/tv-casting-app/linux/CastingShellCommands.cpp
> +    uint8_t buf[74];
Need to explain the sizes here ...74 seems a very particular constant.

2023-06-15 18:57 UTC, andy31415 commented on examples/tv-casting-app/linux/CastingShellCommands.cpp
> +CHIP_ERROR RunJsonTests()
These tests should be unit tests run during test execution, not a shell command (we can include it in the casting app as well, but a variant of unit tests that are stand alone should exist).

2023-06-15 19:06 UTC, andy31415 commented
@chrisdecenzo I moved your PR to draft since the title said so.

2023-06-15 21:47 UTC, bzbarsky-apple commented on examples/common/json/JsonTLV.cpp
> +        if (tagControl == TLVTagControl::ContextSpecific)
What about profile tags in TLV lists?

2023-06-15 21:47 UTC, bzbarsky-apple commented on examples/common/json/JsonTLV.cpp
> +        if (tagControl == TLVTagControl::ContextSpecific)
Again, this does not seem to handle profile tags right.  But also, shouldn't that `"tag" : ` prefix just be written out independently of whether the tag is a container or not?

2023-06-15 21:47 UTC, bzbarsky-apple commented on examples/common/json/JsonTLV.cpp
> +            FormattedWrite(aWriter, "hex:");
I don't think this produces valid JSON, unless I am missing something.....

2023-06-15 21:47 UTC, bzbarsky-apple commented on examples/common/json/JsonTLV.cpp
> +            FormattedWrite(aWriter, "%" PRIu64, uVal);
We're OK with the data corruptions for values > 2^53?

2023-06-15 21:47 UTC, bzbarsky-apple commented on examples/common/json/JsonTLV.h
> +CHIP_ERROR ConvertHexToBytes(chip::CharSpan hex, F bufferAllocator, size_t * octetCount)
We have HexToBytes too, inside the BytesToHex header.

2023-06-15 21:47 UTC, bzbarsky-apple commented on examples/common/json/JsonTLV.h
> +    static bool ParseComplexArgument(const char * label, const char * json, Json::Value & value)
This seems to be duplicating the chip-tool complex argument parser, right?  Is it different from that code?  If so, maybe it should not be called ParseComplexArgument...  If it's not different, why is it separate?

2023-06-15 21:47 UTC, bzbarsky-apple commented on examples/common/json/JsonTLV.h
> +            Json::Value objTlvType = value.get("tlvType", "0x0c");
Please document why the defaulting to 0x0c.

2023-06-16 15:00 UTC, andy31415 commented on examples/common/json/JsonTLV.h
> +CHIP_ERROR ConvertHexToBytes(chip::CharSpan hex, F bufferAllocator, size_t * octetCount)
Well.... that is confusing ... maybe we can find a better name or split headers.

2023-06-20 21:08 UTC, yunhanw-google commented
@chrisdecenzo  we are preparing one pull request that provide the generic TLV-JSON-TLV converter using C++ along with documentation, similar to the kotlin one we provided in https://github.com/project-chip/connectedhomeip/pull/26527
@emargolis is working on this c++ version, which should be ready within 1 or 2 weeks, you can consider to leverage that version

2024-10-01 18:59 UTC, andy31415 commented
This seems in draft for over 1 year. @chrisdecenzo can we close it?

2024-10-10 12:13 UTC, andy31415 commented
Closing very old PR in draft form.

2024-10-10 12:13 UTC, closed without merging