Fix for Android chip-tool build issue (#27284)
project-chip/connectedhomeip pull request #27290
Opened 2023-06-16 13:26 UTC by satyajitanand

Fixes https://github.com/project-chip/connectedhomeip/issues/27284

This commit solves the above build issue of Android chip-tool project.

2023-06-16 14:05 UTC, andy31415 commented
@satyajitanand this seems to break linux builds - I believe these options were added to make error strings not contain developer-specific paths.

2023-06-16 14:06 UTC, andy31415 commented on src/BUILD.gn
> +# build_relative_chip_root = rebase_path("${chip_root}/.", root_build_dir)
do not comment out things, remove them instead.

I believe these are intentional for non-android at least (and android should benefit from them too presumably).

If android really fails to build, then having a current_os check for android may work ... however our github CI passes, so I am unsure what is going on here.

2023-06-16 14:08 UTC, andy31415 requested changes
I believe this works in current CI. The original issue report is probably due to using an old NDK.

2023-06-16 21:36 UTC, bzbarsky-apple requested changes

2023-06-16 21:36 UTC, bzbarsky-apple commented on src/BUILD.gn
> +  # cflags = [ "-fmacro-prefix-map=${build_relative_chip_root}/=" ]
This will expose full paths in error messages which is (1) a privacy leak and (2) larger code.

2023-06-19 15:36 UTC, andy31415 commented
Closing: I don't think a code change is needed, a documentation change may be needed instead.

2023-06-19 15:36 UTC, closed without merging