[Silabs] Update Silicon Labs container
project-chip/connectedhomeip pull request #27531
Opened 2023-06-28 18:43 UTC by jepenven-silabs

As the title described.

Add Sphinx, and Java 17

2023-06-28 18:56 UTC, woody-apple approved these changes

2023-06-28 19:32 UTC, selissia approved these changes

2023-06-28 20:01 UTC, andy31415 requested changes
In this particular case, please describe WHY the changes are needed, not just the changes themselves. 

In particular, I wonder if the vscode image will need updating (and if so, how we would merge openjdk requirements between what android/java images want and openjdk items installed for efr32.

2023-06-29 13:18 UTC, andy31415 approved these changes
Adding checkmark based on separate chat to understand the issue.

Apparently the problem is that `slc_cli_linux.zip` is a moving target, so docker images are inconsistent.

This change makes it so that docker build does not fail, however slc_cli as it currently exists cannot be relied upon to not change.

We only validate a sanity check for EFR32 for now, however long term expectation is that we fix slc_cli somehow (maybe submodule) and at that point we figure out the stable dependencies to put in efr32 and vscode to make it work.

Until then, developers are not expected to validate/run the slc-cli tools (which seem to be meant for a IDE integration mostly)

2023-06-29 13:20 UTC, merged

2023-06-29 13:59 UTC, andy31415 commented on integrations/docker/images/chip-build-efr32/Dockerfile
> +# Install Python Packages
Based on logs now I see that the above command on line 29 will fail since requirements.txt seems gone from the zip file.

2023-06-29 14:00 UTC, andy31415 commented on integrations/docker/images/chip-build-efr32/Dockerfile
> +# SLC required Python Packages
these are not required by SLC, my guess is these are codegen.py requirements by the looks of it (happen to be familiar with that tool, these are exactly its dependencies).