update ci to 0.7.23
project-chip/connectedhomeip pull request #27585
Opened 2023-07-03 04:10 UTC by pankore

- CI use docker image 0.7.23

2023-07-05 17:46 UTC, andy31415 approved these changes

2023-07-07 12:48 UTC, jmartinez-silabs requested changes

2023-07-07 12:48 UTC, jmartinez-silabs commented on .github/workflows/examples-efr32.yaml
> +      image: connectedhomeip/chip-build-efr32:0.7.23
EFR32 now requires 0.7.25 after #27618

2023-07-07 18:48 UTC, woody-apple approved these changes

2023-07-12 04:10 UTC, pankore commented on .github/workflows/examples-efr32.yaml
> +      image: connectedhomeip/chip-build-efr32:0.7.23
updated, thanks

2023-07-12 23:43 UTC, jmartinez-silabs approved these changes

2023-07-14 02:54 UTC, woody-apple commented
I think what you're looking for will be here?

https://github.com/project-chip/connectedhomeip/pull/27879

2023-07-14 04:36 UTC, merged

2023-07-14 20:55 UTC, andy31415 commented
This broke cloudbuild:  vscode 0.7.25 image does not seem to be in dockerhub (and we recently removed it towards gh actions)