[Linux] C++ version of autoptr for glib objects
project-chip/connectedhomeip pull request #28304
Opened 2023-07-26 19:06 UTC by arkq

### Problem

- Valgrind reports glib leaks in chip-tool when commissioning app over BLE
- GLib provides [g_autoptr](https://blogs.gnome.org/desrt/2015/01/30/g_autoptr/), but unfortunately there is no portable C++ version (in the glib project).

### Changes

- provide easily extendable `GAutoPtr<>` template which acts as `g_autoptr` (as a global helper include file)
- pass arguments as `const` if possible and get rid of excessive casting
- fix memory leaks reported by valgrind in chip-tool during BLE commissioning
- in few places `BluezDevice1 * device` has been converted to references in order to get rid of runtime `nullptr` checks 
- remove `#if ...CHIPOBLE` guards in files added to compilation by GN

There are going to be follow-up PRs which will replace glib explicit memory management with  `GAutoPtr<>`.

### Testing

CI will test for potential build breaks.

Commissioning tested with valgrind:
- current master:
  ```
  LEAK SUMMARY:
    definitely lost: 1,600 bytes in 25 blocks
    indirectly lost: 5,245 bytes in 46 blocks
      possibly lost: 640 bytes in 2 blocks
    still reachable: 303,296 bytes in 5,004 blocks
         suppressed: 0 bytes in 0 blocks
  ```
- after applying this PR:
  ```
  LEAK SUMMARY:
    definitely lost: 0 bytes in 0 blocks
    indirectly lost: 0 bytes in 0 blocks
      possibly lost: 640 bytes in 2 blocks
    still reachable: 254,880 bytes in 3,956 blocks
         suppressed: 0 bytes in 0 blocks
  ```

2023-07-28 16:25 UTC, andy31415 commented on src/lib/support/GLibTypes.h
Why the rename? GlibTypeDeleter says this is a deleter. `Types` just made it more vague. Also why move to support instead of linux if this can be platform specific?

2023-07-28 16:26 UTC, andy31415 commented on src/lib/support/GLibTypes.h
Also placed here now it is not part of a BUILD.gn. This must be in a build.gn file (we want layering and dependencies enforced)

2023-07-28 16:27 UTC, andy31415 requested changes, later dismissed
Please figure out the right placement and naming for the deleter heading.

I don't think support is the right place as this is glib-specific and not generic enough.

2023-07-28 19:49 UTC, arkq commented on src/lib/support/GLibTypes.h
> Why the rename?

I've got a different concept before adding `GAutoPtr<>` part, I will revert the rename bit.

> Also why move to support instead of linux if this can be platform specific?

I've moved it here because I'd like to use it on Linux and Tizen. Also WebOS can benefit from extra stuff in that file. Keeping this file in 3 copies seemed to me like a maintenance problem later. But to be honest I'm not sure where to place it... maybe just src/platform/GlibTypeDeleter.h?

> Also placed here now it is not part of a BUILD.gn

I thought that GN will automatically collect all included headers like cmake. But if that's not the case I will add this file as an explicit dependency.

2023-07-29 07:04 UTC, arkq commented on src/lib/support/GLibTypes.h
Include moved to "src/platform/GlibTypeDeleter.h" and added to GN as an explicit dependency.

2023-08-07 13:38 UTC, jmartinez-silabs approved these changes

2023-08-10 18:39 UTC, andy31415 approved these changes

2023-08-10 18:54 UTC, merged