Create retransmit folder and start adding helper classes for CRMP
project-chip/connectedhomeip pull request #2832
Opened 2020-09-25 17:32 UTC by andy31415

#### Problem
CHIP has no reliable messaging (unable to acknowledge and retransmit unacknowledged buffers).

 #### Summary of Changes
This adds a basic skeleton class for build and test reliability base classes.

Creates a 'Cache' class, that is an array-based key/value pair map of things. This is expected to be needed for  CRMP implementation in two ways:
  - packets sent are buffered until acknowledged by the other end whenever a packet is marked as 'needs reliable sending'
  - Message IDs needing acknowledgement are buffered  and either piggybacked on future message sending or sent as a 'null request' periodically if no more communication traffic happens between devices.

2020-09-25 17:51 UTC, rwalker-apple approved these changes

2020-09-25 22:30 UTC, bzbarsky-apple approved these changes

2020-09-25 22:30 UTC, bzbarsky-apple commented on src/retransmit/BUILD.gn
> +
Could we throw `cflags = [ "-Wconversion" ]` in here so that this passes that check up front?

2020-09-25 22:30 UTC, bzbarsky-apple commented on src/retransmit/tests/BUILD.gn
> +  public_deps = [
And here too, `-Wconversion` if we can.

2020-09-26 00:52 UTC, mspang requested changes

2020-09-26 00:52 UTC, mspang commented on src/retransmit/Cache.h
> +        for (unsigned i = 0; i < N; i++)
unsigned -> size_t ?

2020-09-26 00:52 UTC, mspang commented on src/retransmit/Cache.h
> +        for (unsigned i = 0; i < N; i++)
unsigned -> size_t

?

2020-09-26 00:52 UTC, mspang commented on src/retransmit/Cache.h
> +#ifdef UNIT_TESTS
Could the test code be in the test itself or test support library?

2020-09-26 00:52 UTC, mspang commented on src/retransmit/tests/BUILD.gn
> +  output_name = "libRetransmigTests"
libRetransmigTests -> libRetransmitTests

2020-09-28 06:24 UTC, BroderickCarlin commented on src/retransmit/Cache.h
> +     * @tparam Matcher is a generic macher object defining a bool Maches method.
nit: Matcher is a generic matcher object defining a bool Matches method.

2020-09-28 06:26 UTC, BroderickCarlin approved these changes

2020-09-29 21:07 UTC, mspang approved these changes

2020-09-29 21:07 UTC, merged