[Silabs] [EFR32] Bug fix for thermostat application for wifi device
project-chip/connectedhomeip pull request #28427
Opened 2023-08-01 06:25 UTC by kiran0284

Added :
    -   added fix for OccupiedCoolingSetpoint and MaxHeatSetpointLimit write command in thermostat cluster

Issue :
    -   while trying set OccupiedCoolingSetpoint and MaxHeatSetpointLimit got CONSTRAINT_ERROR instead of SUCCESS

Tested  :
    -   manually tested on MG24 + 917 Exp

2023-08-01 06:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=28427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=28427) before we can accept your contribution.<br/><hr/>**KiranKumar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=28427) it.</sub>

2023-08-01 13:49 UTC, mkardous-silabs commented on src/app/clusters/thermostat-server/thermostat-server.cpp
> +        if (requested < AbsMinHeatSetpointLimit || requested < MinHeatSetpointLimit || requested < AbsMaxHeatSetpointLimit)
This change doesn't seem correct. Shouldn't we return `InvalidValue` if the requested value is superior to the `AbsMaxHeatSetpointLimit` ?

2023-08-01 13:51 UTC, mkardous-silabs commented
@kiran0284 Could you change the name of the PR by removing the `[Silabs] [EFR32]` part? The changes you are proposing of not platform specific. The name is misleading in this particular case.

2023-08-03 05:16 UTC, bzbarsky-apple requested changes

2023-08-03 05:16 UTC, bzbarsky-apple commented on src/app/clusters/thermostat-server/thermostat-server.cpp
> +            if (requested > OccupiedHeatingSetpoint + DeadBandTemp)
This change is wrong, as far as I can tell.  What the spec says is:

> if, and only if, the AUTO feature is supported, a deadband must be maintained between Heating and Cooling setpoints and limits:
> ...
> OccupiedHeatingSetpoint ≤ (OccupiedCoolingSetpoint - MinSetpointDeadBand)

So if that condition is violated, i.e. "OccupiedHeatingSetpoint + MinSetpointDeadBand > OccupiedCoolingSetpoint", then that's not a valid setting.  And that's what this code is checking for.

Please clearly explain why you are introducing these changes that violate the spec (and incidentally fail the conformance tests like Test_TC_TSTAT_2_2).

2024-10-11 13:55 UTC, andy31415 commented
1 year old PR is in draft, has changes requested and merge conflicts. Closing as stale.

2024-10-11 13:55 UTC, closed without merging