Add External args in build_examples.py
project-chip/connectedhomeip pull request #28467
Opened 2023-08-02 06:13 UTC by joonhaengHeo

For using config argument in build_examples.py.

2023-08-02 16:04 UTC, arkq commented on scripts/build/build_examples.py
> +    help='Additional build argument')
I'm not sure whether it's the right approach with such args, but if so, this should be documented better, e.g. like where these args are passed, what is the format, etc.?

2023-08-02 16:04 UTC, arkq commented on scripts/build/builders/android.py
> +            if self.args:
Maybe it should be available for all platforms, not Android only?

2023-08-02 17:00 UTC, andy31415 requested changes
We have intentionally not allowed mixed arguments in build_examples, to force explicit instructions even when they end up as gn arguments.

What are the arguments that are considered here? Why not have separate variant entries for them?

2023-08-03 06:08 UTC, joonhaengHeo commented
@andy31415 
I understand. Several features are being added on the Android platform, so it was uploaded during the review process. I will close the PR.

2023-08-03 06:08 UTC, closed without merging