Bugfix using CHIP_CONFIG_SECURITY_TEST_MODE will not allow to build.
project-chip/connectedhomeip pull request #28638
Opened 2023-08-10 17:54 UTC by Sarthak-Shaha

1. Issue : When enabled the CHIP_CONFIG_SECURITY_TEST_MODE created a call for otThreadGetNetworkKey API. The API call fails due to wrong number of arguments
2. Modified the API call otThreadGetNetworkKey() to return the otKey as an argument out. Following the declaration 
    void otThreadGetNetworkKey(otInstance *aInstance, otNetworkKey *aNetworkKey);

2023-08-10 17:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=28638) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=28638) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=28638) it.</sub>

2023-08-10 18:09 UTC, bzbarsky-apple requested changes

2023-08-10 18:09 UTC, bzbarsky-apple commented on src/platform/OpenThread/OpenThreadUtils.cpp
> +            otThreadGetNetworkKey(otInst,otKey);
Was this tested?  Because I would expect this to be an exploitable security bug right here...

2023-08-10 19:52 UTC, Sarthak-Shaha commented on src/platform/OpenThread/OpenThreadUtils.cpp
> +            otThreadGetNetworkKey(otInst,otKey);
Is the security bug regarding printing the key ?The two statements after the changes?

2023-08-10 21:01 UTC, bzbarsky-apple commented on src/platform/OpenThread/OpenThreadUtils.cpp
> +            otThreadGetNetworkKey(otInst,otKey);
No, it's about the misuse of the `otThreadGetNetworkKey` API.

Again: was this tested?

2023-08-11 02:37 UTC, jmartinez-silabs approved these changes

2023-08-11 02:40 UTC, jmartinez-silabs requested changes
This should probably be gated with a #ifdef on the API version of open thread to not break platform that would use an older thread version. It is done a few time in the GenericThread files

2023-08-11 20:02 UTC, selissia commented
In view of this https://github.com/project-chip/connectedhomeip/pull/28058 there's probably no need for the API version check?

2023-08-11 20:20 UTC, jmartinez-silabs commented
@selissia Yes we can ignore that. I didn't realize that it has been broken for so long. The other comment needs to be addressed still.

2023-08-11 20:23 UTC, Sarthak-Shaha commented on src/platform/OpenThread/OpenThreadUtils.cpp
> +            otThreadGetNetworkKey(otInst,otKey);
Updated to use the local variables instead of the pointers. Locally tested and shows the network key in the DUT logs.

2023-08-11 20:32 UTC, jmartinez-silabs approved these changes

2023-08-11 21:25 UTC, selissia approved these changes

2023-08-12 00:36 UTC, bzbarsky-apple approved these changes
This makes much more sense.

2023-08-15 16:40 UTC, merged