Fix script issues Aug 11
project-chip/connectedhomeip pull request #28656
Opened 2023-08-11 12:53 UTC by manjunath-grl

Fixes issues: [607](https://github.com/CHIP-Specifications/chip-test-scripts/issues/607), [604](https://github.com/CHIP-Specifications/chip-test-scripts/issues/604), [603](https://github.com/CHIP-Specifications/chip-test-scripts/issues/603), [601](https://github.com/CHIP-Specifications/chip-test-scripts/issues/601), [594](https://github.com/CHIP-Specifications/chip-test-scripts/issues/594), [593](https://github.com/CHIP-Specifications/chip-test-scripts/issues/593), [592](https://github.com/CHIP-Specifications/chip-test-scripts/issues/592), [937](https://github.com/CHIP-Specifications/chip-certification-tool/issues/937)
Modified tests:
```
TC_ACFREMON_1_1
TC_ACL_1_1
TC_ACT_1_1
TC_AIRQUAL_1_1
TC_ALOGIN_1_12
TC_APBSC_1_10
TC_APPLAUNCHER_1_3
TC_AUDIOOUTPUT_1_8
TC_BIND_1_1
TC_BINFO_1_1
TC_BOOL_1_1
TC_BRBINFO_1_1
TC_CC_1_1
TC_CC_6_5
TC_CDOCONC_1_1
TC_CGEN_1_1
TC_CHANNEL_1_6
TC_CMOCONC_1_1
TC_CNET_1_3
TC_CONTENTLAUNCHER_1_11
TC_DA_1_8
TC_DESC_1_1
TC_DGETH_1_1
TC_DGGEN_1_1
TC_DGSW_1_1
TC_DGTHREAD_1_1
TC_DGTHREAD_2_1
TC_DGWIFI_1_1
TC_DLOG_1_1
TC_DRLK_1_1
TC_DRLK_2_1
TC_FAN_1_1
TC_FLABEL_1_1
TC_FLDCONC_1_1
TC_FLW_1_1
TC_GRPKEY_1_1
TC_G_1_1
TC_G_2_3
TC_HEPAFREMON_1_1
TC_ICDM_1_1
TC_ILL_1_1
TC_I_1_1
TC_KEYPADINPUT_1_2
TC_LCFG_1_1
TC_LOWPOWER_1_1
TC_LTIME_1_2
TC_LUNIT_1_2
TC_LVL_1_1
TC_LWM_1_1
TC_MEDIAINPUT_1_4
TC_MEDIAPLAYBACK_1_7
TC_MOD_1_1
TC_NDOCONC_1_1
TC_OCC_1_1
TC_OO_1_1
TC_OPCREDS_1_2
TC_OPSTATE_1_1
TC_OPSTATE_2_1
TC_OZCONC_1_1
TC_PCC_1_1
TC_PMHCONC_1_1
TC_PMICONC_1_1
TC_PMKCONC_1_1
TC_PRS_1_1
TC_PSCFG_1_1
TC_PS_1_1
TC_PS_2_1
TC_REFALM_1_1
TC_REFALM_2_2
TC_RH_1_1
TC_RNCONC_1_1
TC_RVCCLEANM_1_1
TC_RVCOPSTATE_1_1
TC_RVCOPSTATE_2_1
TC_RVCRUNM_1_1
TC_SMOKECO_1_1
TC_SWTCH_1_1
TC_S_1_1
TC_TCCM_1_1
TC_TCTL_1_1
TC_TGTNAV_1_9
TC_TIMESYNC_1_1
TC_TMP_1_1
TC_TSTAT_1_1
TC_TSUIC_1_1
TC_TVOCCONC_1_1
TC_ULABEL_1_1
TC_WAKEONLAN_1_5
TC_WNCV_1_1
```
Added auto generated files

Tested 
execution logs:
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/12321636/exe_log.txt)

2023-08-11 14:55 UTC, bzbarsky-apple requested changes

2023-08-15 16:44 UTC, yinyihu-silabs approved these changes

2023-08-15 17:44 UTC, manjunath-grl commented on src/app/tests/suites/certification/Test_TC_BOOL_1_1.yaml
> +    # EventList disabled for 1.2
Updated as discussed. Reverted back EventList changes.

2023-08-16 05:47 UTC, raju-apple approved these changes

2023-08-16 16:43 UTC, merged