[Silabs] feature/DIC feature support for thermostat app and window app
project-chip/connectedhomeip pull request #29084
Opened 2023-09-06 10:27 UTC by Thirsrin

Added : 
  -  DIC feature support for thermostat app, window app changes under DIC macro.
 
Tested:
  - Tested locally

2023-09-06 11:54 UTC, jmartinez-silabs commented on examples/thermostat/silabs/include/AppTask.h
> +    void DIC_AttrubiteHandler(AttributeId attributeId);
Typo 
```suggestion
    void DIC_AttributeHandler(AttributeId attributeId);
```

2023-09-06 11:54 UTC, jmartinez-silabs commented on examples/thermostat/silabs/src/ZclCallbacks.cpp
> +        AppTask().DIC_AttrubiteHandler(attributeId);
Why is it done separately? What if someone adds or modify the endpoint?

2023-09-06 11:54 UTC, jmartinez-silabs commented on examples/thermostat/silabs/src/AppTask.cpp
> +void AppTask::DIC_AttrubiteHandler(AttributeId attributeId)
Why is it in Apptask? Why not your own DIC project files? It could probably be merged with the tempMgr attribute change handling also no?

2023-09-06 18:01 UTC, jmartinez-silabs commented on examples/window-app/silabs/src/WindowManager.cpp
> +#define BYTE 5
This naming is odd, BYTE doesn't convey that it is the size of your buffer nor why 5 is used

2023-09-06 18:01 UTC, jmartinez-silabs approved these changes

2023-09-07 22:28 UTC, bzbarsky-apple requested changes

2023-09-07 22:28 UTC, bzbarsky-apple commented on examples/window-app/silabs/src/WindowManager.cpp
> +        itoa(value, buffer, DECIMAL);
So if value is maximal (10000), and we try to print it to a 5-char buffer... where does the null terminator go?

2023-09-12 14:54 UTC, bzbarsky-apple approved these changes

2023-09-12 14:54 UTC, merged