[Silabs] Update Light-switch Data Model
project-chip/connectedhomeip pull request #29106
Opened 2023-09-07 13:10 UTC by jepenven-silabs

Create a custom data model for silabs light-switch app to leverage WIP ICD features.

2023-09-07 13:34 UTC, jmartinez-silabs approved these changes

2023-09-07 20:05 UTC, bzbarsky-apple requested changes

2023-09-07 20:05 UTC, bzbarsky-apple commented on examples/light-switch-app/silabs/data_model/light-switch-app.matter
> +  server cluster Binding {
Why does this have a Binding server on EP0?

2023-09-07 20:05 UTC, bzbarsky-apple commented on examples/light-switch-app/silabs/data_model/light-switch-app.matter
> +  server cluster TimeFormatLocalization {
Does this switch in fact implement TimeFormatLocalization?

2023-09-07 20:05 UTC, bzbarsky-apple commented on examples/light-switch-app/silabs/data_model/light-switch-app.matter
> +  server cluster DiagnosticLogs {
I really doubt this implements DiagnosticLogs.

2023-09-13 21:12 UTC, bzbarsky-apple commented on examples/light-switch-app/silabs/data_model/light-switch-app.matter
> +  server cluster Binding {
I think we need to stop having broken and non-spec-conformant examples.

We should fix it here (whether in this PR in a followup is fine with me, as long as it happens).  We should fix the broken thing this got copy/pasted from (separate PR).

2023-10-18 18:14 UTC, jepenven-silabs commented
close as not relevant for the short term

2023-10-18 18:14 UTC, closed without merging