Generalize name of BtpEngine module in BleLayer.
project-chip/connectedhomeip pull request #293
Opened 2020-04-07 20:39 UTC by turon

The name of the CHIPoBle module is misleading.  

The code actually implements generalized encoding/decoding of BTP (Bluetooth Transport Protocol) packets.

As such, this PR renames the module to BtpEngine for clarity.

2020-04-08 16:58 UTC, woody-apple approved these changes

2020-04-08 18:27 UTC, BroderickCarlin requested changes
A search of the repo reveals a lot of references to `CHIPOBLE` that I believe should be switched over to `BtpEngine`. I don't have a strong preference on `CHIPOBLE` vs `BtpEngine` but would like us to at least be consistent

2020-04-08 20:10 UTC, BroderickCarlin approved these changes

2020-04-09 21:44 UTC, jelderton approved these changes

2020-04-15 16:37 UTC, gerickson approved these changes

2020-04-16 00:38 UTC, merged