Add / Import Missing Tests for Inet Buffer, EndPoint, and Timer
project-chip/connectedhomeip pull request #294
Opened 2020-04-07 20:43 UTC by gerickson

#### Problem
The chip::Inet layer library is missing unit tests for the buffer, endpoint, layer, and timer objects.

#### Summary of Changes
Add or import from openweave-core such tests.

Fixes #213

2020-04-07 20:55 UTC, BroderickCarlin approved these changes

2020-04-07 21:05 UTC, woody-apple approved these changes

2020-04-07 21:06 UTC, woody-apple requested changes
Your branch currently fails building:
https://github.com/gerickson/connectedhomeip/runs/568896015

Can you take a peek at that?

2020-04-09 21:38 UTC, woody-apple approved these changes

2020-04-09 21:42 UTC, jelderton approved these changes

2020-04-09 21:42 UTC, merged