[Silabs] feature/deprecate support for unused apps
project-chip/connectedhomeip pull request #29766
Opened 2023-10-13 19:53 UTC by Sarthak-Shaha

Issue : The light-switch-app is deprecated for wifi NCP combinations and the thermostat app for SiWx917 SoC combination. 
Solution : Added conditions to stop gn_silabs_example.sh script for above mentioned combinations.

2023-10-13 20:15 UTC, andy31415 commented on scripts/examples/gn_silabs_example.sh
> +    if  [[ $ROOT == *"light-switch-app"* && "$WIFI_NCP" == true ]] ||
Do we need updating `scripts/build/builders/efr32.py` (or targets.py) as well?

2023-10-14 07:03 UTC, chirag-silabs commented
Do we need to remove this from here? I know we don't mention these in the release notes but it won't harm to keep right? I don't see any point of adding this condition

2023-10-16 13:35 UTC, Sarthak-Shaha commented
> Do we need to remove this from here? I know we don't mention these in the release notes but it won't harm to keep right? I don't see any point of adding this condition

2023-10-16 21:08 UTC, jepenven-silabs requested changes
Like @chirag-silabs mentioned this PR should be closed

2023-10-17 14:07 UTC, Sarthak-Shaha commented
Change no longer required. The docs update will reflect this change.

2023-10-17 14:07 UTC, closed without merging