Messages Cluster XML
project-chip/connectedhomeip pull request #30254
Opened 2023-11-06 19:39 UTC by drempelg

Adding the XML for the new messages cluster

2023-11-06 22:07 UTC, andy31415 commented
@drempelg could you run zap-regen and fix builds?

2023-11-14 05:03 UTC, bzbarsky-apple requested changes
Please note the CI failures.  Some are probably because you do not have `java` installed so the formatting on all the java bits gets messed up.  But some of the other CI failures look real in various ways (failing lints, failing reads on all-clusters-app because of the broken implementation, etc).

In general, the right order of things is:

1. Add XML.
2. Add implementation which is not too broken.
3. Enable implementation in test apps.

2023-11-14 05:03 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <item fieldId="4" name="Duration" type="int16u" default="0"/>
This is also nullable in the spec.

2023-11-14 05:03 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <item fieldId="5" name="MessageText" type="long_char_string" length="512" default=""/>
Spec has max 256.

2023-11-14 05:03 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <item fieldId="6" name="Responses" type="MessageResponseOptionStruct" array="true"/>
This is optional in the spec.

2023-11-14 05:03 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +  <struct name="PresentMessageRequestStruct">
This does not exist in the spec.

I am stopping here.  Please make this XML match the spec.

2023-11-14 05:03 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/zcl.json
> +        "Messages": ["Messages"],
Shouldn't be here.  Why is it here?

2023-11-14 05:03 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/zcl-with-test-extensions.json
> +        "Messages": ["Messages"],
Shouldn't be here.

2024-01-24 11:49 UTC, lazarkov commented on examples/all-clusters-app/esp32/main/CMakeLists.txt
> +            		      "${CMAKE_SOURCE_DIR}/third_party/connectedhomeip/src/app/clusters/laundry-washer-controls-server"
Removed.

2024-01-24 11:50 UTC, lazarkov commented on src/app/clusters/messages-server/messages-server.cpp
Left the dummy code, but removed the implementation from the example apps.

2024-01-24 11:50 UTC, lazarkov commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <field name="Confirmation" mask="0x1"/>
Updated.

2024-01-24 11:52 UTC, lazarkov commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +  <enum name="MessagePriorityEnum" type="enum8">
Sorted.

2024-01-24 12:44 UTC, lazarkov commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +  <bitmap name="MessageControl" type="bitmap16">
Removed the default=""

2024-01-24 12:45 UTC, lazarkov commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <item fieldId="3" name="StartTime" type="epoch_s" default="0"/>
Updated.

2024-01-24 12:45 UTC, lazarkov commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <item fieldId="4" name="Duration" type="int16u" default="0"/>
Updated.

2024-01-24 12:46 UTC, lazarkov commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <item fieldId="5" name="MessageText" type="long_char_string" length="512" default=""/>
Updated.

2024-01-24 12:47 UTC, lazarkov commented on src/app/zap-templates/zcl/data-model/chip/messages-cluster.xml
> +    <item fieldId="6" name="Responses" type="MessageResponseOptionStruct" array="true"/>
No longer available.

2024-01-24 12:59 UTC, lazarkov commented on src/app/zap-templates/zcl/zcl.json
> +        "Messages": ["Messages"],
Removed

2024-01-24 13:58 UTC, lazarkov commented
@bzbarsky-apple Continued the development here:
https://github.com/project-chip/connectedhomeip/pull/31656

2024-02-01 03:44 UTC, closed without merging