[Telink] change Docker version 26 -> 29
project-chip/connectedhomeip pull request #30979
Opened 2023-12-13 14:08 UTC by interfer

Failing bootstrap after Docker version updated in other places ( possibly "29 : [ESP] Update esp-idf to v5.1.2" #30920 ).
In fact, Github CI wouldn't show any build failures as it used 26 version.
Tests manually on Telink platform showed issues during bootstrap with python module `prompt_toolkit`

2023-12-13 16:36 UTC, andy31415 approved these changes

2023-12-13 16:39 UTC, andy31415 requested changes
I am unclear about why we bump telink only: the latest telink update seems to be version 26 only.

2023-12-13 16:40 UTC, andy31415 commented
> I am unclear about why we bump telink only: the latest telink update seems to be version 26 only.

Looking at the history, https://github.com/project-chip/connectedhomeip/commits/master/integrations/docker/images/stage-2/chip-build-telink/Dockerfile updates at https://github.com/project-chip/connectedhomeip/pull/30462 which is version 26

2023-12-13 17:29 UTC, Damian-Nordic approved these changes

2023-12-18 10:02 UTC, closed without merging

2023-12-18 10:03 UTC, interfer commented
Fix is applied here: https://github.com/project-chip/connectedhomeip/pull/30987
Image update is not needed anymore