fix: remove const because there is internal changes
project-chip/connectedhomeip pull request #31195
Opened 2023-12-28 08:52 UTC by hideakitai

2024-01-03 18:32 UTC, bzbarsky-apple requested changes

2024-01-03 18:32 UTC, bzbarsky-apple commented on examples/bridge-app/asr/subdevice/SubDeviceManager.cpp
> +                      Span<DataVersion> && dataVersionStorage, chip::EndpointId parentEndpointId)
Why is this an rvalue?  Doesn't that allow caller to pass a temporary?  `dataVersionStorage` can't be a temporary...

2024-01-03 18:32 UTC, bzbarsky-apple commented on src/app/util/attribute-storage.h
> +                                        chip::Span<chip::DataVersion> & dataVersionStorage,
I'm not sure this is right.  The Span itself is const: the callee does not mutate its length or what it points to.

The data in the buffer is modified, but that's fine; this is not a `Span<const DataVersion>`; it's a `const Span<DataVersion>`, no?

2024-01-03 18:35 UTC, bzbarsky-apple commented
An in particular, this line that's quoted:
```
 if (Crypto::DRBG_get_bytes(reinterpret_cast<uint8_t *>(dataVersionStorage.data()), dataSize) != CHIP_NO_ERROR) 
```
compiles precisely because `dataVersionStorage.data()` is _not_ a pointer to const data.  If it were, the compiler would fail the cast, because `reinterpret_cast` cannot cast away constness (unlike a C-style cast).

2024-01-03 23:43 UTC, hideakitai commented
@bzbarsky-apple  Thank you for your comment. You are correct in what you say.

The problem in my environment is when the `DataVersion` of `chip::Span<DataVersion>` is `constexpr`. In this case, the compile passes fine, but the write to the `DataVersion` which is `constexpr` causes panic at runtime.

After your comment, I tried to think of a way to prevent this from happening at compile time, but I could have come up with a better idea. Do you have any good ideas?

2024-01-08 22:02 UTC, bzbarsky-apple commented
@hideakitai Hmm.  If that DataVersion is constexpr, how are we ending up with a non-const pointer to it at all?  What does the code on the caller side that creates the Span look like in this case?

2024-01-10 22:47 UTC, bzbarsky-apple commented
@hideakitai Ah, so this line:
```
            (chip::DataVersion*)this->DATA_VERSIONS.data(), 
```
is a C-style cast that casts away const.  And once you are casting away const, and passing const things to something that expects non-const, all bets are off.

You'd get the same problems if you C-style cast a random integer to a pointer or whatnot.

You really shouldn't use C-style casts in anything resembling modern C++.  The fact that one was needed here to get this code to compile should have been a giant red flag.

2024-01-11 00:02 UTC, hideakitai commented
@bzbarsky-apple It was right in front of my eyes, but I completely missed it...that's exactly right. I had completely forgotten about using a C-style cast because I had not passed this part of the compilation for a long time. Thank you very much.

---

By the way, `chip::Span<T>` has the following constructor that takes `std::array<T, N>` (not `const`) as an argument.

```c++
    template <class U, size_t N, typename = std::enable_if_t<std::is_same<std::remove_const_t<T>, std::remove_const_t<U>>::value>>
    constexpr Span(std::array<U, N> & arr) : mDataBuf(arr.data()), mDataLen(N)
    {}
```

However, if I pass a const std::array to it (`this->DEVICE_TYPES` is `constexpr std::array<const EmberAfDeviceType, 1>`), 

```c++
        .device_types = chip::Span<const EmberAfDeviceType>(this->DEVICE_TYPES),
```

I get the following template deduction/substitution error. Is this because `const std::array<U, N>` is not supported by the constructor of `chip::Span<T>` ?

```
connectedhomeip/src/lib/support/Span.h:50:15: note: candidate: 'template<class U, unsigned int N, class> constexpr chip::Span<T>::Span(std::array<U, N>&)'
     constexpr Span(std::array<U, N> & arr) : mDataBuf(arr.data()), mDataLen(N)
               ^~~~
connectedhomeip/src/lib/support/Span.h:50:15: note:   template argument deduction/substitution failed:
matter_core_endpoint.cpp:328:79: note:   types 'std::array<_Tp, _Nm>' and 'const std::array<const EmberAfDeviceType, 1>' have incompatible cv-qualifiers
         .device_types = chip::Span<const EmberAfDeviceType>(this->DEVICE_TYPES),
```

2024-01-11 00:12 UTC, hideakitai commented
Ah I got it. I'm using v1.0.0.2, but the constructors are fixed to accept `const std::array<T, N>` in mainstream.

https://github.com/project-chip/connectedhomeip/blob/caea3ec81b8c1f1e690323a00426301dd9c9a05a/src/lib/support/Span.h#L80-L91

2024-01-11 00:14 UTC, hideakitai commented
Anyway, sorry for making you spend your time debugging my code. It was really helpful, thank you very much!

2024-01-11 00:14 UTC, closed without merging

2024-01-11 16:41 UTC, bzbarsky-apple commented
You're welcome!