Remove depricated rvc items
project-chip/connectedhomeip pull request #31451
Opened 2024-01-16 16:22 UTC by hicklin

Fixes #31447, https://github.com/project-chip/connectedhomeip/issues/30488 and https://github.com/project-chip/connectedhomeip/issues/30489.

This PR aligns the SDK following [this spec PR](https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8637) that deprecated the following
- The `OnMode` attribute for the RvcRunMode and RvcCleanMode clusters
- The `OnOff` feature for the RvcRunMode and RvcCleanMode clusters
- The `Start` and `Stop` commands for the RvcOperationalState cluster.

2024-01-16 17:56 UTC, bzbarsky-apple requested changes

2024-01-16 17:56 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/mode-base-cluster.xml
> -    <cluster code="0x0055"/>
This is a breaking change for Darwin.  This is removing not just the feature bit (which was communicated as likely to be removed and hence never shipped) but also the Feature bitmap definition itself from these clusters.  

That is, from Darwin's pov the bare minimum here is that a Feature definition needs to exist for these two clusters, with no bits defined.

2024-01-19 19:18 UTC, bzbarsky-apple approved these changes

2024-01-25 16:58 UTC, andy31415 approved these changes

2024-01-29 15:07 UTC, merged