Modify the value that checks for invalid values
project-chip/connectedhomeip pull request #31596
Opened 2024-01-22 11:44 UTC by HunsupJung

2024-01-22 22:50 UTC, bzbarsky-apple requested changes

2024-01-22 22:50 UTC, bzbarsky-apple commented on src/app/clusters/thermostat-server/thermostat-server.cpp
> +            EnsureKnownEnumValue(RequestedSystemMode) != SystemModeEnum::kUnknownValue)
This check seems backwards.  Was this tested?  Given that it fails to compile, I assume not....

Please add a test that would have caught the old (incorrect) code.

2024-10-11 13:57 UTC, andy31415 commented
Old PR with changes requested. Closing as stale.

2024-10-11 13:57 UTC, closed without merging

2024-10-11 18:51 UTC, bzbarsky-apple commented
https://github.com/project-chip/connectedhomeip/pull/36048 created to do the right check, with test.