[shell] Fixes for Matter cli
project-chip/connectedhomeip pull request #31768
Opened 2024-01-30 15:27 UTC by andrei-menzopol

* Add backspace character handling in ReadLine
* The otcli command buffer (128) was to small for some ot commands like otcli dataset set active <hex dataset>. The 128 value was taken from an OT config a long time ago and since was increased to 384.

2024-01-30 16:28 UTC, arkq approved these changes

2024-01-30 16:38 UTC, andy31415 commented on examples/shell/shell_common/cmd_otcli.cpp
> +#ifndef SHELL_OTCLI_MAX_LINE_LEN
None of these SHELL_OTCLI constants seem to be defined or overriden in matter config. The shell example is an example so we do not expect this to be a standard ABI outside.

If we do want tunable valies in one place, please create a config header specific to this example that you include.

Constant-wise, using `k....` is a better naming that C-style defines.

2024-01-30 16:40 UTC, andy31415 requested changes
Please just increase the value and apply `you ain't gonna need it` for the define - I don't think this define is worth to have as a configurable compile-time define. Seems overly complex.

set `static constexpr kMaxLineLength` in the file and be done with it. Using a define with a `kCamelCase` name was wrong to begin with.

2024-01-31 08:35 UTC, andrei-menzopol commented
> Please just increase the value and apply `you ain't gonna need it` for the define - I don't think this define is worth to have as a configurable compile-time define. Seems overly complex.
> 
> set `static constexpr kMaxLineLength` in the file and be done with it. Using a define with a `kCamelCase` name was wrong to begin with.

Done, thank you

2024-01-31 18:58 UTC, andy31415 approved these changes

2024-01-31 18:58 UTC, merged