Add missing function to set delegate in Door Lock Server
project-chip/connectedhomeip pull request #31846
Opened 2024-02-01 23:55 UTC by krypton36

Fixes #31845 
There was a delegate recently added to door lock, but not exposed in the header. This PR adds the function the the door lock server header file.

2024-02-02 00:04 UTC, nivi-apple approved these changes

2024-02-02 00:56 UTC, andy31415 requested changes
I just got to review this file given the changes.

It contains `using` in a header, which is very much wrong. Please fix that as well - remove all those using and add them in the C++ file.

2024-02-02 02:20 UTC, andy31415 approved these changes

2024-02-05 14:13 UTC, bzbarsky-apple approved these changes

2024-02-05 14:14 UTC, merged