Use std optional inside chip::Optional
project-chip/connectedhomeip pull request #32178
Opened 2024-02-16 18:24 UTC by andy31415

This exposes bugs:

- several unused variables existed (caught now)
- we do Optional<SessionHandle> move assignment EVERYWHERE even though this handle was supposed to be a reference counted handle that should have denied assignment. I could not actually find a way to fix it ... maybe we have to special case it somehow. The only thing I could do is just make the referencecountedhandle accept move assignment (which does not seem to invalidate its claims of being a reference counter).

2024-02-17 05:25 UTC, bzbarsky-apple requested changes

2024-02-17 05:25 UTC, bzbarsky-apple commented on src/lib/support/ReferenceCountedHandle.h
> +    ReferenceCountedHandle & operator=(const ReferenceCountedHandle & that)
This class should not have assignment operators.

2024-02-17 05:25 UTC, bzbarsky-apple commented on src/lib/support/ReferenceCountedHandle.h
> +    ReferenceCountedHandle(ReferenceCountedHandle && that) : mTarget(std::move(that.mTarget)) { that.mTarget = nullptr; }
This class should arguably not have a move constructor.  Certainly its previous "move constructor" just did a copy.  Doing what this is doing breaks the "this is immutable" guarantee about the mTarget member.

2024-02-17 05:25 UTC, bzbarsky-apple commented on src/transport/SessionHolder.cpp
> +    mSession = std::move(that.mSession);
Yeah, that's broken.  The clearing of `that.mSession` is done by `that.Release()`, and _has to be done that way_, because otherwise `that` does not get a chance to unregister.  This line right here, combined with how the move constructor is implemented above, is use-after-free.

We should not have a move constructor on SessionHandle; it was deleted for a reason.  We should not have a move constructor on ReferenceCountedHandle.

2024-04-26 16:13 UTC, andy31415 commented
Closing - we have to do this gradual or via an alias (alias will be required for IM codegen where zap is currenly only aware of chip::Optional)

2024-04-26 16:13 UTC, closed without merging