Android tv-casting-app: simplified command API
project-chip/connectedhomeip pull request #32188
Opened 2024-02-16 23:08 UTC by sharadb-amazon

This change simplifies and decouples the implementation of the APIs for the LaunchURL command from the old TvCastingApp.java for Android

### Change summary

1.  Added Cluster, MatterCluster, Command, MatterCommand classes which are super classes for the clusters and commands to be supported.
2.  Added new cluster, command objects for Casting use cases in MatterClusters/MattterCommands and the corresponding JNI code int he MatterCommandObjects-JNI.h/.cpp files
3.  Added new fragment to select actions and demonstrate the new LaunchURL API
4.  APIs.md documentation has been updated to illustrate how to use these APIs.

### Testing

Verified and tested locally with Android tv-casting-app running against the Linux TV app

2024-02-17 05:17 UTC, woody-apple approved these changes

2024-02-17 08:56 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/core/MatterCluster-JNI.cpp
> +    const char * className = env->GetStringUTFChars(jClassName, nullptr);
please consider to use https://github.com/project-chip/connectedhomeip/blob/2f2c4f1e311c9c35912e21156f816837986bc857/src/lib/support/JniTypeWrappers.h#L29

2024-02-17 08:56 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/core/MatterCluster-JNI.cpp
> +        env->ReleaseStringUTFChars(jClassName, className);
please consider to use https://github.com/project-chip/connectedhomeip/blob/2f2c4f1e311c9c35912e21156f816837986bc857/src/lib/support/JniTypeWrappers.h#L29, when className is null, you should not ReleaseStringUTFChars

2024-02-17 08:57 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/core/MatterCastingPlayer-JNI.h
> +    CastingPlayer * castingPlayer;
please init all these values.
maybe struct is better here? considering all these public members.

2024-02-17 08:58 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/core/MatterCluster-JNI.h
> + *    Copyright (c) 2020-24 Project CHIP Authors
2020-2024

2024-02-17 08:59 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/clusters/MatterCommandObjects-JNI.h
> + *    Copyright (c) 2020-24 Project CHIP Authors
2020-2024

2024-02-17 09:06 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/java/com/matter/casting/ContentLauncherLaunchURLExampleFragment.java
> +              command.invoke(request, 5000);
I would suggest to use 
https://github.com/project-chip/connectedhomeip/blob/2f2c4f1e311c9c35912e21156f816837986bc857/src/controller/java/src/chip/devicecontroller/ChipDeviceController.java#L1192

AndroidInteractionClient.cpp and its JNI

https://github.com/project-chip/connectedhomeip/blob/2f2c4f1e311c9c35912e21156f816837986bc857/src/controller/java/AndroidInteractionClient.cpp

2024-02-17 09:07 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/java/com/matter/casting/ContentLauncherLaunchURLExampleFragment.java
> +              command.invoke(request, 5000);
We should try our best to leverage the existing Java/JNI code for InteractionModel and reduce the duplicate maintenance effort.

2024-02-17 18:05 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/clusters/MatterCommandObjects-JNI.cpp
> +    jclass integerClass  = env->FindClass("java/lang/Integer");
why don't you check whether it is null?

2024-02-17 18:06 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/clusters/MatterCommandObjects-JNI.cpp
> +    jobject jResponseObj  = env->NewObject(responseTypeClass, constructor);
we need check jResponseObj is null or not

2024-02-17 18:09 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/clusters/MatterCommandObjects-JNI.h
> +            return command->Invoke(jRequest, jTimedInvokeTimeoutMs);
what if new fails, then crash happens...

2024-02-17 18:10 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/core/MatterCommandTemplate-JNI.h
> +                JNIEnv * env = chip::JniReferences::GetInstance().GetEnvForCurrentThread();
no env check

2024-02-17 18:11 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/core/MatterCommandTemplate-JNI.h
> +                JNIEnv * env         = chip::JniReferences::GetInstance().GetEnvForCurrentThread();
this is the callback flow, the whole code is leaking local reference...

2024-02-17 18:13 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/support/Converters-JNI.cpp
> +        chip::JniReferences::GetInstance().GetClassRef(env, "com/matter/casting/support/MatterError", jMatterErrorClass);
GetClassRef has been removed from library...

2024-02-17 18:13 UTC, yunhanw-google commented on examples/tv-casting-app/android/App/app/src/main/jni/cpp/support/Converters-JNI.cpp
> +    JNIEnv * env = JniReferences::GetInstance().GetEnvForCurrentThread();
no check on env...

2024-02-17 18:15 UTC, yunhanw-google requested changes
Please leverage the existing the Java/Jni invoke API instead of creating new path and adding the additional burden for maintenance..

Please address all leaks.

2024-02-17 18:33 UTC, yunhanw-google commented
> Please leverage the existing the Java/Jni invoke API instead of creating new path and adding the additional burden for maintenance..
> 
> Please address all leaks.

@sharadb-amazon 
our controller IM Java/JNI code is couple of deviceControllerPtr, aka deviceProxy. https://github.com/project-chip/connectedhomeip/blob/2f2c4f1e311c9c35912e21156f816837986bc857/src/controller/java/CHIPDeviceController-JNI.cpp#L264, I think we may introduce a deviceProxy function that can be used by Java application which don't need commissioning functionality and need IM functionality?

2024-03-12 21:53 UTC, sharadb-amazon commented
Canceling this PR. Will do this work in parts. I have a separate PR out that just exposed the casting Endpoint API on Android and does some GUI work: #32552 Then, will send a separate PR out that exposes the Interaction Model for Android.

2024-03-12 21:53 UTC, closed without merging