Turned on PowerSource and PowerTopology clusters in EnergyManagementApp for SVE DUTs
project-chip/connectedhomeip pull request #32329
Opened 2024-02-26 22:41 UTC by jamesharrow

- [ ] Turned on PowerSource on EP0 with WIRED mandated attributes,
- [ ] Turned on PowerTopology on EP1 with NODE as the feature (no additional attributes)
- [ ] added ElectricalSensor device type to EP1

2024-02-28 21:41 UTC, andy31415 approved these changes

2024-02-29 03:36 UTC, woody-apple commented
Tagging @naveenkommareddi @raju-apple. Does this require a re-spin of the TH, is this approved?

2024-02-29 03:37 UTC, woody-apple requested changes
Marking CR until CSG confirms

2024-02-29 03:39 UTC, woody-apple approved these changes
Letting this land in mainline, but per CSG, no plan to spin a new TH, so this won't make it to SVE.

2024-02-29 03:39 UTC, merged