[Silabs][SiWx917] Getting the button pressed and button release in sync in sleep wakeup
project-chip/connectedhomeip pull request #32458
Opened 2024-03-06 07:22 UTC by chirag-silabs

**Issue**
Once the device wakes up from sleep it handles a button release event due to the hardware(pull up resistor) 

**Fix**
Checking if the btn was not pressed just released no need of going forward. Making sure pressed and release are in sync

2024-03-06 20:26 UTC, jepenven-silabs commented on src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp
> +    if (btnAction == BUTTON_RELEASED && btn0_pressed == false)
This seems to be completely wrong. You have an API that returns the button number (0 or 1 ) and the corresponding action. there shouldn't be any need for an external global variable...

2024-03-06 20:26 UTC, jepenven-silabs requested changes
remove need for global variable

2024-03-06 20:30 UTC, mkardous-silabs requested changes
I don't believe this is the right way to fix this.

2024-03-11 17:58 UTC, mkardous-silabs approved these changes

2024-03-27 14:01 UTC, jepenven-silabs approved these changes

2024-04-02 15:07 UTC, merged