CI: Add idf_target for esp_example.sh script
project-chip/connectedhomeip pull request #32809
Opened 2024-04-02 10:59 UTC by wqx6

Add IDF target input for esp_example.sh script

2024-04-02 14:04 UTC, andy31415 commented on examples/all-clusters-app/esp32/sdkconfig.defaults.esp32c3
https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/builders/esp32.py#L142 seems to use the naming of _c3devkit.defaults.

If we rename this, we should probably fix that file as well.
Also m5stack seems to use a similar naming convention. Should we change that too?

2024-04-02 14:04 UTC, andy31415 requested changes
Needs fixes for build_examples.py as well.

2024-04-03 02:54 UTC, wqx6 commented on examples/all-clusters-app/esp32/sdkconfig.defaults.esp32c3
When the users run `idf.py set-target {target}`, IDF will choose `sdkconfig.defaults.{target}` as the default sdkconfig file. I renamed this name so that the users will not need to add `-D SDKCONFIG_DEFAULTS={sdkconfi_file}` when they set c3 target. For m5stack, I think we can keep the original name.

Changed scripts/build/builders/esp32.py.

2024-04-03 13:10 UTC, andy31415 approved these changes

2024-04-03 13:11 UTC, merged