Temp fix for #32875
project-chip/connectedhomeip pull request #32884
Opened 2024-04-06 13:50 UTC by chrisdecenzo

Fixes  #32875

TODO:
- checking if this change breaks CI
- add documentation for timing of when this can be reverted

2024-04-06 18:50 UTC, tcarmelveilleux requested changes
- Change description does not indicate what is being changed, or why, only links to an issue number, making tracing harder. Please describe the change.
- Change is removing a check that was deemed correct by spec, and spec interpretation should be validated with TSG before merging.

Note that TC-CNET-4.22 was missing the fix for TH == null (https://github.com/CHIP-Specifications/chip-test-plans/pull/3843), see TC-CNET-4.22 (https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/network_commissioning.adoc#4215-tc-cnet-422-thread-verification-for-scannetworks-command-dut-server), so step 3 implies that the test should pass. Given that the code at play was present at SVE, and nobody failed that test, it begs the question about whether the test was run at all!
  - See https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CNET_4_22.yaml#L142

2024-04-08 18:54 UTC, s-mcclain approved these changes

2024-04-09 12:42 UTC, tcarmelveilleux approved these changes

2024-04-09 13:47 UTC, robszewczyk approved these changes

2024-04-09 15:26 UTC, Damian-Nordic approved these changes

2024-04-09 15:27 UTC, merged