[ESP32] Fix few attributes with fixed quality in DeviceInfoProvider
project-chip/connectedhomeip pull request #32893
Opened 2024-04-08 11:51 UTC by shubhamdp

Fixed labels, supported locales, supported calendar types were being read from the nvs(flash) and during OTA its a hassle if one wants to upgrade these values.

Added few APIs to set the data for these attributes in ESP32DeviceInfoProvider.

#### Tests
- Read/write the attributes from time format localization, localization configuration, and fixed label attributes.

2024-04-08 14:51 UTC, andy31415 approved these changes

2024-04-12 10:17 UTC, dhrishi requested changes
Does this also take care of backward compatibility?

If someone used the existing approach and now they want to do a OTA. Assuming that their fixed quality attributes have not changed, would they be mandated to implement these changes/APIs?

2024-04-22 13:35 UTC, dhrishi approved these changes

2024-04-22 13:36 UTC, merged

2024-04-22 13:37 UTC, dhrishi commented
@shubhamdp Please raise a backport PR on this branch https://github.com/espressif/connectedhomeip/tree/v1.3-branch