Add python platform for perfetto submodule
project-chip/connectedhomeip pull request #33246
Opened 2024-04-30 21:20 UTC by cecille

We need this to compile the python wheel, which is not strictly one of the host platforms. Adding a python platform designation so we can specify this submodule without pulling in the other host platform dependencies.

2024-04-30 21:29 UTC, bzbarsky-apple approved these changes

2024-05-01 13:10 UTC, andy31415 approved these changes

2024-05-01 13:11 UTC, andy31415 commented
@cecille is the python wheel not compiling C++ code, so it would need either darwin or linux dependencies (e.g. our wheel accesses blutooth and dnssd so it may need those underlying libraries)

2024-05-01 13:18 UTC, andy31415 requested changes
Marking request changes for now: I am unclear how we compile python without native bits. This needs to be explained.

Until now we only ever compiled python whl with native bits and then we depend on linux or darwin submodules.

2024-05-01 13:30 UTC, cecille commented
This is submodule specific, trying not to pull in the world. I'd rather not shave this particular yak today, so closing.

2024-05-01 13:30 UTC, closed without merging