Doorlock xml file sync with specs
project-chip/connectedhomeip pull request #33701
Opened 2024-06-03 06:13 UTC by Thirsrin

Description:

Autorelock attribute is optional attribute for doorlock cluster(doorlock.xml) as per matter specs(sec 5.2.9).

2024-06-04 15:55 UTC, bzbarsky-apple commented
So this is not doing a "sync" with the spec like the PR subject says, it's just marking the one attribute as optional?

2024-06-04 15:57 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/door-lock-cluster.xml
The change here is fine, but the commit message needs to be fixed to describe what's actually changing.  This is not a general "make door lock XML follow the spec" change, yes?

2024-06-05 21:19 UTC, jmartinez-silabs approved these changes

2024-06-06 17:06 UTC, bzbarsky-apple approved these changes

2024-06-07 16:09 UTC, andy31415 commented
@Thirsrin this is a backwards-incompatible change (API change). may need a bit more review if/why this would be safe.

2024-06-07 16:13 UTC, andy31415 requested changes, later dismissed
Marking this as hold a bit, until we are able to discuss (likely offline from this PR) about sideffects of API changes.

What we wish we had is full API stability, however in practice this is hard if the spec says one thing and the SDK implements something else.

Looking to figure out what to do here.

2024-06-13 19:56 UTC, merged