adding signed attribute for ZAP to consume
project-chip/connectedhomeip pull request #33719
Opened 2024-06-03 21:57 UTC by paulr34

Fixes https://github.com/project-chip/connectedhomeip/issues/33413

2024-06-03 22:15 UTC, bzbarsky-apple requested changes

2024-06-03 22:15 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/chip-types.xml
1. Commit message should talk about how signed types should be marked as signed.

2. PR description needs to not claim that this fixes an issue it does not (on its own) fix (and PR must not be linked to that issue).

2024-06-04 13:44 UTC, bzbarsky-apple approved these changes

2024-06-04 13:56 UTC, lpbeliveau-silabs approved these changes

2024-06-04 22:09 UTC, merged