Allows opening a commissioning window on a bridged node
project-chip/connectedhomeip pull request #33799
Opened 2024-06-07 07:05 UTC by yufengwangca

FabricSync spec changes were merged,
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/multi_admin/fabric_synchronization.adoc

With the spec update, AdministratorCommissioningCluster is not always on endpoint 0, to open Commissioning Window on bridged node, we need to specify the endpointID

Fixes #33798

2024-06-07 14:04 UTC, andy31415 commented on src/controller/CommissioningWindowOpener.h
> +    CHIP_ERROR OpenCommissioningWindow(NodeId deviceId, EndpointId endpointId, System::Clock::Seconds16 timeout, uint32_t iteration,
These methods start taking too many arguments. Could you create some 'Params' class instead? Methods with more than 3-4 arguments are really hard to follow. This has 10. Same for below.

2024-06-07 14:05 UTC, andy31415 commented on src/controller/CommissioningWindowOpener.h
> +     *   Try to look up the bridged device on the bridge with the given node id
This class currently does not seem to reference bridges at all.

Could we re-phrase the documentation explaining that this is for use for bridges?

2024-06-07 14:09 UTC, andy31415 commented
@yufengwangca please update the PR summary with a description of changes. This seems to be "add ability in the CommissioningWindowOpener to specify the endpoint, so that bridges can be supported" and "enforce the existing opencommissioningwindow to check the endpoint id, since existing implementation is for the current device (i.e. handles root endpoint only)".

2024-06-07 16:01 UTC, bzbarsky-apple requested changes

2024-06-07 16:01 UTC, bzbarsky-apple commented on src/controller/CommissioningWindowOpener.h
> +     *   Try to look up the bridged device on the bridge with the given node id
None of this has anything to do with bridges, as far as this class is concerned.  The right thing to document is "send an OpenCommissioningWindow command with the given parameters to the given endpoint of the given node" or something along those lines.

The fact that this endpoint happens to be a bridge thing of some sort is irrelevant to this class.

2024-06-07 16:01 UTC, bzbarsky-apple commented on src/controller/CommissioningWindowOpener.h
> +     *                          even if those were asked for, that is generated
What does "even if those were asked for" mean here?

Please watch the copy/paste....

2024-06-07 16:01 UTC, bzbarsky-apple commented on src/controller/CommissioningWindowOpener.h
> +    EndpointId mEndpointId                               = kInvalidEndpointId;
```suggestion
    EndpointId mTargetEndpointId                               = kInvalidEndpointId;
```

2024-06-10 22:26 UTC, robszewczyk commented on src/app/clusters/administrator-commissioning-server/administrator-commissioning-server.cpp
> +    VerifyOrExit(endpointId == kRootEndpointId, status.Emplace(StatusCode::kPAKEParameterError));
This is the implementation of the proposed fabric sync feature.   For reference, see section [12.6.3.2. Aggregator Node] of the spec (the text came from https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9106)

2024-06-11 00:03 UTC, bzbarsky-apple commented on src/app/clusters/administrator-commissioning-server/administrator-commissioning-server.cpp
> +    VerifyOrExit(endpointId == kRootEndpointId, status.Emplace(StatusCode::kPAKEParameterError));
Nothing in that spec section says "Ignore command invokes on the Administrator Commissioning cluster if it's not on endpoint 0".

2024-06-11 20:42 UTC, yufengwangca commented on src/app/clusters/administrator-commissioning-server/administrator-commissioning-server.cpp
> +    VerifyOrExit(endpointId == kRootEndpointId, status.Emplace(StatusCode::kPAKEParameterError));
Registered a ticket to clarify the intended behavior when receives OCW command not directed to Endpoint 0
 https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/9354

2024-06-13 23:00 UTC, bzbarsky-apple commented on src/app/clusters/administrator-commissioning-server/administrator-commissioning-server.cpp
> +    VerifyOrExit(endpointId == kRootEndpointId, status.Emplace(StatusCode::kPAKEParameterError));
Great.  Until that's resolved, do not make any changes to this cluster impl, please, because those changes would make it current-spec-not-compliant.

2024-07-19 20:13 UTC, yufengwangca commented
This PR is no more valid after https://github.com/project-chip/connectedhomeip/pull/34209 land, withdraw here and Abdul will create a new one

2024-07-19 20:13 UTC, closed without merging