Fix issue CHIP crypto names are too verbose #312
project-chip/connectedhomeip pull request #339
Opened 2020-04-10 22:54 UTC by bhaskar-apple

#### Problem
Fix issue CHIP crypto names are too verbose #312

 #### Summary of Changes
Use a namespace to make the crypto function names less verbose

fixes #312

2020-04-10 22:58 UTC, gerickson requested changes
Advocate for "Crypto" namespace for consistency with other 2nd-level namespaces.

2020-04-10 23:02 UTC, gerickson approved these changes
@emargolis / @dougsteed / @roydsouza

2020-04-11 00:08 UTC, woody-apple approved these changes

2020-04-11 16:21 UTC, BroderickCarlin approved these changes

2020-04-12 06:01 UTC, emargolis approved these changes

2020-04-13 14:27 UTC, merged