[Silabs] Adding disconnect on factory reset and OTA rename to multi ota
project-chip/connectedhomeip pull request #34098
Opened 2024-06-27 06:03 UTC by chirag-silabs

Disconnecting the wifi, upon the factory reset so that the client sends a deauth, as a successfully disconnection

Renaming the `ota_image_tool.py` to `ota_multi_image_tool.py`

2024-06-27 12:03 UTC, jmartinez-silabs approved these changes

2024-06-27 14:02 UTC, selissia requested changes
The README files should not be updated. The main script is not being renamed.

2024-06-27 16:31 UTC, selissia approved these changes

2024-07-01 16:39 UTC, yufengwangca approved these changes

2024-07-01 16:39 UTC, merged