Logging cleanup
project-chip/connectedhomeip pull request #34108
Opened 2024-06-27 09:12 UTC by mbknust

1. Move LogV.h to src/include/platform/
   - Previously, it was placed in src/platform/logging/

2. Move android's Logging.cpp to src/platform/android/
   - Previously, it was placed in src/platform/logging/impl/android/

2024-06-27 10:21 UTC, arkq commented on examples/common/m5stack-tft/repo
Why this is modified?

2024-06-27 10:52 UTC, mbknust commented on examples/common/m5stack-tft/repo
It was a mistake.

2024-06-27 12:25 UTC, arkq approved these changes

2024-07-02 14:50 UTC, andy31415 requested changes
Could you explain in the PR summary why this change is desirable? The description says that we can remove `logging` directory, however from a code organization perspective a directory named `logging` would give targets of `logging:<name>` and this change moves it to `<name>-logging` so it seems like a noop but with moving thigs out of a dedicated folder. A folder named "logging" is obviously related to logging. A folder named "platform" does not seem so.

I would like to understand how this improves maintainability and structure. Naming-wise, `platform:default-logging` seems slightly worse than `platform/logging:default` (we could even remove the default and name it logging, so then you could use `platform/logging` which could not be done if we move everything in platform.

2024-07-02 14:52 UTC, andy31415 commented on examples/chip-tool/BUILD.gn
> +      "${chip_root}/src/platform:logging-header",
This flattens the "logging" into "platform". We currently have this in `src/app` and it is not good for maintainabilit - we end up getting a lot of separate libraries in one large build files, without them being related. We seem to start getting this into "core" as well as we figured out we have to fix deps. Flattening things out into "platform" seems  undesirable.

2024-07-02 18:42 UTC, arkq commented
> I would like to understand how this improves maintainability and structure.

Currently we have "platform/Linux", "platform/ESP32", "platform/Darwin" and so on. The first impression when looking at the directory structure is that every subdirectory is for a dedicated platform. There is also a "platform/fake" which somehow fits here. And then one discovers "platform/logging". Definitely there is no platform named "logging". So, the reasoning behind getting the logging out of the platform directory was to keep only real (except the "fake") platforms here. IMHO, that should improve readability of that directory level. However, I agree that this might make a mess on the upper level...

On the other hand the "platform" directory level contains a lot of files related to platform which could be grouped into logical blocks (modules). Putting them into dedicated subdirectories will mix real platforms with platform modules...

Currently the "platform/logging" contains logger implementation for STDIO (common for all platforms in case of forced STDIO logging), and implementation for Android. I think, that the Android one should be moved to the "platform/Android" anyway (it will follow pattern for other platforms where platform-specific implementation is kept in "platform/<name>" subdirectory. After  this move, we will end up with only one file in the "platform/logging" - the common STDIO implementation. So, we thought that there is no reason to keep a dedicated directory for only one file in it. Basically that's the story behind this PR :)

2024-08-20 06:46 UTC, arkq commented
Closing, since other approach has been already merged into master.

2024-08-20 06:46 UTC, closed without merging