Revert "[ESP32] Remove SupportedModes implementation of ModeSelect from nvs and use all-clusters-apps common implementation"
project-chip/connectedhomeip pull request #34191
Opened 2024-07-04 05:47 UTC by jadhavrohit924

Reverts project-chip/connectedhomeip#34044

2024-07-05 16:10 UTC, andy31415 requested changes, later dismissed
@jadhavrohit924 please add the reason for the revert in the summary of the PR.

We should try to make PRs clear in what they are doing and why.

2024-07-05 16:36 UTC, jadhavrohit924 commented
@andy31415 Sorry, for the inconvenience. I have updated the PR description.

2024-07-12 05:38 UTC, shubhamdp approved these changes

2024-07-12 05:43 UTC, dhrishi approved these changes

2024-07-15 13:59 UTC, jmartinez-silabs approved these changes

2024-07-15 14:00 UTC, merged