Do not force STDIO output for Linux example apps
project-chip/connectedhomeip pull request #34232
Opened 2024-07-08 13:23 UTC by arkq

### Problem

Example apps should be designed as real applications. Hence, they should integrate with platform logger instead of logging to stdio.

### Changes

- remove forced logging type from examples/platform, so logging can be selected per-app if required

### Testing

CI will verify potential build breaks.

2024-07-08 13:43 UTC, andy31415 approved these changes

2024-07-08 17:47 UTC, yufengwangca approved these changes

2024-07-08 18:07 UTC, kiel-apple approved these changes

2024-07-12 06:06 UTC, bzbarsky-apple requested changes
Test failures are:
```
    raise Exception('Timeout while waiting for %s' % waitForString)
```

because the tests are waiting for some stdio output from the example apps that never comes.

I expect this is actually quite common in workflows involving the example apps (e.g. it's very common for people to find the relevant pairing code in the stdio output).  And certainly we have a bunch of tests that log things from those apps to files in CI and expect those logs to be available later if the test fails.

So I think we need to:

1. Decide whether we actually want to change the default behavior, given the significant pain this will impose on people who currently use the example apps.
2. Decide whether this should be an across-the-board change or whether some commonly-used example apps where this could be a particular problem should default to stdio (for now, or in general).
3. Fix all our build documentation to describe the options for logging and how to select the one you want (no matter what the default is).
4. If we change the default behavior for some apps, ensure that all existing testing that uses those apps is audited to see whether it's OK with the behavior change, and if not update the relevant build args.

But long story short: as-is this will break a _ton_ of people's workflows.  A bunch of in-tree ones (some of them leading to CI failures), but also lots of out-of-tree ones.

2024-07-12 07:07 UTC, arkq commented
> because the tests are waiting for some stdio output from the example apps that never comes.

Yes, I'm aware of that. Now, I'm trying to figure how much work would it be to add support for changing logging to stdio for CI (and potentially other out of tree cases) while still allowing to build example apps with proper platform logging. The case is, that I would like to use the example app on a real device without mich hassle. For Linux apps it's not an issue since the platform logging happens to be stdout as well. But, Darwin and Tizen (Tizen is my real case) by default use dedicated logger. However, the example apps are both based on Linux example platform code, so that's why I'd like the platform common code not to force stdio logging.

I'll convert this PR to draft for now.

2024-08-07 08:01 UTC, closed without merging