Move some common ESP32 CHIP code to its own component
project-chip/connectedhomeip pull request #3429
Opened 2020-10-24 03:43 UTC by pan-apple

#### Problem
We have two ESP32 example apps (wifi-echo, and temprature-measurement) that have same code in both projects. The common code should be moved to a common/shared place.

#### Summary of Changes
Created a new component and moved some low hanging targets to this component.
Also, fixed temperature measurement code, which was failing In build.

2020-10-24 05:02 UTC, rwalker-apple requested changes
`examples/common` was initially a third_party place holder.  it should probably be renamed to third_party.

if this code can be shared across esp32 targets and the functionality is common across platforms, let's consider moving it into CHIP, possibly as a per-platform src/app CRTP class.  Can we do that with this PR?

2020-10-26 16:22 UTC, BroderickCarlin approved these changes

2020-10-26 16:38 UTC, rwalker-apple approved these changes

2020-10-26 17:53 UTC, pan-apple commented
@mspang , @andy31415 do you have any review feedback?

2020-10-27 15:21 UTC, andy31415 approved these changes

2020-10-27 15:41 UTC, merged