CHIP needs an openSSL based Key Derivation Function #257
project-chip/connectedhomeip pull request #346
Opened 2020-04-13 22:17 UTC by bhaskar-apple

#### Problem
CHIP needs an openSSL based Key Derivation Function #257

 #### Summary of Changes
Add a SHA256 based HKDF. 
Add unit tests using test vectors from https://tools.ietf.org/html/rfc5869#appendix-A

fixes #257

2020-04-13 22:27 UTC, balducci-apple requested changes
Two minor nits.

2020-04-14 16:18 UTC, balducci-apple approved these changes

2020-04-14 16:20 UTC, saurabhst approved these changes

2020-04-14 16:24 UTC, BroderickCarlin approved these changes

2020-04-15 03:39 UTC, woody-apple approved these changes

2020-04-15 13:54 UTC, jelderton approved these changes

2020-04-15 14:14 UTC, merged