Add unit test for IPAddress::FromString method
project-chip/connectedhomeip pull request #34788
Opened 2024-08-05 22:27 UTC by swan-amazon

QA reported the following error message while testing. I don't see how this is possible... Added a unit test to test if there should be an issue or not.

```
[1722894966.101286][2144:2145] CHIP:DL: Got IP address on interface: wlan0 IP: 192.168.1.8
[1722894966.101388][2144:2145] CHIP:DL: Failed to report IP address - ip address parsing failed
```

2024-08-07 00:56 UTC, bzbarsky-apple approved these changes
Seems fine, but chances are what happened in the original report is that Matter was built with ipv4 disabled, and then "192.168.1.8" won't parse as an IP address.

2024-08-07 00:56 UTC, bzbarsky-apple commented on src/transport/raw/tests/TestPeerAddress.cpp
> +    bool result           = chip::Inet::IPAddress::FromString(ipStrBuf, ipAddress);
```suggestion
    bool result           = IPAddress::FromString(ipStrBuf, ipAddress);
```

2024-08-07 18:12 UTC, andy31415 commented on src/transport/raw/tests/TestPeerAddress.cpp
> +    const char * ipStrBuf = "192.168.1.8";
https://github.com/project-chip/connectedhomeip/blob/master/src/inet/IPAddress-StringFuncts.cpp#L88 specificaly only parses ipv4 if it is enabled.

2024-08-07 18:13 UTC, andy31415 requested changes
Needs an `#if INET_CONFIG_ENABLE_IPV4`

2024-10-24 13:04 UTC, andy31415 commented
@swan-amazon any updates on this one?

2025-01-09 16:05 UTC, andy31415 commented
@swan-amazon I assume this PR is abandoned as no updates within several months. Please re-open if applicable.

2025-01-09 16:05 UTC, closed without merging