Fix --int-arg, --bool-arg, etc options parsing
project-chip/connectedhomeip pull request #35249
Opened 2024-08-28 08:52 UTC by arkq

### Problem

Multi-argument options are non-intuitive (even our manual did not document it right: https://github.com/project-chip/connectedhomeip/blob/master/docs/testing/python.md#running-tests). Instead of that, use multi-options (which aligns with manual).

### Testing

CI will verify potential failures.

2024-08-28 13:49 UTC, tcarmelveilleux requested changes
Please fix after SVE since the `test_parameters` config in TH is an arguments dict which means if `--string-arg a:foo b:far` shows as:

```
{
   "string-args": "a:foo b:bar"
}
```

Therefore:
```
{
   "string-arg": "a:foo",
   "string-arg": "b:bar"
}
```

would lead to only `b:bar` existing :( 


if we split, then TH can no longer support any tests that has multiple options of same type :(. This is horrendous, but it's more distruptive to change it right now than to leave it.

2024-08-28 17:48 UTC, fabiowmm commented
> Please fix after SVE since the `test_parameters` config in TH is an arguments dict which means if `--string-arg a:foo b:far` shows as:
> 
> ```
> {
>    "string-args": "a:foo b:bar"
> }
> ```
> 
> Therefore:
> 
> ```
> {
>    "string-arg": "a:foo",
>    "string-arg": "b:bar"
> }
> ```
> 
> would lead to only `b:bar` existing :(
> 
> if we split, then TH can no longer support any tests that has multiple options of same type :(. This is horrendous, but it's more distruptive to change it right now than to leave it.

This is correct. We can add the changes needed in TH to our backlog, but I defer to @raju-apple regarding the priority.

2024-10-02 08:23 UTC, arkq commented
@tcarmelveilleux I've updated this PR little bit. Now it will support both option types: multi-argument and multi-option. Also, I've added a unit test to verify that both these behaviors work as expected. What do you think about such compromise?

2024-10-08 12:30 UTC, tcarmelveilleux approved these changes

2024-10-08 13:18 UTC, jmartinez-silabs approved these changes

2024-10-08 13:18 UTC, merged