Auto-commissioner: remove primary network config if failed in commissioning SecondaryNetworkInterface
project-chip/connectedhomeip pull request #35255
Opened 2024-08-28 12:08 UTC by DejinChen

Ref to https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/10335, modified the steps during commissioning a SecondaryNetworkInterface device.

#### Change overview
- If the commissioner fails to configure a network interface, and want to configure another network interface, it SHALL remove the added network configuration before the next attempt.

2024-08-28 13:37 UTC, tcarmelveilleux requested changes
- [ ] Wait for spec PR to land before changing commissioner.

2024-09-04 03:42 UTC, DejinChen commented on src/controller/CHIPDeviceController.cpp
> +        request.networkID = params.GetWiFiCredentials().Value().ssid;
Done.

2024-09-04 13:25 UTC, tcarmelveilleux approved these changes

2024-09-05 00:38 UTC, ksperling-apple approved these changes

2024-09-05 03:06 UTC, chshu approved these changes

2024-09-05 04:54 UTC, merged