[Linux] Matter Linux Water Leak Detector Example
project-chip/connectedhomeip pull request #35392
Opened 2024-09-04 06:44 UTC by lboue

[Linux] Matter Linux Water Leak Detector Example

2024-09-27 11:05 UTC, lboue commented
Is everything in order for validation?

2024-10-02 13:39 UTC, andy31415 submitted a review, later dismissed
Please add support for this to build_examples (you have to change targets.py and host.py at least)

Also without CI this may become stale ...are we sure we want no CI here?

2024-10-03 15:22 UTC, andy31415 approved these changes

2024-10-07 09:50 UTC, fessehaeve approved these changes

2024-10-07 09:50 UTC, merged

2024-10-07 09:55 UTC, fessehaeve requested changes

2024-10-07 09:55 UTC, fessehaeve commented on examples/water-leak-detector-app/water-leak-detector-common/water-leak-detector-app.zap
> +          "name": "Power Source",
This should be on ep0.

2024-10-07 09:55 UTC, fessehaeve commented on examples/water-leak-detector-app/water-leak-detector-common/water-leak-detector-app.zap
> +      "endpointTypeName": "Anonymous Endpoint Type",
should be
```suggestion
      "endpointTypeName": "MA-water-leak-detector",
```
```suggestion
      "endpointTypeName": "Anonymous Endpoint Type",
```

2024-10-07 09:57 UTC, fessehaeve commented
@lboue can you please address my comments as a follow-up?