Camera AV Stream Management Server Impl
project-chip/connectedhomeip pull request #36204
Opened 2024-10-22 22:29 UTC by pidarped

* Delegate definition
  - Support for list entries per index
  - Support for Command handlers

* Attributes support
  - Setters for Application to update values

* Add attributes to json files

* Autogen code changes to zzz_generated/

2025-01-23 04:09 UTC, bzbarsky-apple requested changes

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +                                               static_cast<uint16_t>(writer.GetLengthWritten()));
I do wonder: is there a reason to not use the key format that the other attributes (via SafeAttributePersistenceProvider) use?

And the reason I ask that is this: as soon as you have two instances of this cluster on different endpoints, this setup breaks completely, with the global key name you have here.

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    // TODO
Needs to be at least tracked in an issue that is referenced here.

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    ReturnErrorOnFailure(writer.StartContainer(TLV::AnonymousTag(), TLV::kTLVType_Array, arrayType));
This, and the way viewport is stored, assumes there will never be format/versioning changes, right?  Is that a good assumption?

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    reader.Init(buffer);
Shouldn't this somehow take `len` into account?  The viewport codepath did this right.

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    ReturnErrorOnFailure(reader.ExitContainer(arrayType));
Whoa, wait.  If our Next() failed because the TLV was malformed, we need to return at that point.  Next() is only allowed to return "end of TLV" or success for us to keep going.

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        VerifyOrExit(!commandData.watermarkEnabled.HasValue(), status = Status::InvalidCommand;
I strongly suggest not using "go to exit".  Have this function return a status and have the caller call AddStatus on failure?

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        isWaterMarkEnabled = commandData.watermarkEnabled.ValueOr(false);
This allows invalid commands where we have the WMARK feature but the command is missing the field.

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        isOSDEnabled = commandData.OSDEnabled.ValueOr(false);
Again, this allows invalid commands.

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    // Call the delegate
What happened to verifying that the passed-in enums have valid valies?  That the min/max constraints of all sorts are satisfied?  All of that needs to happen here, because relying on the delegate to do that checking means it won't happen.

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        ctx.mCommandHandler.AddResponse(ctx.mRequestPath, response);
I don't get it.  Where did `response.videoStreamID` get set?

Was this tested at all?

2025-01-23 04:09 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        isWaterMarkEnabled = commandData.watermarkEnabled.ValueOr(false);
This has all the same bugs as VideoStreamAllocate in terms of allowing invalid commands, not validating enums, etc.

I'm stopping here in the .cpp.  Please fix the issues pointed out so far, including in the code I have not read yet.

2025-01-25 04:23 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    std::copy(newPriorities, newPriorities + kNumOfStreamUsageTypes, mRankedVideoStreamPriorities);
Replaced.

2025-02-03 18:58 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +                        const uint16_t minFragmentLen, const uint16_t maxFragmentLen, bool waterMarkEnabled, bool osdEnabled) = 0;
I presume for this call you are talking about the WMARK and OSD features. The checks for the feature are done in the handler before calling this delegate function. If feature is not supported these would default to false.

2025-02-03 19:34 UTC, ksperling-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    SetStreamPriorities(const DataModel::DecodableList<StreamUsageEnum> streamPriorities) = 0;
`Span<StreamUsageEnum>` ?

2025-02-03 19:36 UTC, ksperling-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    LoadAllocatedVideoStreams(std::vector<VideoStreamStruct> & allocatedVideoStreams) = 0;
Has there been a conscious decision to use `std::vector` in this code? Most core code avoids using it.

2025-02-03 20:49 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +constexpr size_t kStreamUsageTlvSize = sizeof(StreamUsageEnum) + 1;
To avoid discrepancy, I am thinking of using a sizeof(uint8_t) for the StreamUsageEnum.

2025-02-04 03:38 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +constexpr size_t kStreamUsageTlvSize = sizeof(StreamUsageEnum) + 1;
No, that's not the point.  The point is that technically nothing requires a number that fits in uint8 to be encoded as one byte in the TLV.  Our TLV encoder does happen to do that, and if we are depending on that, we should probably fail out during encoding if that's violated.

2025-02-04 03:39 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +                        const uint16_t minFragmentLen, const uint16_t maxFragmentLen, bool waterMarkEnabled, bool osdEnabled) = 0;
My question is why we would pass false to the delegate instead of correctly representing the "not present" state?

2025-02-04 03:40 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     * @param aOptionalAttrs                    The bitmask value that identifies the optional attributes supported by this
Because in the spec a "mapN" doesn't mean each bit is independent; some mapN in the spec use two bits to represent stuff.  So you can't use BitFlags for spec mapN when generating code, because you don't know the details of those semantics....

2025-02-04 03:41 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     * @param aOptionalAttrs                    The bitmask value that identifies the optional attributes supported by this
Why wouldn't we just fail out of Init on invalid input, especially since the API docs say we do?

2025-02-04 04:35 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    BitMask<Feature> mFeature;
Have made the BitFlags to be const.

2025-02-04 04:35 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    // TODO
Removed TODO and added the call to delete key.

2025-02-11 03:53 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +                        const uint16_t minFragmentLen, const uint16_t maxFragmentLen, bool waterMarkEnabled, bool osdEnabled) = 0;
Converted to optional args and passed as-is to the delegate.

2025-02-11 03:58 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    SetStreamPriorities(const DataModel::DecodableList<StreamUsageEnum> streamPriorities) = 0;
I realized that I had added the stream priorities as a member array. So, no need to pass to the delegate. Instead, there is a notification callback that is invoked on the delegate when the stream priorities is set via the Command.

2025-02-11 04:20 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    return CHIP_NO_ERROR;
Added the feature and optional attribute checks.

2025-02-11 04:21 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    // Call the delegate
Added sanity checks for args for all the commands.

2025-02-11 04:21 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     * @param aOptionalAttrs                    The bitmask value that identifies the optional attributes supported by this
Added optional bitflag checks along with the feature checks in the Init function.

2025-02-11 06:24 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    LoadAllocatedVideoStreams(std::vector<VideoStreamStruct> & allocatedVideoStreams) = 0;
I have used vectors here mainly for ease of use for managing dynamic lists, and especially, since cameras are expected to be relatively resourceful. What is the preferred approach to represent dynamic lists that are owned?

2025-02-11 23:56 UTC, yufengwangca commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    LoadAllocatedVideoStreams(std::vector<VideoStreamStruct> & allocatedVideoStreams) = 0;
If the objects are very large/non-copyable, then we might use std::vector<std::unique_ptr<VideoStreamStruct>>?
 
std::unique_ptr clearly expresses unique ownership: the vector “owns” the objects. This helps avoid memory leaks and clarifies that nothing else should be responsible for those objects’ lifetimes.

2025-02-13 18:36 UTC, yunhanw-google reviewed
```
2025-02-12 19:21:41 fcd452e3b655 PythonMatterControllerTEST[4749] ERROR Unexpected error occurred when running tests: Cannot decode value for path 2/<class \'chip.clusters.Objects.CameraAvStreamManagement.Attributes.SupportedSnapshotParams\'>, got error: \'InteractionModelError: Failure (0x1)\', raw TLV data: \'None\'
2025-02-12 19:21:41 fcd452e3b655 PythonMatterControllerTEST[4749] ERROR Cannot decode value for path 2/<class \'chip.clusters.Objects.CameraAvStreamManagement.Attributes.SupportedSnapshotParams\'>, got error: \'InteractionModelError: Failure (0x1)\', raw TLV data: \'None\'
Traceback...
```

From cirque mobile test, we see the above error, it looks there is decoding error for CameraAvStreamManagement.Attributes.SupportedSnapshotParam

2025-02-17 20:01 UTC, bzbarsky-apple requested changes

2025-02-17 20:01 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        mDelegate.VideoStreamAllocate(streamUsage, videoCodec, minFrameRate, maxFrameRate, minResolution, maxResolution, minBitRate,
Where is the constraint validation for fields of minResolution/maxResolution?

2025-02-24 22:48 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        DefaultStorageKeyAllocator::AttributeValue(mEndpointId, CameraAvStreamManagement::Id, Attributes::Viewport::Id);
Didn't see the SafeWriteValue/SafeReadValue() APIs earlier for writing/reading TLV encoded bytespans. Have changed to that. Thanks.

2025-02-24 22:49 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +CHIP_ERROR CameraAVStreamMgmtServer::ClearViewport()
I initially thought I would clear before storing but it seems it is not required. Removed it.

2025-02-24 22:49 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        ReturnErrorOnFailure(reader.Next(TLV::kTLVType_UnsignedInteger, TLV::AnonymousTag()));
Have changed the attribute to be a vector. There are some changes that are coming in the Spec where the device would have a SupportedStreamUsages attribute and we will check against that when processing this command. So, changing it to a vector now, and will be updating with those checks when the spec changes land.

2025-02-24 22:53 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        auto & streamUsage          = iter.GetValue();
Added check.

2025-02-24 22:54 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        rankedStreamPriorities[i++] = streamUsage;
Changed to a vector and not a fixed sized array.

2025-02-25 02:36 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    VerifyOrReturn(i == kNumOfStreamUsageTypes, {
Changed to a vector for storing the StreamUsageEnums, which can have less number of items than kNumOfStreamUsageTypes. When the new Spec attributed of SupportedStreamUsages lands, we would need to add checks against that when this command is processed.

2025-02-25 07:08 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    // auto & streamPriorities = commandData.streamPriorities;
Removed spurious commented line.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +            HasFeature(Feature::kAudio) && HasFeature(Feature::kSpeaker), CHIP_IM_GLOBAL_STATUS(UnsupportedAttribute),
Just check Speaker.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +            HasFeature(Feature::kAudio) && HasFeature(Feature::kSpeaker), CHIP_IM_GLOBAL_STATUS(UnsupportedAttribute),
Just check Speaker.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +            HasFeature(Feature::kAudio) && HasFeature(Feature::kSpeaker), CHIP_IM_GLOBAL_STATUS(UnsupportedAttribute),
Just check Speaker.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +            HasFeature(Feature::kAudio) && HasFeature(Feature::kSpeaker), CHIP_IM_GLOBAL_STATUS(UnsupportedAttribute),
Just check Speaker.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +        // Optional Attribute if Video is supported
Not in the spec PR this is claiming to implement.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +            HasFeature(Feature::kAudio) && HasFeature(Feature::kSpeaker), CHIP_IM_GLOBAL_STATUS(UnsupportedAttribute),
Just Speaker.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +            HasFeature(Feature::kAudio) && HasFeature(Feature::kSpeaker), CHIP_IM_GLOBAL_STATUS(UnsupportedAttribute),
Just Speaker.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +// Assumes min-size encoding ( 1 byte ) for the integer.
```suggestion
// StreamUsageEnum + Anonymous tag (1 byte).
// Assumes min-size encoding (1 byte) for the integer.
```

"parentheticals" and "parentheses" are not the same thing.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +            streamUsage; // Indicates the type of usage of stream ( Recording, Liveview, etc ) that this allocation is for.
Look, things with parentheses should be like this: "abc (def ghi) something".  Space before open and after close (which you used to not have) and no spaces after open and before close (which you added for some reason all over here).

Please make this stuff look sane.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    return GetSafeAttributePersistenceProvider()->SafeWriteValue(path, ByteSpan(buffer));
This is wrong.  It should be creating a span with the right length.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    bufferSpan.reduce_size(size);
This is _very very_ wrong.  Please fix.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    bufferSpan.reduce_size(size);
This is wrong.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    VerifyOrReturnError(err == CHIP_END_OF_TLV, err);
OK, so here if the stored TLV had more than kNumOfStreamUsageTypes entries, we will return CHIP_NO_ERROR at this point, right, without doing the ExitContainer/VerifyEndOfContainer below.  Is that the expected behavior?

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +                   ctx.mCommandHandler.AddStatus(ctx.mRequestPath, Status::InvalidCommand));
Why is this checked here and not in the dispatch where Video feature is checked?

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    VerifyOrReturn(commandData.bitRate > 0, {
Where are the constraint checks on minResolution/maxResolution?

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +
Again: Where's the success check for the list iteration?

As in, https://github.com/project-chip/connectedhomeip/pull/36204#discussion_r1958725972 was not addressed.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +
Where is the constraint validation for requestedResolution?

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    if (image.data.size() > kMaxSnapshotImageSize)
Where is kMaxSnapshotImageSize coming from?  I don't see it in the spec.

2025-02-27 20:29 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    memcpy(&response.data, image.data.data(), image.data.size());
You just smashed the stack.  This is a critical security bug right here.  Please let me know if you can't figure out why and how to do this part right.

2025-02-27 21:41 UTC, pidarped commented
Trying to incorporate changes in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/11309 which was in flux. Not all changes from that spec PR have been included yet. Will indicate here once it is ready for review again.

2025-03-06 03:03 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    struct VideoStreamAllocateArgs
The VideoStreamStruct is similar with a ref count field. Replaced with that.

2025-03-06 03:04 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    struct AudioStreamAllocateArgs
Replaced with AudioStreamStruct::Type.

2025-03-06 03:04 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    struct SnapshotStreamAllocateArgs
Replaced with SnapshotStreamStruct::type

2025-03-06 23:39 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    memcpy(&response.data, image.data.data(), image.data.size());
Presumed the response.data to be a byte array. Changed to a ByteSpan.

2025-03-06 23:40 UTC, pidarped commented on examples/all-clusters-app/all-clusters-common/src/camera-av-stream-delegate-impl.cpp
> +    return Status::Success;
Updated comment.

2025-03-06 23:40 UTC, pidarped commented on examples/all-clusters-app/all-clusters-common/src/camera-av-stream-delegate-impl.cpp
> +    return Status::Success;
Updated comment.

2025-03-06 23:40 UTC, pidarped commented on examples/all-clusters-app/all-clusters-common/src/camera-av-stream-delegate-impl.cpp
> +    return Status::Success;
Updated comment.

2025-03-07 19:42 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +    LoadAllocatedVideoStreams(std::vector<VideoStreamStruct> & allocatedVideoStreams) = 0;
Allocation should be infrequent and the number of streams should be relatively small. Keeping it as a vector of structs seems simpler to manage.

2025-03-07 21:26 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    VerifyOrReturnError(err == CHIP_END_OF_TLV, err);
kNumOfStreamUsageTypes is expected to hold the max number of supported stream usages. So, the stored list is not expected to have more than kNumOfStreamUsageTypes entries. However, we have added a new attribute `SupportedStreamUsages` and the `RankedStreamPriorities` list should conform to that. I have filed an issue(https://github.com/project-chip/connectedhomeip/issues/37933) for adding that logic.

2025-03-13 19:03 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     *   @param[in]  allocateArgs   Structure with parameters for video stream allocation.
Should document that callee must ignore the videoStreamID and referenceCount values?  Similar for the other Allocate methods.

2025-03-14 15:58 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.cpp
> +    ReturnErrorOnFailure(reader.ExitContainer(arrayType));
Yes, added the `VerifyOrReturnError(err == CHIP_ERROR_END_OF_TLV)`

2025-03-14 18:40 UTC, bzbarsky-apple approved these changes

2025-03-14 18:40 UTC, bzbarsky-apple commented on examples/all-clusters-app/all-clusters-common/src/camera-av-stream-delegate-impl.cpp
> +            foundAvailableStream = true;
This works, but why do we need a separate loop?  Why can't we have one loop which does:
```
        if (!stream.isAllocated)
        {
            foundAvailableStream = true;
            if (stream.codec == allocateArgs.videoCodec)
            {
                stream.isAllocated = true;
                outStreamID        = stream.id;
                return Status::Success;
            }
        }
```
kind of thing?

2025-03-14 18:40 UTC, bzbarsky-apple commented on examples/all-clusters-app/all-clusters-common/src/camera-av-stream-delegate-impl.cpp
> +    return Status::Failure;
Still needs a spec issue and comment pointing to it here that the behavior on codec mismatch is not defined.  FAILURE is not a good error code to be returning in general.

2025-03-14 18:40 UTC, bzbarsky-apple commented on examples/all-clusters-app/all-clusters-common/src/camera-av-stream-delegate-impl.cpp
> +    for (AudioStream & stream : audioStreams)
See above.

2025-03-14 18:40 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     *   @note The videoStreamID and referenceCount fields in the struct are
```suggestion
     *   @note The videoStreamID and referenceCount fields in the struct must be
```

2025-03-14 18:40 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     *   @note The videoStreamID and referenceCount fields in the struct are
Shouldn't this be part of the param definition?  Or after it and say "fields in allocateArgs"?  Because the obvious question here is "what struct"?

2025-03-14 18:40 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     *   @note The audioStreamID and referenceCount fields in the struct are
See above.

2025-03-14 18:40 UTC, bzbarsky-apple commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     *   @note The snapshotStreamID and referenceCount fields in the struct are
See above.

2025-03-14 20:43 UTC, pidarped commented on examples/all-clusters-app/all-clusters-common/src/camera-av-stream-delegate-impl.cpp
> +    return Status::Failure;
https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/11384

2025-03-14 21:04 UTC, pidarped commented on src/app/clusters/camera-av-stream-management-server/camera-av-stream-management-server.h
> +     *   @note The videoStreamID and referenceCount fields in the struct are
Moved it under allocateArgs.

2025-03-14 21:07 UTC, yufengwangca approved these changes

2025-03-17 05:34 UTC, merged