Have mbedtls use CHIPMem when enabled
project-chip/connectedhomeip pull request #3621
Opened 2020-11-03 16:33 UTC by kpschoedel

#### Problem

Heap allocations from code used by CHIP should go through `CHIPMem.h`
functions. MbedTLS uses heap, and requires configuration once CHIPMem
is initialized.

#### Summary of Changes

- Add run-time mbedtls configurutation to MemoryInit/MemoryShutdown.
- Remove compile-time mbedtls configuration forcing non-CHIP heap allocation.

fixes #3178

2020-11-06 10:25 UTC, mspang requested changes
I don't think we should call mbedtls from src/lib/support.

I'm not sure why this even links to be honest (e.g. src/lib/support/tests - what's the dependency path from that to mbedtls)?

2020-11-06 14:22 UTC, kpschoedel commented
> I don't think we should call mbedtls from src/lib/support.

Do you a suggested location for combined memory init/teardown that isn't fragile? I don't think mbedtls is the only case we'd want to do this in the current structure, e.g. lwip has something similar. (This is another reason I'd rather globally override malloc than have a parallel system.)

2020-11-07 05:30 UTC, bzbarsky-apple approved these changes

2020-11-07 05:31 UTC, saurabhst approved these changes

2020-11-09 19:26 UTC, rwalker-apple approved these changes

2020-11-10 01:11 UTC, mspang commented
> > I don't think we should call mbedtls from src/lib/support.
> 
> Do you a suggested location for combined memory init/teardown that isn't fragile? I don't think mbedtls is the only case we'd want to do this in the current structure, e.g. lwip has something similar. (This is another reason I'd rather globally override malloc than have a parallel system.)

You could put it at src/lib/malloc_initializer as far as I'm concerned. Putting it in src/lib/support is cyclic and I think we should avoid that.

It's not clear to me that's actually desirable that CHIP to enforce an allocator for mbedtls. Even if it does it could be done by providing a helper function that's called by the examples, but not by applications that configure MbedTLS directly.

2020-11-10 15:19 UTC, kpschoedel commented
> It's not clear to me that's actually desirable that CHIP to enforce an allocator for mbedtls.

I'm fine with deferring this unless/until there's a demonstrated need for it and/or consensus on implementation.

2020-11-24 16:56 UTC, andy31415 commented
Closing for now after offline discussion with @kpschoedel . We can reopen if we ever actually need to fix the usage of chip simple-mem with malloc-enabled libraries.

2020-11-24 16:56 UTC, closed without merging