[Telink] Add support for groups multicast control
project-chip/connectedhomeip pull request #36290
Opened 2024-10-29 22:15 UTC by interfer

Add support for up to 8 groups for lighting-app.
Tested on Telink B9x, W91 platform. 
Increased Thread multicast configs for ble-thread plarforms

2024-10-30 03:43 UTC, damien0x0023 requested changes

2024-10-30 03:43 UTC, damien0x0023 commented on examples/lighting-app/telink/include/CHIPProjectConfig.h
Hey, @interfer.

We need to increase the maximum group number per fabric to 8 and the definition `CHIP_CONFIG_MAX_GROUPS_PER_FABRIC` is for this purpose. 
See src/lib/core/CHIPConfig.h (https://github.com/s07641069/connectedhomeip/blob/72e0a68127e9513a97855d3d199d58167b0e7ec1/src/lib/core/CHIPConfig.h#L1072) for details.

However, `CHIP_CONFIG_MAX_GROUP_ENDPOINTS_PER_FABRIC` is the maximum group endpoint number per fabric.
If we set it to 8, the maximum group number per fabric will be 32.
Please check  L1058~1082 to see the differences.

2024-10-30 09:19 UTC, s07641069 approved these changes

2024-10-30 10:11 UTC, interfer commented on examples/lighting-app/telink/include/CHIPProjectConfig.h
@damien0x0023 
Thanks for the hint, agree with your point. Changes applied, tested again and force-pushed

2024-10-30 13:42 UTC, andy31415 approved these changes

2024-10-31 06:21 UTC, damien0x0023 approved these changes

2024-10-31 16:31 UTC, merged