Renaming prior to the delivery of the work about "NFC Commissioning".
project-chip/connectedhomeip pull request #36801
Opened 2024-12-11 14:42 UTC by OlivierGre

In current code, "NFC Commissioning" was used for Onboarding Payload data put into an NFC Tag. This naming will create confusion with the new "NFC Commissioning" feature where NFC is used as the commissioning channel.

We propose to use the folllowing names:
- "NFC onboarding payload" when an NFC Tag is used to store the onboarding payload data (as an alternate solution to QRCode)
- "NFC commissioning" when an NFC Tag is used to perform the first commissioning phase (as an alternate solution to BLE)

Defines, variables and files have been renamed to reflect this. The following renaming have been done:
- CHIP_DEVICE_CONFIG_ENABLE_NFC -> CHIP_DEVICE_CONFIG_ENABLE_NFC_ONBOARDING_PAYLOAD
- CONFIG_CHIP_NFC_COMMISSIONING -> CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD
- chip_enable_nfc -> chip_enable_nfc_onboarding_payload
- NFCManager -> NFCOnboardingPayloadManager
- NFCManagerImpl -> NFCOnboardingPayloadManagerImpl
- NFCMgr -> NFCOnboardingMgr
- NFCMgrImpl -> NFCOnboardingPayloadMgrImpl

The following files have been renamed for the platforms Zephyr, nrfconnect, nxp/k32w0 and telink: NFCManagerImpl.cpp -> NFCOnboardingPayloadManagerImpl.cpp NFCManagerImpl.h -> NFCOnboardingPayloadManagerImpl.h NFCManager.h -> NFCOnboardingPayloadManager.h

> !!!!!!!!!! Please delete the instructions below and replace with PR description
>
> If you have an issue number, please use a syntax of
> `Fixes #12345` and a brief change description
>
> If you do not have an issue number, please have a good description of
> the problem and the fix. Help the reviewer understand what to expect.
>
> Make sure you delete these instructions (to prove you have read them).
>
> !!!!!!!!!! Instructions end

2024-12-11 16:06 UTC, bauerschwan commented
What about `src/lib/shell/commands/NFC.cpp`? Wouldn't it be good to rename it as well? or is the plan to host all NFC-related commands in here?

2024-12-11 17:25 UTC, Damian-Nordic approved these changes
Two consistency nits but lgtm

2024-12-11 17:25 UTC, Damian-Nordic commented on src/include/platform/NFCOnboardingPayloadManager.h
> + * @brief Defines an abstract interface for programming onboarding data in an NFC Tag.
```suggestion
 * @brief Defines an abstract interface for programming an NFC Tag with onboarding payload

2024-12-11 17:25 UTC, Damian-Nordic commented on src/include/platform/internal/GenericPlatformManagerImpl.ipp
> +    // Initialize the CHIP NFC manager for NFC Onboarding
```suggestion
    // Initialize the NFC onboarding payload manager
```

2024-12-12 13:51 UTC, OlivierGre commented
> Two consistency nits but lgtm

@Damian-Nordic Thank you! I have pushed a commit with the changed that you suggested.

2024-12-12 13:55 UTC, OlivierGre commented
> What about `src/lib/shell/commands/NFC.cpp`? Wouldn't it be good to rename it as well? or is the plan to host all NFC-related commands in here?

@bauerschwan I have missed this file. I don't have much a preference. Do you prefer that we keep it like that or rename it?

As indicated on Slack, the code managing "Onboarding Payload" data is for Commissionee side whereas the code adding NFC Commissioning (and using NFC as a new Transport Type) is on Commissioner side. So the classes are completely distinct. In a next PR, you will see the new classes used for NFC Commissioning.

2024-12-12 14:11 UTC, Damian-Nordic commented
> @Damian-Nordic I see that the Zephyr files are used by Nordic:
> 
>     * src/platform/Zephyr/BUILD.gn
> 
>     * src/platform/Zephyr/NFCOnboardingPayloadManagerImpl.cpp
> 
>     * src/platform/Zephyr/NFCOnboardingPayloadManagerImpl.h
> 
> 
> Who should give a green light for the modification of those files?

I think only Nordic uses these files (we should actually move them to nrfconnect dir) so it's enough for you to get +1 from me.

2024-12-12 15:12 UTC, OlivierGre commented
@bauerschwan I see that in the following PR (adding NFC as a new Transport file), I do have some new NFC.cpp and NFC.h files coming in src/transport/raw.

IMO this is not an issue. For BLE this is exactly the same. You've got:
- src/lib/shell/commands/BLE.cpp
- src/transport/raw/BLE.cpp

2024-12-12 15:57 UTC, bauerschwan approved these changes

2024-12-13 04:23 UTC, bzbarsky-apple approved these changes

2024-12-13 04:23 UTC, bzbarsky-apple commented on docs/platforms/nrf/nrfconnect_examples_configuration.md
> +#### Onboarding with NFC support
How about:
```suggestion
#### Onboarding payload delivered over NFC
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on docs/platforms/nrf/nrfconnect_examples_configuration.md
> +of using a QR code, which is the default configuration.
```suggestion
You can configure the Matter protocol to use an NFC tag for delivering the onboarding payload, instead
of using a QR code, which is the default configuration.
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on docs/platforms/nrf/nrfconnect_examples_configuration.md
> +the `CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD` option.
```suggestion
To enable sharing the onboarding payload in an NFC tag, set
the `CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD` option.
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on examples/contact-sensor-app/nxp/k32w1/include/config/CHIPProjectConfig.h
> + * NFC onboarding is not supported on K32W1
```suggestion
 * NFC onboarding payload is not supported on K32W1
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on examples/contact-sensor-app/nxp/mcxw71/include/config/CHIPProjectConfig.h
> + * NFC onboarding is not supported on K32W1
```suggestion
 * NFC onboarding payload is not supported on K32W1
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on examples/lighting-app/nxp/k32w1/include/config/CHIPProjectConfig.h
> + * NFC onboarding is not supported on K32W1
```suggestion
 * NFC onboarding payload is not supported on K32W1
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on examples/lighting-app/nxp/mcxw71/include/config/CHIPProjectConfig.h
> + * NFC onboarding is not supported on K32W1
```suggestion
 * NFC onboarding payload is not supported on K32W1
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on examples/lock-app/nxp/k32w1/include/config/CHIPProjectConfig.h
> + * NFC onboarding is not supported on K32W1
```suggestion
 * NFC onboarding payload is not supported on K32W1
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on examples/lock-app/nxp/mcxw71/include/config/CHIPProjectConfig.h
> + * NFC onboarding is not supported on K32W1
```suggestion
 * NFC onboarding payload is not supported on K32W1
```
This is getting a bit repetitive....

2024-12-13 04:23 UTC, bzbarsky-apple commented on src/include/platform/NFCOnboardingPayloadManager.h
>   * as the device discriminator and PIN code with a commissioner. This class
```suggestion
 * NFC Tag can be used in Project CHIP to share the onboarding payload, including
 * the device discriminator and PIN code, with a commissioner. This class
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on src/include/platform/internal/GenericPlatformManagerImpl.ipp
> +                 ChipLogError(DeviceLayer, "NFC Onboarding Manager initialization failed: %" CHIP_ERROR_FORMAT, err.Format()));
```suggestion
                 ChipLogError(DeviceLayer, "NFC onboarding payload manager initialization failed: %" CHIP_ERROR_FORMAT, err.Format()));
```

2024-12-13 04:23 UTC, bzbarsky-apple commented on src/platform/stm32/args.gni
> +# NFC ONBOARDING CONFIG
```suggestion
# NFC ONBOARDING PAYLOAD CONFIG
```

2024-12-13 11:15 UTC, s07641069 requested changes
@OlivierGre patch with missed changes for Telink & Nordic:
```
diff --git a/config/nrfconnect/chip-module/Kconfig.defaults b/config/nrfconnect/chip-module/Kconfig.defaults
index a2e0a2ba5e..c185a98649 100644
--- a/config/nrfconnect/chip-module/Kconfig.defaults
+++ b/config/nrfconnect/chip-module/Kconfig.defaults
@@ -181,7 +181,7 @@ config MPSL_FEM_NRF21540_RUNTIME_PA_GAIN_CONTROL
 # NFC configuration
 # ==============================================================================
 
-config CHIP_NFC_COMMISSIONING
+config CHIP_NFC_ONBOARDING_PAYLOAD
     default y
 
 # Disable not needed NFC callback to save flash
diff --git a/config/telink/chip-module/Kconfig b/config/telink/chip-module/Kconfig
index 2937b2b0c6..923a2de8c9 100644
--- a/config/telink/chip-module/Kconfig
+++ b/config/telink/chip-module/Kconfig
@@ -22,7 +22,7 @@ if CHIP
 config CHIP_DEVICE_VENDOR_NAME
        default "Telink Semiconductor"
 
-config CHIP_NFC_COMMISSIONING
+config CHIP_NFC_ONBOARDING_PAYLOAD
        bool "Share onboarding payload in NFC tag"
        default n
        imply I2C
diff --git a/examples/lighting-app/telink/prj.conf b/examples/lighting-app/telink/prj.conf
index 9c7bab3e5f..5bf4f5fcd7 100644
--- a/examples/lighting-app/telink/prj.conf
+++ b/examples/lighting-app/telink/prj.conf
@@ -37,7 +37,7 @@ CONFIG_TELINK_OTA_BUTTON_TEST=n
 CONFIG_CHIP_LIB_SHELL=n
 
 # Disable CHIP NFC for commissioning
-CONFIG_CHIP_NFC_COMMISSIONING=n
+CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD=y
 
 # Disable factory data support
 CONFIG_CHIP_FACTORY_DATA=n
diff --git a/examples/shell/nrfconnect/prj.conf b/examples/shell/nrfconnect/prj.conf
index 4c8a3c2c95..bf62a04a71 100644
--- a/examples/shell/nrfconnect/prj.conf
+++ b/examples/shell/nrfconnect/prj.conf
@@ -46,7 +46,7 @@ CONFIG_CHIP_QSPI_NOR=n
 CONFIG_CHIP_PROJECT_CONFIG="CHIPProjectConfig.h"
 # 32786 == 0x8012 (example shell-app)
 CONFIG_CHIP_DEVICE_PRODUCT_ID=32786
-CONFIG_CHIP_NFC_COMMISSIONING=n
+CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD=n
 
 # Disable factory data support. 
 CONFIG_CHIP_FACTORY_DATA=n
```

2024-12-13 11:43 UTC, s07641069 approved these changes

2024-12-13 11:44 UTC, OlivierGre commented
> @OlivierGre patch with missed changes for Telink & Nordic:

Thank you very much Alex! I have pushed your changes. 
I'm going to search if the old names are found in the other files.

2024-12-16 15:43 UTC, andy31415 requested changes, later dismissed
@OlivierGre please add a `Testing` section to your PR to describe how this PR was tested or is to be tested. If `manual` please describe in detail how it was tested and also why automated testing is impossible.

Also make sure you clean it up. There is a `Make sure you delete these instructions (to prove you have read them).` in there still .... 

Also requires restyle fixes.

2024-12-19 13:05 UTC, OlivierGre commented
> @OlivierGre please add a `Testing` section to your PR to describe how this PR was tested or is to be tested. If `manual` please describe in detail how it was tested and also why automated testing is impossible.
> 
> Also make sure you clean it up. There is a `Make sure you delete these instructions (to prove you have read them).` in there still ....
> 
> Also requires restyle fixes.

@andy31415 Hi,

For the tests, I'm not able to test it because this code is for the Commissionee side for platforms that I don't have (Zephyr, nrfconnect, nxp/k32w0 and telink). I have requested a review and an approval from those companies:
- Nordic has approved the change.  He also said that the Zephyr files are only used by Nordic (see https://github.com/project-chip/connectedhomeip/pull/36801#issuecomment-2539062872)
- s07641069 (Alex Tsitsiura) has done a review for Telink.
- I'm in contact with Ethan Tan from NXP. He told me that he is going to review the change.
Do you expect something else from me?

I wanted to do the change about the restyler but, when I look at the details provided, I can see that it ended with an error;
Error: Restyler exited non-zero: 228
The command to apply looks truncated. Do you know how to solve that?

Thanks

2024-12-19 13:13 UTC, OlivierGre commented
@andy31415 Also, I don't understand why many CI checks indicate "cancelled after 1m" (ex: "
Build example - Ameba / Ameba (pull_request) ", "
Build example - EFR32 / EFR32 (pull_request)"...etc).

2024-12-19 18:01 UTC, andy31415 commented
> > @OlivierGre please add a `Testing` section to your PR to describe how this PR was tested or is to be tested. If `manual` please describe in detail how it was tested and also why automated testing is impossible.
> > Also make sure you clean it up. There is a `Make sure you delete these instructions (to prove you have read them).` in there still ....
> > Also requires restyle fixes.
> 
> @andy31415 Hi,
> 
> For the tests, I'm not able to test it because this code is for the Commissionee side for platforms that I don't have (Zephyr, nrfconnect, nxp/k32w0 and telink). I have requested a review and an approval from those companies:
> 
> * Nordic has approved the change.  He also said that the Zephyr files are only used by Nordic (see [Renaming prior to the delivery of the work about "NFC Commissioning". #36801 (comment)](https://github.com/project-chip/connectedhomeip/pull/36801#issuecomment-2539062872))
> * s07641069 (Alex Tsitsiura) has done a review for Telink.
> * I'm in contact with Ethan Tan from NXP. He told me that he is going to review the change.
>   Do you expect something else from me?
> 
> I wanted to do the change about the restyler but, when I look at the details provided, I can see that it ended with an error; Error: Restyler exited non-zero: 228 The command to apply looks truncated. Do you know how to solve that?
> 
> Thanks

So how do we know that this code is good? There has to be some way to test it?
is it compile only then? We need details in the PR summary to understand.

2024-12-19 18:02 UTC, andy31415 commented
@OlivierGre please add a `Testing` section even if it is describing the uncomfortable truth of "This was not actually tested, not even manually, except it compiles".

Then reviewers can make an informed decision about the code. Maybe details about how testing will follow eventualy, because code that will never be tested/executed sounds wrong.

2024-12-19 18:03 UTC, andy31415 commented
> @andy31415 Also, I don't understand why many CI checks indicate "cancelled after 1m" (ex: " Build example - Ameba / Ameba (pull_request) ", " Build example - EFR32 / EFR32 (pull_request)"...etc).

We have a fast-cancel in case some fast required checks fail, so we free up CI resources. In this case `Restyle` failed so all other CI runs were cancelled. Once you fix restyle things should not get cancelled.

2024-12-19 18:04 UTC, andy31415 commented
@OlivierGre for the restyle, the restyler task contains the command needed to restyle, generally ready for copy & paste (I hope it is generally visible)

![image](https://github.com/user-attachments/assets/e7461838-72e0-427c-bd49-77b830c94b17)

2025-01-03 15:02 UTC, OlivierGre commented
@Damian-Nordic 
Hi Damian,
In config/nrfconnect/chip-module/Kconfig.defaults, I have renamed CHIP_NFC_COMMISSIONING into CHIP_NFC_ONBOARDING_PAYLOAD. I have probably missed a file still containing CHIP_NFC_COMMISSIONING because the build on Nordic platform is failing:

```
warning: CHIP_NFC_ONBOARDING_PAYLOAD (defined at /__w/connectedhomeip/connectedhomeip/examples/lock-app/nrfconnect/../../../config/nrfconnect/chip-module/Kconfig.defaults:184) defined without a type

error: Aborting due to Kconfig warnings
```
For the moment I don't find the clue. Would you know where CHIP_NFC_COMMISSIONING could be defined?

Thanks

2025-01-06 22:34 UTC, Damian-Nordic commented
@OlivierGre you seem to have missed `config/nrfconnect/chip-module/Kconfig`. The `Kconfig.defaults` file just overrides certain Kconfigs, but the original Kconfig has to updated as well.

2025-01-07 09:48 UTC, OlivierGre commented
> @OlivierGre you seem to have missed `config/nrfconnect/chip-module/Kconfig`. The `Kconfig.defaults` file just overrides certain Kconfigs, but the original Kconfig has to updated as well.

Oh, thank you Damian. I can see that I have missed this file because my editor did not include the files without extension.

2025-01-16 15:59 UTC, merged