Update `generate_spec_xml.py`
project-chip/connectedhomeip pull request #36854
Opened 2024-12-15 10:39 UTC by lboue

Update `generate_spec_xml.py`:
- Correct branches directory names
- Remove Branch.IN_PROGRESS, not here anymore

2024-12-16 15:09 UTC, andy31415 reviewed
@lboue please add a `Testing` section to the PR summary to describe how you tested this change and why automated testing is not possible.

2024-12-16 15:57 UTC, lboue commented
> I can't test it because I don't have access to Specification repository https://github.com/CHIP-Specifications/connectedhomeip-spec

I can't test it because I don't have access to Specification repository https://github.com/CHIP-Specifications/connectedhomeip-spec

2024-12-16 21:02 UTC, fefemama585 approved these changes

2024-12-17 17:55 UTC, andy31415 commented
> --output-dir data_model

Running the test myself. I am hitting the `raise FileNotFoundError(f"Documentation file does not exist: {documentation_file}")  ` error fixed in #36852. Will try again after applying that patch.

2024-12-17 17:57 UTC, andy31415 commented
> > --output-dir data_model
> 
> Running the test myself. I am hitting the `raise FileNotFoundError(f"Documentation file does not exist: {documentation_file}") ` error fixed in #36852. Will try again after applying that patch.

After fixing that, I get a positional argument error:

![image](https://github.com/user-attachments/assets/ab1cca41-7993-49ee-980c-cdbcb52d8fe9)

2024-12-17 18:04 UTC, andy31415 requested changes
This PR does not work: include_in_progress is a mandatory argument and should not be removed.

2024-12-17 18:04 UTC, andy31415 commented on scripts/spec_xml/generate_spec_xml.py
> -@click.option(
I don't think this is the same: this defines what we include from the spec. Please do not remove this one (but the rest could be removed)

2024-12-17 18:13 UTC, cecille commented on scripts/spec_xml/paths.py
> -    V1_3 = "v1_3"
in_progress directory is required for ongoing work. Please do not remove. It has been re-named, but the directory name is changeable on the command line.

Are you attempting to pull a new data model scrape for ongoing work?

2025-02-03 23:21 UTC, closed without merging