Feature/thermostat events xml
project-chip/connectedhomeip pull request #36909
Opened 2024-12-19 19:15 UTC by drempelg

XML for https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/10444

2024-12-19 22:28 UTC, bzbarsky-apple requested changes

2024-12-19 22:28 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
> +        <optionalConform/>
Shouldn't this be flagged provisional in the XML somehow for now?

2024-12-19 22:28 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
> +        <feature name="TEVT"/>
This does not seem to match the spec's conformance for this event?

2024-12-19 22:28 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
> +      <field id="1" name="CurrentPresetHandle" type="octet_string"/>
These don't match the spec.

2025-01-13 18:13 UTC, drempelg commented
Once https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/10444 is approved I'll make it match the final xml that's chosen.

2025-02-20 19:47 UTC, drempelg commented on src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
> +        <optionalConform/>
is there a way to do so?  I ran alchemy this round instead of handcoding and it didn't mark it with the apiMaturity attribute like the other fields.

2025-02-20 19:49 UTC, drempelg commented on src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
> +      <field id="1" name="CurrentPresetHandle" type="octet_string"/>
generated from latest spec with alchemy, should match now?

2025-02-22 06:35 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
> +        <optionalConform/>
It's possible that nothing supports apiMaturity on bitfields yet... if so, please reach out to @andy31415 and @hasty about fixing that.

2025-02-25 19:45 UTC, hasty commented on src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
> +        <optionalConform/>
ZAP doesn't support apiMaturity outside of clusters, attributes, and structs. Of those, clusters and attributes currently have a method of specifying that they're provisional, in the sense that they have a conformance column; perhaps we should discuss in the DM TT call about how best to do this?

2025-04-01 01:29 UTC, bzbarsky-apple approved these changes

2025-05-29 18:53 UTC, sxb427 approved these changes

2025-11-25 16:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=36909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=36909) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: hasty<br/>:x: drempelg<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=36909) it.</sub>

2025-11-25 16:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=36909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=36909) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: drempelg<br/>:x: hasty<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=36909) it.</sub>

2026-03-16 13:41 UTC, closed without merging