da_revocation: function out generation of revocation set from the crl
project-chip/connectedhomeip pull request #36933
Opened 2024-12-23 14:12 UTC by shubhamdp

Function out generating the revocation set entry and figuring out which CA name and CA subject key Id to use.

This helps generating the revocation set from the CRL itself. This can be helpful in test-mode and we won't require the to go through the DCL workflow for testing revocation feature in the SDK.

#### Testing
manual tested:
- regenerate the revocation set from the test-net and main-net and verified that the results are same.
- Also, imported the script and generated the revocation set from the CRL, and verified the results.

2025-01-14 18:46 UTC, andy31415 requested changes, later dismissed
@shubhamdp would it be possible to have CI validation that `generate-revocation-set.py` can run successfully on some sample output?

Otherwise, why is automation testing impossible? Please describe the reason and add to the summary detaild information about what commands you ran and what you observed (i.e. instead of just `tested manually` list the actual commands used ... also what does `verified` mean? what commands/diffs were used).

We have the bar of `tested manually` intentionally high to make more likely that people implement automated tests (and seeing detailed info about what was done we could evaluate if something can indeed be automated or not).

2025-01-15 04:47 UTC, shubhamdp commented
@andy31415 it is possible, I was waiting on #36929 to land, it has sample indirect CRLs so that I could get in the same PR.

Anyway I'll add them for this already present CRLs and then extend once #36929 lands.

2025-01-15 07:01 UTC, shubhamdp commented
@andy31415 I have added the unittest in the script and enabled them in the CI. PTAL!

2025-01-16 16:48 UTC, andy31415 approved these changes

2025-01-17 10:10 UTC, dhrishi approved these changes

2025-01-17 10:10 UTC, merged