Move 'emberAfPluginOnOffClusterServerPostInitCallback' to src/app/clu…
project-chip/connectedhomeip pull request #3782
Opened 2020-11-11 17:16 UTC by vivien-apple

…ster/on-off-server

 #### Problem
 
#3464 does not have any informations about plugins and will not generate definitions or stubs for the OnOff server methods.

This callback was used by a few applications. I replaced it by `emberAfClusterInitCallback` but there is a semantic difference.
The previous callback was done __Post__ init which means the default value of the light was set into the platform before it is called. But `emberAfClusterInitCallback` is called just before it is set.

In practice, and in the current shape of the tree there should be no differences. But this is one of the case where it the API was used so I though it worth mentioning it since we may want to provide something at some points to have an equivalent method.

 #### Summary of Changes
  * Move  `emberAfPluginOnOffClusterServerPostInitCallback`  into `src/app/clusters/on-off-server`
  * Remove the related definitions/stubs from gen/ folders

2020-11-11 19:17 UTC, bzbarsky-apple commented
> In practice, and in the current shape of the tree there should be no differences

Why not?  The callback will cause the app to sync the data model with the actual state of the light, but then the cluster init will update the data model to default values, overwriting the values the app set, no?  Or am I missing something?

2020-11-11 19:37 UTC, bzbarsky-apple requested changes
>  In practice, and in the current shape of the tree there should be no differences

Why not? The callback will cause the app to sync the data model with the actual state of the light, but then the cluster init will update the data model to default values, overwriting the values the app set, no? Or am I missing something?

2020-11-11 20:00 UTC, vivien-apple commented
> > In practice, and in the current shape of the tree there should be no differences
> 
> Why not? The callback will cause the app to sync the data model with the actual state of the light, but then the cluster init will update the data model to default values, overwriting the values the app set, no? Or am I missing something?

This is why I mention "in the current shape of the tree". My understanding is that the OnOff server init callback does nothing at the moment because there is an #ifdef that is not turned on: https://github.com/project-chip/connectedhomeip/blob/4f757f71661e3c1d56670304a90828d445b7fa6c/src/app/clusters/on-off-server/on-off.cpp#L204

2020-11-11 20:04 UTC, bzbarsky-apple commented
> My understanding is that the OnOff server init callback does nothing at the moment because there is an #ifdef that is not turned on

Ah.  But OK, we're going to want to support that at some point, so we will 100% need a callback that happens after that startup processing happens.  Why do we want to remove an existing callback that does exactly that?

I guess we could be waiting for a better callback-registration setup that won't involve generated stubs?  If so, we should have an issue tracking that and referenced from this stuff.

2020-11-11 20:12 UTC, vivien-apple commented
> > My understanding is that the OnOff server init callback does nothing at the moment because there is an #ifdef that is not turned on
> 
> Ah. But OK, we're going to want to support that at some point, so we will 100% need a callback that happens after that startup processing happens. Why do we want to remove an existing callback that does exactly that?
> 

We definitively want to support that. As well as a bunch of other use cases provided by the current __Plugin Callbacks__ that I'm moving down into the stack.

At the moment I'm removing all the __Plugin Callbacks__ because __ZAP__ does not know how to generate stubs for it. It will basically be hardcoded into the templates.

> I guess we could be waiting for a better callback-registration setup that won't involve generated stubs? If so, we should have an issue tracking that and referenced from this stuff.

I will open an issue to track this and add the #number on top of all the places where I have changed the callback. In fact I should have done that yesterday.

2020-11-12 18:17 UTC, rwalker-apple approved these changes

2020-11-16 09:33 UTC, vivien-apple commented
> > I guess we could be waiting for a better callback-registration setup that won't involve generated stubs? If so, we should have an issue tracking that and referenced from this stuff.

I have opened #3841 and have added the #number to all the places where `emberAfPluginOnOffClusterServerPostInitCallback` has been replaced by `emberAfClusterInitCallback`

2020-11-16 17:18 UTC, BroderickCarlin approved these changes

2020-11-16 18:40 UTC, jelderton approved these changes

2020-11-16 23:31 UTC, rwalker-apple commented
@bzbarsky-apple can you have another look?

2020-11-17 05:07 UTC, bzbarsky-apple approved these changes

2020-11-17 05:07 UTC, bzbarsky-apple commented on examples/lighting-app/efr32/src/ZclCallbacks.cpp
> + * FIXME Issue #3841
I think we are using TODO, not FIXME.

2020-11-17 05:07 UTC, bzbarsky-apple commented on examples/lighting-app/linux/main.cpp
> + * FIXME Issue #3841
TODO

2020-11-17 05:07 UTC, bzbarsky-apple commented on examples/lighting-app/nrfconnect/main/ZclCallbacks.cpp
> + * FIXME Issue #3841
TODO

2020-11-17 05:07 UTC, bzbarsky-apple commented on examples/lock-app/efr32/src/ZclCallbacks.cpp
> + * FIXME Issue #3841
TODO

2020-11-17 05:07 UTC, bzbarsky-apple commented on examples/lock-app/k32w/main/ZclCallbacks.cpp
> + * FIXME Issue #3841
TODO

2020-11-17 05:07 UTC, bzbarsky-apple commented on examples/lock-app/nrfconnect/main/ZclCallbacks.cpp
> + * FIXME Issue #3841
TODO

2020-11-17 15:27 UTC, merged