Add missing client clusters to src/app/clusters
project-chip/connectedhomeip pull request #3924
Opened 2020-11-19 14:53 UTC by vivien-apple

#### Problem

I tried to get rid of all client clusters in #3798 but since it makes sense to keep them around for a little while, this PR adds some missing client clusters to `src/app/clusters`.

It allows us to remove `gen/clusters-callback-stubs.cpp` from the `all-clusters-app` since there is now a platform implementation of `emberAfIdentifyClusterIdentifyQueryResponseCallback` instead of a stub.

 #### Summary of Changes
 * Add `src/app/clusters/identify-client`
 * Add `src/app/clusters/door-lock-client`
 * Remove `gen/clusters-callback-stubs.cpp` from the `gen/` folder of the `all-clusters-app`
 * Add `door-lock-client` and `identify-client` as `all-clusters-app` build dependencies

2020-11-19 15:06 UTC, saurabhst approved these changes

2020-11-19 16:01 UTC, bzbarsky-apple requested changes
Can you please do this in a way that preserves the commit history for the client clusters from the silabs contribution PR, including the explicit "we are licensing this for CHIP use" commits?

2020-11-19 16:22 UTC, vivien-apple commented
> Can you please do this in a way that preserves the commit history for the client clusters from the silabs contribution PR, including the explicit "we are licensing this for CHIP use" commits?

Do we have such clusters ?  If so where. I wrote those by myself...

2020-11-19 16:38 UTC, bzbarsky-apple approved these changes
Sorry, I had misunderstood where this code was coming from!

2020-11-19 19:45 UTC, rwalker-apple approved these changes

2020-11-20 12:46 UTC, andy31415 approved these changes

2020-11-20 18:09 UTC, mspang approved these changes

2020-11-20 18:09 UTC, merged