Turn on unit tests
project-chip/connectedhomeip pull request #407
Opened 2020-04-16 22:28 UTC by rwalker-apple

#### Problems
 * Not running unit tests in CI
 * Overlapping tasks (crypto and setup_payload are part of unit tests)

 #### Summary of Changes
 * Turn on commented out subsystem
 * Remove redundant tests

2020-04-16 23:49 UTC, woody-apple approved these changes

2020-04-16 23:50 UTC, woody-apple requested changes
Why are we deleting tests? Let's keep them commented out until we can re-enable them. I'd like to keep the tests as broken down as possible.

2020-04-17 13:31 UTC, jelderton approved these changes

2020-04-17 20:41 UTC, woody-apple approved these changes

2020-04-18 05:07 UTC, BroderickCarlin approved these changes

2020-04-18 15:35 UTC, merged