[WIP] enable address sanitizer
project-chip/connectedhomeip pull request #4118
Opened 2020-12-08 10:38 UTC by gjc13

#### Problem

https://github.com/project-chip/connectedhomeip/issues/4117

 #### Summary of Changes

Enable address sanitizer.

We'd expect this PR to contain fixes on memory issues as well.

2020-12-08 10:38 UTC, gjc13 commented
The first error message I met is

```
==32==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55647b206783 at pc 0x7f56c2eb417a bp 0x7ffe50a19810 sp 0x7ffe50a18fb8                                                                                       [6/326]
WRITE of size 1 at 0x55647b206783 thread T0
    #0 0x7f56c2eb4179 in memmove (/lib/x86_64-linux-gnu/libasan.so.6+0x3a179)
    #1 0x55647afb2da1 in typeSensitiveMemCopy ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:394
    #2 0x55647afb39a0 in emAfReadOrWriteAttribute(EmberAfAttributeSearchRecord*, EmberAfAttributeMetadata**, unsigned char*, unsigned short, bool) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:563
    #3 0x55647afb4ad8 in emAfLoadAttributeDefaults(unsigned char, bool) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:1106
    #4 0x55647afb43ec in emberAfInitializeAttributes(unsigned char) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:1015
    #5 0x55647afba001 in emberAfInit() ../../third_party/connectedhomeip/src/app/util/util.cpp:261
    #6 0x55647afa8aa7 in InitDataModelHandler() (/usr/bin/chip-tool-server+0x87aa7)
    #7 0x55647b02832c in InitServer(AppDelegate*) ../../third_party/connectedhomeip/examples/common/chip-app-server/Server.cpp:125
    #8 0x55647afa5bdb in main (/usr/bin/chip-tool-server+0x84bdb)
    #9 0x7f56c23f70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x55647afa3d09 in _start (/usr/bin/chip-tool-server+0x82d09)

0x55647b206783 is located 0 bytes to the right of global variable 'attributeData' defined in '../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:60:9' (0x55647b206780) of size 3
0x55647b206783 is located 61 bytes to the left of global variable 'singletonAttributeData' defined in '../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:67:9' (0x55647b2067c0) of size 1
  'singletonAttributeData' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow (/lib/x86_64-linux-gnu/libasan.so.6+0x3a179) in memmove
Shadow bytes around the buggy address:
  0x0aad0f638ca0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 04
  0x0aad0f638cb0: f9 f9 f9 f9 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9
  0x0aad0f638cc0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aad0f638cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aad0f638ce0: f9 f9 f9 f9 00 00 00 00 00 00 00 f9 f9 f9 f9 f9
=>0x0aad0f638cf0:[03]f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0aad0f638d00: 01 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aad0f638d10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aad0f638d20: 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9
  0x0aad0f638d30: 00 f9 f9 f9 f9 f9 f9 f9 02 f9 f9 f9 f9 f9 f9 f9
  0x0aad0f638d40: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32==ABORTING
==32==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55647b206783 at pc 0x7f56c2eb417a bp 0x7ffe50a19810 sp 0x7ffe50a18fb8                                                                                       [6/326]
WRITE of size 1 at 0x55647b206783 thread T0
    #0 0x7f56c2eb4179 in memmove (/lib/x86_64-linux-gnu/libasan.so.6+0x3a179)
    #1 0x55647afb2da1 in typeSensitiveMemCopy ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:394
    #2 0x55647afb39a0 in emAfReadOrWriteAttribute(EmberAfAttributeSearchRecord*, EmberAfAttributeMetadata**, unsigned char*, unsigned short, bool) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:563
    #3 0x55647afb4ad8 in emAfLoadAttributeDefaults(unsigned char, bool) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:1106
    #4 0x55647afb43ec in emberAfInitializeAttributes(unsigned char) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:1015
    #5 0x55647afba001 in emberAfInit() ../../third_party/connectedhomeip/src/app/util/util.cpp:261
    #6 0x55647afa8aa7 in InitDataModelHandler() (/usr/bin/chip-tool-server+0x87aa7)
    #7 0x55647b02832c in InitServer(AppDelegate*) ../../third_party/connectedhomeip/examples/common/chip-app-server/Server.cpp:125
    #8 0x55647afa5bdb in main (/usr/bin/chip-tool-server+0x84bdb)
    #9 0x7f56c23f70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x55647afa3d09 in _start (/usr/bin/chip-tool-server+0x82d09)

0x55647b206783 is located 0 bytes to the right of global variable 'attributeData' defined in '../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:60:9' (0x55647b206780) of size 3
0x55647b206783 is located 61 bytes to the left of global variable 'singletonAttributeData' defined in '../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:67:9' (0x55647b2067c0) of size 1
  'singletonAttributeData' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow (/lib/x86_64-linux-gnu/libasan.so.6+0x3a179) in memmove
Shadow bytes around the buggy address:
  0x0aad0f638ca0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 04
  0x0aad0f638cb0: f9 f9 f9 f9 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9
  0x0aad0f638cc0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aad0f638cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aad0f638ce0: f9 f9 f9 f9 00 00 00 00 00 00 00 f9 f9 f9 f9 f9
=>0x0aad0f638cf0:[03]f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0aad0f638d00: 01 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aad0f638d10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aad0f638d20: 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9
  0x0aad0f638d30: 00 f9 f9 f9 f9 f9 f9 f9 02 f9 f9 f9 f9 f9 f9 f9
  0x0aad0f638d40: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32==ABORTING
==32==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55647b206783 at pc 0x7f56c2eb417a bp 0x7ffe50a19810 sp 0x7ffe50a18fb8                                                                                       [6/326]
WRITE of size 1 at 0x55647b206783 thread T0
    #0 0x7f56c2eb4179 in memmove (/lib/x86_64-linux-gnu/libasan.so.6+0x3a179)
    #1 0x55647afb2da1 in typeSensitiveMemCopy ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:394
    #2 0x55647afb39a0 in emAfReadOrWriteAttribute(EmberAfAttributeSearchRecord*, EmberAfAttributeMetadata**, unsigned char*, unsigned short, bool) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:563
    #3 0x55647afb4ad8 in emAfLoadAttributeDefaults(unsigned char, bool) ../../third_party/connectedhomeip/src/app/util/attribute-storage.cpp:1106
    #4 0x55647afb43ec in emberAfInitializeAttributes(unsigned char) ../../third_party/connectedhomeip/src/app/util/attri [...]

2020-12-08 16:39 UTC, mspang requested changes
Should not be keyed by is_debug

2020-12-08 19:51 UTC, bzbarsky-apple commented
> emAfLoadAttributeDefaults

Hmm.  This seems like a possible issue in the generated code for the relevant app (chip-tool-server?)

Looking at `examples/lighting-app/lighting-common/gen/endpoint_config.h` I am seeing:
```
// Generated attributes
#define GENERATED_ATTRIBUTES                                                                                                       \
    {                                                                                                                              \
        { 0x0000, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t *) 0x00 } },      /* 0 / On/off / on/off*/                     \
            { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t *) 0x0001 } }, /* 1 / On/off / cluster revision*/           \
            { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t *) 0x00 } },    /* 2 / Level Control / current level*/       \
            { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t *) 0x0001 } }, /* 3 / Level Control / cluster revision*/    \
    }
....
#define ATTRIBUTE_MAX_SIZE 3
```
which seems wrong: there are 6 bytes of attributes declared, but only 3 bytes claimed as the needed space.  Possible fallout from https://github.com/project-chip/connectedhomeip/pull/3806 ?

@vivien-apple I assume moving to generating `endpoint-config.h` via ZAP and then regenerating the lighting app config will help here?

2020-12-10 23:54 UTC, mspang requested changes
I think we should create a separate ASAN workflow, at least initially. I believe clang has better sanitizer support, and that we should use that (unless we want to test both gcc+asan and clang+asan).

2020-12-10 23:55 UTC, mspang commented
Need to turn off `-Wl,-z,defs` for sanitizers to avoid breaking shared library linkage.

e.g., 
```
ld.lld: error: undefined symbol: __asan_init
>>> referenced by ChipDeviceController-BleApplicationDelegate.cpp
>>>               linux_x64_clang/obj/src/controller/python/_ChipDeviceCtrl.ChipDeviceController-BleApplicationDelegate.cpp.o:(asan.module_ctor)
>>> referenced by ChipDeviceController-BlePlatformDelegate.cpp
>>>               linux_x64_clang/obj/src/controller/python/_ChipDeviceCtrl.ChipDeviceController-BlePlatformDelegate.cpp.o:(asan.module_ctor)
>>> referenced by ChipDeviceController-ScriptBinding.cpp
>>>               linux_x64_clang/obj/src/controller/python/_ChipDeviceCtrl.ChipDeviceController-ScriptBinding.cpp.o:(asan.module_ctor)
>>> referenced 126 more times

```

This may be a reason to keep separate ASAN build indefinitely (otherwise we lose the checks that this option provides).

2020-12-11 12:44 UTC, vivien-apple commented
> > emAfLoadAttributeDefaults
> 
> Hmm. This seems like a possible issue in the generated code for the relevant app (chip-tool-server?)
> 
> Looking at `examples/lighting-app/lighting-common/gen/endpoint_config.h` I am seeing:
> 
> ```
> // Generated attributes
> #define GENERATED_ATTRIBUTES                                                                                                       \
>     {                                                                                                                              \
>         { 0x0000, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t *) 0x00 } },      /* 0 / On/off / on/off*/                     \
>             { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t *) 0x0001 } }, /* 1 / On/off / cluster revision*/           \
>             { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t *) 0x00 } },    /* 2 / Level Control / current level*/       \
>             { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t *) 0x0001 } }, /* 3 / Level Control / cluster revision*/    \
>     }
> ....
> #define ATTRIBUTE_MAX_SIZE 3
> ```
> 
> which seems wrong: there are 6 bytes of attributes declared, but only 3 bytes claimed as the needed space. Possible fallout from #3806 ?
> 
> @vivien-apple I assume moving to generating `endpoint-config.h` via ZAP and then regenerating the lighting app config will help here?

I will definitively help as you guess. Sorry to not have spot that in #3806 ...

2020-12-14 11:52 UTC, vivien-apple commented
> > which seems wrong: there are 6 bytes of attributes declared, but only 3 bytes claimed as the needed space. Possible fallout from #3806 ?
> > @vivien-apple I assume moving to generating `endpoint-config.h` via ZAP and then regenerating the lighting app config will help here?
> 

I made a build to check if that helps.

And yes, changing this value from `3` to `6` solve the buffer overflow.

But while building I also encountered a `stack-use-after-scope` issue with `TestChipCallback.cpp`.

I did a patch for both of them in https://github.com/project-chip/connectedhomeip/pull/4194

2021-01-07 09:09 UTC, closed without merging