[format] Manually correct code style of examples.
project-chip/connectedhomeip pull request #418
Opened 2020-04-17 20:15 UTC by turon

#### Problem
Make example sources code style compliant to prevent restyled getting involved whenever these files are touched.  

 #### Summary of Changes
Manual run of clang-format on examples.

workaround #345 until resolved

2020-04-17 20:19 UTC, woody-apple requested changes
Please update clang-format so restyled does this automatically.

2020-04-17 21:52 UTC, woody-apple approved these changes

2020-04-18 05:19 UTC, BroderickCarlin approved these changes

2020-04-20 14:26 UTC, jelderton approved these changes

2020-04-20 15:46 UTC, merged