Migrate device controller python binding to new controller and channel API
project-chip/connectedhomeip pull request #4446
Opened 2021-01-21 12:41 UTC by kghost

#### Problem

Migrate to messaging layer #4170

 #### Summary of Changes

Same purpose as **Migrate device controller to messaging layer API** #4171, but migrating chip-tool will break lots of CI test, so instead of migrating chip-tool, we can start from the python binding of device controller.

I'm going to migrate the python binding to the new controller class, instead of the deprecated class.

2021-01-26 17:16 UTC, rwalker-apple approved these changes

2021-01-26 19:57 UTC, jelderton commented on src/messaging/Channel.cpp
> + *    Copyright (c) 2020 Project CHIP Authors
nit: 2021

2021-01-26 19:58 UTC, jelderton commented on src/messaging/Channel.h
> + *    Copyright (c) 2020 Project CHIP Authors
nit: 2021

2021-01-26 20:27 UTC, jelderton commented on src/messaging/ChannelContext.cpp
> + *    Copyright (c) 2020 Project CHIP Authors
nit: 2021

2021-01-26 20:37 UTC, jelderton commented on src/messaging/ChannelContext.h
> + *    Copyright (c) 2020 Project CHIP Authors
nit: 2021

2021-01-26 20:37 UTC, jelderton approved these changes

2021-01-27 05:03 UTC, woody-apple commented
@kghost can you take a peek at merge conflicts?

2021-01-27 05:10 UTC, woody-apple commented
@pan-apple Can you take a peek at this? These seem like changes beyond just a python binding.

2021-01-27 05:11 UTC, woody-apple commented on src/controller/python/chip-device-ctrl.py
> +        self.devCtrl = ChipDeviceCtrl.ChipDeviceController(112233)
Hardcoded number?

2021-01-27 05:12 UTC, woody-apple requested changes
@kghost can you sync up with @vivien-apple about how to code-gen the python platform from ZAP? Lots of this appears hand rolled, which I don't think is something we want to do.

2021-01-27 05:43 UTC, kghost commented
This PR includes #4019, the second commit is python binding part.

2021-01-27 17:53 UTC, pan-apple requested changes
@kghost , this PR is also bringing in Channel API, which seems unrelated to the purpose of this PR. Suggest using a separate PR for reviewing the Channel API.

2021-01-29 02:09 UTC, mspang commented on src/controller/python/chip/Device.py
> +        self.__dmLib = dmLib
What is dmLib?

(please rename this)

2021-01-29 02:09 UTC, mspang commented on src/controller/python/chip/Device.py
> +        pass
Pass not needed here.

2021-02-17 02:56 UTC, closed without merging