Align NFC URI format in Android CHIP Tool and nrfconnect firmware to the iOS.
project-chip/connectedhomeip pull request #4498
Opened 2021-01-26 12:19 UTC by kkasperczyk-no

#### Problem
There is a discussion on the CHIP-Specifications/connectedhomeip-spec#415 about need of replacing spaces with _ in the NFC URI, but it is not fixed yet. Currently iOS CHIP Tool is expecting _ characters, while other Android and nrfconnect platforms are still using spaces.

 #### Summary of Changes
* Added replacing _ with spaces in NFC payload for the Android CHIP Tool
* Added replacing spaces with _ in NFC payload for nrfconnect samples

 Fixes #4497

2021-01-26 17:33 UTC, rwalker-apple requested changes

2021-01-26 17:33 UTC, rwalker-apple commented on examples/lighting-app/nrfconnect/main/AppTask.cpp
> +    // TODO: Remove replacing spaces with _ after problem described in #415 will be fixed.
please file an issue in addition?

2021-01-26 17:33 UTC, rwalker-apple commented on examples/lock-app/nrfconnect/main/AppTask.cpp
> +    // TODO: Remove replacing spaces with _ after problem described in #415 will be fixed.
IBID

2021-01-26 17:33 UTC, rwalker-apple approved these changes

2021-01-26 18:06 UTC, andy31415 approved these changes

2021-01-27 05:01 UTC, woody-apple commented
@jelderton @saurabhst ?

2021-01-27 10:22 UTC, kkasperczyk-no commented on examples/lighting-app/nrfconnect/main/AppTask.cpp
> +    // TODO: Remove replacing spaces with _ after problem described in #415 will be fixed.
Right, done

2021-01-27 20:40 UTC, woody-apple approved these changes

2021-01-28 18:39 UTC, woody-apple commented
@hawk248 ?

2021-02-01 21:55 UTC, mspang approved these changes

2021-02-02 17:44 UTC, woody-apple commented
@jelderton @saurabhst @hawk248 ?

2021-02-02 17:44 UTC, saurabhst approved these changes

2021-02-02 17:52 UTC, merged