Add flashing bundles (tar.xz files) to releases
project-chip/connectedhomeip pull request #4569
Opened 2021-01-29 17:59 UTC by andy31415

#### Problem

Just having an elf/zip file is not as convenient for flashing. Releases should contain stand-alone flashable content (within reason - we cannot copy the entire SDK)

 #### Summary of Changes
 
 - Make EFR32 and ESP32 gn/make scripts generate a file containing 'what is needed for a flashable image'
 - Update the asset uploader python script and github workflow to upload such bundles instead of just the elf/s37 files
 
 This is part of #4532 . Still some items left to do (future PRs):
   - build 'release' versions instead of debug
   - Add any additional boards/builds to have a good coverage for testing

2021-01-29 21:39 UTC, bzbarsky-apple approved these changes

2021-01-29 21:39 UTC, bzbarsky-apple commented on examples/all-clusters-app/esp32/Makefile
> +# NOTE: ESP32 still depends on setting $IDF_PATH being set
```suggestion
# NOTE: ESP32 still depends on $IDF_PATH being set
```

2021-01-29 23:06 UTC, mspang requested changes

2021-02-01 14:13 UTC, kpschoedel approved these changes

2021-02-01 16:15 UTC, andy31415 commented on examples/lock-app/efr32/BUILD.gn
> +generated_file("lock_app_flashbundle") {
Updated. I updated the flashabke_executable to autogenerate flashbundle.

2021-02-01 19:48 UTC, mspang approved these changes

2021-02-02 14:46 UTC, andy31415 commented
@BroderickCarlin @saurabhst @jelderton @hawk248 ?

2021-02-02 17:52 UTC, woody-apple commented
@jelderton @saurabhst ?

2021-02-02 17:53 UTC, saurabhst approved these changes

2021-02-02 18:05 UTC, merged