Add Silabs SDK as a submodule for backward compatibility
project-chip/connectedhomeip pull request #4733
Opened 2021-02-08 18:16 UTC by jepenven-silabs

#### Problem
EFR32 examples doesn't build with a newer version of OpenThread

 #### Summary of Changes
Add Silabs SDK as a submodule for later upgrade. This will prevent any build failure when updating to a newest version

 Partial Fix of #4527

2021-02-08 19:42 UTC, mspang requested changes

2021-02-08 19:42 UTC, mspang commented on scripts/examples/gn_efr32_example.sh
> +sdk_root="$PWD/third_party/efr32_sdk/repo"
Please don't use PWD in our shell scripts as this will break them when running in other directories.

Set and use CHIP_ROOT instead.

2021-02-08 19:42 UTC, mspang commented on scripts/examples/gn_efr32_example.sh
> +    gn gen --check --fail-on-unused-args --root="$1" --args="efr32_sdk_root=\"$sdk_root\"" "$2"/"$EFR32_BOARD"/
Can we not just remove the efr32_sdk_root argument now?

2021-02-08 19:51 UTC, woody-apple approved these changes
Approving pending @mspang

2021-02-08 19:55 UTC, mspang approved these changes

2021-02-09 14:45 UTC, jepenven-silabs commented
@saurabhst @BroderickCarlin @hawk248  ?

2021-02-10 17:43 UTC, jepenven-silabs commented
@jelderton @chrisdecenzo ?

2021-02-10 18:55 UTC, woody-apple commented
@saurabhst ?

2021-02-10 18:56 UTC, saurabhst approved these changes

2021-02-10 19:02 UTC, woody-apple commented
Looks like comments are resolved, merging.

2021-02-10 19:02 UTC, merged