Revise PacketBufferWriter interface
project-chip/connectedhomeip pull request #4874
Opened 2021-02-16 15:20 UTC by kpschoedel

#### Problem

The `PacketBufferWriter` constructor that takes a size and allocates the
`PacketBuffer` internally is awkward for some cases, and useless for the
case of an existing `PacketBufferHandle`.

#### Summary of Changes

- `PacketBufferWriter()` takes ownership of an existing `PacketBufferHandle`
  (same as `PacketBufferTLVWriter`).
- Added a `Finalize()` overload that matches that of `PacketBufferTLVWriter`.

2021-02-16 15:54 UTC, kpschoedel commented on src/system/SystemPacketBuffer.h
> +    PacketBufferWriterBase(System::PacketBufferHandle && aPacket) : Writer(aPacket->Start(), aPacket->AvailableDataLength())
Looks like this still needs a length (possibly optional; checking the cases), for the case that the pool-backed buffer is actually larger than requested.

2021-02-16 15:59 UTC, mspang approved these changes

2021-02-16 16:01 UTC, bzbarsky-apple requested changes
I'm OK with a followup for the MessagePacketBuffer bits, so that we don't combine behavior changes with refactoring in a single PR.  Up to you.

But we do need to sort out the way we get the pointer+length out of the buffer.

2021-02-16 16:01 UTC, bzbarsky-apple commented on src/transport/NetworkProvisioning.cpp
> +    Encoding::LittleEndian::PacketBufferWriter bbuf(System::PacketBufferHandle::New(credentialSize));
This should be a `MessagePacketBuffer` too.

2021-02-16 16:06 UTC, kpschoedel commented on src/system/SystemPacketBuffer.h
> +     * This signature matches `PacketBufferTLVWriter::Finalize()`.
The original signature is more useful in practice; almost all Writer users immediately pass the buffer somewhere else.

2021-02-16 16:14 UTC, bzbarsky-apple commented on src/system/SystemPacketBuffer.h
> +     * This signature matches `PacketBufferTLVWriter::Finalize()`.
OK, but why add the new one then?

2021-02-16 16:40 UTC, kpschoedel commented on src/protocols/bdx/BdxTransferSession.cpp
> +    ::chip::Encoding::LittleEndian::PacketBufferWriter bbuf(::chip::System::PacketBufferHandle::New(msgDataSize));
I'll add them here so they don't get overlooked.

2021-02-16 16:41 UTC, kpschoedel commented on src/system/SystemPacketBuffer.h
> +    PacketBufferWriterBase(System::PacketBufferHandle && aPacket) : Writer(aPacket->Start(), aPacket->AvailableDataLength())
Correct, I started off intended the former, but I think the latter is more useful.

2021-02-16 16:41 UTC, kpschoedel commented on src/system/SystemPacketBuffer.h
> +     * This signature matches `PacketBufferTLVWriter::Finalize()`.
Consistency with `PacketBufferTLVWriter` seemed like a good idea at the time.

2021-02-16 18:18 UTC, bzbarsky-apple approved these changes

2021-02-16 18:18 UTC, bzbarsky-apple commented on src/protocols/bdx/BdxTransferSession.cpp
> +    ::chip::Encoding::LittleEndian::PacketBufferWriter bbuf(chip::MessagePacketBuffer::New(msgDataSize));
Should this also pass `msgDataSize` as second arg?  Or document why we don't care if this overallocates?

2021-02-16 22:39 UTC, msandstedt approved these changes

2021-02-17 00:01 UTC, woody-apple approved these changes

2021-02-17 00:01 UTC, merged