make pretty in efr32
project-chip/connectedhomeip pull request #490
Opened 2020-04-23 20:58 UTC by rwalker-apple

#### Problem
 missing newline on a couple files

 #### Summary of Changes
 newlines

2020-04-23 21:00 UTC, gerickson approved these changes

2020-04-23 22:06 UTC, jelderton approved these changes

2020-04-23 23:26 UTC, woody-apple requested changes
Why doesn't restyle catch this? Can we make it do so?

2020-04-24 01:56 UTC, BroderickCarlin approved these changes

2020-04-24 02:04 UTC, gerickson approved these changes

2020-04-28 14:40 UTC, gerickson approved these changes

2020-04-28 18:48 UTC, woody-apple approved these changes

2020-04-28 18:48 UTC, merged