[mdns] fix esp32 mdns publish error with platform implementation
project-chip/connectedhomeip pull request #5154
Opened 2021-03-04 10:54 UTC by gjc13

#### Problem
The mdns module cannot be initialized until the ESP32 is connected to
the wifi network.

 #### Summary of Changes

* Fix various build errors and warnings
* Move mdns initialization to `Start()`
* Advertise CHIP services in the server until the advertiser has been
  started

 Fixes #<<<<<FILL ME IN  - issue number(s). If no issue, please create one>>>>>

fixes https://github.com/project-chip/connectedhomeip/issues/5076

2021-03-04 10:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=5154) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=5154) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=5154) it.</sub>

2021-03-04 13:21 UTC, andy31415 commented on src/lib/mdns/Advertiser.h
> +    /// Must be called before Advertise() calls.
This conflicts with the implementation in server/Mdns.cpp: there we do a Start followed by Advertise

2021-03-04 13:23 UTC, andy31415 commented on src/lib/mdns/Discovery_ImplPlatform.cpp
> +    CHIP_ERROR error = CHIP_NO_ERROR;
can we delete this line and `return CHIP_NO_ERROR` as the final return instead?

2021-03-04 14:07 UTC, andy31415 approved these changes

2021-03-05 03:17 UTC, saurabhst approved these changes

2021-03-05 03:23 UTC, mspang approved these changes

2021-03-05 03:49 UTC, bzbarsky-apple requested changes, later dismissed

2021-03-05 03:49 UTC, bzbarsky-apple commented on src/lib/mdns/Discovery_ImplPlatform.cpp
> +        ChipMdnsInit(HandleMdnsInit, HandleMdnsError, this);
Why are we no longer checking the return value here?

2021-03-05 03:49 UTC, bzbarsky-apple commented on src/lib/mdns/Discovery_ImplPlatform.cpp
> +CHIP_ERROR DiscoveryImplPlatform::GenerateRotatingDeviceId(char rotatingDeviceIdHexBuffer[], size_t & rotatingDeviceIdHexBufferSize)
Why this change?

2021-03-09 12:41 UTC, kedars approved these changes

2021-03-09 22:56 UTC, woody-apple approved these changes

2021-03-09 23:00 UTC, merged