Add chip-repl support for darwin for device scanning
project-chip/connectedhomeip pull request #5229
Opened 2021-03-08 19:27 UTC by andy31415

#### Problem
chip-repl supports device scanning only for Linux.

 #### Summary of Changes
Add a darwin implementation.

2021-03-08 20:47 UTC, mspang requested changes

2021-03-08 20:47 UTC, mspang commented on src/controller/python/BUILD.gn
> +      print("!!! WARNING: no BLE implementation for the current OS !!!")
assert(false, "No BLE implementation for the current OS")

2021-03-09 22:51 UTC, woody-apple approved these changes

2021-03-10 01:00 UTC, msandstedt approved these changes

2021-03-10 04:47 UTC, mspang approved these changes

2021-03-10 04:47 UTC, merged