Allow the ESP32 example to use a pre-configured WiFi Network
project-chip/connectedhomeip pull request #567
Opened 2020-05-01 20:56 UTC by sagar-apple

#### Problem
Testing the ESP32 echo server requires hopping onto the device's Soft-AP. 
This is a little bit inconvenient.

 #### Summary of Changes
The ESP32 Device Layer already supports connecting to a Network defined during the example's configure stage. Added documentation to show how to use that.

2020-05-01 21:08 UTC, gerickson requested changes

2020-05-01 21:27 UTC, saurabhst approved these changes

2020-05-01 21:37 UTC, BroderickCarlin approved these changes

2020-05-01 22:22 UTC, gerickson approved these changes

2020-05-02 21:27 UTC, rwalker-apple reviewed
awesome

2020-05-04 15:47 UTC, woody-apple approved these changes

2020-05-04 15:48 UTC, merged