Fix mbedTLS configuration for ESP32 platforms
project-chip/connectedhomeip pull request #577
Opened 2020-05-05 22:06 UTC by pan-apple

#### Problem
ESP32's `mbedTLS` configuration does not meet CHIP's crypto requirements. It does not contain `mbedtls_hkdf` function. Also, CHIP's configuration does not work for external `mbedTLS` library. For example, we cannot use ESP32 SDK's `mbedTLS` library with CHIP's crypto.

 #### Summary of Changes

- Fix CHIP's `configure.ac` to be able to link with external `mbedTLS`.
- Add missing functionality in ESP32's `mbedTLS` to CHIP.

fixes #576

2020-05-05 22:09 UTC, woody-apple approved these changes

2020-05-05 22:30 UTC, saurabhst approved these changes

2020-05-05 22:31 UTC, gerickson approved these changes

2020-05-05 22:54 UTC, dougsteed reviewed
HKDF implementation looks fine. Are there test vectors ?

2020-05-05 22:55 UTC, gerickson requested changes
I'd like to see us address the MBEDTLS_CONFIG_FILE issue before merging this.

2020-05-06 01:25 UTC, emargolis approved these changes

2020-05-06 13:31 UTC, gerickson approved these changes

2020-05-06 16:07 UTC, merged