[build] Addition of nlbuild-autotools based build system.
project-chip/connectedhomeip pull request #58
Opened 2020-03-14 08:26 UTC by turon

Adds enhanced autotools build system used by openthread and openweave projects:
* Package management: 'make dist' and 'make distcheck'
* Cross-platform handling: (Linux, Darwin, iOS, Android, embedded arm, etc.)
* Multiple compiler support: clang, GCC
* Integrates automated testing framework: 'make check'
* Code style enforcement: 'make pretty' and 'make pretty-check' integration with clang-format

2020-03-14 17:56 UTC, gerickson requested changes
Thanks for landing this change; great start! There are a number of things that need to be addressed before approving this.

2020-03-14 18:52 UTC, woody-apple requested changes
Can you also please update the GitHub Actions flow to make sure we're running all the builds needed? Thanks!

2020-03-16 22:16 UTC, gerickson approved these changes

2020-03-17 03:46 UTC, woody-apple approved these changes

2020-03-17 20:14 UTC, BroderickCarlin approved these changes

2020-03-17 21:36 UTC, merged