[cirque] Add cirque test for Python device controller
project-chip/connectedhomeip pull request #5851
Opened 2021-04-08 10:02 UTC by erjiaqing

#### Problem

This is a resubmit of #5317, with #5683 included

We are missing some tests for Python binding of chip device controller, this test adds them.

#### Summary of Changes
* Add cirque test for python device controller.
* Update log outputs for tests
* Wrap tests using gdb to catch potential crashes.

Fixes #4645

 Fixes #<<<<<FILL ME IN  - issue number(s). If no issue, please create one>>>>>

2021-04-08 10:38 UTC, Damian-Nordic approved these changes

2021-04-08 10:38 UTC, Damian-Nordic commented on src/controller/python/build-chip-wheel.py
> +            'chip.clusters',
it's already on the list

2021-04-08 10:38 UTC, Damian-Nordic commented on src/controller/python/test/Dockerfile
> +    apt-get install -y ca-certificates libglib2.0-dev avahi-daemon libavahi-client3 \
Consider using  `install --no-install-recommends` to only install necessary packages.

2021-04-09 03:42 UTC, yunhanw-google approved these changes

2021-04-13 13:16 UTC, msandstedt approved these changes

2021-04-13 15:47 UTC, mspang requested changes
Please don't copy artifacts (.whl files) to the source tree. You can copy source files into the output directory instead.

This process looks highly nondeterministic:
- copying files with wildcards
- recursive copies
- building dockers without cleaning up stale files
- load bearing "sleep 1" in startup scripts

2021-04-13 15:47 UTC, mspang commented on examples/lighting-app/linux/LightingManager.cpp
> +        std::cout << "LightingManager::InitiateAction(ON_ACTION)" << std::endl;
Why aren't we using the logging APIs here?

2021-04-19 06:29 UTC, erjiaqing commented
> Please don't copy artifacts (.whl files) to the source tree. You can copy source files into the output directory instead.
> 
> This process looks highly nondeterministic:
> 
> * copying files with wildcards

- Resolved

> * recursive copies

- Resolved

> * building dockers without cleaning up stale files

- This image is local use only

> * load bearing "sleep" calls all over the place

- Removed since most of related feature is implemented, with a note about `EnableNetwork`

2021-04-20 04:35 UTC, mspang commented on src/controller/python/test/mobile-device-test.py
> +from optparse import OptionParser, OptionValueError
nit: This is deprecated, please use `argparse`

2021-04-20 04:35 UTC, mspang commented on src/test_driver/linux-cirque/helper/CHIPTestBase.py
> +    def wait_for_device_output(self, device_id, pattern, timeout = 1):
Can we stream the log output so we don't have to re-read it on a 1s delay ?

2021-04-20 06:28 UTC, mspang approved these changes

2021-04-20 14:13 UTC, LuDuda approved these changes
This is great. Looking forward to having it as a part of our CI asap! 👍

2021-04-20 18:18 UTC, merged