Use Network Provisioning for both chip-tool and ChipTool iOS
project-chip/connectedhomeip pull request #5990
Opened 2021-04-13 23:52 UTC by yufengwangca

#### Problem
 <<<<<FILL ME IN - the issue this PR is intended to address>>>>>

 #### Summary of Changes
 <<<<<FILL ME IN - what's in this PR>>>>>

 Fixes #<<<<<FILL ME IN  - issue number(s). If no issue, please create one>>>>>

2021-04-15 01:34 UTC, woody-apple approved these changes

2021-04-15 01:36 UTC, saurabhst approved these changes

2021-04-15 09:38 UTC, vivien-apple commented on examples/chip-tool/commands/pairing/PairingCommand.h
> +    chip::EndpointId mEndpointId = 1;
Looking at #6000 I guess `1` should be replaced by `0` if #6000 lands before this one.

2021-04-15 16:59 UTC, woody-apple requested changes
Per @vivien-apple 's feedback

2021-04-15 17:16 UTC, yufengwangca commented
> Per @vivien-apple 's feedback

I will wait for #6000 land and make the change

2021-04-19 18:24 UTC, yufengwangca commented
> > Per @vivien-apple 's feedback
> 
> I will wait for #6000 land and make the change

@vivien-apple @woody-apple updated, pls check

2021-04-19 22:45 UTC, woody-apple approved these changes

2021-04-20 02:05 UTC, jmartinez-silabs approved these changes

2021-04-20 07:01 UTC, merged