e2e commissioning flow using chip tool
project-chip/connectedhomeip pull request #6084
Opened 2021-04-16 02:00 UTC by jpk233

#### Problem
There's currently no end to end demonstration of device commissioning using CASE

 #### Summary of Changes
- Adds logic for full commissioning flow: PASE - Attestation - Operation Cert - CASE
- Updates chip tool with additional CLI commands to initiate each step of commissioning

Commands added / demo steps (Using chip tool and lighting app):

./chip-tool pairing softap PASE [PIN] 3840 [IP of lighting app] 11097
./chip-tool commissioning attest
./chip-tool pairing softap CASE [PIN] 3840 [IP of lighting app] 11097
./chip-tool onoff read on-off 1
./chip-tool onoff toggle 1
./chip-tool onoff read on-off 1

2021-04-16 12:52 UTC, Damian-Nordic commented
Two intitial questions:
1. Is `libcertifier.so` file intentionally included in the diff?
2. `PASESession.h` has recently been moved to `protocols/secure_channel` and this diffs brings it back to `src/transport`. Is that required? If not, it would make the diff easier to read.

2021-04-16 15:13 UTC, jpk233 commented
> Two intitial questions:
> 
>     1. Is `libcertifier.so` file intentionally included in the diff?
> 
>     2. `PASESession.h` has recently been moved to `protocols/secure_channel` and this diffs brings it back to `src/transport`. Is that required? If not, it would make the diff easier to read.

1. No, that will get cleaned up so it's not included. Thanks.
2. This will be updated so it conforms with protocols/secure_channel, along with the other latest commits.

2021-04-16 17:24 UTC, pan-apple reviewed
@jpk233 , I have some posted some comments. I think it'll be easier to review the PR if there was a block diagram explaining the design (given the size of the PR).

2021-04-16 17:24 UTC, pan-apple commented on src/app/server/Server.cpp
> +        gNextAvailableAdminId = 0;
Why are we resetting the admins on CASE pairing? This will remove all previously paired admins on the device.

2021-04-16 17:24 UTC, pan-apple commented on src/app/server/Server.cpp
> +    if (resetAdmins == ResetAdmins::kYes)
Why do we want to reset the current admin table while we are opening the pairing window for PASE.

2021-04-16 17:24 UTC, pan-apple commented on src/app/server/Server.cpp
> +static CHIP_ERROR OpenCertificatePairingWindow(ResetAdmins resetAdmins, OperationalCredentialSet * opCredSet)
I am not 100% clear on what `OpenCertificatePairingWindow` is conveying. Does it mean the CASE based pairing window can be closed at some point? Once, the operational credentials are provisioned on the device, it should always be available for a CASE based session (as long as the limit of active sessions has not reached).

For PASE, pairing window makes sense, as the device is not available for provisioning all the time. Once the first pairing is complete, the first fabric admin has to open the pairing window to allow further PASE pairings.

2021-04-16 17:24 UTC, pan-apple commented on src/messaging/ExchangeContext.cpp
> +CHIP_ERROR ExchangeContext::OnAttestedDevice(SecureSessionHandle session, OperationalCredentialSet * opCredSet,
I don't think that `ExchangeContext` should be aware of specifics of device attestation. The message handling of specific types should be one layer above exchange context.

2021-04-16 17:24 UTC, pan-apple commented on src/messaging/ExchangeDelegate.h
> +    virtual void OnReceiveCredentials(SecureSessionHandle session, SecureSessionMgr * mgr, OperationalCredentialSet * opCredSet,
I don't think `OnReceiveCredentials` should be a callback in the Exchange Delegate. The layer above should receive the message via `OnMessageReceived` and process it to figure out that it contains the credentials.

2021-04-16 17:25 UTC, pan-apple commented
> #### Problem
> There's currently no end to end demonstration of device commissioning using CASE
> 
> #### Summary of Changes
> * Adds logic for full commissioning flow: PASE - Attestation - Operation Cert - CASE
> * Updates chip tool with additional CLI commands to initiate each step of commissioning
> 
> Commands added / demo steps (Using chip tool and lighting app):
> 
> ./chip-tool pairing softap PASE [PIN] 3840 [IP of lighting app] 11097
> ./chip-tool commissioning attest
> ./chip-tool pairing softap CASE [PIN] 3840 [IP of lighting app] 11097
> ./chip-tool onoff read on-off 1
> ./chip-tool onoff toggle 1
> ./chip-tool onoff read on-off 1

`./chip-tool pairing softap CASE [PIN] 3840 [IP of lighting app] 11097` should not require a PIN.

2021-04-17 17:17 UTC, bzbarsky-apple reviewed
This seems to be a mix of functional changes and various organizational/cleanup changes, along with some apparent merge problems.  For example, this PR adds  src/app/clusters/on-off-server/on-off.cpp which seems to be a copy of  src/app/clusters/on-off-server/on-off-server.cpp for no obvious reason, undoes some file moves as described above, etc.

Ideally we should have separate PRs for cleanup and for functional changes.  Within the functional change PR, ideally we shoud have separate changesets for the manual changes and the changes due to rerunning codegen.

As things stand, reviewing this in a sane way that might actually be useful will be _extremely_ difficult.

2021-04-17 17:17 UTC, bzbarsky-apple requested changes
See above for changes needed.

2021-04-19 12:57 UTC, hawk248 commented
> > #### Problem
> > There's currently no end to end demonstration of device commissioning using CASE
> > #### Summary of Changes
> > 
> > * Adds logic for full commissioning flow: PASE - Attestation - Operation Cert - CASE
> > * Updates chip tool with additional CLI commands to initiate each step of commissioning
> > 
> > Commands added / demo steps (Using chip tool and lighting app):
> > ./chip-tool pairing softap PASE [PIN] 3840 [IP of lighting app] 11097
> > ./chip-tool commissioning attest
> > ./chip-tool pairing softap CASE [PIN] 3840 [IP of lighting app] 11097
> > ./chip-tool onoff read on-off 1
> > ./chip-tool onoff toggle 1
> > ./chip-tool onoff read on-off 1
> 
> `./chip-tool pairing softap CASE [PIN] 3840 [IP of lighting app] 11097` should not require a PIN.

Yes - they are not needed .. ramnants of existing `chip-tool` syntax. We will update `chip-tool` to remove them from command line.

2021-04-28 12:13 UTC, jpk233 commented
Going to be closing this and splitting the changes into multiple smaller PRs, as per suggestions from bzbarsky-apple

2021-04-28 12:13 UTC, closed without merging