[linux] Land the First (1st) of Nine (9) Phases for the Linux DeviceLayer Adapation
project-chip/connectedhomeip pull request #614
Opened 2020-05-08 20:57 UTC by turon

Clean version of Linux DeviceLayer with no OSAL dependency.

- Adds initial Device Layer for Linux.
- Provides main select loop with event post/dispatch handling.
- Uses SystemLayer Sockets.
- Entropy and time implementations.
- Stub out ble, connectivity, and configuration / storage for follow-on PR.
- Uses pthreads for mutex and tasks.
- Uses std::chrono for monotonic system time.
- Include unit test to validate platform time (currently posix specific).

2020-05-20 23:32 UTC, woody-apple requested changes
@rwalker-apple @sagar-apple @pan-apple @bhaskar-apple @shana-apple ?

2020-05-21 00:53 UTC, woody-apple requested changes

2020-05-21 18:24 UTC, gerickson approved these changes

2020-05-21 23:31 UTC, bhaskar-apple reviewed
LGTM

2020-05-26 16:58 UTC, woody-apple approved these changes

2020-05-26 17:11 UTC, jelderton approved these changes

2020-05-26 22:43 UTC, merged