[chip-tool] change default endpoint 1 for networkcommissioning cluster
project-chip/connectedhomeip pull request #6392
Opened 2021-04-30 02:44 UTC by wissn84

#### Problem
chip-tool(example) can't pairing to chip-lighting app because of invalid endpoint 

 #### Summary of Changes
chip-lighting-app use endpoint 1 but chip-tool use endpoint 0 by default.
So I have changed to endpoint 1 because.
 
Fixes #6391

2021-04-30 02:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=6392) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=6392) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=6392) it.</sub>

2021-04-30 18:04 UTC, woody-apple approved these changes

2021-05-05 05:36 UTC, woody-apple requested changes
per @vivien-apple can you update the endpoint ID here? thanks!

2021-05-10 18:43 UTC, woody-apple commented
@wissn84 There are conflicts, plus can you update this per @vivien-apple ?

2021-05-11 02:31 UTC, wissn84 commented
@woody-apple  Hi, Sorry for late response.
As you know that All Samples use endpoint 1 in CHIP. 
If changed default endpoint 0 , every sample code and description(README) shall be changed.

2021-05-13 22:59 UTC, woody-apple commented
> @woody-apple Hi, Sorry for late response.
> As you know that All Samples(all-clusters and lighting ,, etc..) use endpoint 1.
> If endpoint change 0 , every sample code and description(README) will shall be changed.

That's correct, @vivien-apple is pointing out we should use the correct endpoint everywhere.

2021-05-20 18:39 UTC, woody-apple requested changes
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-06-03 22:54 UTC, closed without merging