Added missing Network Commissioning cluster to the EFR32 Window Covering example
project-chip/connectedhomeip pull request #6467
Opened 2021-05-04 20:01 UTC by ricardo-casallas

#### Problem
The EFR32 Window Covering example is missing the Network Commissioning and Basic clusters. In consequence, zcl NetworkCommissioning returns EMBER_ZCL_STATUS_UNSUPPORTED_CLUSTER.

 #### Summary of Changes
* Added Basic, and Network Commissioning clusters to examples/window-app/common/window-app.zap
* Auto-generated code re-generated using ./scripts/tools/zap_regen_all.py

 Fixes #6466

2021-05-04 20:08 UTC, woody-apple approved these changes

2021-05-04 21:54 UTC, jmartinez-silabs requested changes

2021-05-04 21:54 UTC, jmartinez-silabs commented on examples/window-app/common/window-app.zap
> +      "path": "../../../../../../../../git/chip/main/src/app/zap-templates/zcl/zcl.json",
There is an issue with those paths, here and Line 27, as they are relative to your setup.

2021-05-05 12:30 UTC, jmartinez-silabs approved these changes

2021-05-05 15:45 UTC, msandstedt approved these changes

2021-05-07 15:39 UTC, andy31415 approved these changes

2021-05-07 15:39 UTC, merged