Revert "Zap uint16 t for attribute store"
project-chip/connectedhomeip pull request #6509
Opened 2021-05-05 22:07 UTC by yunhanw-google

Reverts project-chip/connectedhomeip#6446

Cirque device controller test is broken since this PR, in addition, real device controller test with real device is also broken since this PR. It seems this PR has been forcily merged after 3 tries on cirque tests

2021-05-05 22:24 UTC, woody-apple requested changes
Per discussion - @yunhanw-google - Let's investigate why/where the the python controller is mixing up this type instead of reverting spec compliant sizes, that pass cluster automation tests.

2021-05-05 22:28 UTC, yunhanw-google commented
per chat @woody-apple , would hold on this revert until @vivien-apple figure out next step, thanks

2021-05-05 23:49 UTC, yunhanw-google commented
https://github.com/project-chip/connectedhomeip/commit/30daae2b38d8c07c5797f073942113b774f8f299
https://github.com/project-chip/connectedhomeip/commit/ea5b53b598d55f1fb32b2dca7c3a6e32ab924bdc
https://github.com/project-chip/connectedhomeip/commit/6a4fdaad4fdfa0c4dd26abcb0dfc5e82f891a31b
there 3 commits are broken cirque test regarding device controller for cluster validation, and real device controller against real device,  you can manually trigger it via your github action

2021-05-06 19:58 UTC, vivien-apple commented
Closing per #6531

2021-05-06 19:58 UTC, closed without merging