ESP32: Add fixes for lock-app
project-chip/connectedhomeip pull request #6658
Opened 2021-05-11 05:22 UTC by sweetymhaiske

#### Problem
 Add missing fixes for lock-app ESP32.

 #### Summary of Changes
 1. Added missing cluster ID and endpoint ID check for on-off cluster.
 2. Make lock-app as minimal as possible hence removed M5Stack support.

2021-05-11 06:20 UTC, saurabhst approved these changes

2021-05-13 16:55 UTC, woody-apple commented
/rebase

2021-05-14 07:24 UTC, bzbarsky-apple approved these changes

2021-05-14 21:38 UTC, woody-apple commented
Removing WIP title so Pull Approve is happy, this appears ready?

2021-05-14 21:39 UTC, woody-apple commented
@msandstedt @andy31415 ?

2021-05-15 03:03 UTC, dhrishi commented
>Removing WIP title so Pull Approve is happy, this appears ready?

@woody-apple  I think a few changes are pending. Should we move it back to WIP, so that it isn't merged?

2021-05-15 15:54 UTC, msandstedt approved these changes

2021-05-17 14:18 UTC, andy31415 approved these changes

2021-05-17 18:26 UTC, woody-apple commented
Marking this as a draft given it's WIP then :) Please un-draft it when you're ready!

2021-05-18 14:44 UTC, jelderton approved these changes

2021-05-19 13:14 UTC, andy31415 commented
Please add a section in the summary for how this was tested - what steps/tools did you use to validate the functioonality update?

2021-05-20 15:16 UTC, andy31415 commented
@sweetymhaiske - this is almost ready to go in. Please update the PR summary with a 'how did you test this' section before we can merge.

2021-05-20 18:37 UTC, woody-apple requested changes, later dismissed
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-05-21 09:52 UTC, sweetymhaiske commented
> Per the updated template, can you update the PR here?
> 
> ```
> #### Problem
> What is being fixed?  Examples:
> * Fix crash on startup
> * Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).
> 
> #### Change overview
> What's in this PR
> 
> #### Testing
> How was this tested? (at least one bullet point required)
>     • If unit tests were added, how do they cover this issue?
>     • If unit tests existed, how were they fixed/modified to prevent this in future?
>     • If integration tests were added, how do they verify this change?
>     • If manually tested, what platforms controller and device platforms were manually tested, and how?
>     • If no testing is required, why not?
> ```

Done

2021-05-21 13:34 UTC, sweetymhaiske commented
> @sweetymhaiske - this is almost ready to go in. Please update the PR summary with a 'how did you test this' section before we can merge.

Done

2021-05-24 07:56 UTC, dhrishi commented
@sweetymhaiske  Is there anything pending here?

2021-05-24 07:57 UTC, sweetymhaiske commented
> @sweetymhaiske Is there anything pending here?

No.

2021-05-25 14:29 UTC, dhrishi commented
@woody-apple  Can you please take a look?

2021-05-27 13:54 UTC, merged