Add CHIP's controller API and update the standalone example to use it
project-chip/connectedhomeip pull request #666
Opened 2020-05-12 19:55 UTC by sagar-apple

#### Problem
Need a skeleton controller API upon which we can start building controller specific platform APIs(for iOS/macOS/Android for example). 

 #### Summary of Changes
Implemented a barebones "controller" API and updated the Standalone Echo Client to use it.
 
The API is very limited at this early stage but later it will be expanded to add more controller specific functionality. 

fixes https://github.com/project-chip/connectedhomeip/issues/665

2020-05-12 20:56 UTC, woody-apple approved these changes

2020-05-12 21:13 UTC, bhaskar-apple submitted a review, later dismissed

2020-05-13 03:12 UTC, gerickson requested changes
Some mostly mechanical changes to make; however, overall, looks good. I'll pend my final approval on approval @andy31415.

2020-05-14 03:02 UTC, andy31415 approved these changes

2020-05-14 03:03 UTC, gerickson approved these changes

2020-05-14 03:35 UTC, merged