[build] add 'make docdist' to build doxygen.
project-chip/connectedhomeip pull request #668
Opened 2020-05-12 22:02 UTC by turon

Adds support for building doxygen documentation from sources using `make docdist`.

Note: nlbuild-autotools currently requires the documentation directory be named 'doc' rather than 'docs'.

fixes #663

2020-05-12 22:08 UTC, gerickson requested changes
Please eliminate the directory name change.

2020-05-12 22:14 UTC, woody-apple requested changes

2020-05-13 00:13 UTC, gerickson reviewed
Overall, looks good; just a few minor issues. Thanks for tackling this!

2020-05-13 00:23 UTC, woody-apple approved these changes

2020-05-13 17:48 UTC, gerickson approved these changes

2020-05-13 17:51 UTC, jelderton approved these changes

2020-05-13 19:23 UTC, merged