Build is failing on Darwin
project-chip/connectedhomeip pull request #6717
Opened 2021-05-12 12:13 UTC by lazarkov

#### Problem
The gn_build.sh is failing on Mac OS

#### Summary of Changes
- Updated the CHIPClustersObjc.mm file
- Updated the LockTracker.h file

#### Test
Used the ./gn_build.sh to verify the building is successful

2021-05-12 13:24 UTC, bzbarsky-apple approved these changes

2021-05-12 13:26 UTC, bzbarsky-apple requested changes
Wait, no, this is not right.  I assumed this had regenerated the file after some mis-merge, but this is a hand-edit of the generated file, looks like.  The fix needs to be in the generation template.

2021-05-12 13:27 UTC, vivien-apple commented
The fix is to update the templates. It looks like the code has been hand rolled here. I have included the fix into: https://github.com/project-chip/connectedhomeip/pull/6596/commits/9b8a43a8076c1ea0add6fd2b245dfca314c0fd90

2021-05-12 13:33 UTC, lazarkov commented
@bzbarsky-apple Updated the PR and removed the generated code chage

2021-05-12 13:42 UTC, bzbarsky-apple approved these changes

2021-05-12 15:07 UTC, andy31415 approved these changes
We should figure out a way to have darwin also be able to do lock tracking.
Why does darwin not have a CONFIG_H ?

2021-05-12 15:09 UTC, andy31415 reviewed
Does the lock tracking still work at least in linux after this?

Since this is using #ifdefs and not having locking enabled is an acceptable result, I am concerned that this can silently remove the tracking.

2021-05-12 15:32 UTC, andy31415 requested changes
Switching to requested changes: I believe this is more likely to silently remove lock tracking on all platforms. We should figure out why the generated file is not properly listed as a dependency instead.

2021-05-12 16:05 UTC, jmartinez-silabs approved these changes

2021-05-12 20:33 UTC, andy31415 commented
Please try #6748 instead

2021-05-13 20:17 UTC, woody-apple commented
Doesn't appear to be needed anymore, after @andy31415 's changes. Closing - but please re-open if that's incorrect!

2021-05-13 20:17 UTC, closed without merging