CHIPDeviceController::StopPairing does not stop pairing
project-chip/connectedhomeip pull request #6752
Opened 2021-05-12 22:16 UTC by vivien-apple

#### Problem
 
`ChipDeviceController::StopPairing` does not stop pairing anymore. Likely a regression from the shift to the `Network Provisioning` cluster.

2021-05-12 22:42 UTC, woody-apple approved these changes

2021-05-12 22:58 UTC, woody-apple requested changes
@sagar-apple is having issues with this patch and pairing..

2021-05-12 23:36 UTC, sagar-apple commented on src/controller/CHIPDeviceController.cpp
> +    mPairingSession.Clear();
I'm seeing Error 6007 with this PR

2021-05-20 18:37 UTC, woody-apple requested changes
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-06-03 03:40 UTC, woody-apple commented
/rebase

2021-06-03 03:41 UTC, woody-apple commented
@vivien-apple ?

2021-06-04 23:59 UTC, woody-apple commented
/rebase

2021-06-16 04:09 UTC, woody-apple commented
/rebase

2021-06-17 01:38 UTC, woody-apple commented
/rebase

2021-07-01 03:06 UTC, closed without merging