Allow sending IM commands to different peer key id
project-chip/connectedhomeip pull request #6768
Opened 2021-05-13 05:26 UTC by cecille

Chip device has a session open with a device, and that device may
or may not have a key id of 0. The IM command sender assumes a key
of 0 and creates a new exchange using that key. It then fails to
find that peer session becuase the keys don't match. Instead,
allow chip device to pass in its own exchange context. Function
defaults to null, which will create the exchange context with key
0 as normal for other use cases.

 #### Problem
IM command sender assumes the peer has a key id of 0. This is not always the case and the device has proper information about the peer's key.

 #### Summary of Changes
Adds a function parameter to the SendCommand function so the device can pass along its exchange context with the proper values set. Nullptr default will cause a new exchange context with a key of 0 to be created.

 Fixes #6767

2021-05-13 13:14 UTC, msandstedt approved these changes

2021-05-13 14:33 UTC, tcarmelveilleux approved these changes

2021-05-13 15:36 UTC, andy31415 approved these changes

2021-05-13 16:53 UTC, woody-apple commented
/rebase

2021-05-13 17:19 UTC, mrjerryjohns commented on src/controller/CHIPDevice.cpp
> +    Messaging::ExchangeContext * exchange = mExchangeMgr->NewContext(mSecureSession, mCommandSender);
This seems counter to how I thought this whole scheme works - controllers shouldn't have to pass in secure session handles to IM objects. Rather, they should be passing in a logical encapsulation of their destination, which could be a NodeId (in the case of CASE), or, a passcode (in the case of PASE) or, a group (which selects a group key).

The allocation of the exchange should then automatically figure out the 'right' secure session over which to allocate the exchange into.

2021-05-13 18:31 UTC, yufengwangca commented on src/app/CommandSender.cpp
> +        mpExchangeCtx = mpExchangeMgr->NewContext({ aNodeId, 0, aAdminId }, this);
We should pass the correct sessionHandle you received on session establishment

2021-05-13 18:39 UTC, cecille commented
From convo with Jerry and Yufeng and Yunhan - going to change the function parameter to pass the session handle as a pointer, and leave the exchange context allocation inside the command handler. Will retain the default nullptr value for now to avoid breaking tests and open an issue to revisit.

2021-05-13 22:25 UTC, yunhanw-google approved these changes

2021-05-13 22:38 UTC, woody-apple requested changes
Holding, pending @pan-apple taking a look at this. Not sure I love the layering change here...

2021-05-14 00:22 UTC, yunhanw-google commented
> Holding, pending @pan-apple taking a look at this. Not sure I love the layering change here...
Thanks for comments here. Agree. This layer is not looking good, I would argue this would be another temporary change to unblock commisioning work. Jerry and I prefer having channel to encapsulate all sorts of configuration here, but channel is too heavy from code, occupy 50% from message layer, so @pan-apple has decoupled it from example code.
@mrjerryjohns and I would like to have a meeting with @bzbarsky-apple @pan-apple @yufengwangca @tcarmelveilleux to further discuss the message layer including exchange manager, transport, secure session, channel, I think we have reached the time where we need clearly depict the right layering/architecture for final 1.0 message layer.

2021-05-14 15:05 UTC, pan-apple approved these changes

2021-05-14 16:00 UTC, woody-apple approved these changes

2021-05-14 16:31 UTC, merged