Add Telink docker image
project-chip/connectedhomeip pull request #6872
Opened 2021-05-17 12:30 UTC by rikorsev

**Problem**

To integrate and validate Telink port of CHIP, docker images are required to build the examples in the Github workflow.
Like other docker images used by this repository, they should be available in the connectedhomeip docker hub.

**Summary of Changes**

Telink docker image build files are located integrations/docker/images/chip-build-telink.

2021-05-17 14:02 UTC, andy31415 approved these changes

2021-05-17 14:44 UTC, woody-apple approved these changes

2021-05-17 15:43 UTC, jmartinez-silabs approved these changes

2021-05-17 17:51 UTC, woody-apple requested changes
Please collapse RUN statements like other docker images into one :)

2021-05-17 17:51 UTC, woody-apple commented on integrations/docker/images/chip-build-telink/Dockerfile
> +RUN apt install -y git
Note: the reason for this is if you chain commands like this, it's a single docker image snapshot, vs each RUN in this one will create a snapshot for each - thus making the image size larger.

2021-05-18 08:35 UTC, rikorsev commented on integrations/docker/images/chip-build-telink/Dockerfile
> +RUN apt install -y git
Hi @andy31415 and @woody-apple 

Thanks for feedback! It will be fixed.

2021-05-19 11:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=6872) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=6872) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rikorsev<br/>:x: Alexandr Kolosov<br/><hr/>**Alexandr Kolosov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=6872) it.</sub>

2021-05-20 15:14 UTC, andy31415 commented
@woody-apple  for review?

@rikorsev - please add a 'how did you test this' section in the PR summary. In this case I believe building the docker image locally and eventually connecting to it via `run -it` and some path validation could be sufficient.

2021-05-20 18:34 UTC, woody-apple approved these changes

2021-05-20 18:35 UTC, merged

2021-07-03 01:15 UTC, mspang commented on integrations/docker/images/chip-build-telink/Dockerfile
> +# Below step will be removed in future.
ETA?