Update the zap template used for chip-tool to not forced the first le…
project-chip/connectedhomeip pull request #6930
Opened 2021-05-18 12:54 UTC by vivien-apple

…tter of arguments to be lower cased

 #### Problem

Followup to #6873  where arguments such as `CSRNonce` ends up as `cSRNonce`. 

 #### Summary of Changes
 * Update the template so it does not enforce the first letter to be lowercased

2021-05-18 15:50 UTC, msandstedt approved these changes

2021-05-19 14:34 UTC, andy31415 commented on examples/chip-tool/templates/commands.zapt
> +        AddArgument("{{asCamelCased label false}}", &m{{asCamelCased label false}});
For future PRs we may want to look into API readability: the false argument is not obvious in purpose. Maybe something like `startUpperCamelCase` and `startLowerCamelCase` methods would be more readable, although I find those namings awkward as well. Can these be chained? like `camelCase label | uppercaseFirstLetter`

2021-05-19 14:34 UTC, andy31415 approved these changes

2021-05-20 16:15 UTC, jelderton approved these changes

2021-05-20 18:28 UTC, woody-apple requested changes
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-05-21 05:26 UTC, bzbarsky-apple approved these changes

2021-06-04 06:43 UTC, bzbarsky-apple commented
@vivien-apple This is still relevant, right?

2021-06-16 04:09 UTC, woody-apple commented
/rebase

2021-06-17 01:38 UTC, woody-apple commented
/rebase

2021-06-25 16:40 UTC, vivien-apple commented
@woody-apple I have finally updated the template...

2021-06-25 16:47 UTC, msandstedt approved these changes

2021-06-25 19:27 UTC, woody-apple approved these changes

2021-06-25 19:28 UTC, merged