Add Software Diagnostics Cluster definition
project-chip/connectedhomeip pull request #6943
Opened 2021-05-18 16:08 UTC by yufengwangca

#### Problem
Add the Software Diagnostics cluster based on the CHIP-spec.

The specification of Software Diagnostics Cluster:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsSoftware.adoc

To help your review, I put all manual added code into the first commit. The rest of commits contain the changes either from the cluster GUI or codegen.

 #### Summary of Changes
Add Software Diagnostics Cluster definition

2021-05-18 23:25 UTC, jmartinez-silabs approved these changes

2021-05-19 12:48 UTC, saurabhst approved these changes

2021-05-19 23:02 UTC, msandstedt approved these changes

2021-05-20 16:00 UTC, andy31415 approved these changes

2021-05-20 17:30 UTC, jelderton approved these changes

2021-05-20 18:28 UTC, woody-apple requested changes, later dismissed
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-05-20 19:31 UTC, bzbarsky-apple reviewed
Commit message for first commit should have "definition", not "defination"

2021-05-20 20:40 UTC, LuDuda approved these changes

2021-05-20 21:49 UTC, merged