secure channel log should use secure channel tag
project-chip/connectedhomeip pull request #6954
Opened 2021-05-19 10:32 UTC by kghost

2021-05-20 15:47 UTC, andy31415 approved these changes

2021-05-20 15:57 UTC, saurabhst approved these changes

2021-05-20 16:27 UTC, tcarmelveilleux approved these changes

2021-05-20 17:59 UTC, jmartinez-silabs approved these changes

2021-05-20 18:29 UTC, woody-apple requested changes
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-05-20 20:26 UTC, LuDuda approved these changes

2021-05-21 14:59 UTC, andy31415 commented
@kghost regarding testing "This is a straightforward change, no extra test is needed." ... At least smoke test is required. I agree formal CI test is not required, however please run manually a smoke test and document it here. Like

`Ran .... and saw .... in the logs`. In your case this should prove that SecureChannel is indeed used in the logs as expected.

TLDR: "did not run tests beside compilation" is almost never acceptable. You should at least manually run an app to validate it starts up. You can rely on CI that it starts up but then you have to validate that CI logs show the change you expect.

2021-06-05 20:00 UTC, closed without merging