Error reporting cleanup
project-chip/connectedhomeip pull request #6979
Opened 2021-05-19 19:25 UTC by andy31415

#### Problem
OnReceiveError was reporting 'accept failure' and the 'received message from node...' was logged as an error

 #### Summary of Changes
 Expand the message for OnReceive error to  make it clear it is on receiving and to note from where the error came from.
 Switch the progress log to 'progress' instead of error.
 
 ####Testing
 
 Manually ran ble-wifi pairing on esp32 and watced logs with `./scripts/tools/esp32_log_cat.py`
 
 Saw:
 
 ```
 2021-05-19 15:21:36 /dev/ttyUSB0 INFO    I (16710) chip[IN]: Secure transport received message destined to node ID (12344321)
2021-05-19 15:21:36 /dev/ttyUSB0 INFO    I (16720) chip[EM]: Received message of type 8 and protocolId 327680
2021-05-19 15:21:36 /dev/ttyUSB0 INFO    I (16770) chip[IN]: Sending msg from 0x0000000000bc5c01 to 0x000000000001b669 at utc time: 16090 msec
2021-05-19 15:21:36 /dev/ttyUSB0 INFO    I (16780) chip[IN]: Sending secure msg on generic transport
2021-05-19 15:21:36 /dev/ttyUSB0 INFO    I (16780) chip[IN]: Secure msg send status No Error
2021-05-19 15:21:36 /dev/ttyUSB0 ERROR   E (16800) chip[EM]: Error receiving message from BLE: CHIP Error 4000047 (0x003D092F): Invalid argument
```

2021-05-19 19:26 UTC, andy31415 commented
The benefit of this now is: i see that the message counter mismatch occurs in BLE, which may be considered odd as BLE is point-to-point so nodes do not necesarely need to validate destination node id for every incoming message.

2021-05-19 19:26 UTC, saurabhst approved these changes

2021-05-19 21:14 UTC, tcarmelveilleux commented on src/transport/SecureSessionMgr.cpp
> +    ChipLogProgress(Inet, "Secure transport received message destined to node ID (%llu)",
```suggestion
    ChipLogProgress(Inet, "Secure transport received message destined to fabric %d node ID (%llu)", static_cast<int>(state->GetAdminId()),
```

2021-05-19 21:14 UTC, tcarmelveilleux approved these changes

2021-05-20 04:09 UTC, bzbarsky-apple approved these changes

2021-05-25 14:15 UTC, andy31415 commented
@Damian-Nordic @jepenven-silabs @mspang ?

2021-05-25 14:42 UTC, Damian-Nordic requested changes

2021-05-25 14:42 UTC, Damian-Nordic commented on src/messaging/ExchangeMgr.cpp
> +    char srcAddressStr[Transport::PeerAddress::kMaxToStringSize];
nit: might be worth guarding this code with `#if CHIP_ERROR_LOGGING` (not sure if it will be optimized out when logging is disabled).

2021-05-25 15:32 UTC, andy31415 commented on src/transport/SecureSessionMgr.cpp
> +                        static_cast<int>(state->GetAdminId()), packetHeader.GetDestinationNodeId().Value(),
Yes, bad merge. Trying again. Thanks for noticing.

2021-05-25 15:34 UTC, Damian-Nordic approved these changes

2021-05-26 12:16 UTC, merged