[qpg6100] Move extern alloc to ThreadStackManagerImpl
project-chip/connectedhomeip pull request #6990
Opened 2021-05-20 07:09 UTC by nikita-s-wrk

Move otPlatCAlloc and otPlatFree from Logging.cpp

2021-05-20 12:29 UTC, jmartinez-silabs approved these changes

2021-05-20 14:59 UTC, saurabhst approved these changes

2021-05-20 15:24 UTC, andy31415 commented
Please add a 'how did you test this' section to the PR summary.

2021-05-20 15:25 UTC, andy31415 approved these changes

2021-05-20 18:30 UTC, woody-apple requested changes
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-05-20 20:21 UTC, LuDuda approved these changes

2021-05-21 06:30 UTC, nikita-s-wrk commented
@woody-apple Updated PR description

2021-05-21 18:11 UTC, woody-apple approved these changes

2021-05-21 18:11 UTC, merged