Enable arc for chip-device-ctrl
project-chip/connectedhomeip pull request #6992
Opened 2021-05-20 10:34 UTC by vivien-apple

#### Problem
  ARC is not enabled for `chip-device-ctrl`

 #### Summary of Changes
 * Enable it if compiling on macOS.

2021-05-20 12:05 UTC, jmartinez-silabs approved these changes

2021-05-20 12:11 UTC, jmartinez-silabs commented
ARC did find some issues with the Darwin build. Can you push a fix for those build error?

2021-05-20 13:10 UTC, Damian-Nordic approved these changes

2021-05-20 18:30 UTC, woody-apple requested changes
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

2021-05-25 14:25 UTC, andy31415 approved these changes

2021-05-25 14:26 UTC, andy31415 commented
@woody-apple summary was updated according to the template

2021-06-02 16:47 UTC, mspang approved these changes

2021-06-03 03:44 UTC, woody-apple approved these changes

2021-06-03 03:45 UTC, merged