Update to officially assigned port number (5540) for Matter protocol
project-chip/connectedhomeip pull request #7020
Opened 2021-05-21 03:24 UTC by aronrosenberg

Update the code to use the new officially assigned port number (5540) from IANA. This tracks the spec change found at https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/3247

2021-05-21 03:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=7020) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/project-chip/connectedhomeip?pullRequest=7020) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/project-chip/connectedhomeip?pullRequest=7020) it.</sub>

2021-05-21 13:13 UTC, andy31415 approved these changes

2021-05-21 18:13 UTC, woody-apple requested changes
Please update the PR description to follow the standard template, which includes testing details, etc.

2021-05-21 18:20 UTC, aronrosenberg commented
This PR is in Draft mode until IANA formally issues the allocation. Once that confirmation is received, I will mark as ready for commiting.

2021-05-29 22:42 UTC, aronrosenberg commented
The IANA submission is still in progress.

2021-06-10 15:46 UTC, aronrosenberg commented
A clarification question was asked by the IESG expert which means their review is still in progress.

2021-06-16 04:08 UTC, woody-apple commented
/rebase

2021-06-17 04:00 UTC, turon commented on src/darwin/Framework/CHIPTests/CHIPClustersTests.m
> +const uint16_t kLocalPort = 5541;
Should this be an ephemeral port?

2021-06-17 04:00 UTC, turon approved these changes

2021-06-24 12:26 UTC, aronrosenberg commented
Feedback from IANA still in progress.

2021-07-08 14:54 UTC, closed without merging