Fix field id wild card representation
project-chip/connectedhomeip pull request #7064
Opened 2021-05-24 17:15 UTC by yunhanw-google

#### Problem
Per spec, 0xFF is used to represent the wildcard/all for FieldID in attributePath

#### Change overview
Update FieldId kRootFieldId value with 0xFF

#### Testing
Update the existing unit test with updated kRootFieldId

2021-05-24 17:20 UTC, saurabhst approved these changes

2021-05-24 18:24 UTC, msandstedt approved these changes

2021-05-24 18:27 UTC, bzbarsky-apple approved these changes

2021-05-24 18:33 UTC, bzbarsky-apple requested changes
Actually, two things:

1. When I back out the test change (but leave the code change) the test does not fail.  So this test does not seem to be testing the code change?
2. We should probably have a test that ensures that passing in field id 0 is _not_ a wildcard read.  Better yet would be having a test that tests, for the test cluster, that field ids 0 to whatever the max is get a data response, then field ids after that get an invalid field error, then 0xFF (written as a literal) gets the "all the data" response.

2021-05-26 01:06 UTC, jmartinez-silabs approved these changes

2021-06-09 09:52 UTC, closed without merging