Rename CHIPConnection to CHIPUdpExchange
project-chip/connectedhomeip pull request #711
Opened 2020-05-14 19:23 UTC by andy31415

Reasoning is that UDP is connectionless, so we use "exchange" to denote
exchanging messages.

Future CHIPConnection will actually handle connection protocols (tcp,
ble).

 #### Problem
Short version is "UDP is connectionless".
We are considering that several transports including UDP, TCP, BLE, ... are ok for exchanging requests and replies between devices, however a "connection" has additional meaning.

 #### Summary of Changes
Renames existing CHIPConnection to ChipUdpExchange.
Weave port of CHIPConnection does the connection bit (TCP and BLE) and will not replace this class. The weave message layer does support UDP however that will only come in once we have the exchange bits ported. Only at that time, an code merge & update can be feasable.

working towards #157 and #158.

2020-05-14 19:33 UTC, gerickson approved these changes
Seems innocuous if it supports a larger, later goal.

2020-05-15 01:14 UTC, turon approved these changes

2020-05-15 01:30 UTC, woody-apple requested changes
I thought per discussion we'd do this when the CHIPConnection + Managers above are in place, that would replace this?

Let's do this as a part of: https://github.com/project-chip/connectedhomeip/issues/157

2020-05-18 15:35 UTC, jelderton approved these changes

2020-05-18 16:01 UTC, saurabhst approved these changes

2020-05-29 13:19 UTC, closed without merging