Do not use an undefined node id for mdns advertising
project-chip/connectedhomeip pull request #7488
Opened 2021-06-09 12:48 UTC by vivien-apple

#### Problem

If an accessory already connected to the network and without any admin pairing is on the network, the mdns advertisement is `0000000000000000-0000000000000000` instead of beeing (for example): `0000000000000000-0000000000BC5C01` if the node id is `12344321`.

#### Change overview
 * Do not use an undefined node if from the admin pairing table

#### Testing
 * It was tested on Mac with `chip-all-clusters-app`,  with `chip_config_network_layer_ble=false`, advertising over mdns on the local network.
 * Similarly to #7487, I'm trying to get mdns advertisement working in order to have a working test.

2021-06-09 13:05 UTC, msandstedt approved these changes

2021-06-09 13:07 UTC, msandstedt commented on src/app/server/Mdns.cpp
> +    if (pairing != GetGlobalAdminPairingTable().cend() && pairing->GetNodeId() != kUndefinedNodeId)
Wrt the TODO above:

`// TODO: once operational credentials are implemented, node ID should be read from them`

I would think that once we are getting the node ID from operational credentials, we should remove this check.

2021-06-09 14:21 UTC, andy31415 commented
Could you explain the situation a bit?

Why do we have an admin pairing info without a well defined node id? Should the admin pairing info be missing in that case? 
I would have expected the fix to be "do not have an invalid admin pairing" rather than  "if admin pairing  is invalid, ignore it".

2021-06-09 14:31 UTC, bzbarsky-apple approved these changes
I think this could definitely use a comment answering @andy31415's question.  Is this about the time period between an admin being added and a node id being provisioned?  Or nodes that were partially provisioned?  Or something else?

2021-06-10 15:19 UTC, woody-apple commented
@saurabhst @jelderton @Damian-Nordic @LuDuda ?

2021-06-11 06:15 UTC, Damian-Nordic approved these changes

2021-06-11 06:18 UTC, Damian-Nordic commented
Not sure what's @vivien-apple's case, but it once happened to me that the pairing window has expired and when I started BLE advertising again, a new admin has been allocated and after the commissioning the previously allocated admin had the node ID uninitialized. I guess this change will fix such issues although it might have been better to remove incomplete admins when commissioning fails.

2021-06-11 14:17 UTC, andy31415 requested changes
Marking as changes requested to not get merged until we understand the case.

not having an invalid state at all seems better than ignoring invalid state when we see it.

2021-06-14 11:16 UTC, vivien-apple commented
> Could you explain the situation a bit?
> 
> Why do we have an admin pairing info without a well defined node id? Should the admin pairing info be missing in that case?
> I would have expected the fix to be "do not have an invalid admin pairing" rather than "if admin pairing is invalid, ignore it".

I'm... not sure. Asking @shana-apple since she may have an answer.

But actually this is interesting. I dig more into the code and I'm curious of what is the right fix here. 

The current code flow is, when the pairing window is opened, the next available admin id is populated to the `AdminPairingTable` (in this case `0`) without a node id. The reason for not assigning any node id is because it is currently assigned at https://github.com/project-chip/connectedhomeip/blob/0bca29299b5fbd1d86001afdbcda4bb620928378/src/transport/SecureSessionMgr.cpp#L438 

The comment "`AddOpCert` is implemented" suggests that  `NodeId` should be populated when an operational certificate is received ?

2021-06-14 13:27 UTC, shana-apple commented
> > Could you explain the situation a bit?
> > Why do we have an admin pairing info without a well defined node id? Should the admin pairing info be missing in that case?
> > I would have expected the fix to be "do not have an invalid admin pairing" rather than "if admin pairing is invalid, ignore it".
> 
> I'm... not sure. Asking @shana-apple since she may have an answer.
> 
> But actually this is interesting. I dig more into the code and I'm curious of what is the right fix here.
> 
> The current code flow is, when the pairing window is opened, the next available admin id is populated to the `AdminPairingTable` (in this case `0`) without a node id. The reason for not assigning any node id is because it is currently assigned at
> 
> https://github.com/project-chip/connectedhomeip/blob/0bca29299b5fbd1d86001afdbcda4bb620928378/src/transport/SecureSessionMgr.cpp#L438
> 
> The comment "`AddOpCert` is implemented" suggests that `NodeId` should be populated when an operational certificate is received ?

This will be resolved by my next patch. This wasn't just AddOpCert landing but further implementation is needed to hook it all up.

2021-06-14 15:45 UTC, vivien-apple commented
After some investigations, it seems like the issue here is that the accessory is locally broadcasting using `AdvertiseOperational` instead of `AdvertiseCommissionableNode`. I will update the patch

2021-06-16 04:03 UTC, woody-apple commented
/rebase

2021-06-17 01:31 UTC, woody-apple commented
/rebase

2021-06-17 17:17 UTC, msandstedt approved these changes

2021-07-01 19:38 UTC, closed without merging