Fix path conflicts in chip_data_model in some projects
project-chip/connectedhomeip pull request #7590
Opened 2021-06-14 05:50 UTC by mspang

The chip_data_model template builds a library that contains 2 files
named encoder.cpp and two files name attribute-size.cpp.

While this is not a problem with pigweed's toolchain definitions because
different directories are used, it can cause a path conflict if a
project defines a toolchain that places all of a library's .o files in
the same directory:

```
ERROR at //third_party/connectedhomeip/repo/src/app/chip_data_model.gni:59:3: Duplicate object file
  source_set(_data_model_name) {
  ^-----------------------------
The target //third_party/connectedhomeip/repo/src/controller/data_model:data_model
generates two object files with the same name:
  obj/third_party/connectedhomeip/repo/src/controller/data_model/data_model/attribute-size.o
```

Rename some files so that all files in the same library have distinct
filenames, which should be compatible with most reasonable toolchain
definitions.

2021-06-14 05:51 UTC, saurabhst approved these changes

2021-06-14 06:20 UTC, woody-apple requested changes
Can we update this to conform to the standard template?

2021-06-15 18:25 UTC, woody-apple approved these changes

2021-06-15 18:25 UTC, woody-apple commented
/rebase

2021-06-16 00:56 UTC, andy31415 approved these changes

2021-06-16 04:02 UTC, woody-apple commented
/rebase

2021-06-16 04:02 UTC, woody-apple commented
/rebase

2021-06-16 05:39 UTC, bzbarsky-apple commented on src/darwin/Framework/CHIP.xcodeproj/project.pbxproj
> +		1E85731F26551A490050A4D9 /* attribute-size.cpp */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.cpp.cpp; name = "attribute-size-util.cpp"; path = "../../../app/util/at
```suggestion
		1E85731F26551A490050A4D9 /* attribute-size-util.cpp */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.cpp.cpp; name = "attribute-size-util.cpp"; path = "../../../app/util/attribute-size-util.cpp"; sourceTree = "<group>"; };
```

2021-06-16 14:05 UTC, merged