Cleaning up CI scripts so they're more emulatable
project-chip/connectedhomeip pull request #796
Opened 2020-05-20 22:43 UTC by woody-apple

#### Problem
@turon was curious about how to add a matrix, cleaning up mbedTLS so it can be emulated more cleanly

2020-05-20 22:46 UTC, gerickson approved these changes

2020-05-20 22:52 UTC, turon requested changes
Thanks for the fast turn-around!

2020-05-20 23:02 UTC, anush-apple approved these changes

2020-05-20 23:04 UTC, turon approved these changes
LGTM :+1:

2020-05-21 00:10 UTC, saurabhst approved these changes

2020-05-21 00:32 UTC, merged