Add CommissionedFabrics and SupportedFabrics attribute to opCreds cluster
project-chip/connectedhomeip pull request #8003
Opened 2021-06-29 15:31 UTC by shana-apple

#### Problem
Add CommissionedFabrics and SupportedFabrics attribute to opCreds cluster
#### Change overview
Add CommissionedFabrics and SupportedFabrics attribute to opCreds cluster
Update CommissionedFabrics when number of fabrics is updated in fabrics list.

2021-06-29 15:32 UTC, woody-apple approved these changes

2021-06-30 05:11 UTC, bzbarsky-apple requested changes

2021-06-30 05:11 UTC, bzbarsky-apple commented on src/app/clusters/operational-credentials-server/operational-credentials-server.cpp
>      emberAfPrintln(EMBER_AF_PRINT_DEBUG, "OpCreds: Stored %" PRIu32 " admins in fabrics list attribute.", fabricIndex);
```suggestion
    emberAfPrintln(EMBER_AF_PRINT_DEBUG, "OpCreds: Stored %" PRIu8 " admins in fabrics list attribute.", fabricIndex);
```

2021-06-30 05:11 UTC, bzbarsky-apple commented on src/app/clusters/operational-credentials-server/operational-credentials-server.cpp
>      if (writeFabricAttribute((uint8_t *) &fabricIndex) != EMBER_ZCL_STATUS_SUCCESS)
```suggestion
    if (writeFabricAttribute(&fabricIndex) != EMBER_ZCL_STATUS_SUCCESS)
```

2021-06-30 05:11 UTC, bzbarsky-apple commented on src/app/zap-templates/zcl/data-model/chip/operational-credentials-cluster.xml
> +    <attribute side="server" code="0x0003" define="COMMISSIONED_FABRICS" type="INT8U" min="0x00" max="0xFF" writable="false" optional="false">commissioned fabrics</attribute>
Shouldn't these also be added to .zap files somewhere?

2021-06-30 05:11 UTC, bzbarsky-apple commented on src/controller/data_model/gen/CHIPClusters.cpp
>  #include <cstdint>
The changes to this file are a bit unexpected... and are failing the ZAP CI.

2021-07-06 02:21 UTC, mspang commented
@shana-apple This didn't get sent out because it's failing restyle..

2021-07-06 16:28 UTC, shana-apple commented
Closing and switching to: https://github.com/shana-apple/connectedhomeip/pull/new/sazria/commissionedFabrics

2021-07-06 16:28 UTC, closed without merging