move zap to CHIP build system
project-chip/connectedhomeip pull request #802
Opened 2020-05-21 04:03 UTC by rwalker-apple

#### Problem
 Chip-ZCL doesn't subscribe to CHIP's make system

 #### Summary of Changes
 reworking so that it does

fixes #783
fixes #789

2020-05-21 14:17 UTC, gerickson requested changes
Some recommended changes for abstracting relative paths and test driver naming conventions.

2020-05-21 23:22 UTC, gerickson approved these changes

2020-05-21 23:23 UTC, woody-apple approved these changes
given @gerickson agrees, I agree :)

2020-05-26 17:15 UTC, jelderton approved these changes

2020-05-26 18:09 UTC, merged