Remove unused code in PeerConnections.h
project-chip/connectedhomeip pull request #8188
Opened 2021-07-08 02:56 UTC by kghost

#### Problem
Clean up code which is not used anymore

#### Change overview
* Remove APIs which use address as key.
* NodeId should be mandatory for a secure session

#### Testing
Verified using unit-tests

2021-07-08 14:25 UTC, andy31415 approved these changes

2021-07-09 05:30 UTC, bzbarsky-apple requested changes

2021-07-09 05:30 UTC, bzbarsky-apple commented on src/transport/PeerConnections.h
> +                mStates[i].SetPeerNodeId(peerNode);
What if caller passes `kUndefinedNodeId` ?

2021-07-09 05:30 UTC, bzbarsky-apple commented on src/transport/PeerConnections.h
> +            if (iter->GetPeerNodeId() == nodeId && (peerKeyId == kAnyKeyId || iter->GetPeerKeyID() == peerKeyId))
This changes the handling around `kUndefinedNodeId`.  Is that expected/ok?

2021-07-09 05:30 UTC, bzbarsky-apple commented on src/transport/PeerConnections.h
> +            if (iter->GetPeerNodeId() == nodeId && iter->GetLocalKeyID() == localKeyId)
Again, changes handling of `kUndefinedNodeId`.

2021-07-09 05:39 UTC, kghost commented
I'd probably close this PR and move the content into #8206 , because most code introduced by this PR is immediately remove by that PR.

As @andy31415 suggested, I'll use `PeerId` class to remove (`NodeId`, `AdminId`) tuple.

2021-07-09 05:39 UTC, closed without merging