[fix] emberAfCopyString should accept uint16 size
project-chip/connectedhomeip pull request #8241
Opened 2021-07-09 05:54 UTC by erjiaqing

#### Problem
emberAfCopyString accepts uint8_t currently, however we should be able to pass longer buffer to emberAfCopyString.

#### Change overview

```diff
- void emberAfCopyString(uint8_t * dest, const uint8_t * src, uint8_t size);
+ void emberAfCopyString(uint8_t * dest, const uint8_t * src, uint16_t size);
```

#### Testing
Manaully tested.

2021-07-09 13:35 UTC, msandstedt approved these changes

2021-07-09 16:03 UTC, yunhanw-google approved these changes

2021-07-09 18:00 UTC, bzbarsky-apple requested changes
> This actually fixed the issue that lighting app will return empty string for some fields.

Because the buffersize we pass in to `typeSensitiveMemCopy` overflows `uint8_t`?  But shouldn't the real fix then be in the casting in that function?  Because passing a size larger than `uint8_t` to `emberAfCopyString` doesn't necessarily make sense as things stand, because the callee will never copy more than `uint8_t`s-count of bytes....  Unless we just want to make that param `size_t` or something like that in general?

In any case, if this affects app behavior in an observable way, it sounds like we should be able to add CI for it.  Can the problem be reproduced with all-clusters-app, or just with lighing-app?

2021-07-09 19:32 UTC, andy31415 commented
I have previously tried to add unit tests for ember and failed - at that time recursive includes (ember lib including gen files) prevented me from creating a library to build tests upon.

2021-07-09 19:32 UTC, andy31415 approved these changes

2021-07-09 20:18 UTC, msandstedt commented
> > This actually fixed the issue that lighting app will return empty string for some fields.
> 
> Because the buffersize we pass in to `typeSensitiveMemCopy` overflows `uint8_t`? But shouldn't the real fix then be in the casting in that function? Because passing a size larger than `uint8_t` to `emberAfCopyString` doesn't necessarily make sense as things stand, because the callee will never copy more than `uint8_t`s-count of bytes.... Unless we just want to make that param `size_t` or something like that in general?
> 
> In any case, if this affects app behavior in an observable way, it sounds like we should be able to add CI for it. Can the problem be reproduced with all-clusters-app, or just with lighing-app?

Agreed.  The current behavior is:

* destination buffer can be any size (large or small)
* copied strings will be (silently) truncated if destination size is too small

If we're going to retain that behavior, size_t makes more sense to me.  Isn't the bigger problem the silent truncation though?  Is that actually what we want?

2021-07-09 21:04 UTC, bzbarsky-apple commented
> I have previously tried to add unit tests for ember and failed

2021-07-09 21:06 UTC, bzbarsky-apple commented
> Isn't the bigger problem the silent truncation though? Is that actually what we want?

@vivien-apple has been looking into that a bit recently, I think...

2021-07-09 21:07 UTC, franck-apple commented
removing the "TE4 cherrypick" label, while waiting for CSG's validation that it's needed.
Cherrypicking time is nearly over anyway.

2021-07-12 02:01 UTC, erjiaqing commented
> > This actually fixed the issue that lighting app will return empty string for some fields.
> 
> Because the buffersize we pass in to `typeSensitiveMemCopy` overflows `uint8_t`? But shouldn't the real fix then be in the casting in that function? Because passing a size larger than `uint8_t` to `emberAfCopyString` doesn't necessarily make sense as things stand, because the callee will never copy more than `uint8_t`s-count of bytes.... Unless we just want to make that param `size_t` or something like that in general?
> 
> In any case, if this affects app behavior in an observable way, it sounds like we should be able to add CI for it. Can the problem be reproduced with all-clusters-app, or just with lighing-app?

Yes, we should add more tests between different apps -- I would suggest a follow up.

Changed uint16_t -> size_t for `emberAfCopyString`

2021-07-12 21:28 UTC, bzbarsky-apple commented
> Yes, we should add more tests between different apps -- I would suggest a follow up.

I respectfully disagree, unless the tests are a lot of work to add (which it doesn't seem like they should be _if_ all-clusters-app shows the problem too).  This is fixing an app-visible bug, we have an existing harness for exercising such things, it's easy to add tests to this harness, tests should be added with the fix if possible.  Why would we _not_ add the tests here?

2021-07-12 21:41 UTC, bzbarsky-apple commented
> which it doesn't seem like they should be if all-clusters-app shows the problem too

Ah, but it does not, because ATTRIBUTE_LARGEST there is not 257 like it is in lighting-app; it's 1001, which leads to different behavior inside emberAfCopyString.

Alright, that's a good enough reason to sort out tests in a followup....

2021-07-12 21:47 UTC, bzbarsky-apple approved these changes

2021-07-12 21:47 UTC, bzbarsky-apple commented on src/app/util/attribute-storage.cpp
> +        emberAfCopyString(dest, src, static_cast<size_t>(bufferSize - 1));
Why not just remove this cast?  If that leads to signed-vs-unsigned issues, change the type of bufferSize in this function to `size_t`?
```suggestion
        emberAfCopyString(dest, src, bufferSize - 1);
```

2021-07-12 21:47 UTC, bzbarsky-apple commented on src/app/util/attribute-storage.cpp
> +        emberAfCopyLongString(dest, src, static_cast<size_t>(bufferSize - 2));
Again, no cast.
```suggestion
        emberAfCopyLongString(dest, src, bufferSize - 2);
```

2021-07-12 21:47 UTC, bzbarsky-apple commented on src/app/util/util.cpp
> +            // Here, since we have checked that size < length, so size must be able to fit into length.
```suggestion
            // Since we have checked that size < length, size must be able to fit into the type of length.
```

2021-07-12 21:47 UTC, bzbarsky-apple commented on src/app/util/util.cpp
> +            // Here, since we have checked that size < length, so size must be able to fit into length.
```suggestion
            // Since we have checked that size < length, size must be able to fit into the type of length.
```

2021-07-12 23:03 UTC, merged