Fix casing for "chip" in comments
project-chip/connectedhomeip pull request #85
Opened 2020-03-20 22:35 UTC by pan-apple

#### Problem
Code has mixed use of `Chip`, `CHIP` and `chip` in the comments

 #### Summary of Changes
Use `CHIP` in comments.

2020-03-20 22:45 UTC, gerickson requested changes
Overall, this looks good; however, the prevailing coding style for method and free function calls is `<lower Case><Captial Case><Capital Case>`. I'd recommend that we preserve that.

The other option is to transition to the other advocated styles of `"a"<Capital Case><Captial Case><Capital Case>` for arguments or `"i"<Capital Case><Captial Case><Capital Case>` for input arguments, `"o"<Capital Case><Captial Case><Capital Case>` for output arguments, and `"io"<Capital Case><Captial Case><Capital Case>` for input/output arguments.

2020-03-20 23:19 UTC, gerickson approved these changes

2020-03-23 17:48 UTC, woody-apple approved these changes

2020-03-23 18:09 UTC, hawk248 approved these changes
👍

2020-03-23 18:10 UTC, merged