Manual Payload check digit implementation
project-chip/connectedhomeip pull request #851
Opened 2020-05-27 12:44 UTC by shana-apple

#### Problem
We need to have generate a check digit and verify it on the manual setup payload

 #### Summary of Changes
Get the verhoeff implementation from open weave and use it in the manual setup payload generator and parser.

Note: All the verhoeff code in weave was ifdefed out under WEAVE_WITH_VERHOEFF which was set to default to no. We should figure out what we want here. 

fixes #570

2020-05-27 15:41 UTC, gerickson approved these changes

2020-05-27 16:17 UTC, woody-apple approved these changes

2020-05-27 16:18 UTC, rwalker-apple requested changes

2020-05-27 18:08 UTC, bhaskar-apple submitted a review, later dismissed

2020-05-27 18:53 UTC, jelderton approved these changes
Seems fine to me, but bhaskar requested some changes so I think we should wait for those to be resolved before merging.

2020-05-27 20:20 UTC, BroderickCarlin approved these changes

2020-05-28 16:48 UTC, rwalker-apple approved these changes
lgtm

2020-05-28 23:23 UTC, merged