[docs] Document IP Pairing and chip-tool tests.
project-chip/connectedhomeip pull request #8548
Opened 2021-07-21 17:54 UTC by turon

#### Problem
The quickstart instructions are incomplete with regard to running a Node and Controller as processes on a single laptop in order to test PASE pairing over IP.

#### Change overview
Add instructions for setting up PASE pairing with chip-tool and all-apps-cluster on a single laptop.

#### Testing
Manually tested the amended workflow instructions on both Mac and Linux.

2021-07-22 01:54 UTC, bzbarsky-apple requested changes

2021-07-22 01:54 UTC, bzbarsky-apple commented on docs/QUICK_START.md
> +`chip-tool tests Test_TC_OO_1_` will run a suite of tests that use CASE To communicate with a paired `all-clusters-app` peer node.
```suggestion
`chip-tool tests Test_TC_OO_1_1` will run a suite of tests that use CASE To communicate with a paired `all-clusters-app` peer node.
```

2021-07-22 01:54 UTC, bzbarsky-apple commented on docs/QUICK_START.md
> +`chip-tool pairing onnetwork 0 20202021 3840 ::1 11097` will use PASE over IUP to pair a device.
```suggestion
`chip-tool pairing onnetwork 0 20202021 3840 ::1 5540` will use PASE over IUP to pair a device.
```

2021-07-22 01:54 UTC, bzbarsky-apple commented on examples/chip-tool/README.md
> +The command below will pair to a localhost device (`::1`) running the `all-clusters-app` on the default port (`11097`) over IPv6:
```suggestion
The command below will pair to a localhost device (`::1`) running the `all-clusters-app` on the default port (`5540`) over IPv6:
```

2021-07-22 01:54 UTC, bzbarsky-apple commented on examples/chip-tool/README.md
> +    $ chip-tool pairing onnetwork 0 20202021 3840 ::1 11097
```suggestion
    $ chip-tool pairing onnetwork 0 20202021 3840 ::1 5540
```

2021-07-22 01:54 UTC, bzbarsky-apple commented on examples/chip-tool/README.md
> +    $ chip-tool tests Test_TC_OO_1_
```suggestion
    $ chip-tool tests Test_TC_OO_1_1
```

2021-08-02 22:23 UTC, bzbarsky-apple approved these changes

2021-08-04 18:50 UTC, andy31415 approved these changes

2021-08-05 12:54 UTC, mspang approved these changes

2021-08-27 13:49 UTC, jmeg-sfy approved these changes

2021-08-31 21:36 UTC, jmartinez-silabs approved these changes

2021-08-31 23:04 UTC, merged