Create a transport layer directory and include it to the build system.
project-chip/connectedhomeip pull request #884
Opened 2020-05-28 16:48 UTC by andy31415

The intent is to proide the transport support (UDP, TCP, BLE and others) into its own layer.
Currently started with the message header according to the WML format, with encryption and tunneling flags and options stripped out.

 #### Problem
Transport layer is not yet defined. WML wholesale port does not seem viable due to class interlinkage. Trying for small PRs with a clear goal.

 #### Summary of Changes
Created MessageHeader class that defines encoding and decoding methods for message headers.

2020-05-28 17:33 UTC, woody-apple reviewed
This looks great to me. Any thoughts @bzbarsky-apple @sagar-apple @pan-apple @rwalker-apple @bhaskar-apple ?

2020-05-28 17:55 UTC, gerickson requested changes
Overall, looks good to me. I have one quantitative question in terms of the Optional template cost and some minor style nits that I am hoping that @rwalker-apple or @woody-apple can tell me can be enforced by clang-format:

* `(void)` vs. `()` for declarations.
* Blank line before `return` calls.
* No one liners: `foo() { return (bar); }`

2020-05-28 20:26 UTC, gerickson approved these changes

2020-05-28 22:04 UTC, woody-apple approved these changes

2020-06-01 14:36 UTC, jelderton approved these changes

2020-06-01 16:12 UTC, merged