Fix/hue calculation
project-chip/connectedhomeip pull request #8883
Opened 2021-08-10 16:25 UTC by mkardous-silabs

#### Problem
* Calculation Error for finalHue when using EnhancedMoveHue with hue decreasing (moveMode = 3)
The incorrect finalHue is calculated when recalculting it when the first move hue is complete. This cause delta between two hues to be incorrect.
To reproduce:
`zcl ColorControl EnhancedMoveHue 12344321 1 0 moveMode=3 rate=100 optionsMask=0 optionsOverride=0`
* Fixes #8828 

#### Change overview
* For issue 8828, changes constants to max uint8 for wrap arround
* For finalhue error, switched initial and final hue in substract function

#### Testing
For finalHue error, 
Used following command to validate delta between two hues was correct after recalculation:
`zcl ColorControl EnhancedMoveHue 12344321 1 0 moveMode=3 rate=100 optionsMask=0 optionsOverride=0`

For issue 8828,
Used following commands to valiadate that wrap around was not skipping a value
`zcl ColorControl StepHue 12344321 1 0 stepMode=1 stepSize=10 transitionTime=300 optionsMask=0 optionsOverride=0`
`zcl ColorControl StepHue 12344321 1 0 stepMode=3 stepSize=10 transitionTime=300 optionsMask=0 optionsOverride=0`

2021-08-10 17:18 UTC, jmartinez-silabs approved these changes

2021-08-10 20:35 UTC, bzbarsky-apple requested changes
This was a bug in the original Silicon Labs code, right?  @selissia @tecimovic could you please check whether there's a reason for the old (apparently buggy) behavior?

2021-08-10 20:35 UTC, bzbarsky-apple commented on src/app/clusters/color-control-server/color-control-server.cpp
> +        hue16 = static_cast<uint16_t>(hue16 - UINT8_MAX);
Shouldn't this be `hue16 - MAX_HUE_VALUE - 1`, so we don't assume `MAX_HUE_VALUE == UINT8_MAX - 1`?

2021-08-10 20:35 UTC, bzbarsky-apple commented on src/app/clusters/color-control-server/color-control-server.cpp
> +        hue16 = static_cast<uint16_t>(hue16 + UINT8_MAX);
Similarly, this should be `hue16 + MAX_HUE_VALUE + 1`?

2021-08-10 20:36 UTC, bzbarsky-apple reviewed
Also, can we add automatic tests for this?

2021-08-11 12:46 UTC, mkardous-silabs commented
> Also, can we add automatic tests for this?
Tests are already implemented in the yaml files for hue and enhanced hue variation. The only problem is, for them to actually check a variation, a wait/sleepFor needs to be added to the test suite. Right now, if we enable those tests, the test would start the hue viartion (moveHue, moveToHue, etc) and read the hue value right away before it has time to change.

2021-08-11 13:24 UTC, andy31415 commented
> > Also, can we add automatic tests for this?
> 
> Tests are already implemented in the yaml files for hue and enhanced hue variation. The only problem is, for them to actually check a variation, a wait/sleepFor needs to be added to the test suite. Right now, if we enable those tests, the test would start the hue viartion (moveHue, moveToHue, etc) and read the hue value right away before it has time to change.

Is there a TODO/issue for this? 
Would the test if adding wait/sleep have caught this bug? Is sleeping the only option or could we have 'only return success/failure after attribute has been applied'?

2021-08-11 13:24 UTC, andy31415 approved these changes

2021-08-11 14:43 UTC, mkardous-silabs commented
> > > Also, can we add automatic tests for this?
> > 
> > 
> > Tests are already implemented in the yaml files for hue and enhanced hue variation. The only problem is, for them to actually check a variation, a wait/sleepFor needs to be added to the test suite. Right now, if we enable those tests, the test would start the hue viartion (moveHue, moveToHue, etc) and read the hue value right away before it has time to change.
> 
> Is there a TODO/issue for this?

I don't know if there is an issue/TODO for adding wait/sleeps in the test suite. All I know is that there have been conversations about adding them.

> Would the test if adding wait/sleep have caught this bug? 

A test case checking the rollover at MAX_HUE and MIN_HUE for the max/min hue calculations issue and another test case that verifies that steps between hue updates remains the same after the recalculation should have detected the bugs. These tests would be complicated to implement since we need to wait a certain amount of time before checking the `currentHue` and the wait/sleep won't necessarly be exact in the timeout time.

> Is sleeping the only option or could we have 'only return success/failure after attribute has been applied'?

To evaluate that the hue variations are correct, we need a sleep/wait to be able to the let the functions (moveHue, moveTohue, etc) iterate a few times. A success/failure after attribute application is only usefull to check if attributs were properly written and not if all the hue variation calculations are correct.

2021-08-11 15:47 UTC, bzbarsky-apple commented
>  The only problem is, for them to actually check a variation, a wait/sleepFor needs to be added to the test suite

Looking at the spec StepHue can send a TransitionTime of 0, which I would expect to take effect immediately... but our implementation uses 1 if 0 is sent.  Is the implementation wrong here, or the spec, or is something something else going on?

@Rob-Houtepen-Signify @selissia

2021-08-11 15:48 UTC, bzbarsky-apple approved these changes

2021-08-11 15:57 UTC, merged

2021-08-11 18:52 UTC, Rob-Houtepen-Signify commented
> > The only problem is, for them to actually check a variation, a wait/sleepFor needs to be added to the test suite
> 
> Looking at the spec StepHue can send a TransitionTime of 0, which I would expect to take effect immediately... but our implementation uses 1 if 0 is sent. Is the implementation wrong here, or the spec, or is something something else going on?
> 
Too me sounds like an implementation detail, where with 1 some code is executed and stopped at 0. I would not mind too much.

2021-08-11 21:46 UTC, bzbarsky-apple commented
> Too me sounds like an implementation detail

It's a spec-observable difference, right?  If I do a StepHue with a TransitionTime of 0, does the spec allow a subsequent read of hue to get the old value?  It needs to clearly define the behavior....

2021-08-11 21:58 UTC, jmartinez-silabs commented
@bzbarsky-apple @andy31415 @Rob-Houtepen-Signify @mkardous-silabs Even if we do transitiontime 0, the test could validate the final result (final value of the hue or enhanced Hue) but it would not validated the transition or calculation of the steps/rates. It becomes essentially a write attributes to hue in the received command callback.

Right now when we receive such commands we set our transition states and calculate de rate/steps to be done during that transition time and kick of the state machine. The state machine then establish the transition every 100ms.

Not sure what is the best way to test those transition and corner case in the unit test