[cleanup] Move non generated code to seperate file
project-chip/connectedhomeip pull request #9121
Opened 2021-08-19 10:11 UTC by erjiaqing

#### Problem

Many non-generated code lives in CHIPClusterCallbacks, let move them to seperate files.

#### Change overview

- Adds `src/app/util/im-client-callbacks.cpp` for these non generated client callbacks.

#### Testing

- This move does not break CI

2021-08-19 14:48 UTC, chrisdecenzo requested changes
If its non-generated code, can we move it out of the gen directory?

2021-08-19 14:48 UTC, chrisdecenzo commented on src/app/util/im-client-callbacks.h
> +void BasicAttributeFilter(chip::TLV::TLVReader * data, chip::Callback::Cancelable * onSuccess,
Can we move BasicAttributeFilter out of files that get included by CHIPClientCallbacks.h since this is causing a conflict in the tv-app?

2021-08-19 14:56 UTC, chrisdecenzo approved these changes

2021-08-19 16:22 UTC, andy31415 approved these changes

2021-08-19 16:24 UTC, andy31415 commented
QPG seems to say 'heap to small'. I am unclear why this would be the case here so I restearted it, however it may be an actual failure.

@erjiaqing - is this  expected to use more RAM?

2021-08-20 03:14 UTC, erjiaqing commented
> QPG seems to say 'heap to small'. I am unclear why this would be the case here so I restearted it, however it may be an actual failure.
> 
> @erjiaqing - is this expected to use more RAM?

This is not expected to use more RAM since this does not introduce any new code, as well as ESP32 build result suggests:

File | Section | File | VM
-- | -- | -- | --
chip-bridge-app.elf | .flash.text | -48 | -48
chip-temperature-measurement-app.elf | .flash.text | 56 | 56

I guess the reason is that linker from QPG includes some dead symbol, moved the target and only build it when `use_default_client_callbacks`. Should fix this.

2021-08-20 22:12 UTC, woody-apple approved these changes

2021-08-20 22:27 UTC, andy31415 commented
@erjiaqing -  conflicts - we start having more generated files changes recently

2021-08-20 22:59 UTC, woody-apple commented
@erjiaqing Can you please rebase/regen?

2021-08-21 03:26 UTC, erjiaqing commented
@andy31415 @woody-apple Done and green

2021-08-21 14:48 UTC, merged