Add non-copying string and byte getters on a TLV reader.
project-chip/connectedhomeip pull request #9249
Opened 2021-08-25 21:55 UTC by bzbarsky-apple

We have existing callsites that are doing what GetString/GetBytes say to do and call GetLength() to decide how big a buffer to allocate.  But the return value from GetLength() doesn't have to be sane, so we end up allocating buffers with attacker-controlled sizes.

The changes here are:

1) Add ContiguousBufferTLVReader that is always backed by a single
   buffer, so it can guarantee that the in-place view makes sense.

2) Use the new class in setup payload parsers, fixing various bugs in
   the process.

Fixes https://github.com/project-chip/connectedhomeip/issues/9009

#### Problem
See above.

#### Change overview
See above.

#### Testing
Added unit tests for the new readers.  I haven't found a good way to test the buggy codepaths being fixed: for `retrieveOptionalInfoString` we would need to feed it invalid TLV data, and `AdditionalDataPayloadParser` is completely untested (tracked in https://github.com/project-chip/connectedhomeip/issues/9248).

2021-08-25 23:31 UTC, woody-apple approved these changes

2021-08-26 13:53 UTC, andy31415 approved these changes

2021-08-26 13:57 UTC, andy31415 requested changes
Marking request changes to understand the separation - on second consideration, the new code also creates spans using GetLength() as the previous code, so actual length is identical as before, except the benefit of not really allocating it but just creating a view.

Following that line of reasoning, these methods could work on TLVReader as before or we may not even need the methods and just call GetDataPtr/GetLength in the places in setup payload as needed (stop allocating temporary storage space)

2021-08-26 15:42 UTC, andy31415 approved these changes

2021-08-26 18:22 UTC, tcarmelveilleux approved these changes

2021-08-26 21:22 UTC, jmartinez-silabs approved these changes

2021-08-26 21:24 UTC, emargolis approved these changes

2021-08-26 21:52 UTC, saurabhst approved these changes

2021-08-27 15:39 UTC, merged