Don't output an unused PrepareListFromTLV function.
project-chip/connectedhomeip pull request #9250
Opened 2021-08-25 22:34 UTC by bzbarsky-apple

Only output it if it's needed.

#### Problem
We are outputting a function that is not used in some cases, and that fails to compile.

#### Change overview
Output the function conditionally.

#### Testing
@holbrookt says this fixes the compilation issues he was seeing.

2021-08-25 22:35 UTC, holbrookt approved these changes

2021-08-25 23:30 UTC, woody-apple approved these changes

2021-08-26 14:00 UTC, andy31415 requested changes
Requesting changes: adding complexity to zap files is undesirable if it can be avoided.

In this case I believe it can: the function can be moved into a header/cpp file. I believe there  is no significant gain of having it inside the cpp file as a static  function.

2021-08-26 14:04 UTC, selissia approved these changes

2021-08-30 16:44 UTC, holbrookt commented on src/app/zap-templates/templates/app/CHIPClientCallbacks-src.zapt
> +{{#if (chip_has_client_cluster_with_server_list_attribute)}}
That sounds good to me. @bzbarsky-apple are you tagging me just to get my thoughts on this suggestion?

2021-08-30 19:49 UTC, holbrookt commented
@andy31415 
> In this case I believe it can: the function can be moved into a header/cpp file. I believe there is no significant gain of having it inside the cpp file as a static function.

I'm fine with this. Do you have a suggestion for an existing file or directory? Maybe `src/app/` ?

2021-08-30 21:53 UTC, holbrookt commented
Filed https://github.com/project-chip/connectedhomeip/pull/9346 for the alternate fix suggested by @andy31415 . Suggest closing this PR once that one is approved

2021-09-08 19:35 UTC, andy31415 commented
#9346 was merged. Closing this PR based on comment from @holbrookt .

@bzbarsky-apple if this is wrong please re-open and comment on what the real status should be.

2021-09-08 19:35 UTC, closed without merging

2021-09-08 20:09 UTC, bzbarsky-apple commented
Yep, closing this is correct.  Thanks!