[controller] reset Device state for usage in accessories
project-chip/connectedhomeip pull request #9386
Opened 2021-09-01 03:22 UTC by gjc13

#### Problem

The controller::Device class is currently tightly assuming the device state and forcing a commssion flow starting from PASE.

#### Change overview

Reset the state in `OperationalCertProvisioned` so that we can call this function to start from CASE.

#### Testing
How was this tested? 
* CI build and unit tests.

2021-09-01 03:26 UTC, gjc13 commented
@msandstedt The change follows our discussion in https://github.com/project-chip/connectedhomeip/pull/9103. Though it's kind of hack it unblocks us.

@mspang @andy31415 PTAL.

2021-09-01 03:39 UTC, gjc13 commented
I had offline discussion with Tennessee and here is his comments:

>I think you misunderstood Michael's comment
My point in the original comment is that reimplementing Device with subset functionality for each example is problematic
Separate from that I agree with Michael's points but I would say that just hacking the PASE state machine is not quite right. I agree with Michael that changes are few. Since I do not have much time this week, I suggest you work with Spang and Michael on resolution. I think the interaction peer change also was helpful, and overall, we will need to incrementally "separate" device/controller but we have to unblock device to device. I just want to make sure we dont make too many "compromise" changes that make the final solution hard to maintain (that is, as hard or harder to maintain than the problematic code we have now)

Personally I believe the delegate class https://github.com/project-chip/connectedhomeip/pull/9103 is not an elegant solution.
The correct way out is to remove `Device` class from our controller generated code and use `InteractionModelEngine` as the only entrypoint to send ZCL or BDX messages. We'll add another class to manage the pairing process and setup the symmetric  credentials. 

This approach requires rewriting a large amount of code. As an unblocker, this hack looks quite acceptable compared to https://github.com/project-chip/connectedhomeip/pull/9103. If we are using a temporary solution anyway, I'll prefer a smaller change.

2021-09-01 04:42 UTC, msandstedt approved these changes

2021-09-01 13:26 UTC, jmartinez-silabs approved these changes

2021-09-01 13:57 UTC, tcarmelveilleux commented
> 
> Personally I believe the delegate class #9103 is not an elegant solution.
> The correct way out is to remove `Device` class from our controller generated code and use `InteractionModelEngine` as the only entrypoint to send ZCL or BDX messages. We'll add another class to manage the pairing process and setup the symmetric credentials.
> 
`InteractionModelEngine` is for the IM, which is a layer above Message Layer. BDX is a protocol handler that does not relate  at all to IM. I disagree that `InteractionModelEngine` should be the entrypoint for everything.

2021-09-01 14:05 UTC, woody-apple requested changes
While a 1 line change, what test failed? What is this fixing? What new test is added to confirm that this doesn't regress?

2021-09-02 06:47 UTC, gjc13 commented
> While a 1 line change, what test failed? What is this fixing? What new test is added to confirm that this doesn't regress?

Unit test added. It's testing calling `EstablishConnectivity` after manually calling `OperationalCertProvisioned`. We'd expect a CASE session to be setup in this case. Before the change it will report `ERROR_INCORRECT_STATE`.

2021-09-09 03:35 UTC, woody-apple approved these changes

2021-09-09 03:43 UTC, merged