[CI] Fix unit test TestConfigurationMgr random failure
project-chip/connectedhomeip pull request #9409
Opened 2021-09-01 18:20 UTC by yufengwangca

#### Problem
What is being fixed?  Examples:
* The CI randomly failed with the following error:
[1630514648.709927][29145:29145] CHIP:DL: writing settings to file (/tmp/chip_factory.ini.tmp)
[1630514648.709969][29145:29145] CHIP:DL: failed to rename (/tmp/chip_factory.ini.tmp), No such file or directory (2)
[1630514648.709980][29145:29145] CHIP:DL: Configuration Manager initialization failed: ../../src/platform/Linux/CHIPLinuxStorageIni.cpp:113: CHIP Error 0x000000AF: Write to file failed

The root cause of this failure is the unit test run in parallel in CI and all share the same temp file on the storage which cause race condition.

#### Change overview
Use ramdam temporary file name to prevent racing on the shared file.

#### Testing
How was this tested? (at least one bullet point required)
* Covered by CI

2021-09-01 18:21 UTC, woody-apple approved these changes

2021-09-01 18:27 UTC, andy31415 commented
Will this work for chip-tool? I believe chip-tool assumes persistence. We may see this in the 'TESTS' where we have step(1) running pairing and step(2) running some test.

2021-09-01 19:05 UTC, andy31415 approved these changes

2021-09-01 19:07 UTC, yufengwangca commented
> Will this work for chip-tool? I believe chip-tool assumes persistence. We may see this in the 'TESTS' where we have step(1) running pairing and step(2) running some test.

Yes, it seems the race only occurs on ephemeral temp files, no change for the final configuration files

2021-09-01 22:26 UTC, mspang requested changes
Please don't use pid to create temporary files. It is

- Not sufficiently unqiue
- Not atomic

This problem probably cannot be solved with ofstream. The solution is to use an API for temporary files (at least name generation). The file _must_ be opened with `O_EXCL|O_CREAT` to avoid the race.

2021-09-01 22:31 UTC, mspang commented
> Please don't use pid to create temporary files. It is
> 
> * Not sufficiently unique
> * Not atomic
> 
> This problem probably cannot be solved with ofstream. The solution is to use an API for temporary files (at least name generation). The file _must_ be opened with `O_EXCL|O_CREAT` to avoid the race.

If we're sure we've created the file it should be safe to open again with ofstream.

2021-09-01 22:38 UTC, yufengwangca commented
> > Please don't use pid to create temporary files. It is
> > 
> > * Not sufficiently unique
> > * Not atomic
> > 
> > This problem probably cannot be solved with ofstream. The solution is to use an API for temporary files (at least name generation). The file _must_ be opened with `O_EXCL|O_CREAT` to avoid the race.
> 
> If we're sure we've created the file it should be safe to open again with ofstream.

The problem is the file is deleted by another instance of program which run into ofs.close(); The race is not among multiple threads, but multiple programs which use the same tmp file name.

2021-09-01 23:14 UTC, mspang commented
> > > Please don't use pid to create temporary files. It is
> > > 
> > > * Not sufficiently unique
> > > * Not atomic
> > > 
> > > This problem probably cannot be solved with ofstream. The solution is to use an API for temporary files (at least name generation). The file _must_ be opened with `O_EXCL|O_CREAT` to avoid the race.
> > 
> > 
> > If we're sure we've created the file it should be safe to open again with ofstream.
> 
> The problem is the file is deleted by another instance of program which run into ofs.close(); The race is not among multiple threads, but multiple programs which use the same tmp file name.

I assume you mean that the race is with rename(). Closing doesn't delete the file.

My position is that if we are going to try to work around this problem by using a unique temporary file, at least the creation of the unique temporary file should be done in the correct way. How to do it is well known and available in the standard library as mkstemp is for (or mkdtemp would work too). Doing it the wrong way is either still subject to races or is a vector for symlink attacks. There is no point in doing it a worse way when the standard library provides the implementation.

Using a unique name still does not solve the general problem that concurrent unit tests behavior might be affected by shared storage (if they are, it will most likely be in a subtle and nondeterministic way due to the concurrency, just like we have with this race).

2021-09-01 23:21 UTC, mspang commented
> > > Please don't use pid to create temporary files. It is
> > > 
> > > * Not sufficiently unique
> > > * Not atomic
> > > 
> > > This problem probably cannot be solved with ofstream. The solution is to use an API for temporary files (at least name generation). The file _must_ be opened with `O_EXCL|O_CREAT` to avoid the race.
> > 
> > 
> > If we're sure we've created the file it should be safe to open again with ofstream.
> 
> Could you explain more? If there are two instance of programs try to open the same temp file with both O_CREAT and O_EXCL are set, then the second open should fail since the specified file already exists. The CI still fails in this case.

The answer is that if open with O_EXCL|O_CREAT fails, you must retry with a different name.

2021-09-02 21:33 UTC, mspang requested changes
Please don't const_cast a const string argument.

2021-09-02 21:38 UTC, mspang commented on src/platform/Linux/CHIPLinuxStorageIni.cpp
> +    int fd = mkstemp(const_cast<char *>(tmpPath.c_str()));
mkstemp(&tmpPath[0]) ?

2021-09-02 21:39 UTC, mspang commented
> Please don't const_cast a const string argument.

Ah sorry I see the copy. I'd still avoid it though.

2021-09-02 21:39 UTC, mspang approved these changes

2021-09-02 21:58 UTC, yufengwangca commented on src/platform/Linux/CHIPLinuxStorageIni.cpp
> +    int fd = mkstemp(const_cast<char *>(tmpPath.c_str()));
Acked

2021-09-03 14:47 UTC, andy31415 commented
@chrisdecenzo @jelderton @jmartinez-silabs @LuDuda @saurabhst ?

2021-09-03 15:31 UTC, LuDuda approved these changes

2021-09-03 15:36 UTC, saurabhst approved these changes

2021-09-03 15:36 UTC, merged