[Telink]: Fix entropy source failed crash on boot
project-chip/connectedhomeip pull request #9635
Opened 2021-09-13 13:40 UTC by rikorsev

#### Problem
Fix crash on startup for Telink platform with following log:
```
*** Booting Zephyr OS build zephyr-v2.5.0-7511-g083f3065b44a  ***
I: Notifier: StateChanged (0x00000001) [Ip6+]
I: Init CHIP stack
E: 75 [CR]mbedTLS error: CTR_DRBG - The entropy source failed
E: 80 [DL]Entropy initialization failed: Error CHIP:0x000000AC
E: PlatformMgr().InitChipStack() failed
E: Exited with code ac
I: 8 Sectors of 256 bytes
I: alloc wra: 0, e8
I: data wra: 0, 0
I: Notifier: StateChanged (0x00038200) [NetData PanId NetName ExtPanId]

```
Investigation  shows that the issue occurs due to changes made by this https://github.com/project-chip/connectedhomeip/pull/9420 PR

Did previous solution works for nRF platform?

Any way, according to previous solution, **srand()** were called twice. 
First time in ${chip_root}/src/platform/Zephyr/PlatformManagerImpl.cpp in **_InitChipStack**
Second time in ${chip_root}/src/platform/Entropy.cpp in **InitEntropy**

#### Change overview

- Remove srand call from ${chip_root}/src/platform/Zephyr/PlatformManagerImpl.cpp
- Move Zephyr related entropy driver calls to **app_entropy_source** function
- Add **chip::Crypto::add_entropy_source** call in **_InitChipStack** method

#### Testing
Manually. Steps:
1. Build lighting example
2. Flash it on Telink device
3. Check if it does not crash on boot
4. Pair device over chip-tool
5. Send chip-tool onoff on 1 command
6. Check if it works correctly

2021-09-13 15:04 UTC, msandstedt approved these changes

2021-09-13 15:07 UTC, andy31415 commented on src/platform/Zephyr/PlatformManagerImpl.cpp
> +exit:
please remove this goto exit pattern - no cleanup code and it seems to make the code more complex to follow.

```cpp

if (entropy_get_entropy(entropy, output, len) == 0) {
   *olen = len;
} else {
   *olen = 0;  // is this ok? should we set any value?
}
```

`entropy_get_entropy` does not return a CHIP_ERROR so we should not use the SuccessOrExit macro which is supposed to work on CHIP_ERROR.

2021-09-13 15:08 UTC, andy31415 commented on src/platform/Zephyr/PlatformManagerImpl.cpp
> +    err = chip::Crypto::add_entropy_source(app_entropy_source, NULL, 16);
use a kConstant for 16. What does it represent? I cannot obviously see it while reading the code  without trying to find the doc for Crypto::add_entropy_source

2021-09-13 18:48 UTC, woody-apple approved these changes

2021-09-14 04:43 UTC, kghost approved these changes
Is it possible to automactically verify the issue by CI ? In case we may have regression problems like this one.

2021-09-14 12:26 UTC, Damian-Nordic requested changes

2021-09-14 12:26 UTC, Damian-Nordic commented on src/platform/Zephyr/PlatformManagerImpl.cpp
> +    err = chip::Crypto::add_entropy_source(app_entropy_source, NULL, 16);
Can you call this code only if `!CONFIG_NORDIC_SECURITY_BACKEND`? All nRF Connect examples use crypto libraries from our SDK which automatically configures entropy sources and this code breaks the examples.

2021-09-14 12:26 UTC, Damian-Nordic commented on src/platform/nrfconnect/BUILD.gn
> +    "${chip_root}/src/crypto",
This change won't be needed after resolving the previous comment.

2021-09-14 14:25 UTC, Damian-Nordic approved these changes

2021-09-14 19:02 UTC, bzbarsky-apple commented on src/platform/Zephyr/PlatformManagerImpl.cpp
> +#include <crypto/CHIPCryptoPAL.h>
```suggestion
#include <crypto/CHIPCryptoPAL.h> // nogncheck
```

2021-09-14 19:50 UTC, bzbarsky-apple approved these changes

2021-09-14 19:50 UTC, bzbarsky-apple commented on src/platform/Zephyr/PlatformManagerImpl.cpp
> +#endif // !CONFIG_NORDIC_SECURITY_BACKEND
```suggestion
#include <crypto/CHIPCryptoPAL.h> // nogncheck
#endif                            // !CONFIG_NORDIC_SECURITY_BACKEND
```

2021-09-14 22:03 UTC, merged