Move config CHIP_DEVICE_CONFIG_ETHERNET_IF_NAME to platform specific …
project-chip/connectedhomeip pull request #9708
Opened 2021-09-14 21:50 UTC by yufengwangca

…configuration.

#### Problem
What is being fixed?  Examples:
* Address the left review comment, the CHIP_DEVICE_CONFIG_ETHERNET_IF_NAME should be placed in platform specific config file since there is no sane default interface name cross platforms.
 

#### Change overview
Move config CHIP_DEVICE_CONFIG_ETHERNET_IF_NAME to platform specific configuration.

#### Testing
How was this tested? (at least one bullet point required)
*No logic change, regression check is covered by CI

2021-09-14 22:33 UTC, msandstedt approved these changes

2021-09-14 22:35 UTC, saurabhst approved these changes

2021-09-14 23:01 UTC, woody-apple requested changes
Can we support this being passed in rather than an hardcoded ubuntu specific one? (That is just the first ethernet, not all)

2021-09-14 23:31 UTC, yufengwangca commented
> Can we support this being passed in rather than an hardcoded ubuntu specific one? (That is just the first ethernet, not all)

@woody-apple You means just use the first Ethernet by default? what if the vendor want to connect Matter stack to the second ethernet interface?

The getifaddrs() return a linked list of structures describing the network interfaces of the local system, but this structure does not provide network type, the only way is to filter its name with prefix 'en' by latest naming convention, but I found a lot of systems use customized interface name such as 'eth0'

2021-09-15 18:11 UTC, woody-apple commented
Here's some code that might work:
https://chromium.googlesource.com/chromium/src/net/+/refs/heads/main/base/network_interfaces_linux.cc

2021-09-15 20:39 UTC, woody-apple approved these changes
Thank you!

2021-09-15 20:50 UTC, andy31415 approved these changes

2021-09-15 21:13 UTC, andy31415 approved these changes

2021-09-15 22:24 UTC, merged