Set commissioner discovery flags for Python chip-device-ctrl tool
project-chip/connectedhomeip pull request #9757
Opened 2021-09-16 17:38 UTC by sharadb-amazon

#### Problem
The flags defined in src/platform/include/CHIPDeviceConfig.h could be overriden by various example apps, but not for the python controller. And we needed a way to set the commissioner discovery flags to true for the python controller.

#### Change overview
* Creates a way to override feature flags for the python controller.
* Sets CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY and CHIP_DEVICE_CONFIG_ENABLE_BOTH_COMMISSIONER_AND_COMMISSIONEE to 1

#### Testing
Tested against the minimal-mdns client and verified that the py chip-device-ctrl tool advertises itself as a commissioner after this config change.

2021-09-17 01:56 UTC, mspang requested changes, later dismissed
Adding a new .gn dir is for establishing an entirely new project. We use this from examples/ because those are examples of making a new project.

The python controller is part of the main project, and shouldn't have it's own build system.

2021-09-17 19:44 UTC, andy31415 commented
Why do we need a compile-time configuration for this in python?

I would generally expect python to have 'enable everything' and then at runtime to be able  to select if something is used or not.

It seems to me like user defined commisioning compile-time enabling or not has more deep sideffects in functionality...maybe it should not.

@sharadb-amazon - could you explain why we need a compile-time flag for python? What do these compile flags enable and why can't we have python build with 'enabled' and change functionality via methods (some true/false enabling or other arguments)?

2021-09-17 21:01 UTC, sharadb-amazon commented
> Why do we need a compile-time configuration for this in python?
> 
> I would generally expect python to have 'enable everything' and then at runtime to be able to select if something is used or not.
> 
> It seems to me like user defined commisioning compile-time enabling or not has more deep sideffects in functionality...maybe it should not.
> 
> @sharadb-amazon - could you explain why we need a compile-time flag for python? What do these compile flags enable and why can't we have python build with 'enabled' and change functionality via methods (some true/false enabling or other arguments)?

CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY and CHIP_DEVICE_CONFIG_ENABLE_BOTH_COMMISSIONER_AND_COMMISSIONEE are pre-existing compile time flags that are used in the CHIPDeviceController.cpp (and elsewhere) to guard code that implements user directed commissioning and commissioner advertisement in the SDK. These need to be enabled *only* for the python controller (disabled by default for example apps) so that it responds to commissioner discovery and UDC requests.

2021-09-21 22:45 UTC, mspang commented
> > Why do we need a compile-time configuration for this in python?
> > I would generally expect python to have 'enable everything' and then at runtime to be able to select if something is used or not.
> > It seems to me like user defined commisioning compile-time enabling or not has more deep sideffects in functionality...maybe it should not.
> > @sharadb-amazon - could you explain why we need a compile-time flag for python? What do these compile flags enable and why can't we have python build with 'enabled' and change functionality via methods (some true/false enabling or other arguments)?
> 
> CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY and CHIP_DEVICE_CONFIG_ENABLE_BOTH_COMMISSIONER_AND_COMMISSIONEE are pre-existing compile time flags that are used in the CHIPDeviceController.cpp (and elsewhere) to guard code that implements user directed commissioning and commissioner advertisement in the SDK. These need to be enabled _only_ for the python controller (disabled by default for example apps) so that it responds to commissioner discovery and UDC requests. Note, these are NOT new or python specific flags.

Those defines are part of the implementation of this feature. Even if it's already merged in the tree, it's still subject to scrutiny later when we go to adjust configurations. 

I don't agree that the Linux samples should be forced to statically enable or disable these features. It isn't a scalable approach and will cause a huge amount of combinatorial pain as we try to test different cases of optional features being enabled or disabled.

2021-09-21 23:01 UTC, mspang commented on scripts/build_python.sh
> +gn --root="$CHIP_ROOT" gen "$OUTPUT_ROOT" --args="chip_detail_logging=$chip_detail_logging enable_pylib=$enable_pybindings enable_rtti=$enable_pybindings chip_use_clusters_for_ip_commissioning=$clust
Doesn't this work already?

```
chip_project_config_include_dirs = [ "//config/python" ]
```

2021-09-21 23:06 UTC, chrisdecenzo approved these changes

2021-09-21 23:08 UTC, mspang commented
I can help you make a targeted compile time argument for this to unblock the test event, but I would advocate strongly for the position that **optional features be able to be disabled without recompiling the code** and that Linux should by default have a maximalist compile-time configuration and enable or disable features as appropriate at runtime. 

> #### Problem
> The flags defined in src/platform/include/CHIPDeviceConfig.h could be overriden by various example apps, but not for the python controller. And we needed a way to set the commissioner discovery flags to true for the python controller.

While they 'can' be overridden by sample apps, we were not using this capability on Linux until recently. I actually don't agree with the changes that were made here in the lighting, tv, and tv-casting apps - these changes only apply when building from the subdirectory and we also support building them at the top level.

> 
> #### Change overview
> * Creates a way to override feature flags for the python controller.
> * Sets CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY and CHIP_DEVICE_CONFIG_ENABLE_BOTH_COMMISSIONER_AND_COMMISSIONEE to 1
> 
> #### Testing
> Tested against the minimal-mdns client and verified that the py chip-device-ctrl tool advertises itself as a commissioner after this config change.

2021-09-22 15:58 UTC, mspang approved these changes

2021-09-22 16:13 UTC, sharadb-amazon commented
> **optional features be able to be disabled without recompiling the code** and that Linux should by default have a maximalist compile-time configuration and enable or disable features as appropriate at runtime.

Opened an issue to track this work: https://github.com/project-chip/connectedhomeip/issues/9889

2021-09-22 16:38 UTC, hawk248 approved these changes

2021-09-22 16:39 UTC, woody-apple approved these changes

2021-09-22 19:19 UTC, merged

2021-09-24 16:58 UTC, franck-apple commented
This seems to be breaking BLE provisioning in the TE6 branch. Need to remove it from the TE6 branch.

2021-09-24 20:55 UTC, andy31415 commented
Revert done.